# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from metamath_setmm_provider.shards.s004 import (
    biorf as biorf,
)
from metamath_setmm_provider.shards.s004 import (
    biorfi as biorfi,
)
from metamath_setmm_provider.shards.s004 import (
    biorfri as biorfri,
)
from metamath_setmm_provider.shards.s004 import (
    biorfriOLD as biorfriOLD,
)
from metamath_setmm_provider.shards.s004 import (
    biort as biort,
)
from metamath_setmm_provider.shards.s004 import (
    biortn as biortn,
)
from metamath_setmm_provider.shards.s004 import (
    df_or as df_or,
)
from metamath_setmm_provider.shards.s004 import (
    dfor2 as dfor2,
)
from metamath_setmm_provider.shards.s004 import (
    exmid as exmid,
)
from metamath_setmm_provider.shards.s004 import (
    exmidd as exmidd,
)
from metamath_setmm_provider.shards.s004 import (
    imor as imor,
)
from metamath_setmm_provider.shards.s004 import (
    imori as imori,
)
from metamath_setmm_provider.shards.s004 import (
    imorri as imorri,
)
from metamath_setmm_provider.shards.s004 import (
    jao as jao,
)
from metamath_setmm_provider.shards.s004 import (
    jao1i as jao1i,
)
from metamath_setmm_provider.shards.s004 import (
    jaob as jaob,
)
from metamath_setmm_provider.shards.s004 import (
    jaod as jaod,
)
from metamath_setmm_provider.shards.s004 import (
    jaodan as jaodan,
)
from metamath_setmm_provider.shards.s004 import (
    jaoi as jaoi,
)
from metamath_setmm_provider.shards.s004 import (
    jaoian as jaoian,
)
from metamath_setmm_provider.shards.s004 import (
    mpjaod as mpjaod,
)
from metamath_setmm_provider.shards.s004 import (
    mpjaodan as mpjaodan,
)
from metamath_setmm_provider.shards.s004 import (
    mtord as mtord,
)
from metamath_setmm_provider.shards.s004 import (
    nbior as nbior,
)
from metamath_setmm_provider.shards.s004 import (
    norbi as norbi,
)
from metamath_setmm_provider.shards.s004 import (
    oibabs as oibabs,
)
from metamath_setmm_provider.shards.s004 import (
    olc as olc,
)
from metamath_setmm_provider.shards.s004 import (
    olcd as olcd,
)
from metamath_setmm_provider.shards.s004 import (
    olci as olci,
)
from metamath_setmm_provider.shards.s004 import (
    olcnd as olcnd,
)
from metamath_setmm_provider.shards.s004 import (
    olcs as olcs,
)
from metamath_setmm_provider.shards.s004 import (
    or4 as or4,
)
from metamath_setmm_provider.shards.s004 import (
    or12 as or12,
)
from metamath_setmm_provider.shards.s004 import (
    or32 as or32,
)
from metamath_setmm_provider.shards.s004 import (
    or42 as or42,
)
from metamath_setmm_provider.shards.s004 import (
    orass as orass,
)
from metamath_setmm_provider.shards.s004 import (
    orbi1 as orbi1,
)
from metamath_setmm_provider.shards.s004 import (
    orbi1d as orbi1d,
)
from metamath_setmm_provider.shards.s004 import (
    orbi1i as orbi1i,
)
from metamath_setmm_provider.shards.s004 import (
    orbi2d as orbi2d,
)
from metamath_setmm_provider.shards.s004 import (
    orbi2i as orbi2i,
)
from metamath_setmm_provider.shards.s004 import (
    orbi12d as orbi12d,
)
from metamath_setmm_provider.shards.s004 import (
    orbi12i as orbi12i,
)
from metamath_setmm_provider.shards.s004 import (
    orbidi as orbidi,
)
from metamath_setmm_provider.shards.s004 import (
    orc as orc,
)
from metamath_setmm_provider.shards.s004 import (
    orcd as orcd,
)
from metamath_setmm_provider.shards.s004 import (
    orci as orci,
)
from metamath_setmm_provider.shards.s004 import (
    orcnd as orcnd,
)
from metamath_setmm_provider.shards.s004 import (
    orcom as orcom,
)
from metamath_setmm_provider.shards.s004 import (
    orcomd as orcomd,
)
from metamath_setmm_provider.shards.s004 import (
    orcoms as orcoms,
)
from metamath_setmm_provider.shards.s004 import (
    orcs as orcs,
)
from metamath_setmm_provider.shards.s004 import (
    ord as ord,
)
from metamath_setmm_provider.shards.s004 import (
    orel1 as orel1,
)
from metamath_setmm_provider.shards.s004 import (
    orel2 as orel2,
)
from metamath_setmm_provider.shards.s004 import (
    ori as ori,
)
from metamath_setmm_provider.shards.s004 import (
    oridm as oridm,
)
from metamath_setmm_provider.shards.s004 import (
    orim1d as orim1d,
)
from metamath_setmm_provider.shards.s004 import (
    orim1i as orim1i,
)
from metamath_setmm_provider.shards.s004 import (
    orim2 as orim2,
)
from metamath_setmm_provider.shards.s004 import (
    orim2d as orim2d,
)
from metamath_setmm_provider.shards.s004 import (
    orim2i as orim2i,
)
from metamath_setmm_provider.shards.s004 import (
    orim12d as orim12d,
)
from metamath_setmm_provider.shards.s004 import (
    orim12dALT as orim12dALT,
)
from metamath_setmm_provider.shards.s004 import (
    orim12da as orim12da,
)
from metamath_setmm_provider.shards.s004 import (
    orim12i as orim12i,
)
from metamath_setmm_provider.shards.s004 import (
    orimdi as orimdi,
)
from metamath_setmm_provider.shards.s004 import (
    orordi as orordi,
)
from metamath_setmm_provider.shards.s004 import (
    orordir as orordir,
)
from metamath_setmm_provider.shards.s004 import (
    orrd as orrd,
)
from metamath_setmm_provider.shards.s004 import (
    orri as orri,
)
from metamath_setmm_provider.shards.s004 import (
    pm1_2 as pm1_2,
)
from metamath_setmm_provider.shards.s004 import (
    pm1_4 as pm1_4,
)
from metamath_setmm_provider.shards.s004 import (
    pm1_5 as pm1_5,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_1 as pm2_1,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_3 as pm2_3,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_4 as pm2_4,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_07 as pm2_07,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_8 as pm2_8,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_13 as pm2_13,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_25 as pm2_25,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_26 as pm2_26,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_31 as pm2_31,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_32 as pm2_32,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_36 as pm2_36,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_37 as pm2_37,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_38 as pm2_38,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_41 as pm2_41,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_42 as pm2_42,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_45 as pm2_45,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_46 as pm2_46,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_47 as pm2_47,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_48 as pm2_48,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_49 as pm2_49,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_53 as pm2_53,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_54 as pm2_54,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_62 as pm2_62,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_63 as pm2_63,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_64 as pm2_64,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_67 as pm2_67,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_67_2 as pm2_67_2,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_68 as pm2_68,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_73 as pm2_73,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_74 as pm2_74,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_75 as pm2_75,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_76 as pm2_76,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_81 as pm2_81,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_82 as pm2_82,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_85 as pm2_85,
)
from metamath_setmm_provider.shards.s004 import (
    pm2_621 as pm2_621,
)
from metamath_setmm_provider.shards.s004 import (
    pm3_2ni as pm3_2ni,
)
from metamath_setmm_provider.shards.s004 import (
    pm3_44 as pm3_44,
)
from metamath_setmm_provider.shards.s004 import (
    pm3_48 as pm3_48,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_25 as pm4_25,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_39 as pm4_39,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_62 as pm4_62,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_64 as pm4_64,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_66 as pm4_66,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_77 as pm4_77,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_78 as pm4_78,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_7 as pm5_7,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_11 as pm5_11,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_11g as pm5_11g,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_12 as pm5_12,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_13 as pm5_13,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_14 as pm5_14,
)
from metamath_setmm_provider.shards.s004 import (
    pm5_55 as pm5_55,
)
from metamath_setmm_provider.shards.s004 import (
    wo as wo,
)
from metamath_setmm_provider.shards.s005 import (
    jaoi2 as jaoi2,
)
from metamath_setmm_provider.shards.s005 import (
    jaoi3 as jaoi3,
)
from metamath_setmm_provider.shards.s005 import (
    ornld as ornld,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_53 as pm5_53,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.metamath_language import FormationBinding
from skfd.authoring.theory import TheoryProofAuthor

if str(wo.syntax_assertion) != (
    'urn:uuid:617c46d0-9cdf-5401-8cd6-adadfbde4ab5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(df_or.id) != (
    'urn:uuid:91797ea3-c2a5-5314-9a9f-5649970c7ea9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_64.id) != (
    'urn:uuid:8556a788-8932-5132-b687-1e3092f4a3a2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_66.id) != (
    'urn:uuid:3ab7614d-ffc1-5403-85ee-5c2e7fd3894a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_53.id) != (
    'urn:uuid:cb8436fa-e665-542d-bc30-e393ede6df7e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_54.id) != (
    'urn:uuid:9975f2bb-a83b-5d5e-8b11-b9fdf857db99'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imor.id) != (
    'urn:uuid:5466b298-1aeb-556d-961c-a8cc73818d6e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imori.id) != (
    'urn:uuid:7fe2f581-9fcb-5d19-9adf-a3713ea7a64e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imorri.id) != (
    'urn:uuid:70f0cfd5-fe3d-5c72-9227-ddf2c0811518'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_62.id) != (
    'urn:uuid:38c2f524-758d-51d8-8f14-386b544b4398'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaoi.id) != (
    'urn:uuid:8c388d53-c20a-5b1f-a24f-1dab7b192845'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jao1i.id) != (
    'urn:uuid:85d81760-86fe-5d4e-8212-391ca470b8e9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaod.id) != (
    'urn:uuid:bc224cdd-d016-501d-bc8b-f5da2ce59758'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpjaod.id) != (
    'urn:uuid:d908c91c-4a41-532e-93cc-3362719033f4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ori.id) != (
    'urn:uuid:a3d8171d-b7fa-59b5-a074-97ddf990bb32'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orri.id) != (
    'urn:uuid:ed620a48-c07b-5307-8dea-2dfb03b3d78a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orrd.id) != (
    'urn:uuid:c670c2dc-5e8b-5226-a25e-35dd325a8e87'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ord.id) != (
    'urn:uuid:54abd682-de38-54e6-aa61-1687785ccd9b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orci.id) != (
    'urn:uuid:79b55b9f-a030-58e6-a3e5-3182b4c7fdfe'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(olci.id) != (
    'urn:uuid:4dc22c73-be1b-5c2f-8c0b-71e50d32d367'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orc.id) != (
    'urn:uuid:7a1ff9f7-8066-55dd-b14d-ed0944caae03'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(olc.id) != (
    'urn:uuid:1b3fb2b8-088f-505c-8de1-0e407a37884d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm1_4.id) != (
    'urn:uuid:6065a984-2427-51bd-9cef-fc62ea0d0329'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcom.id) != (
    'urn:uuid:37c7eef7-4f05-52be-ad44-89d4b216ae74'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcomd.id) != (
    'urn:uuid:5305778c-1e2e-54d7-ba53-5e772a839c85'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcoms.id) != (
    'urn:uuid:77bd748b-f724-5dd1-8fd2-c67f93af066e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcd.id) != (
    'urn:uuid:f271482d-fc69-5691-b518-4c79cf616411'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(olcd.id) != (
    'urn:uuid:92598eb2-e38e-52e8-8d97-6a92ba4c80e1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcs.id) != (
    'urn:uuid:7f26b949-7d52-5149-bebc-9e9bf648da20'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(olcs.id) != (
    'urn:uuid:2d1cd084-edcc-5845-95ee-005c5d495fcd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(olcnd.id) != (
    'urn:uuid:8d58130b-5ff7-5641-b621-43c00c52807e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcnd.id) != (
    'urn:uuid:da66cf9b-0e1d-5988-baeb-6c7afc5df64b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mtord.id) != (
    'urn:uuid:e6aeacaf-bd8a-503f-b60b-ee1934d89527'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_2ni.id) != (
    'urn:uuid:c3358b6c-ab7e-5e34-a23b-7039fecb0b60'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_45.id) != (
    'urn:uuid:4c7d3023-b3e4-5490-aa5c-4d3f59aa9386'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_46.id) != (
    'urn:uuid:61abe479-33c2-5c9b-871f-6579fc229408'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_47.id) != (
    'urn:uuid:9aaad054-bdbd-510d-9def-d02d02275474'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_48.id) != (
    'urn:uuid:f16dd8f7-97b3-59a9-ab51-a22e6484d476'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_49.id) != (
    'urn:uuid:c3790b9c-de2d-5421-a86a-f29af29ba1d9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norbi.id) != (
    'urn:uuid:64f33164-c773-59c8-b36e-2a883bab49ab'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(nbior.id) != (
    'urn:uuid:2fded45f-28c6-53ed-8069-41017dacc968'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orel1.id) != (
    'urn:uuid:7e9c5cf6-23c7-567a-9ff3-07690e638a5e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_25.id) != (
    'urn:uuid:574d3f6c-48ea-54ce-92d8-d99f8fd44b00'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orel2.id) != (
    'urn:uuid:b34606ec-be9c-52a4-b35d-123f8641f941'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_67_2.id) != (
    'urn:uuid:f9716110-480a-506e-aaea-4d8f7fa54589'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_67.id) != (
    'urn:uuid:2b33c048-ff5d-5c39-8a0c-919d757188c2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(exmid.id) != (
    'urn:uuid:d30aa314-885c-5745-bd0c-38fd79132f5e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(exmidd.id) != (
    'urn:uuid:3d179774-8b9f-5c1f-85c4-7b16597476f9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_1.id) != (
    'urn:uuid:f9966168-2661-55e2-a872-69bfdc508dd2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_13.id) != (
    'urn:uuid:c59052a0-9344-567d-a60f-32fe35af0647'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_621.id) != (
    'urn:uuid:c2df33b9-67da-5497-b4fb-2fafec2b30ab'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_62.id) != (
    'urn:uuid:f473db8a-466c-52cb-978a-301717501f15'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_68.id) != (
    'urn:uuid:e7e22029-0cb0-5aab-9622-2b23c46549fc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dfor2.id) != (
    'urn:uuid:59f4d61b-40ad-5254-9bbb-32d47914adb8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_07.id) != (
    'urn:uuid:3fde23a3-9455-5977-81fc-b5fd095f9f1d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm1_2.id) != (
    'urn:uuid:97bd2fc1-f70f-595e-a102-a628bc05d6ff'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(oridm.id) != (
    'urn:uuid:aa3e52fb-f2e9-580e-ac48-ed7fcd1a01ae'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_25.id) != (
    'urn:uuid:435b3541-51ab-5840-a7c5-484f39d407fb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_4.id) != (
    'urn:uuid:4e9ddc42-f231-5c04-b3a1-63da6efa9d82'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_41.id) != (
    'urn:uuid:ea50b035-0587-537b-bfca-295c6c57327d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim12i.id) != (
    'urn:uuid:5a1777e9-693d-59f9-9a0c-01961656694b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim1i.id) != (
    'urn:uuid:7c1c8969-c7a4-50b6-a399-da2e39f62dcc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim2i.id) != (
    'urn:uuid:3b455607-9d83-59dc-97aa-202797956218'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim12dALT.id) != (
    'urn:uuid:325bdbc0-147b-5700-929d-0d0f6ec41b04'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi2i.id) != (
    'urn:uuid:0cd80444-d959-5777-8631-73c54c6de748'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi1i.id) != (
    'urn:uuid:094bd7c6-b958-54b7-9795-f55eaf35c9ee'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi12i.id) != (
    'urn:uuid:39f7c62e-dc2d-548d-a2d4-b52cd4d09453'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi2d.id) != (
    'urn:uuid:684dcbae-00f7-5904-86ca-a1b714228a7c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi1d.id) != (
    'urn:uuid:9ce437a4-d6be-50e1-b190-9f2561bec156'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi1.id) != (
    'urn:uuid:6915c10e-a5de-5417-a895-65575c0d1919'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbi12d.id) != (
    'urn:uuid:f5b9cdd1-8d1b-5924-83bd-278647a663f1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm1_5.id) != (
    'urn:uuid:13fbb0c9-188e-5a33-b241-c02e4756dd90'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(or12.id) != (
    'urn:uuid:b54b9fa9-0efe-553b-9e78-e36f042de61e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orass.id) != (
    'urn:uuid:ca3a5f38-07f1-5034-91bc-65fa4a2f8757'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_31.id) != (
    'urn:uuid:8ca8ef7d-4086-54d7-80ea-29cb5ff66672'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_32.id) != (
    'urn:uuid:36b381e5-0924-5b7f-9636-de36abc07bef'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_3.id) != (
    'urn:uuid:95746564-ddcc-59fe-8f72-f5b02d6a0b09'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(or32.id) != (
    'urn:uuid:3dbb961e-9f03-5a73-b888-fdaa9449d182'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(or4.id) != (
    'urn:uuid:72e6c75e-0b36-5272-bced-bbc343039dbf'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(or42.id) != (
    'urn:uuid:2373f27d-fe32-5179-bc19-4dd0d1c174cd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orordi.id) != (
    'urn:uuid:2825304b-b136-57b9-8d39-944ec7c855fc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orordir.id) != (
    'urn:uuid:332c5b02-fa7c-5cbc-9f96-fccb18b7fb46'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orimdi.id) != (
    'urn:uuid:737a1691-64e2-5b8e-bf5a-5275f4d49964'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_76.id) != (
    'urn:uuid:c5453d7c-9f94-5b18-b963-c32f27e82d7c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_85.id) != (
    'urn:uuid:d79be4d5-0962-5c18-ad20-c1d90e81112b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_75.id) != (
    'urn:uuid:e4a43287-2e99-51db-9acf-ffcf1b8f5366'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_78.id) != (
    'urn:uuid:ef5d519c-eb45-5c59-ab8f-a1fcbc77f6e8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biort.id) != (
    'urn:uuid:1a96610f-1193-59f6-a377-cab63f1c5410'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biorf.id) != (
    'urn:uuid:8b948c60-b05d-53d0-ab4c-8138035851de'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biortn.id) != (
    'urn:uuid:dfdbdd87-d555-5dc1-b639-cfe74007f78e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biorfi.id) != (
    'urn:uuid:4105421d-b90e-5b57-959f-f2dd449b6592'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biorfri.id) != (
    'urn:uuid:4dfefcd4-f232-5792-8649-cc9018df9bf7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(biorfriOLD.id) != (
    'urn:uuid:f0fbc88a-438a-55d1-a54d-a1c0c6d251f7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_26.id) != (
    'urn:uuid:02009c5a-8f3a-55ea-a198-ec857643e485'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_63.id) != (
    'urn:uuid:dc3e509a-017c-5b1e-84fb-2b73a5c2e129'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_64.id) != (
    'urn:uuid:309c27eb-dd5e-5507-b7ec-f009652294ed'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_42.id) != (
    'urn:uuid:670df123-f49e-5e3c-9291-91c01079f63d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_11g.id) != (
    'urn:uuid:218cd502-8ec0-501e-94f0-0820fe6f1ba8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_11.id) != (
    'urn:uuid:411005e3-fb71-539f-a2aa-ad6fd35ed924'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_12.id) != (
    'urn:uuid:1d5c7673-5ad3-5b0e-bdff-99f0b20c1d26'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_14.id) != (
    'urn:uuid:77875082-b7b8-5ecc-bd67-5db3cb41e97f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_13.id) != (
    'urn:uuid:37299545-463c-571f-9f93-af2dbb4f239f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_55.id) != (
    'urn:uuid:86a9672a-f9a7-51a1-8558-b425da66c061'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(oibabs.id) != (
    'urn:uuid:10216f44-c09e-5769-85de-392319363d15'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orbidi.id) != (
    'urn:uuid:925ce3ab-a12e-5f7f-96fa-616ca8eb45c5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_7.id) != (
    'urn:uuid:7689456c-ebff-562a-b019-e868e1bd37bb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaoian.id) != (
    'urn:uuid:8e392b6a-4961-5819-93f2-10373aad055a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaodan.id) != (
    'urn:uuid:163eccf1-7943-53e6-b33e-f90c69e04636'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpjaodan.id) != (
    'urn:uuid:446c4bd1-000b-555b-9e7f-f0df00c5667f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_44.id) != (
    'urn:uuid:3e4e61c6-68d1-5675-bdb5-37b74f266c7f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jao.id) != (
    'urn:uuid:0960f0ec-e181-57e7-94a7-272d7761f117'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaob.id) != (
    'urn:uuid:737bc208-2d4a-5862-8cbc-9ad1bb727eb0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_77.id) != (
    'urn:uuid:afb14aaa-1f30-557f-a8ab-d92bd905ebac'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_48.id) != (
    'urn:uuid:c0d0ec73-1ea2-5009-ad6d-70366cecbc5c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim12d.id) != (
    'urn:uuid:ac46ef4f-250f-5976-8456-6d936a93bb5a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim12da.id) != (
    'urn:uuid:fe11a798-241b-577e-bd22-808dd738d657'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim1d.id) != (
    'urn:uuid:08ab0b9f-fcc5-526e-8d48-89708acff20f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim2d.id) != (
    'urn:uuid:811d4dc6-50ec-5cb2-b0da-9855e287fd8c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orim2.id) != (
    'urn:uuid:c6189cb9-0ed8-5946-8bd3-0a4fcbab94d1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_38.id) != (
    'urn:uuid:fcdd1954-6dd3-56ec-9e08-b14c4dce0737'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_36.id) != (
    'urn:uuid:dd2a27c2-c209-5c4f-9935-7c54f32bacf9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_37.id) != (
    'urn:uuid:d718a19c-2a67-5942-b417-3dc885aa1d6a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_81.id) != (
    'urn:uuid:c0f8ac24-21f8-5b4e-9375-2f020b51393d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_8.id) != (
    'urn:uuid:0a6e519c-1b64-5280-9fac-e2cfc858bf28'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_73.id) != (
    'urn:uuid:afd75b10-dacf-5d4d-9042-c0d962688e76'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_74.id) != (
    'urn:uuid:fece323b-1b53-5726-b267-c20e7437e246'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_82.id) != (
    'urn:uuid:aaf18e18-4d90-5b0e-94dc-ff91c4f1e3ea'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_39.id) != (
    'urn:uuid:cdae4adc-d03b-528f-bdcc-edf97b0348d0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_53.id) != (
    'urn:uuid:4600ce4f-6fe7-5e46-b989-937f12c0a2b7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaoi2.id) != (
    'urn:uuid:b6fa821a-fffb-5771-9a13-10e3176317f9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaoi3.id) != (
    'urn:uuid:5952d524-83ef-5b5b-958f-5d9577c084d2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ornld.id) != (
    'urn:uuid:f3201241-3aad-5c30-aedf-e8dcff97ba58'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@pm4_64.proof
def prove_pm4_64(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi


    _step_1 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wi(wn(ph), ps), wo(ph, ps))
    return proof.qed(_step_2)


@pm4_66.proof
def prove_pm4_66(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        pm4_64,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wi(wn(ph), wn(ps)), wo(ph, wn(ps)))
    return proof.qed(_step_1)


@pm2_53.proof
def prove_pm2_53(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi


    _step_1 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wo(ph, ps), wi(wn(ph), ps))
    return proof.qed(_step_2)


@pm2_54.proof
def prove_pm2_54(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpri


    _step_1 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(biimpri, _step_1)  # ⊢ wi(wi(wn(ph), ps), wo(ph, ps))
    return proof.qed(_step_2)


@imor.proof
def prove_imor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, imbi1i, notnotb


    _step_1 = proof.use(notnotb, subst={"ph": "ph"})  # ⊢ wb(ph, wn(wn(ph)))
    _step_2 = proof.use(imbi1i, _step_1, subst={"ch": "ps"})  # ⊢ wb(wi(ph, ps), wi(wn(wn(ph)), ps))
    _step_3 = proof.use(
        df_or,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
        },
    )  # ⊢ wb(wo(wn(ph), ps), wi(wn(wn(ph)), ps))
    _step_4 = proof.use(bitr4i, _step_2, _step_3)  # ⊢ wb(wi(ph, ps), wo(wn(ph), ps))
    return proof.qed(_step_4)


@imori.proof
def prove_imori(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbi


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(imor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wi(ph, ps), wo(wn(ph), ps))
    _step_2 = proof.use(mpbi, _hypothesis_1, _step_1)  # ⊢ wo(wn(ph), ps)
    return proof.qed(_step_2)


@imorri.proof
def prove_imorri(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbir


    _hypothesis_1, = proof.hypotheses  # ⊢ wo(wn(ph), ps)
    _step_1 = proof.use(imor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wi(ph, ps), wo(wn(ph), ps))
    _step_2 = proof.use(mpbir, _hypothesis_1, _step_1)  # ⊢ wi(ph, ps)
    return proof.qed(_step_2)


@pm4_62.proof
def prove_pm4_62(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        imor,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wi(ph, wn(ps)), wo(wn(ph), wn(ps)))
    return proof.qed(_step_1)


@jaoi.proof
def prove_jaoi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_61d2, syl6


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, ps)
    _step_1 = proof.use(pm2_53, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(wo(ph, ch), wi(wn(ph), ch))
    _step_2 = proof.use(syl6, _step_1, _hypothesis_2)  # ⊢ wi(wo(ph, ch), wi(wn(ph), ps))
    _step_3 = proof.use(pm2_61d2, _step_2, _hypothesis_1)  # ⊢ wi(wo(ph, ch), ps)
    return proof.qed(_step_3)


@jao1i.proof
def prove_jao1i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ps, wi(ch, ph))
    _step_1 = proof.use(ax_1, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(ph, wi(ch, ph))
    _step_2 = proof.use(jaoi, _step_1, _hypothesis_1)  # ⊢ wi(wo(ph, ps), wi(ch, ph))
    return proof.qed(_step_2)


@jaod.proof
def prove_jaod(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, ch))
    _step_1 = proof.use(com12, _hypothesis_1)  # ⊢ wi(ps, wi(ph, ch))
    _step_2 = proof.use(com12, _hypothesis_2)  # ⊢ wi(th, wi(ph, ch))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ps, th), wi(ph, ch))
    _step_4 = proof.use(com12, _step_3)  # ⊢ wi(ph, wi(wo(ps, th), ch))
    return proof.qed(_step_4)


@mpjaod.proof
def prove_mpjaod(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import mpd


    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, ch)); wi(ph, wo(ps, th))
    _step_1 = proof.use(jaod, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(wo(ps, th), ch))
    _step_2 = proof.use(mpd, _hypothesis_3, _step_1)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@ori.proof
def prove_ori(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbi


    _hypothesis_1, = proof.hypotheses  # ⊢ wo(ph, ps)
    _step_1 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(mpbi, _hypothesis_1, _step_1)  # ⊢ wi(wn(ph), ps)
    return proof.qed(_step_2)


@orri.proof
def prove_orri(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbir


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wn(ph), ps)
    _step_1 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(mpbir, _hypothesis_1, _step_1)  # ⊢ wo(ph, ps)
    return proof.qed(_step_2)


@orrd.proof
def prove_orrd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(wn(ps), ch))
    _step_1 = proof.use(pm2_54, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(wi(wn(ps), ch), wo(ps, ch))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wo(ps, ch))
    return proof.qed(_step_2)


@ord.proof
def prove_ord(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylib


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wo(ps, ch))
    _step_1 = proof.use(df_or, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wo(ps, ch), wi(wn(ps), ch))
    _step_2 = proof.use(sylib, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wn(ps), ch))
    return proof.qed(_step_2)


@orci.proof
def prove_orci(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_24i


    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(pm2_24i, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wi(wn(ph), ps)
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(ph, ps)
    return proof.qed(_step_2)


@olci.proof
def prove_olci(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import a1i


    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "wn(ps)"})  # ⊢ wi(wn(ps), ph)
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(ps, ph)
    return proof.qed(_step_2)


@orc.proof
def prove_orc(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_24


    _step_1 = proof.use(pm2_24, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(wn(ph), ps))
    _step_2 = proof.use(orrd, _step_1)  # ⊢ wi(ph, wo(ph, ps))
    return proof.qed(_step_2)


@olc.proof
def prove_olc(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1


    _step_1 = proof.use(ax_1, subst={"ph": "ph", "ps": "wn(ps)"})  # ⊢ wi(ph, wi(wn(ps), ph))
    _step_2 = proof.use(orrd, _step_1)  # ⊢ wi(ph, wo(ps, ph))
    return proof.qed(_step_2)


@pm1_4.proof
def prove_pm1_4(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(olc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ps, ph))
    _step_2 = proof.use(orc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ps, ph))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, ps), wo(ps, ph))
    return proof.qed(_step_3)


@orcom.proof
def prove_orcom(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbii


    _step_1 = proof.use(pm1_4, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wo(ps, ph))
    _step_2 = proof.use(pm1_4, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wo(ps, ph), wo(ph, ps))
    _step_3 = proof.use(impbii, _step_1, _step_2)  # ⊢ wb(wo(ph, ps), wo(ps, ph))
    return proof.qed(_step_3)


@orcomd.proof
def prove_orcomd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylib


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wo(ps, ch))
    _step_1 = proof.use(orcom, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wo(ps, ch), wo(ch, ps))
    _step_2 = proof.use(sylib, _hypothesis_1, _step_1)  # ⊢ wi(ph, wo(ch, ps))
    return proof.qed(_step_2)


@orcoms.proof
def prove_orcoms(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wo(ph, ps), ch)
    _step_1 = proof.use(pm1_4, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wo(ps, ph), wo(ph, ps))
    _step_2 = proof.use(syl, _step_1, _hypothesis_1)  # ⊢ wi(wo(ps, ph), ch)
    return proof.qed(_step_2)


@orcd.proof
def prove_orcd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(orc, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(ps, wo(ps, ch))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wo(ps, ch))
    return proof.qed(_step_2)


@olcd.proof
def prove_olcd(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(orcd, _hypothesis_1, subst={"ch": "ch"})  # ⊢ wi(ph, wo(ps, ch))
    _step_2 = proof.use(orcomd, _step_1)  # ⊢ wi(ph, wo(ch, ps))
    return proof.qed(_step_2)


@orcs.proof
def prove_orcs(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wo(ph, ps), ch)
    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(syl, _step_1, _hypothesis_1)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@olcs.proof
def prove_olcs(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wo(ph, ps), ch)
    _step_1 = proof.use(orcoms, _hypothesis_1)  # ⊢ wi(wo(ps, ph), ch)
    _step_2 = proof.use(orcs, _step_1)  # ⊢ wi(ps, ch)
    return proof.qed(_step_2)


@olcnd.proof
def prove_olcnd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import mt3d


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wo(ps, ch)); wi(ph, wn(ch))
    _step_1 = proof.use(ord, _hypothesis_1)  # ⊢ wi(ph, wi(wn(ps), ch))
    _step_2 = proof.use(mt3d, _hypothesis_2, _step_1)  # ⊢ wi(ph, ps)
    return proof.qed(_step_2)


@orcnd.proof
def prove_orcnd(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wo(ps, ch)); wi(ph, wn(ps))
    _step_1 = proof.use(orcomd, _hypothesis_1)  # ⊢ wi(ph, wo(ch, ps))
    _step_2 = proof.use(olcnd, _step_1, _hypothesis_2)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@mtord.proof
def prove_mtord(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl6ci
    from metamath_setmm_provider.shards.s001 import mtod


    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wn(ch)); wi(ph, wn(th)); wi(ph, wi(ps, wo(ch, th)))
    _step_1 = proof.use(pm2_53, subst={"ph": "ch", "ps": "th"})  # ⊢ wi(wo(ch, th), wi(wn(ch), th))
    _step_2 = proof.use(syl6ci, _hypothesis_3, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, th))
    _step_3 = proof.use(mtod, _hypothesis_2, _step_2)  # ⊢ wi(ph, wn(ps))
    return proof.qed(_step_3)


@pm3_2ni.proof
def prove_pm3_2ni(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id, mto, pm2_21i


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wn(ph); wn(ps)
    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(pm2_21i, _hypothesis_2, subst={"ps": "ph"})  # ⊢ wi(ps, ph)
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, ps), ph)
    _step_4 = proof.use(mto, _hypothesis_1, _step_3)  # ⊢ wn(wo(ph, ps))
    return proof.qed(_step_4)


@pm2_45.proof
def prove_pm2_45(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con3i


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(con3i, _step_1)  # ⊢ wi(wn(wo(ph, ps)), wn(ph))
    return proof.qed(_step_2)


@pm2_46.proof
def prove_pm2_46(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con3i


    _step_1 = proof.use(olc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ph, ps))
    _step_2 = proof.use(con3i, _step_1)  # ⊢ wi(wn(wo(ph, ps)), wn(ps))
    return proof.qed(_step_2)


@pm2_47.proof
def prove_pm2_47(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(pm2_45, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wn(ph))
    _step_2 = proof.use(orcd, _step_1, subst={"ch": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wo(wn(ph), ps))
    return proof.qed(_step_2)


@pm2_48.proof
def prove_pm2_48(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(pm2_46, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wn(ps))
    _step_2 = proof.use(olcd, _step_1, subst={"ch": "ph"})  # ⊢ wi(wn(wo(ph, ps)), wo(ph, wn(ps)))
    return proof.qed(_step_2)


@pm2_49.proof
def prove_pm2_49(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(pm2_46, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wn(ps))
    _step_2 = proof.use(
        olcd,
        _step_1,
        subst={
            "ch": "wn(ph)",
        },
    )  # ⊢ wi(wn(wo(ph, ps)), wo(wn(ph), wn(ps)))
    return proof.qed(_step_2)


@norbi.proof
def prove_norbi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import pm5_21ni


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(olc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ph, ps))
    _step_3 = proof.use(pm5_21ni, _step_1, _step_2)  # ⊢ wi(wn(wo(ph, ps)), wb(ph, ps))
    return proof.qed(_step_3)


@nbior.proof
def prove_nbior(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con1i


    _step_1 = proof.use(norbi, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wb(ph, ps))
    _step_2 = proof.use(con1i, _step_1)  # ⊢ wi(wn(wb(ph, ps)), wo(ph, ps))
    return proof.qed(_step_2)


@orel1.proof
def prove_orel1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12


    _step_1 = proof.use(pm2_53, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(wn(ph), wi(wo(ph, ps), ps))
    return proof.qed(_step_2)


@pm2_25.proof
def prove_pm2_25(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(orel1, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(wo(ph, ps), ps))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(ph, wi(wo(ph, ps), ps))
    return proof.qed(_step_2)


@orel2.proof
def prove_orel2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import idd, pm2_21


    _step_1 = proof.use(idd, subst={"ph": "wn(ph)", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ps, ps))
    _step_2 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ph, ps))
    _step_3 = proof.use(jaod, _step_1, _step_2)  # ⊢ wi(wn(ph), wi(wo(ps, ph), ps))
    return proof.qed(_step_3)


@pm2_67_2.proof
def prove_pm2_67_2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import imim1i


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(ph, wo(ph, ch))
    _step_2 = proof.use(imim1i, _step_1, subst={"ch": "ps"})  # ⊢ wi(wi(wo(ph, ch), ps), wi(ph, ps))
    return proof.qed(_step_2)


@pm2_67.proof
def prove_pm2_67(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        pm2_67_2,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ps",
        },
    )  # ⊢ wi(wi(wo(ph, ps), ps), wi(ph, ps))
    return proof.qed(_step_1)


@exmid.proof
def prove_exmid(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "wn(ph)"})  # ⊢ wi(wn(ph), wn(ph))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(ph, wn(ph))
    return proof.qed(_step_2)


@exmidd.proof
def prove_exmidd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import a1i


    _step_1 = proof.use(exmid, subst={"ph": "ps"})  # ⊢ wo(ps, wn(ps))
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ph"})  # ⊢ wi(ph, wo(ps, wn(ps)))
    return proof.qed(_step_2)


@pm2_1.proof
def prove_pm2_1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(imori, _step_1)  # ⊢ wo(wn(ph), ph)
    return proof.qed(_step_2)


@pm2_13.proof
def prove_pm2_13(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import notnot


    _step_1 = proof.use(notnot, subst={"ph": "wn(ph)"})  # ⊢ wi(wn(ph), wn(wn(wn(ph))))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(ph, wn(wn(wn(ph))))
    return proof.qed(_step_2)


@pm2_621.proof
def prove_pm2_621(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id, idd


    _step_1 = proof.use(id, subst={"ph": "wi(ph, ps)"})  # ⊢ wi(wi(ph, ps), wi(ph, ps))
    _step_2 = proof.use(idd, subst={"ph": "wi(ph, ps)", "ps": "ps"})  # ⊢ wi(wi(ph, ps), wi(ps, ps))
    _step_3 = proof.use(jaod, _step_1, _step_2)  # ⊢ wi(wi(ph, ps), wi(wo(ph, ps), ps))
    return proof.qed(_step_3)


@pm2_62.proof
def prove_pm2_62(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12


    _step_1 = proof.use(
        pm2_621,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wo(ph, ps), ps))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(wo(ph, ps), wi(wi(ph, ps), ps))
    return proof.qed(_step_2)


@pm2_68.proof
def prove_pm2_68(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import jarl


    _step_1 = proof.use(
        jarl,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ps",
        },
    )  # ⊢ wi(wi(wi(ph, ps), ps), wi(wn(ph), ps))
    _step_2 = proof.use(orrd, _step_1)  # ⊢ wi(wi(wi(ph, ps), ps), wo(ph, ps))
    return proof.qed(_step_2)


@dfor2.proof
def prove_dfor2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbii


    _step_1 = proof.use(
        pm2_62,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wo(ph, ps), wi(wi(ph, ps), ps))
    _step_2 = proof.use(
        pm2_68,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wi(wi(ph, ps), ps), wo(ph, ps))
    _step_3 = proof.use(impbii, _step_1, _step_2)  # ⊢ wb(wo(ph, ps), wi(wi(ph, ps), ps))
    return proof.qed(_step_3)


@pm2_07.proof
def prove_pm2_07(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(olc, subst={"ph": "ph", "ps": "ph"})  # ⊢ wi(ph, wo(ph, ph))
    return proof.qed(_step_1)


@pm1_2.proof
def prove_pm1_2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, ph), ph)
    return proof.qed(_step_3)


@oridm.proof
def prove_oridm(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbii


    _step_1 = proof.use(pm1_2, subst={"ph": "ph"})  # ⊢ wi(wo(ph, ph), ph)
    _step_2 = proof.use(pm2_07, subst={"ph": "ph"})  # ⊢ wi(ph, wo(ph, ph))
    _step_3 = proof.use(impbii, _step_1, _step_2)  # ⊢ wb(wo(ph, ph), ph)
    return proof.qed(_step_3)


@pm4_25.proof
def prove_pm4_25(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi


    _step_1 = proof.use(oridm, subst={"ph": "ph"})  # ⊢ wb(wo(ph, ph), ph)
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(ph, wo(ph, ph))
    return proof.qed(_step_2)


@pm2_4.proof
def prove_pm2_4(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(id, subst={"ph": "wo(ph, ps)"})  # ⊢ wi(wo(ph, ps), wo(ph, ps))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, wo(ph, ps)), wo(ph, ps))
    return proof.qed(_step_3)


@pm2_41.proof
def prove_pm2_41(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(olc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ph, ps))
    _step_2 = proof.use(id, subst={"ph": "wo(ph, ps)"})  # ⊢ wi(wo(ph, ps), wo(ph, ps))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ps, wo(ph, ps)), wo(ph, ps))
    return proof.qed(_step_3)


@orim12i.proof
def prove_orim12i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, th)
    _step_1 = proof.use(orcd, _hypothesis_1, subst={"ch": "th"})  # ⊢ wi(ph, wo(ps, th))
    _step_2 = proof.use(olcd, _hypothesis_2, subst={"ch": "ps"})  # ⊢ wi(ch, wo(ps, th))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, ch), wo(ps, th))
    return proof.qed(_step_3)


@orim1i.proof
def prove_orim1i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(id, subst={"ph": "ch"})  # ⊢ wi(ch, ch)
    _step_2 = proof.use(orim12i, _hypothesis_1, _step_1)  # ⊢ wi(wo(ph, ch), wo(ps, ch))
    return proof.qed(_step_2)


@orim2i.proof
def prove_orim2i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(id, subst={"ph": "ch"})  # ⊢ wi(ch, ch)
    _step_2 = proof.use(orim12i, _step_1, _hypothesis_1)  # ⊢ wi(wo(ch, ph), wo(ch, ps))
    return proof.qed(_step_2)


@orim12dALT.proof
def prove_orim12dALT(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con3d, imim12d, syl56


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, ta))
    _step_1 = proof.use(pm2_53, subst={"ph": "ps", "ps": "th"})  # ⊢ wi(wo(ps, th), wi(wn(ps), th))
    _step_2 = proof.use(con3d, _hypothesis_1)  # ⊢ wi(ph, wi(wn(ch), wn(ps)))
    _step_3 = proof.use(
        imim12d,
        _step_2,
        _hypothesis_2,
    )  # ⊢ wi(ph, wi(wi(wn(ps), th), wi(wn(ch), ta)))
    _step_4 = proof.use(pm2_54, subst={"ph": "ch", "ps": "ta"})  # ⊢ wi(wi(wn(ch), ta), wo(ch, ta))
    _step_5 = proof.use(syl56, _step_1, _step_3, _step_4)  # ⊢ wi(ph, wi(wo(ps, th), wo(ch, ta)))
    return proof.qed(_step_5)


@orbi2i.proof
def prove_orbi2i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi, biimpri, impbii


    _hypothesis_1, = proof.hypotheses  # ⊢ wb(ph, ps)
    _step_1 = proof.use(biimpi, _hypothesis_1)  # ⊢ wi(ph, ps)
    _step_2 = proof.use(orim2i, _step_1, subst={"ch": "ch"})  # ⊢ wi(wo(ch, ph), wo(ch, ps))
    _step_3 = proof.use(biimpri, _hypothesis_1)  # ⊢ wi(ps, ph)
    _step_4 = proof.use(orim2i, _step_3, subst={"ch": "ch"})  # ⊢ wi(wo(ch, ps), wo(ch, ph))
    _step_5 = proof.use(impbii, _step_2, _step_4)  # ⊢ wb(wo(ch, ph), wo(ch, ps))
    return proof.qed(_step_5)


@orbi1i.proof
def prove_orbi1i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitri


    _hypothesis_1, = proof.hypotheses  # ⊢ wb(ph, ps)
    _step_1 = proof.use(orcom, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wo(ph, ch), wo(ch, ph))
    _step_2 = proof.use(orbi2i, _hypothesis_1, subst={"ch": "ch"})  # ⊢ wb(wo(ch, ph), wo(ch, ps))
    _step_3 = proof.use(orcom, subst={"ph": "ch", "ps": "ps"})  # ⊢ wb(wo(ch, ps), wo(ps, ch))
    _step_4 = proof.use(mm_3bitri, _step_1, _step_2, _step_3)  # ⊢ wb(wo(ph, ch), wo(ps, ch))
    return proof.qed(_step_4)


@orbi12i.proof
def prove_orbi12i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wb(ph, ps); wb(ch, th)
    _step_1 = proof.use(orbi2i, _hypothesis_2, subst={"ch": "ph"})  # ⊢ wb(wo(ph, ch), wo(ph, th))
    _step_2 = proof.use(orbi1i, _hypothesis_1, subst={"ch": "th"})  # ⊢ wb(wo(ph, th), wo(ps, th))
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(wo(ph, ch), wo(ps, th))
    return proof.qed(_step_3)


@orbi2d.proof
def prove_orbi2d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import imbi2d, mm_3bitr4g


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wb(ps, ch))
    _step_1 = proof.use(
        imbi2d,
        _hypothesis_1,
        subst={
            "th": "wn(th)",
        },
    )  # ⊢ wi(ph, wb(wi(wn(th), ps), wi(wn(th), ch)))
    _step_2 = proof.use(df_or, subst={"ph": "th", "ps": "ps"})  # ⊢ wb(wo(th, ps), wi(wn(th), ps))
    _step_3 = proof.use(df_or, subst={"ph": "th", "ps": "ch"})  # ⊢ wb(wo(th, ch), wi(wn(th), ch))
    _step_4 = proof.use(
        mm_3bitr4g,
        _step_1,
        _step_2,
        _step_3,
    )  # ⊢ wi(ph, wb(wo(th, ps), wo(th, ch)))
    return proof.qed(_step_4)


@orbi1d.proof
def prove_orbi1d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4g


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wb(ps, ch))
    _step_1 = proof.use(
        orbi2d,
        _hypothesis_1,
        subst={
            "th": "th",
        },
    )  # ⊢ wi(ph, wb(wo(th, ps), wo(th, ch)))
    _step_2 = proof.use(orcom, subst={"ph": "ps", "ps": "th"})  # ⊢ wb(wo(ps, th), wo(th, ps))
    _step_3 = proof.use(orcom, subst={"ph": "ch", "ps": "th"})  # ⊢ wb(wo(ch, th), wo(th, ch))
    _step_4 = proof.use(
        mm_3bitr4g,
        _step_1,
        _step_2,
        _step_3,
    )  # ⊢ wi(ph, wb(wo(ps, th), wo(ch, th)))
    return proof.qed(_step_4)


@orbi1.proof
def prove_orbi1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "wb(ph, ps)"})  # ⊢ wi(wb(ph, ps), wb(ph, ps))
    _step_2 = proof.use(
        orbi1d,
        _step_1,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wb(ph, ps), wb(wo(ph, ch), wo(ps, ch)))
    return proof.qed(_step_2)


@orbi12d.proof
def prove_orbi12d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitrd


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wb(ps, ch)); wi(ph, wb(th, ta))
    _step_1 = proof.use(
        orbi1d,
        _hypothesis_1,
        subst={
            "th": "th",
        },
    )  # ⊢ wi(ph, wb(wo(ps, th), wo(ch, th)))
    _step_2 = proof.use(
        orbi2d,
        _hypothesis_2,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(ph, wb(wo(ch, th), wo(ch, ta)))
    _step_3 = proof.use(bitrd, _step_1, _step_2)  # ⊢ wi(ph, wb(wo(ps, th), wo(ch, ta)))
    return proof.qed(_step_3)


@pm1_5.proof
def prove_pm1_5(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(ph, wo(ph, ch))
    _step_2 = proof.use(olcd, _step_1, subst={"ch": "ps"})  # ⊢ wi(ph, wo(ps, wo(ph, ch)))
    _step_3 = proof.use(olc, subst={"ph": "ch", "ps": "ph"})  # ⊢ wi(ch, wo(ph, ch))
    _step_4 = proof.use(orim2i, _step_3, subst={"ch": "ps"})  # ⊢ wi(wo(ps, ch), wo(ps, wo(ph, ch)))
    _step_5 = proof.use(jaoi, _step_2, _step_4)  # ⊢ wi(wo(ph, wo(ps, ch)), wo(ps, wo(ph, ch)))
    return proof.qed(_step_5)


@or12.proof
def prove_or12(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbii


    _step_1 = proof.use(
        pm1_5,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wo(ph, wo(ps, ch)), wo(ps, wo(ph, ch)))
    _step_2 = proof.use(
        pm1_5,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wi(wo(ps, wo(ph, ch)), wo(ph, wo(ps, ch)))
    _step_3 = proof.use(impbii, _step_1, _step_2)  # ⊢ wb(wo(ph, wo(ps, ch)), wo(ps, wo(ph, ch)))
    return proof.qed(_step_3)


@orass.proof
def prove_orass(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitri


    _step_1 = proof.use(
        orcom,
        subst={
            "ph": "wo(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(ch, wo(ph, ps)))
    _step_2 = proof.use(
        or12,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wb(wo(ch, wo(ph, ps)), wo(ph, wo(ch, ps)))
    _step_3 = proof.use(orcom, subst={"ph": "ch", "ps": "ps"})  # ⊢ wb(wo(ch, ps), wo(ps, ch))
    _step_4 = proof.use(
        orbi2i,
        _step_3,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wo(ph, wo(ch, ps)), wo(ph, wo(ps, ch)))
    _step_5 = proof.use(
        mm_3bitri,
        _step_1,
        _step_2,
        _step_4,
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(ph, wo(ps, ch)))
    return proof.qed(_step_5)


@pm2_31.proof
def prove_pm2_31(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpri


    _step_1 = proof.use(
        orass,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(ph, wo(ps, ch)))
    _step_2 = proof.use(biimpri, _step_1)  # ⊢ wi(wo(ph, wo(ps, ch)), wo(wo(ph, ps), ch))
    return proof.qed(_step_2)


@pm2_32.proof
def prove_pm2_32(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi


    _step_1 = proof.use(
        orass,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(ph, wo(ps, ch)))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wo(wo(ph, ps), ch), wo(ph, wo(ps, ch)))
    return proof.qed(_step_2)


@pm2_3.proof
def prove_pm2_3(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(pm1_4, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(wo(ps, ch), wo(ch, ps))
    _step_2 = proof.use(
        orim2i,
        _step_1,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wi(wo(ph, wo(ps, ch)), wo(ph, wo(ch, ps)))
    return proof.qed(_step_2)


@or32.proof
def prove_or32(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitri


    _step_1 = proof.use(
        orass,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(ph, wo(ps, ch)))
    _step_2 = proof.use(
        or12,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(ph, wo(ps, ch)), wo(ps, wo(ph, ch)))
    _step_3 = proof.use(
        orcom,
        subst={
            "ph": "ps",
            "ps": "wo(ph, ch)",
        },
    )  # ⊢ wb(wo(ps, wo(ph, ch)), wo(wo(ph, ch), ps))
    _step_4 = proof.use(
        mm_3bitri,
        _step_1,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(wo(ph, ch), ps))
    return proof.qed(_step_4)


@or4.proof
def prove_or4(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4i


    _step_1 = proof.use(
        or12,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wb(wo(ps, wo(ch, th)), wo(ch, wo(ps, th)))
    _step_2 = proof.use(
        orbi2i,
        _step_1,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wo(ph, wo(ps, wo(ch, th))), wo(ph, wo(ch, wo(ps, th))))
    _step_3 = proof.use(
        orass,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wo(ch, th)",
        },
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, th)), wo(ph, wo(ps, wo(ch, th))))
    _step_4 = proof.use(
        orass,
        subst={
            "ph": "ph",
            "ps": "ch",
            "ch": "wo(ps, th)",
        },
    )  # ⊢ wb(wo(wo(ph, ch), wo(ps, th)), wo(ph, wo(ch, wo(ps, th))))
    _step_5 = proof.use(
        mm_3bitr4i,
        _step_2,
        _step_3,
        _step_4,
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, th)), wo(wo(ph, ch), wo(ps, th)))
    return proof.qed(_step_5)


@or42.proof
def prove_or42(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri


    _step_1 = proof.use(
        or4,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
            "th": "th",
        },
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, th)), wo(wo(ph, ch), wo(ps, th)))
    _step_2 = proof.use(orcom, subst={"ph": "ps", "ps": "th"})  # ⊢ wb(wo(ps, th), wo(th, ps))
    _step_3 = proof.use(
        orbi2i,
        _step_2,
        subst={
            "ch": "wo(ph, ch)",
        },
    )  # ⊢ wb(wo(wo(ph, ch), wo(ps, th)), wo(wo(ph, ch), wo(th, ps)))
    _step_4 = proof.use(
        bitri,
        _step_1,
        _step_3,
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, th)), wo(wo(ph, ch), wo(th, ps)))
    return proof.qed(_step_4)


@orordi.proof
def prove_orordi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr3i


    _step_1 = proof.use(oridm, subst={"ph": "ph"})  # ⊢ wb(wo(ph, ph), ph)
    _step_2 = proof.use(
        orbi1i,
        _step_1,
        subst={
            "ch": "wo(ps, ch)",
        },
    )  # ⊢ wb(wo(wo(ph, ph), wo(ps, ch)), wo(ph, wo(ps, ch)))
    _step_3 = proof.use(
        or4,
        subst={
            "ph": "ph",
            "ps": "ph",
            "ch": "ps",
            "th": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ph), wo(ps, ch)), wo(wo(ph, ps), wo(ph, ch)))
    _step_4 = proof.use(
        bitr3i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(ph, wo(ps, ch)), wo(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_4)


@orordir.proof
def prove_orordir(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr3i


    _step_1 = proof.use(oridm, subst={"ph": "ch"})  # ⊢ wb(wo(ch, ch), ch)
    _step_2 = proof.use(
        orbi2i,
        _step_1,
        subst={
            "ch": "wo(ph, ps)",
        },
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, ch)), wo(wo(ph, ps), ch))
    _step_3 = proof.use(
        or4,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
            "th": "ch",
        },
    )  # ⊢ wb(wo(wo(ph, ps), wo(ch, ch)), wo(wo(ph, ch), wo(ps, ch)))
    _step_4 = proof.use(
        bitr3i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(wo(ph, ps), ch), wo(wo(ph, ch), wo(ps, ch)))
    return proof.qed(_step_4)


@orimdi.proof
def prove_orimdi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import imbi12i, imdi, mm_3bitr4i


    _step_1 = proof.use(
        imdi,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wn(ph), wi(ps, ch)), wi(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_2 = proof.use(
        df_or,
        subst={
            "ph": "ph",
            "ps": "wi(ps, ch)",
        },
    )  # ⊢ wb(wo(ph, wi(ps, ch)), wi(wn(ph), wi(ps, ch)))
    _step_3 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_4 = proof.use(df_or, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wo(ph, ch), wi(wn(ph), ch))
    _step_5 = proof.use(
        imbi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wi(wo(ph, ps), wo(ph, ch)), wi(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_6 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wo(ph, wi(ps, ch)), wi(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_6)


@pm2_76.proof
def prove_pm2_76(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi


    _step_1 = proof.use(
        orimdi,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(ph, wi(ps, ch)), wi(wo(ph, ps), wo(ph, ch)))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wo(ph, wi(ps, ch)), wi(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_2)


@pm2_85.proof
def prove_pm2_85(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpri


    _step_1 = proof.use(
        orimdi,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(ph, wi(ps, ch)), wi(wo(ph, ps), wo(ph, ch)))
    _step_2 = proof.use(biimpri, _step_1)  # ⊢ wi(wi(wo(ph, ps), wo(ph, ch)), wo(ph, wi(ps, ch)))
    return proof.qed(_step_2)


@pm2_75.proof
def prove_pm2_75(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12


    _step_1 = proof.use(
        pm2_76,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wo(ph, wi(ps, ch)), wi(wo(ph, ps), wo(ph, ch)))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(wo(ph, ps), wi(wo(ph, wi(ps, ch)), wo(ph, ch)))
    return proof.qed(_step_2)


@pm4_78.proof
def prove_pm4_78(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4ri


    _step_1 = proof.use(
        orordi,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wn(ph), wo(ps, ch)), wo(wo(wn(ph), ps), wo(wn(ph), ch)))
    _step_2 = proof.use(
        imor,
        subst={
            "ph": "ph",
            "ps": "wo(ps, ch)",
        },
    )  # ⊢ wb(wi(ph, wo(ps, ch)), wo(wn(ph), wo(ps, ch)))
    _step_3 = proof.use(imor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wi(ph, ps), wo(wn(ph), ps))
    _step_4 = proof.use(imor, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wi(ph, ch), wo(wn(ph), ch))
    _step_5 = proof.use(
        orbi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wo(wi(ph, ps), wi(ph, ch)), wo(wo(wn(ph), ps), wo(wn(ph), ch)))
    _step_6 = proof.use(
        mm_3bitr4ri,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wo(wi(ph, ps), wi(ph, ch)), wi(ph, wo(ps, ch)))
    return proof.qed(_step_6)


@biort.proof
def prove_biort(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s001 import mm_2thd


    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_3 = proof.use(mm_2thd, _step_1, _step_2)  # ⊢ wi(ph, wb(ph, wo(ph, ps)))
    return proof.qed(_step_3)


@biorf.proof
def prove_biorf(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbid2


    _step_1 = proof.use(olc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ph, ps))
    _step_2 = proof.use(orel1, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(wo(ph, ps), ps))
    _step_3 = proof.use(impbid2, _step_1, _step_2)  # ⊢ wi(wn(ph), wb(ps, wo(ph, ps)))
    return proof.qed(_step_3)


@biortn.proof
def prove_biortn(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import notnot, syl


    _step_1 = proof.use(notnot, subst={"ph": "ph"})  # ⊢ wi(ph, wn(wn(ph)))
    _step_2 = proof.use(
        biorf,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
        },
    )  # ⊢ wi(wn(wn(ph)), wb(ps, wo(wn(ph), ps)))
    _step_3 = proof.use(syl, _step_1, _step_2)  # ⊢ wi(ph, wb(ps, wo(wn(ph), ps)))
    return proof.qed(_step_3)


@biorfi.proof
def prove_biorfi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp


    _hypothesis_1, = proof.hypotheses  # ⊢ wn(ph)
    _step_1 = proof.use(biorf, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wb(ps, wo(ph, ps)))
    _step_2 = proof.use(ax_mp, _hypothesis_1, _step_1)  # ⊢ wb(ps, wo(ph, ps))
    return proof.qed(_step_2)


@biorfri.proof
def prove_biorfri(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri


    _hypothesis_1, = proof.hypotheses  # ⊢ wn(ph)
    _step_1 = proof.use(biorfi, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wb(ps, wo(ph, ps))
    _step_2 = proof.use(orcom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wo(ps, ph))
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(ps, wo(ps, ph))
    return proof.qed(_step_3)


@biorfriOLD.proof
def prove_biorfriOLD(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import mt3i
    from metamath_setmm_provider.shards.s001 import impbii


    _hypothesis_1, = proof.hypotheses  # ⊢ wn(ph)
    _step_1 = proof.use(orc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ps, ph))
    _step_2 = proof.use(pm2_53, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wo(ps, ph), wi(wn(ps), ph))
    _step_3 = proof.use(mt3i, _hypothesis_1, _step_2)  # ⊢ wi(wo(ps, ph), ps)
    _step_4 = proof.use(impbii, _step_1, _step_3)  # ⊢ wb(ps, wo(ps, ph))
    return proof.qed(_step_4)


@pm2_26.proof
def prove_pm2_26(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_27


    _step_1 = proof.use(pm2_27, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(wi(ph, ps), ps))
    _step_2 = proof.use(imori, _step_1)  # ⊢ wo(wn(ph), wi(wi(ph, ps), ps))
    return proof.qed(_step_2)


@pm2_63.proof
def prove_pm2_63(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import idd


    _step_1 = proof.use(pm2_53, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(idd, subst={"ph": "wo(ph, ps)", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wi(ps, ps))
    _step_3 = proof.use(jaod, _step_1, _step_2)  # ⊢ wi(wo(ph, ps), wi(wo(wn(ph), ps), ps))
    return proof.qed(_step_3)


@pm2_64.proof
def prove_pm2_64(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12


    _step_1 = proof.use(orel2, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(ps), wi(wo(ph, ps), ph))
    _step_2 = proof.use(jao1i, _step_1)  # ⊢ wi(wo(ph, wn(ps)), wi(wo(ph, ps), ph))
    _step_3 = proof.use(com12, _step_2)  # ⊢ wi(wo(ph, ps), wi(wo(ph, wn(ps)), ph))
    return proof.qed(_step_3)


@pm2_42.proof
def prove_pm2_42(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id, pm2_21


    _step_1 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ph, ps))
    _step_2 = proof.use(id, subst={"ph": "wi(ph, ps)"})  # ⊢ wi(wi(ph, ps), wi(ph, ps))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(wn(ph), wi(ph, ps)), wi(ph, ps))
    return proof.qed(_step_3)


@pm5_11g.proof
def prove_pm5_11g(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_5g


    _step_1 = proof.use(
        pm2_5g,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wn(wi(ph, ps)), wi(wn(ph), ch))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(wi(ph, ps), wi(wn(ph), ch))
    return proof.qed(_step_2)


@pm5_11.proof
def prove_pm5_11(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        pm5_11g,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ps",
        },
    )  # ⊢ wo(wi(ph, ps), wi(wn(ph), ps))
    return proof.qed(_step_1)


@pm5_12.proof
def prove_pm5_12(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_51


    _step_1 = proof.use(
        pm2_51,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wn(wi(ph, ps)), wi(ph, wn(ps)))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(wi(ph, ps), wi(ph, wn(ps)))
    return proof.qed(_step_2)


@pm5_14.proof
def prove_pm5_14(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_521g


    _step_1 = proof.use(
        pm2_521g,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wn(wi(ph, ps)), wi(ps, ch))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(wi(ph, ps), wi(ps, ch))
    return proof.qed(_step_2)


@pm5_13.proof
def prove_pm5_13(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        pm5_14,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ph",
        },
    )  # ⊢ wo(wi(ph, ps), wi(ps, ph))
    return proof.qed(_step_1)


@pm5_55.proof
def prove_pm5_55(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import nsyl5
    from metamath_setmm_provider.shards.s001 import bicomd


    _step_1 = proof.use(biort, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wb(ph, wo(ph, ps)))
    _step_2 = proof.use(bicomd, _step_1)  # ⊢ wi(ph, wb(wo(ph, ps), ph))
    _step_3 = proof.use(biorf, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wb(ps, wo(ph, ps)))
    _step_4 = proof.use(bicomd, _step_3)  # ⊢ wi(wn(ph), wb(wo(ph, ps), ps))
    _step_5 = proof.use(nsyl5, _step_2, _step_4)  # ⊢ wi(wn(wb(wo(ph, ps), ph)), wb(wo(ph, ps), ps))
    _step_6 = proof.use(orri, _step_5)  # ⊢ wo(wb(wo(ph, ps), ph), wb(wo(ph, ps), ps))
    return proof.qed(_step_6)


@oibabs.proof
def prove_oibabs(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1, id, ja
    from metamath_setmm_provider.shards.s001 import impbii


    _step_1 = proof.use(norbi, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(wo(ph, ps)), wb(ph, ps))
    _step_2 = proof.use(id, subst={"ph": "wb(ph, ps)"})  # ⊢ wi(wb(ph, ps), wb(ph, ps))
    _step_3 = proof.use(ja, _step_1, _step_2)  # ⊢ wi(wi(wo(ph, ps), wb(ph, ps)), wb(ph, ps))
    _step_4 = proof.use(
        ax_1,
        subst={
            "ph": "wb(ph, ps)",
            "ps": "wo(ph, ps)",
        },
    )  # ⊢ wi(wb(ph, ps), wi(wo(ph, ps), wb(ph, ps)))
    _step_5 = proof.use(impbii, _step_3, _step_4)  # ⊢ wb(wi(wo(ph, ps), wb(ph, ps)), wb(ph, ps))
    return proof.qed(_step_5)


@orbidi.proof
def prove_orbidi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bibi12i, mm_3bitr4i, pm5_74


    _step_1 = proof.use(
        pm5_74,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wn(ph), wb(ps, ch)), wb(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_2 = proof.use(
        df_or,
        subst={
            "ph": "ph",
            "ps": "wb(ps, ch)",
        },
    )  # ⊢ wb(wo(ph, wb(ps, ch)), wi(wn(ph), wb(ps, ch)))
    _step_3 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_4 = proof.use(df_or, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wo(ph, ch), wi(wn(ph), ch))
    _step_5 = proof.use(
        bibi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wb(wo(ph, ps), wo(ph, ch)), wb(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_6 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wo(ph, wb(ps, ch)), wb(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_6)


@pm5_7.proof
def prove_pm5_7(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bibi12i, bitr2i


    _step_1 = proof.use(
        orbidi,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wb(wo(ch, wb(ph, ps)), wb(wo(ch, ph), wo(ch, ps)))
    _step_2 = proof.use(orcom, subst={"ph": "ch", "ps": "ph"})  # ⊢ wb(wo(ch, ph), wo(ph, ch))
    _step_3 = proof.use(orcom, subst={"ph": "ch", "ps": "ps"})  # ⊢ wb(wo(ch, ps), wo(ps, ch))
    _step_4 = proof.use(
        bibi12i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wb(wo(ch, ph), wo(ch, ps)), wb(wo(ph, ch), wo(ps, ch)))
    _step_5 = proof.use(
        bitr2i,
        _step_1,
        _step_4,
    )  # ⊢ wb(wb(wo(ph, ch), wo(ps, ch)), wo(ch, wb(ph, ps)))
    return proof.qed(_step_5)


@jaoian.proof
def prove_jaoian(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import ex, imp


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(wa(ph, ps), ch); wi(wa(th, ps), ch)
    _step_1 = proof.use(ex, _hypothesis_1)  # ⊢ wi(ph, wi(ps, ch))
    _step_2 = proof.use(ex, _hypothesis_2)  # ⊢ wi(th, wi(ps, ch))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, th), wi(ps, ch))
    _step_4 = proof.use(imp, _step_3)  # ⊢ wi(wa(wo(ph, th), ps), ch)
    return proof.qed(_step_4)


@jaodan.proof
def prove_jaodan(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import ex, imp


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(wa(ph, ps), ch); wi(wa(ph, th), ch)
    _step_1 = proof.use(ex, _hypothesis_1)  # ⊢ wi(ph, wi(ps, ch))
    _step_2 = proof.use(ex, _hypothesis_2)  # ⊢ wi(ph, wi(th, ch))
    _step_3 = proof.use(jaod, _step_1, _step_2)  # ⊢ wi(ph, wi(wo(ps, th), ch))
    _step_4 = proof.use(imp, _step_3)  # ⊢ wi(wa(ph, wo(ps, th)), ch)
    return proof.qed(_step_4)


@mpjaodan.proof
def prove_mpjaodan(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s003 import mpdan


    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(wa(ph, ps), ch); wi(wa(ph, th), ch); wi(ph, wo(ps, th))
    _step_1 = proof.use(jaodan, _hypothesis_1, _hypothesis_2)  # ⊢ wi(wa(ph, wo(ps, th)), ch)
    _step_2 = proof.use(mpdan, _hypothesis_3, _step_1)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@pm3_44.proof
def prove_pm3_44(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s004 import jaao


    _step_1 = proof.use(id, subst={"ph": "wi(ps, ph)"})  # ⊢ wi(wi(ps, ph), wi(ps, ph))
    _step_2 = proof.use(id, subst={"ph": "wi(ch, ph)"})  # ⊢ wi(wi(ch, ph), wi(ch, ph))
    _step_3 = proof.use(
        jaao,
        _step_1,
        _step_2,
    )  # ⊢ wi(wa(wi(ps, ph), wi(ch, ph)), wi(wo(ps, ch), ph))
    return proof.qed(_step_3)


@jao.proof
def prove_jao(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import ex


    _step_1 = proof.use(
        pm3_44,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wi(wa(wi(ph, ps), wi(ch, ps)), wi(wo(ph, ch), ps))
    _step_2 = proof.use(ex, _step_1)  # ⊢ wi(wi(ph, ps), wi(wi(ch, ps), wi(wo(ph, ch), ps)))
    return proof.qed(_step_2)


@jaob.proof
def prove_jaob(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import imim1i
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s002 import jca


    _step_1 = proof.use(
        pm2_67_2,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wi(wo(ph, ch), ps), wi(ph, ps))
    _step_2 = proof.use(olc, subst={"ph": "ch", "ps": "ph"})  # ⊢ wi(ch, wo(ph, ch))
    _step_3 = proof.use(imim1i, _step_2, subst={"ch": "ps"})  # ⊢ wi(wi(wo(ph, ch), ps), wi(ch, ps))
    _step_4 = proof.use(
        jca,
        _step_1,
        _step_3,
    )  # ⊢ wi(wi(wo(ph, ch), ps), wa(wi(ph, ps), wi(ch, ps)))
    _step_5 = proof.use(
        pm3_44,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wi(wa(wi(ph, ps), wi(ch, ps)), wi(wo(ph, ch), ps))
    _step_6 = proof.use(
        impbii,
        _step_4,
        _step_5,
    )  # ⊢ wb(wi(wo(ph, ch), ps), wa(wi(ph, ps), wi(ch, ps)))
    return proof.qed(_step_6)


@pm4_77.proof
def prove_pm4_77(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi


    _step_1 = proof.use(
        jaob,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wo(ps, ch), ph), wa(wi(ps, ph), wi(ch, ph)))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wa(wi(ps, ph), wi(ch, ph)), wi(wo(ps, ch), ph))
    return proof.qed(_step_2)


@pm3_48.proof
def prove_pm3_48(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import imim2i
    from metamath_setmm_provider.shards.s004 import jaao


    _step_1 = proof.use(orc, subst={"ph": "ps", "ps": "th"})  # ⊢ wi(ps, wo(ps, th))
    _step_2 = proof.use(imim2i, _step_1, subst={"ch": "ph"})  # ⊢ wi(wi(ph, ps), wi(ph, wo(ps, th)))
    _step_3 = proof.use(olc, subst={"ph": "th", "ps": "ps"})  # ⊢ wi(th, wo(ps, th))
    _step_4 = proof.use(imim2i, _step_3, subst={"ch": "ch"})  # ⊢ wi(wi(ch, th), wi(ch, wo(ps, th)))
    _step_5 = proof.use(
        jaao,
        _step_2,
        _step_4,
    )  # ⊢ wi(wa(wi(ph, ps), wi(ch, th)), wi(wo(ph, ch), wo(ps, th)))
    return proof.qed(_step_5)


@orim12d.proof
def prove_orim12d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import syl2anc


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, ta))
    _step_1 = proof.use(
        pm3_48,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
            "th": "ta",
        },
    )  # ⊢ wi(wa(wi(ps, ch), wi(th, ta)), wi(wo(ps, th), wo(ch, ta)))
    _step_2 = proof.use(
        syl2anc,
        _hypothesis_1,
        _hypothesis_2,
        _step_1,
    )  # ⊢ wi(ph, wi(wo(ps, th), wo(ch, ta)))
    return proof.qed(_step_2)


@orim12da.proof
def prove_orim12da(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import mpd
    from metamath_setmm_provider.shards.s002 import ex


    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(wa(ph, ps), th); wi(wa(ph, ch), ta); wi(ph, wo(ps, ch))
    _step_1 = proof.use(ex, _hypothesis_1)  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(ex, _hypothesis_2)  # ⊢ wi(ph, wi(ch, ta))
    _step_3 = proof.use(orim12d, _step_1, _step_2)  # ⊢ wi(ph, wi(wo(ps, ch), wo(th, ta)))
    _step_4 = proof.use(mpd, _hypothesis_3, _step_3)  # ⊢ wi(ph, wo(th, ta))
    return proof.qed(_step_4)


@orim1d.proof
def prove_orim1d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import idd


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(idd, subst={"ph": "ph", "ps": "th"})  # ⊢ wi(ph, wi(th, th))
    _step_2 = proof.use(orim12d, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wo(ps, th), wo(ch, th)))
    return proof.qed(_step_2)


@orim2d.proof
def prove_orim2d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import idd


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(idd, subst={"ph": "ph", "ps": "th"})  # ⊢ wi(ph, wi(th, th))
    _step_2 = proof.use(orim12d, _step_1, _hypothesis_1)  # ⊢ wi(ph, wi(wo(th, ps), wo(th, ch)))
    return proof.qed(_step_2)


@orim2.proof
def prove_orim2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "wi(ps, ch)"})  # ⊢ wi(wi(ps, ch), wi(ps, ch))
    _step_2 = proof.use(
        orim2d,
        _step_1,
        subst={
            "th": "ph",
        },
    )  # ⊢ wi(wi(ps, ch), wi(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_2)


@pm2_38.proof
def prove_pm2_38(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id


    _step_1 = proof.use(id, subst={"ph": "wi(ps, ch)"})  # ⊢ wi(wi(ps, ch), wi(ps, ch))
    _step_2 = proof.use(
        orim1d,
        _step_1,
        subst={
            "th": "ph",
        },
    )  # ⊢ wi(wi(ps, ch), wi(wo(ps, ph), wo(ch, ph)))
    return proof.qed(_step_2)


@pm2_36.proof
def prove_pm2_36(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl5


    _step_1 = proof.use(pm1_4, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wo(ps, ph))
    _step_2 = proof.use(
        pm2_38,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wi(ps, ch), wi(wo(ps, ph), wo(ch, ph)))
    _step_3 = proof.use(syl5, _step_1, _step_2)  # ⊢ wi(wi(ps, ch), wi(wo(ph, ps), wo(ch, ph)))
    return proof.qed(_step_3)


@pm2_37.proof
def prove_pm2_37(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl6


    _step_1 = proof.use(
        pm2_38,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wi(ps, ch), wi(wo(ps, ph), wo(ch, ph)))
    _step_2 = proof.use(pm1_4, subst={"ph": "ch", "ps": "ph"})  # ⊢ wi(wo(ch, ph), wo(ph, ch))
    _step_3 = proof.use(syl6, _step_1, _step_2)  # ⊢ wi(wi(ps, ch), wi(wo(ps, ph), wo(ph, ch)))
    return proof.qed(_step_3)


@pm2_81.proof
def prove_pm2_81(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl6


    _step_1 = proof.use(
        orim2,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wi(ch, th)",
        },
    )  # ⊢ wi(wi(ps, wi(ch, th)), wi(wo(ph, ps), wo(ph, wi(ch, th))))
    _step_2 = proof.use(
        pm2_76,
        subst={
            "ph": "ph",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wi(wo(ph, wi(ch, th)), wi(wo(ph, ch), wo(ph, th)))
    _step_3 = proof.use(
        syl6,
        _step_1,
        _step_2,
    )  # ⊢ wi(wi(ps, wi(ch, th)), wi(wo(ph, ps), wi(wo(ph, ch), wo(ph, th))))
    return proof.qed(_step_3)


@pm2_8.proof
def prove_pm2_8(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con1d


    _step_1 = proof.use(pm2_53, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wo(ph, ps), wi(wn(ph), ps))
    _step_2 = proof.use(con1d, _step_1)  # ⊢ wi(wo(ph, ps), wi(wn(ps), ph))
    _step_3 = proof.use(
        orim1d,
        _step_2,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wo(ph, ps), wi(wo(wn(ps), ch), wo(ph, ch)))
    return proof.qed(_step_3)


@pm2_73.proof
def prove_pm2_73(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        pm2_621,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wo(ph, ps), ps))
    _step_2 = proof.use(
        orim1d,
        _step_1,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wo(wo(ph, ps), ch), wo(ps, ch)))
    return proof.qed(_step_2)


@pm2_74.proof
def prove_pm2_74(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1, ja


    _step_1 = proof.use(orel2, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(ps), wi(wo(ph, ps), ph))
    _step_2 = proof.use(
        ax_1,
        subst={
            "ph": "ph",
            "ps": "wo(ph, ps)",
        },
    )  # ⊢ wi(ph, wi(wo(ph, ps), ph))
    _step_3 = proof.use(ja, _step_1, _step_2)  # ⊢ wi(wi(ps, ph), wi(wo(ph, ps), ph))
    _step_4 = proof.use(
        orim1d,
        _step_3,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wi(ps, ph), wi(wo(wo(ph, ps), ch), wo(ph, ch)))
    return proof.qed(_step_4)


@pm2_82.proof
def prove_pm2_82(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_24


    _step_1 = proof.use(pm2_24, subst={"ph": "ch", "ps": "ps"})  # ⊢ wi(ch, wi(wn(ch), ps))
    _step_2 = proof.use(
        orim2d,
        _step_1,
        subst={
            "th": "ph",
        },
    )  # ⊢ wi(ch, wi(wo(ph, wn(ch)), wo(ph, ps)))
    _step_3 = proof.use(jao1i, _step_2)  # ⊢ wi(wo(wo(ph, ps), ch), wi(wo(ph, wn(ch)), wo(ph, ps)))
    _step_4 = proof.use(
        orim1d,
        _step_3,
        subst={
            "th": "th",
        },
    )  # ⊢ wi(wo(wo(ph, ps), ch), wi(wo(wo(ph, wn(ch)), th), wo(wo(ph, ps), th)))
    return proof.qed(_step_4)


@pm4_39.proof
def prove_pm4_39(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpl, simpr


    _step_1 = proof.use(
        simpl,
        subst={
            "ph": "wb(ph, ch)",
            "ps": "wb(ps, th)",
        },
    )  # ⊢ wi(wa(wb(ph, ch), wb(ps, th)), wb(ph, ch))
    _step_2 = proof.use(
        simpr,
        subst={
            "ph": "wb(ph, ch)",
            "ps": "wb(ps, th)",
        },
    )  # ⊢ wi(wa(wb(ph, ch), wb(ps, th)), wb(ps, th))
    _step_3 = proof.use(
        orbi12d,
        _step_1,
        _step_2,
    )  # ⊢ wi(wa(wb(ph, ch), wb(ps, th)), wb(wo(ph, ps), wo(ch, th)))
    return proof.qed(_step_3)


@pm5_53.proof
def prove_pm5_53(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s003 import bianbi


    _step_1 = proof.use(
        jaob,
        subst={
            "ph": "wo(ph, ps)",
            "ps": "th",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wo(wo(ph, ps), ch), th), wa(wi(wo(ph, ps), th), wi(ch, th)))
    _step_2 = proof.use(
        jaob,
        subst={
            "ph": "ph",
            "ps": "th",
            "ch": "ps",
        },
    )  # ⊢ wb(wi(wo(ph, ps), th), wa(wi(ph, th), wi(ps, th)))
    _step_3 = proof.use(
        bianbi,
        _step_1,
        _step_2,
    )  # ⊢ wb(wi(wo(wo(ph, ps), ch), th), wa(wa(wi(ph, th), wi(ps, th)), wi(ch, th)))
    return proof.qed(_step_3)


@jaoi2.proof
def prove_jaoi2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylbi
    from metamath_setmm_provider.shards.s005 import pm5_63


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wo(ph, wa(wn(ph), ch)), ps)
    _step_1 = proof.use(
        pm5_63,
        subst={
            "ph": "ph",
            "ps": "ch",
        },
    )  # ⊢ wb(wo(ph, ch), wo(ph, wa(wn(ph), ch)))
    _step_2 = proof.use(sylbi, _step_1, _hypothesis_1)  # ⊢ wi(wo(ph, ch), ps)
    return proof.qed(_step_2)


@jaoi3.proof
def prove_jaoi3(proof: TheoryProofAuthor) -> CompleteProof:

    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(wa(wn(ph), ch), ps)
    _step_1 = proof.use(jaoi, _hypothesis_1, _hypothesis_2)  # ⊢ wi(wo(ph, wa(wn(ph), ch)), ps)
    _step_2 = proof.use(jaoi2, _step_1)  # ⊢ wi(wo(ph, ch), ps)
    return proof.qed(_step_2)


@ornld.proof
def prove_ornld(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import expimpd
    from metamath_setmm_provider.shards.s004 import pm3_35


    _step_1 = proof.use(
        pm3_35,
        subst={
            "ph": "ph",
            "ps": "wo(th, ta)",
        },
    )  # ⊢ wi(wa(ph, wi(ph, wo(th, ta))), wo(th, ta))
    _step_2 = proof.use(ord, _step_1)  # ⊢ wi(wa(ph, wi(ph, wo(th, ta))), wi(wn(th), ta))
    _step_3 = proof.use(expimpd, _step_2)  # ⊢ wi(ph, wi(wa(wi(ph, wo(th, ta)), wn(th)), ta))
    return proof.qed(_step_3)

__all__ = (
    'df_or',
    'pm4_64',
    'pm4_66',
    'pm2_53',
    'pm2_54',
    'imor',
    'imori',
    'imorri',
    'pm4_62',
    'jaoi',
    'jao1i',
    'jaod',
    'mpjaod',
    'ori',
    'orri',
    'orrd',
    'ord',
    'orci',
    'olci',
    'orc',
    'olc',
    'pm1_4',
    'orcom',
    'orcomd',
    'orcoms',
    'orcd',
    'olcd',
    'orcs',
    'olcs',
    'olcnd',
    'orcnd',
    'mtord',
    'pm3_2ni',
    'pm2_45',
    'pm2_46',
    'pm2_47',
    'pm2_48',
    'pm2_49',
    'norbi',
    'nbior',
    'orel1',
    'pm2_25',
    'orel2',
    'pm2_67_2',
    'pm2_67',
    'exmid',
    'exmidd',
    'pm2_1',
    'pm2_13',
    'pm2_621',
    'pm2_62',
    'pm2_68',
    'dfor2',
    'pm2_07',
    'pm1_2',
    'oridm',
    'pm4_25',
    'pm2_4',
    'pm2_41',
    'orim12i',
    'orim1i',
    'orim2i',
    'orim12dALT',
    'orbi2i',
    'orbi1i',
    'orbi12i',
    'orbi2d',
    'orbi1d',
    'orbi1',
    'orbi12d',
    'pm1_5',
    'or12',
    'orass',
    'pm2_31',
    'pm2_32',
    'pm2_3',
    'or32',
    'or4',
    'or42',
    'orordi',
    'orordir',
    'orimdi',
    'pm2_76',
    'pm2_85',
    'pm2_75',
    'pm4_78',
    'biort',
    'biorf',
    'biortn',
    'biorfi',
    'biorfri',
    'biorfriOLD',
    'pm2_26',
    'pm2_63',
    'pm2_64',
    'pm2_42',
    'pm5_11g',
    'pm5_11',
    'pm5_12',
    'pm5_14',
    'pm5_13',
    'pm5_55',
    'oibabs',
    'orbidi',
    'pm5_7',
    'jaoian',
    'jaodan',
    'mpjaodan',
    'pm3_44',
    'jao',
    'jaob',
    'pm4_77',
    'pm3_48',
    'orim12d',
    'orim12da',
    'orim1d',
    'orim2d',
    'orim2',
    'pm2_38',
    'pm2_36',
    'pm2_37',
    'pm2_81',
    'pm2_8',
    'pm2_73',
    'pm2_74',
    'pm2_82',
    'pm4_39',
    'pm5_53',
    'jaoi2',
    'jaoi3',
    'ornld',
)

FORMATION_BINDINGS_BY_LABEL: Mapping[str, FormationBinding] = MappingProxyType({
    'wo': wo,
})
