# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from metamath_setmm_provider.shards.s000 import (
    a1d as a1d,
)
from metamath_setmm_provider.shards.s000 import (
    a1dd as a1dd,
)
from metamath_setmm_provider.shards.s000 import (
    a1ddd as a1ddd,
)
from metamath_setmm_provider.shards.s000 import (
    a1i as a1i,
)
from metamath_setmm_provider.shards.s000 import (
    a1i13 as a1i13,
)
from metamath_setmm_provider.shards.s000 import (
    a2d as a2d,
)
from metamath_setmm_provider.shards.s000 import (
    a2i as a2i,
)
from metamath_setmm_provider.shards.s000 import (
    ax1w as ax1w,
)
from metamath_setmm_provider.shards.s000 import (
    com3l as com3l,
)
from metamath_setmm_provider.shards.s000 import (
    com3r as com3r,
)
from metamath_setmm_provider.shards.s000 import (
    com4l as com4l,
)
from metamath_setmm_provider.shards.s000 import (
    com4r as com4r,
)
from metamath_setmm_provider.shards.s000 import (
    com4t as com4t,
)
from metamath_setmm_provider.shards.s000 import (
    com5l as com5l,
)
from metamath_setmm_provider.shards.s000 import (
    com5r as com5r,
)
from metamath_setmm_provider.shards.s000 import (
    com12 as com12,
)
from metamath_setmm_provider.shards.s000 import (
    com13 as com13,
)
from metamath_setmm_provider.shards.s000 import (
    com14 as com14,
)
from metamath_setmm_provider.shards.s000 import (
    com15 as com15,
)
from metamath_setmm_provider.shards.s000 import (
    com23 as com23,
)
from metamath_setmm_provider.shards.s000 import (
    com24 as com24,
)
from metamath_setmm_provider.shards.s000 import (
    com25 as com25,
)
from metamath_setmm_provider.shards.s000 import (
    com34 as com34,
)
from metamath_setmm_provider.shards.s000 import (
    com35 as com35,
)
from metamath_setmm_provider.shards.s000 import (
    com45 as com45,
)
from metamath_setmm_provider.shards.s000 import (
    com52l as com52l,
)
from metamath_setmm_provider.shards.s000 import (
    com52r as com52r,
)
from metamath_setmm_provider.shards.s000 import (
    embantd as embantd,
)
from metamath_setmm_provider.shards.s000 import (
    id as id,
)
from metamath_setmm_provider.shards.s000 import (
    idALT as idALT,
)
from metamath_setmm_provider.shards.s000 import (
    idd as idd,
)
from metamath_setmm_provider.shards.s000 import (
    imim1 as imim1,
)
from metamath_setmm_provider.shards.s000 import (
    imim1d as imim1d,
)
from metamath_setmm_provider.shards.s000 import (
    imim1i as imim1i,
)
from metamath_setmm_provider.shards.s000 import (
    imim2 as imim2,
)
from metamath_setmm_provider.shards.s000 import (
    imim2d as imim2d,
)
from metamath_setmm_provider.shards.s000 import (
    imim2i as imim2i,
)
from metamath_setmm_provider.shards.s000 import (
    imim3i as imim3i,
)
from metamath_setmm_provider.shards.s000 import (
    imim12 as imim12,
)
from metamath_setmm_provider.shards.s000 import (
    imim12d as imim12d,
)
from metamath_setmm_provider.shards.s000 import (
    imim12i as imim12i,
)
from metamath_setmm_provider.shards.s000 import (
    jarr as jarr,
)
from metamath_setmm_provider.shards.s000 import (
    jarri as jarri,
)
from metamath_setmm_provider.shards.s000 import (
    mm_2a1 as mm_2a1,
)
from metamath_setmm_provider.shards.s000 import (
    mm_2a1d as mm_2a1d,
)
from metamath_setmm_provider.shards.s000 import (
    mm_2a1dd as mm_2a1dd,
)
from metamath_setmm_provider.shards.s000 import (
    mm_2a1i as mm_2a1i,
)
from metamath_setmm_provider.shards.s000 import (
    mm_3syl as mm_3syl,
)
from metamath_setmm_provider.shards.s000 import (
    mm_3syld as mm_3syld,
)
from metamath_setmm_provider.shards.s000 import (
    mm_4syl as mm_4syl,
)
from metamath_setmm_provider.shards.s000 import (
    mp1i as mp1i,
)
from metamath_setmm_provider.shards.s000 import (
    mp2 as mp2,
)
from metamath_setmm_provider.shards.s000 import (
    mp2b as mp2b,
)
from metamath_setmm_provider.shards.s000 import (
    mp2d as mp2d,
)
from metamath_setmm_provider.shards.s000 import (
    mpcom as mpcom,
)
from metamath_setmm_provider.shards.s000 import (
    mpd as mpd,
)
from metamath_setmm_provider.shards.s000 import (
    mpdd as mpdd,
)
from metamath_setmm_provider.shards.s000 import (
    mpdi as mpdi,
)
from metamath_setmm_provider.shards.s000 import (
    mpi as mpi,
)
from metamath_setmm_provider.shards.s000 import (
    mpid as mpid,
)
from metamath_setmm_provider.shards.s000 import (
    mpii as mpii,
)
from metamath_setmm_provider.shards.s000 import (
    mpisyl as mpisyl,
)
from metamath_setmm_provider.shards.s000 import (
    mpsyl as mpsyl,
)
from metamath_setmm_provider.shards.s000 import (
    mpsylsyld as mpsylsyld,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_04 as pm2_04,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_27 as pm2_27,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_43 as pm2_43,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_43a as pm2_43a,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_43b as pm2_43b,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_43d as pm2_43d,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_43i as pm2_43i,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_83 as pm2_83,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_86 as pm2_86,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_86d as pm2_86d,
)
from metamath_setmm_provider.shards.s000 import (
    pm2_86i as pm2_86i,
)
from metamath_setmm_provider.shards.s000 import (
    syl as syl,
)
from metamath_setmm_provider.shards.s000 import (
    syl2im as syl2im,
)
from metamath_setmm_provider.shards.s000 import (
    syl2imc as syl2imc,
)
from metamath_setmm_provider.shards.s000 import (
    syl3c as syl3c,
)
from metamath_setmm_provider.shards.s000 import (
    syl5 as syl5,
)
from metamath_setmm_provider.shards.s000 import (
    syl5com as syl5com,
)
from metamath_setmm_provider.shards.s000 import (
    syl5d as syl5d,
)
from metamath_setmm_provider.shards.s000 import (
    syl6 as syl6,
)
from metamath_setmm_provider.shards.s000 import (
    syl6c as syl6c,
)
from metamath_setmm_provider.shards.s000 import (
    syl6ci as syl6ci,
)
from metamath_setmm_provider.shards.s000 import (
    syl6com as syl6com,
)
from metamath_setmm_provider.shards.s000 import (
    syl6d as syl6d,
)
from metamath_setmm_provider.shards.s000 import (
    syl6mpi as syl6mpi,
)
from metamath_setmm_provider.shards.s000 import (
    syl7 as syl7,
)
from metamath_setmm_provider.shards.s000 import (
    syl8 as syl8,
)
from metamath_setmm_provider.shards.s000 import (
    syl9 as syl9,
)
from metamath_setmm_provider.shards.s000 import (
    syl9r as syl9r,
)
from metamath_setmm_provider.shards.s000 import (
    syl10 as syl10,
)
from metamath_setmm_provider.shards.s000 import (
    syl11 as syl11,
)
from metamath_setmm_provider.shards.s000 import (
    syl56 as syl56,
)
from metamath_setmm_provider.shards.s000 import (
    sylc as sylc,
)
from metamath_setmm_provider.shards.s000 import (
    sylcom as sylcom,
)
from metamath_setmm_provider.shards.s000 import (
    syld as syld,
)
from metamath_setmm_provider.shards.s000 import (
    syldc as syldc,
)
from metamath_setmm_provider.shards.s000 import (
    syldd as syldd,
)
from metamath_setmm_provider.shards.s000 import (
    syli as syli,
)
from metamath_setmm_provider.shards.s000 import (
    sylsyld as sylsyld,
)
from metamath_setmm_provider.shards.s004 import (
    imimorb as imimorb,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_72 as pm4_72,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.theory import TheoryProofAuthor

if str(mp2.id) != (
    'urn:uuid:55939789-39fb-5a0b-9edd-41986858a3d7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mp2b.id) != (
    'urn:uuid:6b0f92d3-3ac2-597f-a6e2-9e6b96762924'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a1i.id) != (
    'urn:uuid:483db224-6436-5489-b125-f0312b8427a2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_2a1i.id) != (
    'urn:uuid:41a1cfb2-12e9-55a7-b6ce-80f3a675a3b9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ax1w.id) != (
    'urn:uuid:3e832751-15c5-525d-8da1-96882579634f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mp1i.id) != (
    'urn:uuid:9338d71d-a39c-560a-b6a3-67fc40366c46'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a2i.id) != (
    'urn:uuid:21767d82-1496-5ced-8486-3f7b5b8ba2bd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpd.id) != (
    'urn:uuid:fba6dab9-ed2d-5a68-abd3-085c7b856df1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim2i.id) != (
    'urn:uuid:6b8c1640-0673-5a6c-a542-b65ce03d7985'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl.id) != (
    'urn:uuid:4fa2ca7b-6613-56ec-8f15-987c1d88e828'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_3syl.id) != (
    'urn:uuid:c2f1d49e-da40-5522-b1b6-8fdc9bb09a7e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_4syl.id) != (
    'urn:uuid:ce1761c5-597a-5a56-9a25-5066af53bd4f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpi.id) != (
    'urn:uuid:32bfe4e4-3fc4-5f80-99de-2fd6881bd98b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpisyl.id) != (
    'urn:uuid:90d511e9-66c6-5ecc-9b6f-336d53709006'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(id.id) != (
    'urn:uuid:f11b7019-7f94-55f6-ab7e-dbad6da0df29'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(idALT.id) != (
    'urn:uuid:31b2cefb-c077-5c27-a910-58067ff46ad9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(idd.id) != (
    'urn:uuid:8b657d0f-d214-52fa-a2d0-95c2a4a6c469'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a1d.id) != (
    'urn:uuid:c0f2035c-078d-5cfb-8790-293ee2e92d6c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_2a1d.id) != (
    'urn:uuid:7f630d2f-76b0-5c09-982b-ad9b823cf110'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a1i13.id) != (
    'urn:uuid:409e7494-cb8c-5fa2-aba3-6448002cc25e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_2a1.id) != (
    'urn:uuid:d2f14ce8-8b23-5a00-9bfe-32befb9d93dc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a2d.id) != (
    'urn:uuid:b7e1327d-50b2-5fb9-b0f2-a3de7955c6dd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(sylcom.id) != (
    'urn:uuid:eaed991d-71fd-5821-88fc-4e2b89e2f161'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl5com.id) != (
    'urn:uuid:4c956108-9548-5c43-a68f-7c1fc944c010'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com12.id) != (
    'urn:uuid:b36fa5b1-705b-5950-a836-e3135218077c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl11.id) != (
    'urn:uuid:8d07e137-6f3b-55f0-86d3-520713d64290'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl5.id) != (
    'urn:uuid:49b21bba-7179-5a1b-89d9-e30d5819064e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6.id) != (
    'urn:uuid:67594c40-1070-52aa-b742-dfcb8272201e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl56.id) != (
    'urn:uuid:f9a4f774-c820-541a-aeed-90657dc323a8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6com.id) != (
    'urn:uuid:dcf8cc7b-0c83-51d7-9087-e069c8a57cfc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpcom.id) != (
    'urn:uuid:532f2406-4fa6-5c4b-b585-e7414d140a1c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syli.id) != (
    'urn:uuid:40219032-c2a6-5886-91ad-0fb71c23d46e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl2im.id) != (
    'urn:uuid:24ef54ed-d8cb-5289-ba16-79c5c9f3be1a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl2imc.id) != (
    'urn:uuid:2ad5395a-2ae1-58b5-99a0-7b20f3c65699'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_27.id) != (
    'urn:uuid:d23de79e-fdc7-5611-8318-72c5f2e9acfa'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpdd.id) != (
    'urn:uuid:c25941b0-e2be-5613-b6a8-d1008057f3ca'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpid.id) != (
    'urn:uuid:3121f23d-7581-5720-86a0-0862f4e6a3c1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpdi.id) != (
    'urn:uuid:e3ed4e0a-154d-5595-ae37-244a7a03d1f2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpii.id) != (
    'urn:uuid:8369c4f5-7c9e-54e6-bb5b-f32af9f041a5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syld.id) != (
    'urn:uuid:4e42e0a3-f8f5-56e4-827c-0f76b229de3c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syldc.id) != (
    'urn:uuid:92b2755b-55ee-5145-b939-1e288e8c20f5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mp2d.id) != (
    'urn:uuid:da97729c-8010-560e-bf78-dfa12bf7617e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a1dd.id) != (
    'urn:uuid:ecb9fca1-8b9c-541a-a2f2-a93026bb119b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_2a1dd.id) != (
    'urn:uuid:ebded40f-7521-5178-816b-47832ea4348d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_43i.id) != (
    'urn:uuid:d7587140-7e7f-56b4-80f4-c4bbba293d60'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_43d.id) != (
    'urn:uuid:8f11b2c4-8843-5867-b1ee-ba14b62a0f64'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_43a.id) != (
    'urn:uuid:c0314425-a215-5885-9ed9-4556cb090a00'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_43b.id) != (
    'urn:uuid:6694560a-e109-5388-a1f3-8ef28b3daf1d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_43.id) != (
    'urn:uuid:5a1f6ff8-5d05-5646-b2c1-94e2c293b1ef'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim2d.id) != (
    'urn:uuid:9898ee1b-3d1b-5c73-b1bd-7da6dd2419df'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim2.id) != (
    'urn:uuid:5af6b34c-83ae-546a-a17e-bd372fed4fb4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(embantd.id) != (
    'urn:uuid:524cd620-f477-538e-a9f1-24d7d60a71b2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_3syld.id) != (
    'urn:uuid:4b377877-33c0-5ab9-9d9f-c018534e18e1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(sylsyld.id) != (
    'urn:uuid:e3b631ad-8776-56b5-8524-45c89dd277f7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim12i.id) != (
    'urn:uuid:a6a6eac1-ed1b-59af-8784-621021ad3105'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim1i.id) != (
    'urn:uuid:185cbee4-cfb1-52dc-97c0-44296ca23dd0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim3i.id) != (
    'urn:uuid:a9b6775e-d8ee-5afd-8b23-8ab9d9d9537e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(sylc.id) != (
    'urn:uuid:215ba276-21b3-56b6-a73a-162e22bba167'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl3c.id) != (
    'urn:uuid:ed361d4a-4fc3-502d-9acc-c01e218c8890'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6mpi.id) != (
    'urn:uuid:ca868994-cf49-5a45-ad84-8b2b494527a6'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpsyl.id) != (
    'urn:uuid:aa192e58-9a17-51df-bffd-7a4847b74724'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mpsylsyld.id) != (
    'urn:uuid:93005c98-40a7-5a50-83b2-32b57383bb0e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6c.id) != (
    'urn:uuid:71a5d017-8bd1-530a-abb6-1ef01ebe7826'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6ci.id) != (
    'urn:uuid:fd7de027-571c-5d5f-9108-e862d4a5b698'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syldd.id) != (
    'urn:uuid:ceb61ed3-e3b7-539a-81f9-acc732e08616'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl5d.id) != (
    'urn:uuid:e4632ae5-a19f-5c6b-beec-ee4cb7690b22'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl7.id) != (
    'urn:uuid:031838d4-8198-5eea-8d56-55dc7fc8ac7b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl6d.id) != (
    'urn:uuid:d2c8708f-3208-5afd-a669-f93a945da798'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl8.id) != (
    'urn:uuid:5803822c-f3f9-5ff4-86dc-dc200c4f957e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl9.id) != (
    'urn:uuid:f7217827-9e3f-5a83-b596-dd33317a271b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl9r.id) != (
    'urn:uuid:f574f543-0be0-55c1-a3b1-0c40a022137c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(syl10.id) != (
    'urn:uuid:086cd951-f103-5ed8-9baa-82b1b9bd908c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(a1ddd.id) != (
    'urn:uuid:16eb2c66-aea4-5c15-af0a-8ceac054890a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim12d.id) != (
    'urn:uuid:aef66549-c41a-5daf-afdd-23c9dcc3b008'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim1d.id) != (
    'urn:uuid:c5987783-2867-56f1-bdf0-9c90673b0280'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim1.id) != (
    'urn:uuid:5d0e3df8-0c99-5044-a190-51b062367500'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_83.id) != (
    'urn:uuid:fef533c5-80d9-51dd-9c2e-fad929a7ecc7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com23.id) != (
    'urn:uuid:5c4539a3-0496-5e8a-a7ab-f38cce0c3522'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com3r.id) != (
    'urn:uuid:8d6efbe2-8005-5720-a3c0-5bf4411f16e0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com13.id) != (
    'urn:uuid:adf74078-7017-51e9-8c5e-f987eded3a45'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com3l.id) != (
    'urn:uuid:de997853-2771-599b-a75c-90182331784d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_04.id) != (
    'urn:uuid:8a4ed832-ecc8-5b8d-a934-af471b864c0a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com34.id) != (
    'urn:uuid:1031683f-6979-5139-ab9e-78fb5eec2259'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com4l.id) != (
    'urn:uuid:2f9f7f16-8151-5b76-b582-eb52e5f3ef40'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com4t.id) != (
    'urn:uuid:82c99cd1-637e-5499-81fe-d4f29b7369bc'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com4r.id) != (
    'urn:uuid:960d9fe6-6867-5fa9-a5ce-acc6f9f89247'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com24.id) != (
    'urn:uuid:6ed9a456-14df-5efc-a4f2-6d337f92d415'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com14.id) != (
    'urn:uuid:b73f8406-ae71-5ce1-8751-44589250399a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com45.id) != (
    'urn:uuid:b5eabf99-ef9e-5acb-88de-713797852498'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com35.id) != (
    'urn:uuid:042a2a8f-f950-53ef-928b-5ef15fac7f4f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com25.id) != (
    'urn:uuid:2e077c3c-10ea-5e55-9bf9-c49d4573a47e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com5l.id) != (
    'urn:uuid:88ea99e3-1182-55da-aa9d-31b12f918649'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com15.id) != (
    'urn:uuid:30f27a89-ee41-5640-8245-263b1426eb2e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com52l.id) != (
    'urn:uuid:b21aaa34-bc33-5065-b700-15ce41ec93a9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com52r.id) != (
    'urn:uuid:99a4702d-746e-5f4d-9a5c-668cc971828c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(com5r.id) != (
    'urn:uuid:a04b00db-eb57-5ce6-a2f7-cfe3799eea80'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imim12.id) != (
    'urn:uuid:336e2578-33fd-59a8-b981-61cd7d7ec717'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jarr.id) != (
    'urn:uuid:6b022e5d-9d0f-5d81-902e-49377dbfd492'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jarri.id) != (
    'urn:uuid:461d1bc0-0fa6-5512-9ae2-b743ee0c1d09'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_86d.id) != (
    'urn:uuid:69729d4c-e11c-5572-9509-95acace33653'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_86.id) != (
    'urn:uuid:c89608e3-cd6b-5a51-9aa5-a43de72bbeb6'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_86i.id) != (
    'urn:uuid:547f9088-5434-5134-b80e-d2c2f59f205f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_72.id) != (
    'urn:uuid:50c47503-97d9-5d01-afeb-19fcff8bf8bd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(imimorb.id) != (
    'urn:uuid:b14b5420-b7fa-540f-84df-e2108f125bdd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@mp2.proof
def prove_mp2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp

    _hypothesis_1, _hypothesis_2, _hypothesis_3 = proof.hypotheses  # ⊢ ph; ps; wi(ph, wi(ps, ch))
    _step_1 = proof.use(ax_mp, _hypothesis_1, _hypothesis_3)  # ⊢ wi(ps, ch)
    _step_2 = proof.use(ax_mp, _hypothesis_2, _step_1)  # ⊢ ch
    return proof.qed(_step_2)


@mp2b.proof
def prove_mp2b(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp

    _hypothesis_1, _hypothesis_2, _hypothesis_3 = proof.hypotheses  # ⊢ ph; wi(ph, ps); wi(ps, ch)
    _step_1 = proof.use(ax_mp, _hypothesis_1, _hypothesis_2)  # ⊢ ps
    _step_2 = proof.use(ax_mp, _step_1, _hypothesis_3)  # ⊢ ch
    return proof.qed(_step_2)


@a1i.proof
def prove_a1i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1, ax_mp

    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(ax_1, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(ps, ph))
    _step_2 = proof.use(ax_mp, _hypothesis_1, _step_1)  # ⊢ wi(ps, ph)
    return proof.qed(_step_2)


@mm_2a1i.proof
def prove_mm_2a1i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ch"})  # ⊢ wi(ch, ph)
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ps"})  # ⊢ wi(ps, wi(ch, ph))
    return proof.qed(_step_2)


@ax1w.proof
def prove_ax1w(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _step_1 = proof.use(ax_1, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(ps, wi(ch, ps))
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ph"})  # ⊢ wi(ph, wi(ps, wi(ch, ps)))
    return proof.qed(_step_2)


@mp1i.proof
def prove_mp1i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp

    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ ph; wi(ph, ps)
    _step_1 = proof.use(ax_mp, _hypothesis_1, _hypothesis_2)  # ⊢ ps
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ch"})  # ⊢ wi(ch, ps)
    return proof.qed(_step_2)


@a2i.proof
def prove_a2i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_2, ax_mp

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(
        ax_2,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wi(ph, wi(ps, ch)), wi(wi(ph, ps), wi(ph, ch)))
    _step_2 = proof.use(ax_mp, _hypothesis_1, _step_1)  # ⊢ wi(wi(ph, ps), wi(ph, ch))
    return proof.qed(_step_2)


@mpd.proof
def prove_mpd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp

    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, wi(ps, ch))
    _step_1 = proof.use(a2i, _hypothesis_2)  # ⊢ wi(wi(ph, ps), wi(ph, ch))
    _step_2 = proof.use(ax_mp, _hypothesis_1, _step_1)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@imim2i.proof
def prove_imim2i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ch"})  # ⊢ wi(ch, wi(ph, ps))
    _step_2 = proof.use(a2i, _step_1)  # ⊢ wi(wi(ch, ph), wi(ch, ps))
    return proof.qed(_step_2)


@syl.proof
def prove_syl(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ps, ch)
    _step_1 = proof.use(a1i, _hypothesis_2, subst={"ps": "ph"})  # ⊢ wi(ph, wi(ps, ch))
    _step_2 = proof.use(mpd, _hypothesis_1, _step_1)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@mm_3syl.proof
def prove_mm_3syl(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ps, ch); wi(ch, th)
    _step_1 = proof.use(syl, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, ch)
    _step_2 = proof.use(syl, _step_1, _hypothesis_3)  # ⊢ wi(ph, th)
    return proof.qed(_step_2)


@mm_4syl.proof
def prove_mm_4syl(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
        _hypothesis_4,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ps, ch); wi(ch, th); wi(th, ta)
    _step_1 = proof.use(mm_3syl, _hypothesis_1, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ph, th)
    _step_2 = proof.use(syl, _step_1, _hypothesis_4)  # ⊢ wi(ph, ta)
    return proof.qed(_step_2)


@mpi.proof
def prove_mpi(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ ps; wi(ph, wi(ps, ch))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ph"})  # ⊢ wi(ph, ps)
    _step_2 = proof.use(mpd, _step_1, _hypothesis_2)  # ⊢ wi(ph, ch)
    return proof.qed(_step_2)


@mpisyl.proof
def prove_mpisyl(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); ch; wi(ps, wi(ch, th))
    _step_1 = proof.use(mpi, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ps, th)
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, th)
    return proof.qed(_step_2)


@id.proof
def prove_id(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _step_1 = proof.use(ax_1, subst={"ph": "ph", "ps": "ph"})  # ⊢ wi(ph, wi(ph, ph))
    _step_2 = proof.use(
        ax_1,
        subst={
            "ph": "ph",
            "ps": "wi(ph, ph)",
        },
    )  # ⊢ wi(ph, wi(wi(ph, ph), ph))
    _step_3 = proof.use(mpd, _step_1, _step_2)  # ⊢ wi(ph, ph)
    return proof.qed(_step_3)


@idALT.proof
def prove_idALT(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1, ax_2, ax_mp

    _step_1 = proof.use(ax_1, subst={"ph": "ph", "ps": "ph"})  # ⊢ wi(ph, wi(ph, ph))
    _step_2 = proof.use(
        ax_1,
        subst={
            "ph": "ph",
            "ps": "wi(ph, ph)",
        },
    )  # ⊢ wi(ph, wi(wi(ph, ph), ph))
    _step_3 = proof.use(
        ax_2,
        subst={
            "ph": "ph",
            "ps": "wi(ph, ph)",
            "ch": "ph",
        },
    )  # ⊢ wi(wi(ph, wi(wi(ph, ph), ph)), wi(wi(ph, wi(ph, ph)), wi(ph, ph)))
    _step_4 = proof.use(ax_mp, _step_2, _step_3)  # ⊢ wi(wi(ph, wi(ph, ph)), wi(ph, ph))
    _step_5 = proof.use(ax_mp, _step_1, _step_4)  # ⊢ wi(ph, ph)
    return proof.qed(_step_5)


@idd.proof
def prove_idd(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(id, subst={"ph": "ps"})  # ⊢ wi(ps, ps)
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ph"})  # ⊢ wi(ph, wi(ps, ps))
    return proof.qed(_step_2)


@a1d.proof
def prove_a1d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(ax_1, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(ps, wi(ch, ps))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ch, ps))
    return proof.qed(_step_2)


@mm_2a1d.proof
def prove_mm_2a1d(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "th"})  # ⊢ wi(ph, wi(th, ps))
    _step_2 = proof.use(a1d, _step_1, subst={"ch": "ch"})  # ⊢ wi(ph, wi(ch, wi(th, ps)))
    return proof.qed(_step_2)


@a1i13.proof
def prove_a1i13(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ps, th)
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "ch"})  # ⊢ wi(ps, wi(ch, th))
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ph"})  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    return proof.qed(_step_2)


@mm_2a1.proof
def prove_mm_2a1(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(
        mm_2a1d,
        _step_1,
        subst={
            "ch": "ps",
            "th": "ch",
        },
    )  # ⊢ wi(ph, wi(ps, wi(ch, ph)))
    return proof.qed(_step_2)


@a2d.proof
def prove_a2d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_2

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(
        ax_2,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wi(wi(ps, wi(ch, th)), wi(wi(ps, ch), wi(ps, th)))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wi(ps, ch), wi(ps, th)))
    return proof.qed(_step_2)


@sylcom.proof
def prove_sylcom(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ps, wi(ch, th))
    _step_1 = proof.use(a2i, _hypothesis_2)  # ⊢ wi(wi(ps, ch), wi(ps, th))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@syl5com.proof
def prove_syl5com(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, wi(ps, th))
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "ch"})  # ⊢ wi(ph, wi(ch, ps))
    _step_2 = proof.use(sylcom, _step_1, _hypothesis_2)  # ⊢ wi(ph, wi(ch, th))
    return proof.qed(_step_2)


@com12.proof
def prove_com12(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(id, subst={"ph": "ps"})  # ⊢ wi(ps, ps)
    _step_2 = proof.use(syl5com, _step_1, _hypothesis_1)  # ⊢ wi(ps, wi(ph, ch))
    return proof.qed(_step_2)


@syl11.proof
def prove_syl11(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(th, ph)
    _step_1 = proof.use(syl, _hypothesis_2, _hypothesis_1)  # ⊢ wi(th, wi(ps, ch))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ps, wi(th, ch))
    return proof.qed(_step_2)


@syl5.proof
def prove_syl5(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, wi(ps, th))
    _step_1 = proof.use(syl5com, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(ch, th))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ch, wi(ph, th))
    return proof.qed(_step_2)


@syl6.proof
def prove_syl6(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ch, th)
    _step_1 = proof.use(a1i, _hypothesis_2, subst={"ps": "ps"})  # ⊢ wi(ps, wi(ch, th))
    _step_2 = proof.use(sylcom, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@syl56.proof
def prove_syl56(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, wi(ps, th)); wi(th, ta)
    _step_1 = proof.use(syl6, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ch, wi(ps, ta))
    _step_2 = proof.use(syl5, _hypothesis_1, _step_1)  # ⊢ wi(ch, wi(ph, ta))
    return proof.qed(_step_2)


@syl6com.proof
def prove_syl6com(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ch, th)
    _step_1 = proof.use(syl6, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ps, wi(ph, th))
    return proof.qed(_step_2)


@mpcom.proof
def prove_mpcom(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ps, ph); wi(ph, wi(ps, ch))
    _step_1 = proof.use(com12, _hypothesis_2)  # ⊢ wi(ps, wi(ph, ch))
    _step_2 = proof.use(mpd, _hypothesis_1, _step_1)  # ⊢ wi(ps, ch)
    return proof.qed(_step_2)


@syli.proof
def prove_syli(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ps, wi(ph, ch)); wi(ch, wi(ph, th))
    _step_1 = proof.use(com12, _hypothesis_2)  # ⊢ wi(ph, wi(ch, th))
    _step_2 = proof.use(sylcom, _hypothesis_1, _step_1)  # ⊢ wi(ps, wi(ph, th))
    return proof.qed(_step_2)


@syl2im.proof
def prove_syl2im(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, th); wi(ps, wi(th, ta))
    _step_1 = proof.use(syl5, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ps, wi(ch, ta))
    _step_2 = proof.use(syl, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ch, ta))
    return proof.qed(_step_2)


@syl2imc.proof
def prove_syl2imc(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, th); wi(ps, wi(th, ta))
    _step_1 = proof.use(syl2im, _hypothesis_1, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ph, wi(ch, ta))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ch, wi(ph, ta))
    return proof.qed(_step_2)


@pm2_27.proof
def prove_pm2_27(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(id, subst={"ph": "wi(ph, ps)"})  # ⊢ wi(wi(ph, ps), wi(ph, ps))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ph, wi(wi(ph, ps), ps))
    return proof.qed(_step_2)


@mpdd.proof
def prove_mpdd(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(a2d, _hypothesis_2)  # ⊢ wi(ph, wi(wi(ps, ch), wi(ps, th)))
    _step_2 = proof.use(mpd, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@mpid.proof
def prove_mpid(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ch); wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "ps"})  # ⊢ wi(ph, wi(ps, ch))
    _step_2 = proof.use(mpdd, _step_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@mpdi.proof
def prove_mpdi(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ps, ch); wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ph"})  # ⊢ wi(ph, wi(ps, ch))
    _step_2 = proof.use(mpdd, _step_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@mpii.proof
def prove_mpii(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ ch; wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wi(ps, ch)
    _step_2 = proof.use(mpdi, _step_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@syld.proof
def prove_syld(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ch, th))
    _step_1 = proof.use(a1d, _hypothesis_2, subst={"ch": "ps"})  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_2 = proof.use(mpdd, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, th))
    return proof.qed(_step_2)


@syldc.proof
def prove_syldc(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ch, th))
    _step_1 = proof.use(syld, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ps, wi(ph, th))
    return proof.qed(_step_2)


@mp2d.proof
def prove_mp2d(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, ch); wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(mpid, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(mpd, _hypothesis_1, _step_1)  # ⊢ wi(ph, th)
    return proof.qed(_step_2)


@a1dd.proof
def prove_a1dd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(ax_1, subst={"ph": "ch", "ps": "th"})  # ⊢ wi(ch, wi(th, ch))
    _step_2 = proof.use(syl6, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, wi(th, ch)))
    return proof.qed(_step_2)


@mm_2a1dd.proof
def prove_mm_2a1dd(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(a1dd, _hypothesis_1, subst={"th": "ta"})  # ⊢ wi(ph, wi(ps, wi(ta, ch)))
    _step_2 = proof.use(a1dd, _step_1, subst={"th": "th"})  # ⊢ wi(ph, wi(ps, wi(th, wi(ta, ch))))
    return proof.qed(_step_2)


@pm2_43i.proof
def prove_pm2_43i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ph, ps))
    _step_1 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_2 = proof.use(mpd, _step_1, _hypothesis_1)  # ⊢ wi(ph, ps)
    return proof.qed(_step_2)


@pm2_43d.proof
def prove_pm2_43d(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ps, ch)))
    _step_1 = proof.use(id, subst={"ph": "ps"})  # ⊢ wi(ps, ps)
    _step_2 = proof.use(mpdi, _step_1, _hypothesis_1)  # ⊢ wi(ph, wi(ps, ch))
    return proof.qed(_step_2)


@pm2_43a.proof
def prove_pm2_43a(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ps, wi(ph, wi(ps, ch)))
    _step_1 = proof.use(id, subst={"ph": "ps"})  # ⊢ wi(ps, ps)
    _step_2 = proof.use(mpid, _step_1, _hypothesis_1)  # ⊢ wi(ps, wi(ph, ch))
    return proof.qed(_step_2)


@pm2_43b.proof
def prove_pm2_43b(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ps, wi(ph, wi(ps, ch)))
    _step_1 = proof.use(pm2_43a, _hypothesis_1)  # ⊢ wi(ps, wi(ph, ch))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ph, wi(ps, ch))
    return proof.qed(_step_2)


@pm2_43.proof
def prove_pm2_43(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(pm2_27, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(wi(ph, ps), ps))
    _step_2 = proof.use(a2i, _step_1)  # ⊢ wi(wi(ph, wi(ph, ps)), wi(ph, ps))
    return proof.qed(_step_2)


@imim2d.proof
def prove_imim2d(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "th"})  # ⊢ wi(ph, wi(th, wi(ps, ch)))
    _step_2 = proof.use(a2d, _step_1)  # ⊢ wi(ph, wi(wi(th, ps), wi(th, ch)))
    return proof.qed(_step_2)


@imim2.proof
def prove_imim2(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(id, subst={"ph": "wi(ph, ps)"})  # ⊢ wi(wi(ph, ps), wi(ph, ps))
    _step_2 = proof.use(
        imim2d,
        _step_1,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wi(ch, ph), wi(ch, ps)))
    return proof.qed(_step_2)


@embantd.proof
def prove_embantd(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, wi(ch, th))
    _step_1 = proof.use(
        imim2d,
        _hypothesis_2,
        subst={
            "th": "ps",
        },
    )  # ⊢ wi(ph, wi(wi(ps, ch), wi(ps, th)))
    _step_2 = proof.use(mpid, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wi(ps, ch), th))
    return proof.qed(_step_2)


@mm_3syld.proof
def prove_mm_3syld(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ch, th)); wi(ph, wi(th, ta))
    _step_1 = proof.use(syld, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(syld, _step_1, _hypothesis_3)  # ⊢ wi(ph, wi(ps, ta))
    return proof.qed(_step_2)


@sylsyld.proof
def prove_sylsyld(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, wi(ch, th)); wi(ps, wi(th, ta))
    _step_1 = proof.use(syl, _hypothesis_1, _hypothesis_3)  # ⊢ wi(ph, wi(th, ta))
    _step_2 = proof.use(syld, _hypothesis_2, _step_1)  # ⊢ wi(ph, wi(ch, ta))
    return proof.qed(_step_2)


@imim12i.proof
def prove_imim12i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, th)
    _step_1 = proof.use(imim2i, _hypothesis_2, subst={"ch": "ps"})  # ⊢ wi(wi(ps, ch), wi(ps, th))
    _step_2 = proof.use(syl5, _hypothesis_1, _step_1)  # ⊢ wi(wi(ps, ch), wi(ph, th))
    return proof.qed(_step_2)


@imim1i.proof
def prove_imim1i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, ps)
    _step_1 = proof.use(id, subst={"ph": "ch"})  # ⊢ wi(ch, ch)
    _step_2 = proof.use(imim12i, _hypothesis_1, _step_1)  # ⊢ wi(wi(ps, ch), wi(ph, ch))
    return proof.qed(_step_2)


@imim3i.proof
def prove_imim3i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(
        imim2i,
        _hypothesis_1,
        subst={
            "ch": "th",
        },
    )  # ⊢ wi(wi(th, ph), wi(th, wi(ps, ch)))
    _step_2 = proof.use(a2d, _step_1)  # ⊢ wi(wi(th, ph), wi(wi(th, ps), wi(th, ch)))
    return proof.qed(_step_2)


@sylc.proof
def prove_sylc(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, ch); wi(ps, wi(ch, th))
    _step_1 = proof.use(syl2im, _hypothesis_1, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ph, wi(ph, th))
    _step_2 = proof.use(pm2_43i, _step_1)  # ⊢ wi(ph, th)
    return proof.qed(_step_2)


@syl3c.proof
def prove_syl3c(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
        _hypothesis_4,
    ) = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, ch); wi(ph, th); wi(ps, wi(ch, wi(th, ta)))
    _step_1 = proof.use(sylc, _hypothesis_1, _hypothesis_2, _hypothesis_4)  # ⊢ wi(ph, wi(th, ta))
    _step_2 = proof.use(mpd, _hypothesis_3, _step_1)  # ⊢ wi(ph, ta)
    return proof.qed(_step_2)


@syl6mpi.proof
def prove_syl6mpi(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); th; wi(ch, wi(th, ta))
    _step_1 = proof.use(mpi, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ch, ta)
    _step_2 = proof.use(syl6, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, ta))
    return proof.qed(_step_2)


@mpsyl.proof
def prove_mpsyl(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ ph; wi(ps, ch); wi(ph, wi(ch, th))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wi(ps, ph)
    _step_2 = proof.use(sylc, _step_1, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ps, th)
    return proof.qed(_step_2)


@mpsylsyld.proof
def prove_mpsylsyld(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ ph; wi(ps, wi(ch, th)); wi(ph, wi(th, ta))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wi(ps, ph)
    _step_2 = proof.use(sylsyld, _step_1, _hypothesis_2, _hypothesis_3)  # ⊢ wi(ps, wi(ch, ta))
    return proof.qed(_step_2)


@syl6c.proof
def prove_syl6c(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ps, th)); wi(ch, wi(th, ta))
    _step_1 = proof.use(syl6, _hypothesis_1, _hypothesis_3)  # ⊢ wi(ph, wi(ps, wi(th, ta)))
    _step_2 = proof.use(mpdd, _hypothesis_2, _step_1)  # ⊢ wi(ph, wi(ps, ta))
    return proof.qed(_step_2)


@syl6ci.proof
def prove_syl6ci(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, th); wi(ch, wi(th, ta))
    _step_1 = proof.use(a1d, _hypothesis_2, subst={"ch": "ps"})  # ⊢ wi(ph, wi(ps, th))
    _step_2 = proof.use(syl6c, _hypothesis_1, _step_1, _hypothesis_3)  # ⊢ wi(ph, wi(ps, ta))
    return proof.qed(_step_2)


@syldd.proof
def prove_syldd(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th))); wi(ph, wi(ps, wi(th, ta)))
    _step_1 = proof.use(
        imim2,
        subst={
            "ph": "th",
            "ps": "ta",
            "ch": "ch",
        },
    )  # ⊢ wi(wi(th, ta), wi(wi(ch, th), wi(ch, ta)))
    _step_2 = proof.use(
        syl6c,
        _hypothesis_2,
        _hypothesis_1,
        _step_1,
    )  # ⊢ wi(ph, wi(ps, wi(ch, ta)))
    return proof.qed(_step_2)


@syl5d.proof
def prove_syl5d(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, wi(ch, ta)))
    _step_1 = proof.use(a1d, _hypothesis_1, subst={"ch": "th"})  # ⊢ wi(ph, wi(th, wi(ps, ch)))
    _step_2 = proof.use(syldd, _step_1, _hypothesis_2)  # ⊢ wi(ph, wi(th, wi(ps, ta)))
    return proof.qed(_step_2)


@syl7.proof
def prove_syl7(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ch, wi(th, wi(ps, ta)))
    _step_1 = proof.use(a1i, _hypothesis_1, subst={"ps": "ch"})  # ⊢ wi(ch, wi(ph, ps))
    _step_2 = proof.use(syl5d, _step_1, _hypothesis_2)  # ⊢ wi(ch, wi(th, wi(ph, ta)))
    return proof.qed(_step_2)


@syl6d.proof
def prove_syl6d(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th))); wi(ph, wi(th, ta))
    _step_1 = proof.use(a1d, _hypothesis_2, subst={"ch": "ps"})  # ⊢ wi(ph, wi(ps, wi(th, ta)))
    _step_2 = proof.use(syldd, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, wi(ch, ta)))
    return proof.qed(_step_2)


@syl8.proof
def prove_syl8(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th))); wi(th, ta)
    _step_1 = proof.use(a1i, _hypothesis_2, subst={"ps": "ph"})  # ⊢ wi(ph, wi(th, ta))
    _step_2 = proof.use(syl6d, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, wi(ch, ta)))
    return proof.qed(_step_2)


@syl9.proof
def prove_syl9(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(th, wi(ch, ta))
    _step_1 = proof.use(a1i, _hypothesis_2, subst={"ps": "ph"})  # ⊢ wi(ph, wi(th, wi(ch, ta)))
    _step_2 = proof.use(syl5d, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(th, wi(ps, ta)))
    return proof.qed(_step_2)


@syl9r.proof
def prove_syl9r(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(th, wi(ch, ta))
    _step_1 = proof.use(syl9, _hypothesis_1, _hypothesis_2)  # ⊢ wi(ph, wi(th, wi(ps, ta)))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(th, wi(ph, wi(ps, ta)))
    return proof.qed(_step_2)


@syl10.proof
def prove_syl10(proof: TheoryProofAuthor) -> CompleteProof:
    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(ps, wi(th, ta))); wi(ch, wi(ta, et))
    _step_1 = proof.use(syl6, _hypothesis_1, _hypothesis_3)  # ⊢ wi(ph, wi(ps, wi(ta, et)))
    _step_2 = proof.use(syldd, _hypothesis_2, _step_1)  # ⊢ wi(ph, wi(ps, wi(th, et)))
    return proof.qed(_step_2)


@a1ddd.proof
def prove_a1ddd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, ta)))
    _step_1 = proof.use(ax_1, subst={"ph": "ta", "ps": "th"})  # ⊢ wi(ta, wi(th, ta))
    _step_2 = proof.use(syl8, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    return proof.qed(_step_2)


@imim12d.proof
def prove_imim12d(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(ph, wi(th, ta))
    _step_1 = proof.use(
        imim2d,
        _hypothesis_2,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(ph, wi(wi(ch, th), wi(ch, ta)))
    _step_2 = proof.use(syl5d, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wi(ch, th), wi(ps, ta)))
    return proof.qed(_step_2)


@imim1d.proof
def prove_imim1d(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch))
    _step_1 = proof.use(idd, subst={"ph": "ph", "ps": "th"})  # ⊢ wi(ph, wi(th, th))
    _step_2 = proof.use(imim12d, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(wi(ch, th), wi(ps, th)))
    return proof.qed(_step_2)


@imim1.proof
def prove_imim1(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(id, subst={"ph": "wi(ph, ps)"})  # ⊢ wi(wi(ph, ps), wi(ph, ps))
    _step_2 = proof.use(
        imim1d,
        _step_1,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wi(ps, ch), wi(ph, ch)))
    return proof.qed(_step_2)


@pm2_83.proof
def prove_pm2_83(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        imim1,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wi(wi(ps, ch), wi(wi(ch, th), wi(ps, th)))
    _step_2 = proof.use(
        imim3i,
        _step_1,
        subst={
            "th": "ph",
        },
    )  # ⊢ wi(wi(ph, wi(ps, ch)), wi(wi(ph, wi(ch, th)), wi(ph, wi(ps, th))))
    return proof.qed(_step_2)


@com23.proof
def prove_com23(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(pm2_27, subst={"ph": "ch", "ps": "th"})  # ⊢ wi(ch, wi(wi(ch, th), th))
    _step_2 = proof.use(syl9, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ch, wi(ps, th)))
    return proof.qed(_step_2)


@com3r.proof
def prove_com3r(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(com23, _hypothesis_1)  # ⊢ wi(ph, wi(ch, wi(ps, th)))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ch, wi(ph, wi(ps, th)))
    return proof.qed(_step_2)


@com13.proof
def prove_com13(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(com3r, _hypothesis_1)  # ⊢ wi(ch, wi(ph, wi(ps, th)))
    _step_2 = proof.use(com23, _step_1)  # ⊢ wi(ch, wi(ps, wi(ph, th)))
    return proof.qed(_step_2)


@com3l.proof
def prove_com3l(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    _step_1 = proof.use(com3r, _hypothesis_1)  # ⊢ wi(ch, wi(ph, wi(ps, th)))
    _step_2 = proof.use(com3r, _step_1)  # ⊢ wi(ps, wi(ch, wi(ph, th)))
    return proof.qed(_step_2)


@pm2_04.proof
def prove_pm2_04(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        id,
        subst={
            "ph": "wi(ph, wi(ps, ch))",
        },
    )  # ⊢ wi(wi(ph, wi(ps, ch)), wi(ph, wi(ps, ch)))
    _step_2 = proof.use(com23, _step_1)  # ⊢ wi(wi(ph, wi(ps, ch)), wi(ps, wi(ph, ch)))
    return proof.qed(_step_2)


@com34.proof
def prove_com34(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(
        pm2_04,
        subst={
            "ph": "ch",
            "ps": "th",
            "ch": "ta",
        },
    )  # ⊢ wi(wi(ch, wi(th, ta)), wi(th, wi(ch, ta)))
    _step_2 = proof.use(syl6, _hypothesis_1, _step_1)  # ⊢ wi(ph, wi(ps, wi(th, wi(ch, ta))))
    return proof.qed(_step_2)


@com4l.proof
def prove_com4l(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(com3l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(ph, wi(th, ta))))
    _step_2 = proof.use(com34, _step_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ph, ta))))
    return proof.qed(_step_2)


@com4t.proof
def prove_com4t(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(com4l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ph, ta))))
    _step_2 = proof.use(com4l, _step_1)  # ⊢ wi(ch, wi(th, wi(ph, wi(ps, ta))))
    return proof.qed(_step_2)


@com4r.proof
def prove_com4r(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(com4t, _hypothesis_1)  # ⊢ wi(ch, wi(th, wi(ph, wi(ps, ta))))
    _step_2 = proof.use(com4l, _step_1)  # ⊢ wi(th, wi(ph, wi(ps, wi(ch, ta))))
    return proof.qed(_step_2)


@com24.proof
def prove_com24(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(com4t, _hypothesis_1)  # ⊢ wi(ch, wi(th, wi(ph, wi(ps, ta))))
    _step_2 = proof.use(com13, _step_1)  # ⊢ wi(ph, wi(th, wi(ch, wi(ps, ta))))
    return proof.qed(_step_2)


@com14.proof
def prove_com14(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, ta))))
    _step_1 = proof.use(com4l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ph, ta))))
    _step_2 = proof.use(com3r, _step_1)  # ⊢ wi(th, wi(ps, wi(ch, wi(ph, ta))))
    return proof.qed(_step_2)


@com45.proof
def prove_com45(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(
        pm2_04,
        subst={
            "ph": "th",
            "ps": "ta",
            "ch": "et",
        },
    )  # ⊢ wi(wi(th, wi(ta, et)), wi(ta, wi(th, et)))
    _step_2 = proof.use(
        syl8,
        _hypothesis_1,
        _step_1,
    )  # ⊢ wi(ph, wi(ps, wi(ch, wi(ta, wi(th, et)))))
    return proof.qed(_step_2)


@com35.proof
def prove_com35(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com34, _hypothesis_1)  # ⊢ wi(ph, wi(ps, wi(th, wi(ch, wi(ta, et)))))
    _step_2 = proof.use(com45, _step_1)  # ⊢ wi(ph, wi(ps, wi(th, wi(ta, wi(ch, et)))))
    _step_3 = proof.use(com34, _step_2)  # ⊢ wi(ph, wi(ps, wi(ta, wi(th, wi(ch, et)))))
    return proof.qed(_step_3)


@com25.proof
def prove_com25(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com24, _hypothesis_1)  # ⊢ wi(ph, wi(th, wi(ch, wi(ps, wi(ta, et)))))
    _step_2 = proof.use(com45, _step_1)  # ⊢ wi(ph, wi(th, wi(ch, wi(ta, wi(ps, et)))))
    _step_3 = proof.use(com24, _step_2)  # ⊢ wi(ph, wi(ta, wi(ch, wi(th, wi(ps, et)))))
    return proof.qed(_step_3)


@com5l.proof
def prove_com5l(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com4l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ph, wi(ta, et)))))
    _step_2 = proof.use(com45, _step_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ta, wi(ph, et)))))
    return proof.qed(_step_2)


@com15.proof
def prove_com15(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com5l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ta, wi(ph, et)))))
    _step_2 = proof.use(com4r, _step_1)  # ⊢ wi(ta, wi(ps, wi(ch, wi(th, wi(ph, et)))))
    return proof.qed(_step_2)


@com52l.proof
def prove_com52l(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com5l, _hypothesis_1)  # ⊢ wi(ps, wi(ch, wi(th, wi(ta, wi(ph, et)))))
    _step_2 = proof.use(com5l, _step_1)  # ⊢ wi(ch, wi(th, wi(ta, wi(ph, wi(ps, et)))))
    return proof.qed(_step_2)


@com52r.proof
def prove_com52r(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com52l, _hypothesis_1)  # ⊢ wi(ch, wi(th, wi(ta, wi(ph, wi(ps, et)))))
    _step_2 = proof.use(com5l, _step_1)  # ⊢ wi(th, wi(ta, wi(ph, wi(ps, wi(ch, et)))))
    return proof.qed(_step_2)


@com5r.proof
def prove_com5r(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(ps, wi(ch, wi(th, wi(ta, et)))))
    _step_1 = proof.use(com52l, _hypothesis_1)  # ⊢ wi(ch, wi(th, wi(ta, wi(ph, wi(ps, et)))))
    _step_2 = proof.use(com52l, _step_1)  # ⊢ wi(ta, wi(ph, wi(ps, wi(ch, wi(th, et)))))
    return proof.qed(_step_2)


@imim12.proof
def prove_imim12(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        imim2,
        subst={
            "ph": "ch",
            "ps": "th",
            "ch": "ps",
        },
    )  # ⊢ wi(wi(ch, th), wi(wi(ps, ch), wi(ps, th)))
    _step_2 = proof.use(
        imim1,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "th",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wi(ps, th), wi(ph, th)))
    _step_3 = proof.use(
        syl9r,
        _step_1,
        _step_2,
    )  # ⊢ wi(wi(ph, ps), wi(wi(ch, th), wi(wi(ps, ch), wi(ph, th))))
    return proof.qed(_step_3)


@jarr.proof
def prove_jarr(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _step_1 = proof.use(ax_1, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wi(ph, ps))
    _step_2 = proof.use(imim1i, _step_1, subst={"ch": "ch"})  # ⊢ wi(wi(wi(ph, ps), ch), wi(ps, ch))
    return proof.qed(_step_2)


@jarri.proof
def prove_jarri(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wi(ph, ps), ch)
    _step_1 = proof.use(ax_1, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wi(ph, ps))
    _step_2 = proof.use(syl, _step_1, _hypothesis_1)  # ⊢ wi(ps, ch)
    return proof.qed(_step_2)


@pm2_86d.proof
def prove_pm2_86d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_1

    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wi(wi(ps, ch), wi(ps, th)))
    _step_1 = proof.use(ax_1, subst={"ph": "ch", "ps": "ps"})  # ⊢ wi(ch, wi(ps, ch))
    _step_2 = proof.use(syl5, _step_1, _hypothesis_1)  # ⊢ wi(ph, wi(ch, wi(ps, th)))
    _step_3 = proof.use(com23, _step_2)  # ⊢ wi(ph, wi(ps, wi(ch, th)))
    return proof.qed(_step_3)


@pm2_86.proof
def prove_pm2_86(proof: TheoryProofAuthor) -> CompleteProof:
    _step_1 = proof.use(
        id,
        subst={
            "ph": "wi(wi(ph, ps), wi(ph, ch))",
        },
    )  # ⊢ wi(wi(wi(ph, ps), wi(ph, ch)), wi(wi(ph, ps), wi(ph, ch)))
    _step_2 = proof.use(pm2_86d, _step_1)  # ⊢ wi(wi(wi(ph, ps), wi(ph, ch)), wi(ph, wi(ps, ch)))
    return proof.qed(_step_2)


@pm2_86i.proof
def prove_pm2_86i(proof: TheoryProofAuthor) -> CompleteProof:
    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wi(ph, ps), wi(ph, ch))
    _step_1 = proof.use(jarri, _hypothesis_1)  # ⊢ wi(ps, wi(ph, ch))
    _step_2 = proof.use(com12, _step_1)  # ⊢ wi(ph, wi(ps, ch))
    return proof.qed(_step_2)


@pm4_72.proof
def prove_pm4_72(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpr, impbid2, impbii
    from metamath_setmm_provider.shards.s004 import olc, orc, pm2_621


    _step_1 = proof.use(olc, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wo(ph, ps))
    _step_2 = proof.use(
        pm2_621,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wo(ph, ps), ps))
    _step_3 = proof.use(impbid2, _step_1, _step_2)  # ⊢ wi(wi(ph, ps), wb(ps, wo(ph, ps)))
    _step_4 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_5 = proof.use(
        biimpr,
        subst={
            "ph": "ps",
            "ps": "wo(ph, ps)",
        },
    )  # ⊢ wi(wb(ps, wo(ph, ps)), wi(wo(ph, ps), ps))
    _step_6 = proof.use(syl5, _step_4, _step_5)  # ⊢ wi(wb(ps, wo(ph, ps)), wi(ph, ps))
    _step_7 = proof.use(impbii, _step_3, _step_6)  # ⊢ wb(wi(ph, ps), wb(ps, wo(ph, ps)))
    return proof.qed(_step_7)


@imimorb.proof
def prove_imimorb(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bi2_04, bitr4i, imbi2i
    from metamath_setmm_provider.shards.s004 import dfor2


    _step_1 = proof.use(
        bi2_04,
        subst={
            "ph": "wi(ps, ch)",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wi(ps, ch), wi(ph, ch)), wi(ph, wi(wi(ps, ch), ch)))
    _step_2 = proof.use(
        dfor2,
        subst={
            "ph": "ps",
            "ps": "ch",
        },
    )  # ⊢ wb(wo(ps, ch), wi(wi(ps, ch), ch))
    _step_3 = proof.use(
        imbi2i,
        _step_2,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wi(ph, wo(ps, ch)), wi(ph, wi(wi(ps, ch), ch)))
    _step_4 = proof.use(
        bitr4i,
        _step_1,
        _step_3,
    )  # ⊢ wb(wi(wi(ps, ch), wi(ph, ch)), wi(ph, wo(ps, ch)))
    return proof.qed(_step_4)

__all__ = (
    'mp2',
    'mp2b',
    'a1i',
    'mm_2a1i',
    'ax1w',
    'mp1i',
    'a2i',
    'mpd',
    'imim2i',
    'syl',
    'mm_3syl',
    'mm_4syl',
    'mpi',
    'mpisyl',
    'id',
    'idALT',
    'idd',
    'a1d',
    'mm_2a1d',
    'a1i13',
    'mm_2a1',
    'a2d',
    'sylcom',
    'syl5com',
    'com12',
    'syl11',
    'syl5',
    'syl6',
    'syl56',
    'syl6com',
    'mpcom',
    'syli',
    'syl2im',
    'syl2imc',
    'pm2_27',
    'mpdd',
    'mpid',
    'mpdi',
    'mpii',
    'syld',
    'syldc',
    'mp2d',
    'a1dd',
    'mm_2a1dd',
    'pm2_43i',
    'pm2_43d',
    'pm2_43a',
    'pm2_43b',
    'pm2_43',
    'imim2d',
    'imim2',
    'embantd',
    'mm_3syld',
    'sylsyld',
    'imim12i',
    'imim1i',
    'imim3i',
    'sylc',
    'syl3c',
    'syl6mpi',
    'mpsyl',
    'mpsylsyld',
    'syl6c',
    'syl6ci',
    'syldd',
    'syl5d',
    'syl7',
    'syl6d',
    'syl8',
    'syl9',
    'syl9r',
    'syl10',
    'a1ddd',
    'imim12d',
    'imim1d',
    'imim1',
    'pm2_83',
    'com23',
    'com3r',
    'com13',
    'com3l',
    'pm2_04',
    'com34',
    'com4l',
    'com4t',
    'com4r',
    'com24',
    'com14',
    'com45',
    'com35',
    'com25',
    'com5l',
    'com15',
    'com52l',
    'com52r',
    'com5r',
    'imim12',
    'jarr',
    'jarri',
    'pm2_86d',
    'pm2_86',
    'pm2_86i',
    'pm4_72',
    'imimorb',
)
