# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from metamath_setmm_provider.shards.s004 import (
    animorl as animorl,
)
from metamath_setmm_provider.shards.s004 import (
    animorlr as animorlr,
)
from metamath_setmm_provider.shards.s004 import (
    animorr as animorr,
)
from metamath_setmm_provider.shards.s004 import (
    animorrl as animorrl,
)
from metamath_setmm_provider.shards.s004 import (
    anor as anor,
)
from metamath_setmm_provider.shards.s004 import (
    ianor as ianor,
)
from metamath_setmm_provider.shards.s004 import (
    ioran as ioran,
)
from metamath_setmm_provider.shards.s004 import (
    jaao as jaao,
)
from metamath_setmm_provider.shards.s004 import (
    jaoa as jaoa,
)
from metamath_setmm_provider.shards.s004 import (
    pm4_52 as pm4_52,
)
from metamath_setmm_provider.shards.s005 import (
    anddi as anddi,
)
from metamath_setmm_provider.shards.s005 import (
    andi as andi,
)
from metamath_setmm_provider.shards.s005 import (
    andir as andir,
)
from metamath_setmm_provider.shards.s005 import (
    bianir as bianir,
)
from metamath_setmm_provider.shards.s005 import (
    bigolden as bigolden,
)
from metamath_setmm_provider.shards.s005 import (
    cases2 as cases2,
)
from metamath_setmm_provider.shards.s005 import (
    cases2ALT as cases2ALT,
)
from metamath_setmm_provider.shards.s005 import (
    consensus as consensus,
)
from metamath_setmm_provider.shards.s005 import (
    mm_4exmid as mm_4exmid,
)
from metamath_setmm_provider.shards.s005 import (
    niabn as niabn,
)
from metamath_setmm_provider.shards.s005 import (
    ninba as ninba,
)
from metamath_setmm_provider.shards.s005 import (
    orabs as orabs,
)
from metamath_setmm_provider.shards.s005 import (
    oran as oran,
)
from metamath_setmm_provider.shards.s005 import (
    oranabs as oranabs,
)
from metamath_setmm_provider.shards.s005 import (
    orcanai as orcanai,
)
from metamath_setmm_provider.shards.s005 import (
    orddi as orddi,
)
from metamath_setmm_provider.shards.s005 import (
    ordi as ordi,
)
from metamath_setmm_provider.shards.s005 import (
    ordir as ordir,
)
from metamath_setmm_provider.shards.s005 import (
    pclem6 as pclem6,
)
from metamath_setmm_provider.shards.s005 import (
    pm3_1 as pm3_1,
)
from metamath_setmm_provider.shards.s005 import (
    pm3_11 as pm3_11,
)
from metamath_setmm_provider.shards.s005 import (
    pm3_12 as pm3_12,
)
from metamath_setmm_provider.shards.s005 import (
    pm3_13 as pm3_13,
)
from metamath_setmm_provider.shards.s005 import (
    pm3_14 as pm3_14,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_42 as pm4_42,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_43 as pm4_43,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_44 as pm4_44,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_45 as pm4_45,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_53 as pm4_53,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_54 as pm4_54,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_55 as pm4_55,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_56 as pm4_56,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_57 as pm4_57,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_79 as pm4_79,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_82 as pm4_82,
)
from metamath_setmm_provider.shards.s005 import (
    pm4_83 as pm4_83,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_6 as pm5_6,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_54 as pm5_54,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_61 as pm5_61,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_62 as pm5_62,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_63 as pm5_63,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_71 as pm5_71,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_75 as pm5_75,
)
from metamath_setmm_provider.shards.s005 import (
    prlem2 as prlem2,
)
from metamath_setmm_provider.shards.s007 import (
    norasslem2 as norasslem2,
)
from metamath_setmm_provider.shards.s007 import (
    norasslem3 as norasslem3,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.theory import TheoryProofAuthor

if str(jaao.id) != (
    'urn:uuid:0a14e0c7-b0a2-5d7b-b216-81d78738aa83'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(jaoa.id) != (
    'urn:uuid:949271c3-1ae0-5c55-9099-8f4ac9ebd4e4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(animorl.id) != (
    'urn:uuid:16e4a9f1-f73a-524e-a3e9-aa0f10569d4f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(animorr.id) != (
    'urn:uuid:0a202acd-c705-5be7-b828-34151f11f5aa'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(animorlr.id) != (
    'urn:uuid:76f50ea0-af75-501e-9eda-9f3fc2cb9fe4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(animorrl.id) != (
    'urn:uuid:a90b4bcb-bf3d-534e-a828-dec3985b2664'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ianor.id) != (
    'urn:uuid:703ed58e-d19b-5a47-9c56-d0ca351bbc86'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(anor.id) != (
    'urn:uuid:4ddf579a-e8a5-53c4-a5ae-dfcab8383687'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ioran.id) != (
    'urn:uuid:49e2c7b3-cc3b-53b8-850d-b1a78b85f7cd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_52.id) != (
    'urn:uuid:1bb5de2c-d5c6-565f-abe8-9040941716fa'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_53.id) != (
    'urn:uuid:bbb79f4d-743c-5deb-8892-5d19c56faba7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_54.id) != (
    'urn:uuid:502e0b77-804b-5253-91b0-86b1ecc34d76'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_55.id) != (
    'urn:uuid:cce3486c-6b6f-54fd-8529-f2f7eceeb7b8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_56.id) != (
    'urn:uuid:0cb7e65b-af98-5382-999a-b21eec62e3c1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(oran.id) != (
    'urn:uuid:28e53089-8078-5a87-81ce-e82b3ae096bd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_57.id) != (
    'urn:uuid:41c6b03e-581a-5deb-8de4-9224a517791b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_1.id) != (
    'urn:uuid:9df2a6c5-655c-5a50-8a11-2384ad2978a7'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_11.id) != (
    'urn:uuid:01bee889-f034-58ba-8b5e-aba70b332eda'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_12.id) != (
    'urn:uuid:6a9de8b9-ccfc-5701-879d-d49885f6cf41'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_13.id) != (
    'urn:uuid:92b89027-8790-57bd-8563-4f793f782b53'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm3_14.id) != (
    'urn:uuid:0365d16c-5d26-5fbe-a10b-3b508f767fcd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_44.id) != (
    'urn:uuid:8ea8d0a9-50c6-58fc-8569-432c4bb4d348'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_45.id) != (
    'urn:uuid:6786c874-e7db-57f7-ba39-74843cf05420'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orabs.id) != (
    'urn:uuid:630c1855-9fbd-5374-8b71-e38e303731ca'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(oranabs.id) != (
    'urn:uuid:28ab24e2-aa5d-5d0f-94c0-2ba7ed96116b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_61.id) != (
    'urn:uuid:2e67218e-c99f-5edd-b6ac-9a3674b3851b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_6.id) != (
    'urn:uuid:1ef57bfc-3d92-587d-baaf-f195b77eb76f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orcanai.id) != (
    'urn:uuid:2e89d8c1-290b-5300-ab56-7de6e08cfbe2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_79.id) != (
    'urn:uuid:b93c26ec-4ae0-59dd-b07a-0b6ad40b47f8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ordi.id) != (
    'urn:uuid:be7fd33e-98d8-5c60-ac66-688983dcfd07'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ordir.id) != (
    'urn:uuid:e7ad7b8b-9fb7-53f6-a6c9-904d7de05fb5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(andi.id) != (
    'urn:uuid:20e2a359-50fc-57c0-bcce-87562efcba66'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(andir.id) != (
    'urn:uuid:b2c033cb-377f-5faa-97a5-5c36db437cdb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(orddi.id) != (
    'urn:uuid:a79aba34-9c30-545d-86a4-712ab3a656eb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(anddi.id) != (
    'urn:uuid:0e511a59-d5d5-5843-adea-65871d1c4796'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_54.id) != (
    'urn:uuid:3f41bd5f-b239-5f81-9024-723eddb0583f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_62.id) != (
    'urn:uuid:a4dfb166-9214-5409-98b3-3e074a67cdff'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_63.id) != (
    'urn:uuid:e21da46c-289e-567c-95ef-280492227bb9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(niabn.id) != (
    'urn:uuid:64d8c696-1419-54d1-a286-e1c6b84a897b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ninba.id) != (
    'urn:uuid:83e46993-e8e0-5856-abed-ff17ab6b7e47'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_43.id) != (
    'urn:uuid:59b21413-bdd2-52c6-a0a9-2b4237543f88'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_82.id) != (
    'urn:uuid:ca511f65-ad47-543b-9c2f-fd8203f93fc5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_83.id) != (
    'urn:uuid:bd6fbc66-1dd7-5273-b5d0-9fd21885404a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pclem6.id) != (
    'urn:uuid:768a0f0f-55bf-55aa-b6f0-3b3cd398245a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(bigolden.id) != (
    'urn:uuid:8c3f70e6-016f-588d-ad34-b856c69f27bb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_71.id) != (
    'urn:uuid:c1587383-bdd2-5df1-8cc0-cdd3457640ee'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_75.id) != (
    'urn:uuid:2864e195-59f2-503d-9d3d-4415fcef9537'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(cases2.id) != (
    'urn:uuid:42415930-b774-553f-b190-571218ae537c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(cases2ALT.id) != (
    'urn:uuid:9c233c2a-b5ec-561e-b37c-8582142e8d25'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mm_4exmid.id) != (
    'urn:uuid:487b8043-1e36-5636-bfbc-8e6a47cab5a8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(consensus.id) != (
    'urn:uuid:c62c0f18-28b7-5bba-8d35-1a90eb7324a1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm4_42.id) != (
    'urn:uuid:7e86ac2e-821b-5584-8925-137da85538eb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(prlem2.id) != (
    'urn:uuid:17f4bfb6-b468-5960-95d5-51c52bd03b46'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(bianir.id) != (
    'urn:uuid:bbe60a97-51aa-5b30-82e5-0ff386748a3c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norasslem2.id) != (
    'urn:uuid:6b5306e4-d09e-54a0-9344-2e264726cc65'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norasslem3.id) != (
    'urn:uuid:69108a7e-88db-5533-a665-c61f90392e92'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@jaao.proof
def prove_jaao(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import adantl, adantr
    from metamath_setmm_provider.shards.s004 import jaod


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(th, wi(ta, ch))
    _step_1 = proof.use(adantr, _hypothesis_1, subst={"ch": "th"})  # ⊢ wi(wa(ph, th), wi(ps, ch))
    _step_2 = proof.use(adantl, _hypothesis_2, subst={"ch": "ph"})  # ⊢ wi(wa(ph, th), wi(ta, ch))
    _step_3 = proof.use(jaod, _step_1, _step_2)  # ⊢ wi(wa(ph, th), wi(wo(ps, ta), ch))
    return proof.qed(_step_3)


@jaoa.proof
def prove_jaoa(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import adantld, adantrd
    from metamath_setmm_provider.shards.s004 import jaoi


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wi(ps, ch)); wi(th, wi(ta, ch))
    _step_1 = proof.use(adantrd, _hypothesis_1, subst={"th": "ta"})  # ⊢ wi(ph, wi(wa(ps, ta), ch))
    _step_2 = proof.use(adantld, _hypothesis_2, subst={"th": "ps"})  # ⊢ wi(th, wi(wa(ps, ta), ch))
    _step_3 = proof.use(jaoi, _step_1, _step_2)  # ⊢ wi(wo(ph, th), wi(wa(ps, ta), ch))
    return proof.qed(_step_3)


@animorl.proof
def prove_animorl(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpl
    from metamath_setmm_provider.shards.s004 import orcd


    _step_1 = proof.use(simpl, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ph)
    _step_2 = proof.use(orcd, _step_1, subst={"ch": "ch"})  # ⊢ wi(wa(ph, ps), wo(ph, ch))
    return proof.qed(_step_2)


@animorr.proof
def prove_animorr(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpr
    from metamath_setmm_provider.shards.s004 import olcd


    _step_1 = proof.use(simpr, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ps)
    _step_2 = proof.use(olcd, _step_1, subst={"ch": "ch"})  # ⊢ wi(wa(ph, ps), wo(ch, ps))
    return proof.qed(_step_2)


@animorlr.proof
def prove_animorlr(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpl
    from metamath_setmm_provider.shards.s004 import olcd


    _step_1 = proof.use(simpl, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ph)
    _step_2 = proof.use(olcd, _step_1, subst={"ch": "ch"})  # ⊢ wi(wa(ph, ps), wo(ch, ph))
    return proof.qed(_step_2)


@animorrl.proof
def prove_animorrl(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpr
    from metamath_setmm_provider.shards.s004 import orcd


    _step_1 = proof.use(simpr, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ps)
    _step_2 = proof.use(orcd, _step_1, subst={"ch": "ch"})  # ⊢ wi(wa(ph, ps), wo(ps, ch))
    return proof.qed(_step_2)


@ianor.proof
def prove_ianor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr3i
    from metamath_setmm_provider.shards.s002 import imnan
    from metamath_setmm_provider.shards.s004 import pm4_62


    _step_1 = proof.use(
        imnan,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, wn(ps)), wn(wa(ph, ps)))
    _step_2 = proof.use(
        pm4_62,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, wn(ps)), wo(wn(ph), wn(ps)))
    _step_3 = proof.use(bitr3i, _step_1, _step_2)  # ⊢ wb(wn(wa(ph, ps)), wo(wn(ph), wn(ps)))
    return proof.qed(_step_3)


@anor.proof
def prove_anor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import notnotb, xchbinx


    _step_1 = proof.use(notnotb, subst={"ph": "wa(ph, ps)"})  # ⊢ wb(wa(ph, ps), wn(wn(wa(ph, ps))))
    _step_2 = proof.use(
        ianor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wa(ph, ps)), wo(wn(ph), wn(ps)))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    return proof.qed(_step_3)


@ioran.proof
def prove_ioran(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import xchnxbi
    from metamath_setmm_provider.shards.s002 import pm4_65
    from metamath_setmm_provider.shards.s004 import pm4_64


    _step_1 = proof.use(
        pm4_65,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wi(wn(ph), ps)), wa(wn(ph), wn(ps)))
    _step_2 = proof.use(pm4_64, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wi(wn(ph), ps), wo(ph, ps))
    _step_3 = proof.use(xchnxbi, _step_1, _step_2)  # ⊢ wb(wn(wo(ph, ps)), wa(wn(ph), wn(ps)))
    return proof.qed(_step_3)


@pm4_52.proof
def prove_pm4_52(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import xchbinx
    from metamath_setmm_provider.shards.s002 import annim
    from metamath_setmm_provider.shards.s004 import imor


    _step_1 = proof.use(
        annim,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(ph, wn(ps)), wn(wi(ph, ps)))
    _step_2 = proof.use(imor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wi(ph, ps), wo(wn(ph), ps))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wa(ph, wn(ps)), wn(wo(wn(ph), ps)))
    return proof.qed(_step_3)


@pm4_53.proof
def prove_pm4_53(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi, con2bii


    _step_1 = proof.use(
        pm4_52,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(ph, wn(ps)), wn(wo(wn(ph), ps)))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wo(wn(ph), ps), wn(wa(ph, wn(ps))))
    _step_3 = proof.use(bicomi, _step_2)  # ⊢ wb(wn(wa(ph, wn(ps))), wo(wn(ph), ps))
    return proof.qed(_step_3)


@pm4_54.proof
def prove_pm4_54(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import xchbinx
    from metamath_setmm_provider.shards.s002 import df_an
    from metamath_setmm_provider.shards.s004 import pm4_66


    _step_1 = proof.use(
        df_an,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(wn(ph), ps), wn(wi(wn(ph), wn(ps))))
    _step_2 = proof.use(
        pm4_66,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(wn(ph), wn(ps)), wo(ph, wn(ps)))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wa(wn(ph), ps), wn(wo(ph, wn(ps))))
    return proof.qed(_step_3)


@pm4_55.proof
def prove_pm4_55(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi, con2bii


    _step_1 = proof.use(
        pm4_54,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(wn(ph), ps), wn(wo(ph, wn(ps))))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wo(ph, wn(ps)), wn(wa(wn(ph), ps)))
    _step_3 = proof.use(bicomi, _step_2)  # ⊢ wb(wn(wa(wn(ph), ps)), wo(ph, wn(ps)))
    return proof.qed(_step_3)


@pm4_56.proof
def prove_pm4_56(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi


    _step_1 = proof.use(
        ioran,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wo(ph, ps)), wa(wn(ph), wn(ps)))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wa(wn(ph), wn(ps)), wn(wo(ph, ps)))
    return proof.qed(_step_2)


@oran.proof
def prove_oran(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import con2bii


    _step_1 = proof.use(
        pm4_56,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(wn(ph), wn(ps)), wn(wo(ph, ps)))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wo(ph, ps), wn(wa(wn(ph), wn(ps))))
    return proof.qed(_step_2)


@pm4_57.proof
def prove_pm4_57(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi


    _step_1 = proof.use(
        oran,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wo(ph, ps), wn(wa(wn(ph), wn(ps))))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wn(wa(wn(ph), wn(ps))), wo(ph, ps))
    return proof.qed(_step_2)


@pm3_1.proof
def prove_pm3_1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi


    _step_1 = proof.use(
        anor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    return proof.qed(_step_2)


@pm3_11.proof
def prove_pm3_11(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpri


    _step_1 = proof.use(
        anor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    _step_2 = proof.use(biimpri, _step_1)  # ⊢ wi(wn(wo(wn(ph), wn(ps))), wa(ph, ps))
    return proof.qed(_step_2)


@pm3_12.proof
def prove_pm3_12(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import orri


    _step_1 = proof.use(
        pm3_11,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wn(wo(wn(ph), wn(ps))), wa(ph, ps))
    _step_2 = proof.use(orri, _step_1)  # ⊢ wo(wo(wn(ph), wn(ps)), wa(ph, ps))
    return proof.qed(_step_2)


@pm3_13.proof
def prove_pm3_13(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con1i


    _step_1 = proof.use(
        pm3_11,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wn(wo(wn(ph), wn(ps))), wa(ph, ps))
    _step_2 = proof.use(con1i, _step_1)  # ⊢ wi(wn(wa(ph, ps)), wo(wn(ph), wn(ps)))
    return proof.qed(_step_2)


@pm3_14.proof
def prove_pm3_14(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con2i


    _step_1 = proof.use(
        pm3_1,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    _step_2 = proof.use(con2i, _step_1)  # ⊢ wi(wo(wn(ph), wn(ps)), wn(wa(ph, ps)))
    return proof.qed(_step_2)


@pm4_44.proof
def prove_pm4_44(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s002 import simpl
    from metamath_setmm_provider.shards.s004 import jaoi, orc


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "wa(ph, ps)"})  # ⊢ wi(ph, wo(ph, wa(ph, ps)))
    _step_2 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_3 = proof.use(simpl, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ph)
    _step_4 = proof.use(jaoi, _step_2, _step_3)  # ⊢ wi(wo(ph, wa(ph, ps)), ph)
    _step_5 = proof.use(impbii, _step_1, _step_4)  # ⊢ wb(ph, wo(ph, wa(ph, ps)))
    return proof.qed(_step_5)


@pm4_45.proof
def prove_pm4_45(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import pm4_71i
    from metamath_setmm_provider.shards.s004 import orc


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(pm4_71i, _step_1)  # ⊢ wb(ph, wa(ph, wo(ph, ps)))
    return proof.qed(_step_2)


@orabs.proof
def prove_orabs(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import pm4_71ri
    from metamath_setmm_provider.shards.s004 import orc


    _step_1 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_2 = proof.use(pm4_71ri, _step_1)  # ⊢ wb(ph, wa(wo(ph, ps), ph))
    return proof.qed(_step_2)


@oranabs.proof
def prove_oranabs(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr2di
    from metamath_setmm_provider.shards.s002 import pm5_32ri
    from metamath_setmm_provider.shards.s004 import biortn, orcom


    _step_1 = proof.use(biortn, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wb(ph, wo(wn(ps), ph)))
    _step_2 = proof.use(
        orcom,
        subst={
            "ph": "wn(ps)",
            "ps": "ph",
        },
    )  # ⊢ wb(wo(wn(ps), ph), wo(ph, wn(ps)))
    _step_3 = proof.use(bitr2di, _step_1, _step_2)  # ⊢ wi(ps, wb(wo(ph, wn(ps)), ph))
    _step_4 = proof.use(pm5_32ri, _step_3)  # ⊢ wb(wa(wo(ph, wn(ps)), ps), wa(ph, ps))
    return proof.qed(_step_4)


@pm5_61.proof
def prove_pm5_61(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbid1
    from metamath_setmm_provider.shards.s002 import pm5_32ri
    from metamath_setmm_provider.shards.s004 import orc, orel2


    _step_1 = proof.use(orel2, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(ps), wi(wo(ph, ps), ph))
    _step_2 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_3 = proof.use(impbid1, _step_1, _step_2)  # ⊢ wi(wn(ps), wb(wo(ph, ps), ph))
    _step_4 = proof.use(pm5_32ri, _step_3)  # ⊢ wb(wa(wo(ph, ps), wn(ps)), wa(ph, wn(ps)))
    return proof.qed(_step_4)


@pm5_6.proof
def prove_pm5_6(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, imbi2i
    from metamath_setmm_provider.shards.s002 import impexp
    from metamath_setmm_provider.shards.s004 import df_or


    _step_1 = proof.use(
        impexp,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wa(ph, wn(ps)), ch), wi(ph, wi(wn(ps), ch)))
    _step_2 = proof.use(df_or, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wo(ps, ch), wi(wn(ps), ch))
    _step_3 = proof.use(
        imbi2i,
        _step_2,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wi(ph, wo(ps, ch)), wi(ph, wi(wn(ps), ch)))
    _step_4 = proof.use(
        bitr4i,
        _step_1,
        _step_3,
    )  # ⊢ wb(wi(wa(ph, wn(ps)), ch), wi(ph, wo(ps, ch)))
    return proof.qed(_step_4)


@orcanai.proof
def prove_orcanai(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import imp
    from metamath_setmm_provider.shards.s004 import ord


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(ph, wo(ps, ch))
    _step_1 = proof.use(ord, _hypothesis_1)  # ⊢ wi(ph, wi(wn(ps), ch))
    _step_2 = proof.use(imp, _step_1)  # ⊢ wi(wa(ph, wn(ps)), ch)
    return proof.qed(_step_2)


@pm4_79.proof
def prove_pm4_79(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id, simplim, syl5
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s002 import pm3_3
    from metamath_setmm_provider.shards.s004 import orrd


    _step_1 = proof.use(id, subst={"ph": "wi(ps, ph)"})  # ⊢ wi(wi(ps, ph), wi(ps, ph))
    _step_2 = proof.use(id, subst={"ph": "wi(ch, ph)"})  # ⊢ wi(wi(ch, ph), wi(ch, ph))
    _step_3 = proof.use(
        jaoa,
        _step_1,
        _step_2,
    )  # ⊢ wi(wo(wi(ps, ph), wi(ch, ph)), wi(wa(ps, ch), ph))
    _step_4 = proof.use(simplim, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(wi(ps, ph)), ps)
    _step_5 = proof.use(
        pm3_3,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "ph",
        },
    )  # ⊢ wi(wi(wa(ps, ch), ph), wi(ps, wi(ch, ph)))
    _step_6 = proof.use(
        syl5,
        _step_4,
        _step_5,
    )  # ⊢ wi(wi(wa(ps, ch), ph), wi(wn(wi(ps, ph)), wi(ch, ph)))
    _step_7 = proof.use(orrd, _step_6)  # ⊢ wi(wi(wa(ps, ch), ph), wo(wi(ps, ph), wi(ch, ph)))
    _step_8 = proof.use(
        impbii,
        _step_3,
        _step_7,
    )  # ⊢ wb(wo(wi(ps, ph), wi(ch, ph)), wi(wa(ps, ch), ph))
    return proof.qed(_step_8)


@ordi.proof
def prove_ordi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4i
    from metamath_setmm_provider.shards.s002 import jcab
    from metamath_setmm_provider.shards.s003 import anbi12i
    from metamath_setmm_provider.shards.s004 import df_or


    _step_1 = proof.use(
        jcab,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wn(ph), wa(ps, ch)), wa(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_2 = proof.use(
        df_or,
        subst={
            "ph": "ph",
            "ps": "wa(ps, ch)",
        },
    )  # ⊢ wb(wo(ph, wa(ps, ch)), wi(wn(ph), wa(ps, ch)))
    _step_3 = proof.use(df_or, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wi(wn(ph), ps))
    _step_4 = proof.use(df_or, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wo(ph, ch), wi(wn(ph), ch))
    _step_5 = proof.use(
        anbi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wa(wo(ph, ps), wo(ph, ch)), wa(wi(wn(ph), ps), wi(wn(ph), ch)))
    _step_6 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wo(ph, wa(ps, ch)), wa(wo(ph, ps), wo(ph, ch)))
    return proof.qed(_step_6)


@ordir.proof
def prove_ordir(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4i
    from metamath_setmm_provider.shards.s003 import anbi12i
    from metamath_setmm_provider.shards.s004 import orcom


    _step_1 = proof.use(
        ordi,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wb(wo(ch, wa(ph, ps)), wa(wo(ch, ph), wo(ch, ps)))
    _step_2 = proof.use(
        orcom,
        subst={
            "ph": "wa(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wo(wa(ph, ps), ch), wo(ch, wa(ph, ps)))
    _step_3 = proof.use(orcom, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wo(ph, ch), wo(ch, ph))
    _step_4 = proof.use(orcom, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wo(ps, ch), wo(ch, ps))
    _step_5 = proof.use(
        anbi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wa(wo(ph, ch), wo(ps, ch)), wa(wo(ch, ph), wo(ch, ps)))
    _step_6 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wo(wa(ph, ps), ch), wa(wo(ph, ch), wo(ps, ch)))
    return proof.qed(_step_6)


@andi.proof
def prove_andi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s003 import anim2i
    from metamath_setmm_provider.shards.s004 import jaodan, jaoi, olc, orc


    _step_1 = proof.use(
        orc,
        subst={
            "ph": "wa(ph, ps)",
            "ps": "wa(ph, ch)",
        },
    )  # ⊢ wi(wa(ph, ps), wo(wa(ph, ps), wa(ph, ch)))
    _step_2 = proof.use(
        olc,
        subst={
            "ph": "wa(ph, ch)",
            "ps": "wa(ph, ps)",
        },
    )  # ⊢ wi(wa(ph, ch), wo(wa(ph, ps), wa(ph, ch)))
    _step_3 = proof.use(
        jaodan,
        _step_1,
        _step_2,
    )  # ⊢ wi(wa(ph, wo(ps, ch)), wo(wa(ph, ps), wa(ph, ch)))
    _step_4 = proof.use(orc, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(ps, wo(ps, ch))
    _step_5 = proof.use(anim2i, _step_4, subst={"ch": "ph"})  # ⊢ wi(wa(ph, ps), wa(ph, wo(ps, ch)))
    _step_6 = proof.use(olc, subst={"ph": "ch", "ps": "ps"})  # ⊢ wi(ch, wo(ps, ch))
    _step_7 = proof.use(anim2i, _step_6, subst={"ch": "ph"})  # ⊢ wi(wa(ph, ch), wa(ph, wo(ps, ch)))
    _step_8 = proof.use(
        jaoi,
        _step_5,
        _step_7,
    )  # ⊢ wi(wo(wa(ph, ps), wa(ph, ch)), wa(ph, wo(ps, ch)))
    _step_9 = proof.use(
        impbii,
        _step_3,
        _step_8,
    )  # ⊢ wb(wa(ph, wo(ps, ch)), wo(wa(ph, ps), wa(ph, ch)))
    return proof.qed(_step_9)


@andir.proof
def prove_andir(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4i
    from metamath_setmm_provider.shards.s002 import ancom
    from metamath_setmm_provider.shards.s004 import orbi12i


    _step_1 = proof.use(
        andi,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wb(wa(ch, wo(ph, ps)), wo(wa(ch, ph), wa(ch, ps)))
    _step_2 = proof.use(
        ancom,
        subst={
            "ph": "wo(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wa(wo(ph, ps), ch), wa(ch, wo(ph, ps)))
    _step_3 = proof.use(ancom, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wa(ph, ch), wa(ch, ph))
    _step_4 = proof.use(ancom, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wa(ps, ch), wa(ch, ps))
    _step_5 = proof.use(
        orbi12i,
        _step_3,
        _step_4,
    )  # ⊢ wb(wo(wa(ph, ch), wa(ps, ch)), wo(wa(ch, ph), wa(ch, ps)))
    _step_6 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_2,
        _step_5,
    )  # ⊢ wb(wa(wo(ph, ps), ch), wo(wa(ph, ch), wa(ps, ch)))
    return proof.qed(_step_6)


@orddi.proof
def prove_orddi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s003 import anbi12i


    _step_1 = proof.use(
        ordir,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wa(ch, th)",
        },
    )  # ⊢ wb(wo(wa(ph, ps), wa(ch, th)), wa(wo(ph, wa(ch, th)), wo(ps, wa(ch, th))))
    _step_2 = proof.use(
        ordi,
        subst={
            "ph": "ph",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wb(wo(ph, wa(ch, th)), wa(wo(ph, ch), wo(ph, th)))
    _step_3 = proof.use(
        ordi,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wb(wo(ps, wa(ch, th)), wa(wo(ps, ch), wo(ps, th)))
    _step_4 = proof.use(
        anbi12i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wa(wo(ph, wa(ch, th)), wo(ps, wa(ch, th))), wa(wa(wo(ph, ch), wo(ph, th)), wa(wo(ps, …
    _step_5 = proof.use(
        bitri,
        _step_1,
        _step_4,
    )  # ⊢ wb(wo(wa(ph, ps), wa(ch, th)), wa(wa(wo(ph, ch), wo(ph, th)), wa(wo(ps, ch), wo(ps, th))…
    return proof.qed(_step_5)


@anddi.proof
def prove_anddi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s004 import orbi12i


    _step_1 = proof.use(
        andir,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wo(ch, th)",
        },
    )  # ⊢ wb(wa(wo(ph, ps), wo(ch, th)), wo(wa(ph, wo(ch, th)), wa(ps, wo(ch, th))))
    _step_2 = proof.use(
        andi,
        subst={
            "ph": "ph",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wb(wa(ph, wo(ch, th)), wo(wa(ph, ch), wa(ph, th)))
    _step_3 = proof.use(
        andi,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "th",
        },
    )  # ⊢ wb(wa(ps, wo(ch, th)), wo(wa(ps, ch), wa(ps, th)))
    _step_4 = proof.use(
        orbi12i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(wa(ph, wo(ch, th)), wa(ps, wo(ch, th))), wo(wo(wa(ph, ch), wa(ph, th)), wo(wa(ps, …
    _step_5 = proof.use(
        bitri,
        _step_1,
        _step_4,
    )  # ⊢ wb(wa(wo(ph, ps), wo(ch, th)), wo(wo(wa(ph, ch), wa(ph, th)), wo(wa(ps, ch), wa(ps, th))…
    return proof.qed(_step_5)


@pm5_54.proof
def prove_pm5_54(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomd, pm5_21ni
    from metamath_setmm_provider.shards.s002 import adantl, iba
    from metamath_setmm_provider.shards.s004 import orri


    _step_1 = proof.use(iba, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wb(ph, wa(ph, ps)))
    _step_2 = proof.use(bicomd, _step_1)  # ⊢ wi(ps, wb(wa(ph, ps), ph))
    _step_3 = proof.use(adantl, _step_2, subst={"ch": "ph"})  # ⊢ wi(wa(ph, ps), wb(wa(ph, ps), ph))
    _step_4 = proof.use(iba, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(ps, wb(ph, wa(ph, ps)))
    _step_5 = proof.use(bicomd, _step_4)  # ⊢ wi(ps, wb(wa(ph, ps), ph))
    _step_6 = proof.use(
        pm5_21ni,
        _step_3,
        _step_5,
    )  # ⊢ wi(wn(wb(wa(ph, ps), ph)), wb(wa(ph, ps), ps))
    _step_7 = proof.use(orri, _step_6)  # ⊢ wo(wb(wa(ph, ps), ph), wb(wa(ph, ps), ps))
    return proof.qed(_step_7)


@pm5_62.proof
def prove_pm5_62(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s003 import mpbiran2
    from metamath_setmm_provider.shards.s004 import exmid


    _step_1 = proof.use(exmid, subst={"ph": "ps"})  # ⊢ wo(ps, wn(ps))
    _step_2 = proof.use(
        ordir,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wn(ps)",
        },
    )  # ⊢ wb(wo(wa(ph, ps), wn(ps)), wa(wo(ph, wn(ps)), wo(ps, wn(ps))))
    _step_3 = proof.use(mpbiran2, _step_1, _step_2)  # ⊢ wb(wo(wa(ph, ps), wn(ps)), wo(ph, wn(ps)))
    return proof.qed(_step_3)


@pm5_63.proof
def prove_pm5_63(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s003 import mpbiran
    from metamath_setmm_provider.shards.s004 import exmid


    _step_1 = proof.use(exmid, subst={"ph": "ph"})  # ⊢ wo(ph, wn(ph))
    _step_2 = proof.use(
        ordi,
        subst={
            "ph": "ph",
            "ps": "wn(ph)",
            "ch": "ps",
        },
    )  # ⊢ wb(wo(ph, wa(wn(ph), ps)), wa(wo(ph, wn(ph)), wo(ph, ps)))
    _step_3 = proof.use(mpbiran, _step_1, _step_2)  # ⊢ wb(wo(ph, wa(wn(ph), ps)), wo(ph, ps))
    _step_4 = proof.use(bicomi, _step_3)  # ⊢ wb(wo(ph, ps), wo(ph, wa(wn(ph), ps)))
    return proof.qed(_step_4)


@niabn.proof
def prove_niabn(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_24i
    from metamath_setmm_provider.shards.s001 import pm5_21ni
    from metamath_setmm_provider.shards.s002 import simpr


    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(simpr, subst={"ph": "ch", "ps": "ps"})  # ⊢ wi(wa(ch, ps), ps)
    _step_2 = proof.use(pm2_24i, _hypothesis_1, subst={"ps": "ps"})  # ⊢ wi(wn(ph), ps)
    _step_3 = proof.use(pm5_21ni, _step_1, _step_2)  # ⊢ wi(wn(ps), wb(wa(ch, ps), wn(ph)))
    return proof.qed(_step_3)


@ninba.proof
def prove_ninba(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomd


    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(
        niabn,
        _hypothesis_1,
        subst={
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wn(ps), wb(wa(ch, ps), wn(ph)))
    _step_2 = proof.use(bicomd, _step_1)  # ⊢ wi(wn(ps), wb(wn(ph), wa(ch, ps)))
    return proof.qed(_step_2)


@pm4_43.proof
def prove_pm4_43(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s002 import pm3_24
    from metamath_setmm_provider.shards.s004 import biorfri


    _step_1 = proof.use(pm3_24, subst={"ph": "ps"})  # ⊢ wn(wa(ps, wn(ps)))
    _step_2 = proof.use(biorfri, _step_1, subst={"ps": "ph"})  # ⊢ wb(ph, wo(ph, wa(ps, wn(ps))))
    _step_3 = proof.use(
        ordi,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wn(ps)",
        },
    )  # ⊢ wb(wo(ph, wa(ps, wn(ps))), wa(wo(ph, ps), wo(ph, wn(ps))))
    _step_4 = proof.use(bitri, _step_2, _step_3)  # ⊢ wb(ph, wa(wo(ph, ps), wo(ph, wn(ps))))
    return proof.qed(_step_4)


@pm4_82.proof
def prove_pm4_82(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_21, pm2_65
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s002 import imp, jca


    _step_1 = proof.use(
        pm2_65,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wi(wi(ph, ps), wi(wi(ph, wn(ps)), wn(ph)))
    _step_2 = proof.use(imp, _step_1)  # ⊢ wi(wa(wi(ph, ps), wi(ph, wn(ps))), wn(ph))
    _step_3 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ph, ps))
    _step_4 = proof.use(pm2_21, subst={"ph": "ph", "ps": "wn(ps)"})  # ⊢ wi(wn(ph), wi(ph, wn(ps)))
    _step_5 = proof.use(jca, _step_3, _step_4)  # ⊢ wi(wn(ph), wa(wi(ph, ps), wi(ph, wn(ps))))
    _step_6 = proof.use(impbii, _step_2, _step_5)  # ⊢ wb(wa(wi(ph, ps), wi(ph, wn(ps))), wn(ph))
    return proof.qed(_step_6)


@pm4_83.proof
def prove_pm4_83(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import a1bi, bitr2i
    from metamath_setmm_provider.shards.s004 import exmid, jaob


    _step_1 = proof.use(exmid, subst={"ph": "ph"})  # ⊢ wo(ph, wn(ph))
    _step_2 = proof.use(a1bi, _step_1, subst={"ps": "ps"})  # ⊢ wb(ps, wi(wo(ph, wn(ph)), ps))
    _step_3 = proof.use(
        jaob,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "wn(ph)",
        },
    )  # ⊢ wb(wi(wo(ph, wn(ph)), ps), wa(wi(ph, ps), wi(wn(ph), ps)))
    _step_4 = proof.use(bitr2i, _step_2, _step_3)  # ⊢ wb(wa(wi(ph, ps), wi(wn(ph), ps)), ps)
    return proof.qed(_step_4)


@pclem6.proof
def prove_pclem6(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import con2i
    from metamath_setmm_provider.shards.s001 import nbbn, sylib
    from metamath_setmm_provider.shards.s002 import ibar


    _step_1 = proof.use(
        ibar,
        subst={
            "ph": "ps",
            "ps": "wn(ph)",
        },
    )  # ⊢ wi(ps, wb(wn(ph), wa(ps, wn(ph))))
    _step_2 = proof.use(
        nbbn,
        subst={
            "ph": "ph",
            "ps": "wa(ps, wn(ph))",
        },
    )  # ⊢ wb(wb(wn(ph), wa(ps, wn(ph))), wn(wb(ph, wa(ps, wn(ph)))))
    _step_3 = proof.use(sylib, _step_1, _step_2)  # ⊢ wi(ps, wn(wb(ph, wa(ps, wn(ph)))))
    _step_4 = proof.use(con2i, _step_3)  # ⊢ wi(wb(ph, wa(ps, wn(ph))), wn(ps))
    return proof.qed(_step_4)


@bigolden.proof
def prove_bigolden(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicom, mm_3bitr3ri
    from metamath_setmm_provider.shards.s002 import pm4_71
    from metamath_setmm_provider.shards.s004 import pm4_72


    _step_1 = proof.use(
        pm4_71,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, ps), wb(ph, wa(ph, ps)))
    _step_2 = proof.use(
        pm4_72,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, ps), wb(ps, wo(ph, ps)))
    _step_3 = proof.use(
        bicom,
        subst={
            "ph": "ph",
            "ps": "wa(ph, ps)",
        },
    )  # ⊢ wb(wb(ph, wa(ph, ps)), wb(wa(ph, ps), ph))
    _step_4 = proof.use(
        mm_3bitr3ri,
        _step_1,
        _step_2,
        _step_3,
    )  # ⊢ wb(wb(wa(ph, ps), ph), wb(ps, wo(ph, ps)))
    return proof.qed(_step_4)


@pm5_71.proof
def prove_pm5_71(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ja, pm2_21
    from metamath_setmm_provider.shards.s001 import impbid1
    from metamath_setmm_provider.shards.s002 import pm5_32rd
    from metamath_setmm_provider.shards.s003 import anbi1d
    from metamath_setmm_provider.shards.s004 import orc, orel2


    _step_1 = proof.use(orel2, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(ps), wi(wo(ph, ps), ph))
    _step_2 = proof.use(orc, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wo(ph, ps))
    _step_3 = proof.use(impbid1, _step_1, _step_2)  # ⊢ wi(wn(ps), wb(wo(ph, ps), ph))
    _step_4 = proof.use(
        anbi1d,
        _step_3,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wn(ps), wb(wa(wo(ph, ps), ch), wa(ph, ch)))
    _step_5 = proof.use(
        pm2_21,
        subst={
            "ph": "ch",
            "ps": "wb(wo(ph, ps), ph)",
        },
    )  # ⊢ wi(wn(ch), wi(ch, wb(wo(ph, ps), ph)))
    _step_6 = proof.use(pm5_32rd, _step_5)  # ⊢ wi(wn(ch), wb(wa(wo(ph, ps), ch), wa(ph, ch)))
    _step_7 = proof.use(
        ja,
        _step_4,
        _step_6,
    )  # ⊢ wi(wi(ps, wn(ch)), wb(wa(wo(ph, ps), ch), wa(ph, ch)))
    return proof.qed(_step_7)


@pm5_75.proof
def prove_pm5_75(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomd, bitrdi
    from metamath_setmm_provider.shards.s002 import pm5_32ri, rbaib, sylan9bbr
    from metamath_setmm_provider.shards.s003 import anbi1
    from metamath_setmm_provider.shards.s004 import abai, biorf


    _step_1 = proof.use(
        anbi1,
        subst={
            "ph": "ph",
            "ps": "wo(ps, ch)",
            "ch": "wn(ps)",
        },
    )  # ⊢ wi(wb(ph, wo(ps, ch)), wb(wa(ph, wn(ps)), wa(wo(ps, ch), wn(ps))))
    _step_2 = proof.use(biorf, subst={"ph": "ps", "ps": "ch"})  # ⊢ wi(wn(ps), wb(ch, wo(ps, ch)))
    _step_3 = proof.use(bicomd, _step_2)  # ⊢ wi(wn(ps), wb(wo(ps, ch), ch))
    _step_4 = proof.use(pm5_32ri, _step_3)  # ⊢ wb(wa(wo(ps, ch), wn(ps)), wa(ch, wn(ps)))
    _step_5 = proof.use(
        bitrdi,
        _step_1,
        _step_4,
    )  # ⊢ wi(wb(ph, wo(ps, ch)), wb(wa(ph, wn(ps)), wa(ch, wn(ps))))
    _step_6 = proof.use(
        abai,
        subst={
            "ph": "ch",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wa(ch, wn(ps)), wa(ch, wi(ch, wn(ps))))
    _step_7 = proof.use(rbaib, _step_6)  # ⊢ wi(wi(ch, wn(ps)), wb(wa(ch, wn(ps)), ch))
    _step_8 = proof.use(
        sylan9bbr,
        _step_5,
        _step_7,
    )  # ⊢ wi(wa(wi(ch, wn(ps)), wb(ph, wo(ps, ch))), wb(wa(ph, wn(ps)), ch))
    return proof.qed(_step_8)


@cases2.proof
def prove_cases2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4ri, pm5_74i
    from metamath_setmm_provider.shards.s002 import ancom
    from metamath_setmm_provider.shards.s003 import anbi12i
    from metamath_setmm_provider.shards.s004 import orbi12i
    from metamath_setmm_provider.shards.s005 import dedlema, dedlemb


    _step_1 = proof.use(
        pm4_83,
        subst={
            "ph": "ph",
            "ps": "wo(wa(ps, ph), wa(ch, wn(ph)))",
        },
    )  # ⊢ wb(wa(wi(ph, wo(wa(ps, ph), wa(ch, wn(ph)))), wi(wn(ph), wo(wa(ps, ph), wa(ch, wn(ph))))…
    _step_2 = proof.use(
        dedlema,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(ph, wb(ps, wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_3 = proof.use(
        pm5_74i,
        _step_2,
    )  # ⊢ wb(wi(ph, ps), wi(ph, wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_4 = proof.use(
        dedlemb,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wi(wn(ph), wb(ch, wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_5 = proof.use(
        pm5_74i,
        _step_4,
    )  # ⊢ wb(wi(wn(ph), ch), wi(wn(ph), wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_6 = proof.use(
        anbi12i,
        _step_3,
        _step_5,
    )  # ⊢ wb(wa(wi(ph, ps), wi(wn(ph), ch)), wa(wi(ph, wo(wa(ps, ph), wa(ch, wn(ph)))), wi(wn(ph),…
    _step_7 = proof.use(ancom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wa(ph, ps), wa(ps, ph))
    _step_8 = proof.use(
        ancom,
        subst={
            "ph": "wn(ph)",
            "ps": "ch",
        },
    )  # ⊢ wb(wa(wn(ph), ch), wa(ch, wn(ph)))
    _step_9 = proof.use(
        orbi12i,
        _step_7,
        _step_8,
    )  # ⊢ wb(wo(wa(ph, ps), wa(wn(ph), ch)), wo(wa(ps, ph), wa(ch, wn(ph))))
    _step_10 = proof.use(
        mm_3bitr4ri,
        _step_1,
        _step_6,
        _step_9,
    )  # ⊢ wb(wo(wa(ph, ps), wa(wn(ph), ch)), wa(wi(ph, ps), wi(wn(ph), ch)))
    return proof.qed(_step_10)


@cases2ALT.proof
def prove_cases2ALT(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_21, pm2_24, pm2_27
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s002 import adantr, imdistani, jca
    from metamath_setmm_provider.shards.s003 import adantrl, adantrr
    from metamath_setmm_provider.shards.s004 import jaoi, olcd, orcd, pm2_61ian, pm3_4


    _step_1 = proof.use(pm3_4, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), wi(ph, ps))
    _step_2 = proof.use(pm2_24, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(ph, wi(wn(ph), ch))
    _step_3 = proof.use(adantr, _step_2, subst={"ch": "ps"})  # ⊢ wi(wa(ph, ps), wi(wn(ph), ch))
    _step_4 = proof.use(jca, _step_1, _step_3)  # ⊢ wi(wa(ph, ps), wa(wi(ph, ps), wi(wn(ph), ch)))
    _step_5 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ph, ps))
    _step_6 = proof.use(adantr, _step_5, subst={"ch": "ch"})  # ⊢ wi(wa(wn(ph), ch), wi(ph, ps))
    _step_7 = proof.use(
        pm3_4,
        subst={
            "ph": "wn(ph)",
            "ps": "ch",
        },
    )  # ⊢ wi(wa(wn(ph), ch), wi(wn(ph), ch))
    _step_8 = proof.use(
        jca,
        _step_6,
        _step_7,
    )  # ⊢ wi(wa(wn(ph), ch), wa(wi(ph, ps), wi(wn(ph), ch)))
    _step_9 = proof.use(
        jaoi,
        _step_4,
        _step_8,
    )  # ⊢ wi(wo(wa(ph, ps), wa(wn(ph), ch)), wa(wi(ph, ps), wi(wn(ph), ch)))
    _step_10 = proof.use(pm2_27, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(wi(ph, ps), ps))
    _step_11 = proof.use(imdistani, _step_10)  # ⊢ wi(wa(ph, wi(ph, ps)), wa(ph, ps))
    _step_12 = proof.use(
        orcd,
        _step_11,
        subst={
            "ch": "wa(wn(ph), ch)",
        },
    )  # ⊢ wi(wa(ph, wi(ph, ps)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_13 = proof.use(
        adantrr,
        _step_12,
        subst={
            "th": "wi(wn(ph), ch)",
        },
    )  # ⊢ wi(wa(ph, wa(wi(ph, ps), wi(wn(ph), ch))), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_14 = proof.use(
        pm2_27,
        subst={
            "ph": "wn(ph)",
            "ps": "ch",
        },
    )  # ⊢ wi(wn(ph), wi(wi(wn(ph), ch), ch))
    _step_15 = proof.use(imdistani, _step_14)  # ⊢ wi(wa(wn(ph), wi(wn(ph), ch)), wa(wn(ph), ch))
    _step_16 = proof.use(
        olcd,
        _step_15,
        subst={
            "ch": "wa(ph, ps)",
        },
    )  # ⊢ wi(wa(wn(ph), wi(wn(ph), ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_17 = proof.use(
        adantrl,
        _step_16,
        subst={
            "th": "wi(ph, ps)",
        },
    )  # ⊢ wi(wa(wn(ph), wa(wi(ph, ps), wi(wn(ph), ch))), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_18 = proof.use(
        pm2_61ian,
        _step_13,
        _step_17,
    )  # ⊢ wi(wa(wi(ph, ps), wi(wn(ph), ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_19 = proof.use(
        impbii,
        _step_9,
        _step_18,
    )  # ⊢ wb(wo(wa(ph, ps), wa(wn(ph), ch)), wa(wi(ph, ps), wi(wn(ph), ch)))
    return proof.qed(_step_19)


@mm_4exmid.proof
def prove_mm_4exmid(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi
    from metamath_setmm_provider.shards.s004 import orri
    from metamath_setmm_provider.shards.s005 import pm5_24


    _step_1 = proof.use(
        pm5_24,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wo(wa(ph, ps), wa(wn(ph), wn(ps)))), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    _step_2 = proof.use(
        biimpi,
        _step_1,
    )  # ⊢ wi(wn(wo(wa(ph, ps), wa(wn(ph), wn(ps)))), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    _step_3 = proof.use(
        orri,
        _step_2,
    )  # ⊢ wo(wo(wa(ph, ps), wa(wn(ph), wn(ps))), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    return proof.qed(_step_3)


@consensus.proof
def prove_consensus(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s001 import impbii
    from metamath_setmm_provider.shards.s003 import adantrl, adantrr
    from metamath_setmm_provider.shards.s004 import jaoi, olc, orc, pm2_61ian


    _step_1 = proof.use(
        id,
        subst={
            "ph": "wo(wa(ph, ps), wa(wn(ph), ch))",
        },
    )  # ⊢ wi(wo(wa(ph, ps), wa(wn(ph), ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_2 = proof.use(
        orc,
        subst={
            "ph": "wa(ph, ps)",
            "ps": "wa(wn(ph), ch)",
        },
    )  # ⊢ wi(wa(ph, ps), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_3 = proof.use(
        adantrr,
        _step_2,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wa(ph, wa(ps, ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_4 = proof.use(
        olc,
        subst={
            "ph": "wa(wn(ph), ch)",
            "ps": "wa(ph, ps)",
        },
    )  # ⊢ wi(wa(wn(ph), ch), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_5 = proof.use(
        adantrl,
        _step_4,
        subst={
            "th": "ps",
        },
    )  # ⊢ wi(wa(wn(ph), wa(ps, ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_6 = proof.use(
        pm2_61ian,
        _step_3,
        _step_5,
    )  # ⊢ wi(wa(ps, ch), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_7 = proof.use(
        jaoi,
        _step_1,
        _step_6,
    )  # ⊢ wi(wo(wo(wa(ph, ps), wa(wn(ph), ch)), wa(ps, ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    _step_8 = proof.use(
        orc,
        subst={
            "ph": "wo(wa(ph, ps), wa(wn(ph), ch))",
            "ps": "wa(ps, ch)",
        },
    )  # ⊢ wi(wo(wa(ph, ps), wa(wn(ph), ch)), wo(wo(wa(ph, ps), wa(wn(ph), ch)), wa(ps, ch)))
    _step_9 = proof.use(
        impbii,
        _step_7,
        _step_8,
    )  # ⊢ wb(wo(wo(wa(ph, ps), wa(wn(ph), ch)), wa(ps, ch)), wo(wa(ph, ps), wa(wn(ph), ch)))
    return proof.qed(_step_9)


@pm4_42.proof
def prove_pm4_42(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_61i
    from metamath_setmm_provider.shards.s005 import dedlema, dedlemb


    _step_1 = proof.use(
        dedlema,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ph",
        },
    )  # ⊢ wi(ps, wb(ph, wo(wa(ph, ps), wa(ph, wn(ps)))))
    _step_2 = proof.use(
        dedlemb,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ph",
        },
    )  # ⊢ wi(wn(ps), wb(ph, wo(wa(ph, ps), wa(ph, wn(ps)))))
    _step_3 = proof.use(pm2_61i, _step_1, _step_2)  # ⊢ wb(ph, wo(wa(ph, ps), wa(ph, wn(ps))))
    return proof.qed(_step_3)


@prlem2.proof
def prove_prlem2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import pm4_71ri, simpl
    from metamath_setmm_provider.shards.s004 import orim12i


    _step_1 = proof.use(simpl, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ph)
    _step_2 = proof.use(simpl, subst={"ph": "ch", "ps": "th"})  # ⊢ wi(wa(ch, th), ch)
    _step_3 = proof.use(orim12i, _step_1, _step_2)  # ⊢ wi(wo(wa(ph, ps), wa(ch, th)), wo(ph, ch))
    _step_4 = proof.use(
        pm4_71ri,
        _step_3,
    )  # ⊢ wb(wo(wa(ph, ps), wa(ch, th)), wa(wo(ph, ch), wo(wa(ph, ps), wa(ch, th))))
    return proof.qed(_step_4)


@bianir.proof
def prove_bianir(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpr
    from metamath_setmm_provider.shards.s002 import impcom


    _step_1 = proof.use(biimpr, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wb(ps, ph), wi(ph, ps))
    _step_2 = proof.use(impcom, _step_1)  # ⊢ wi(wa(ph, wb(ps, ph)), ps)
    return proof.qed(_step_2)


@norasslem2.proof
def prove_norasslem2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimt
    from metamath_setmm_provider.shards.s004 import orcs


    _step_1 = proof.use(
        biimt,
        subst={
            "ph": "wo(ph, ch)",
            "ps": "ps",
        },
    )  # ⊢ wi(wo(ph, ch), wb(ps, wi(wo(ph, ch), ps)))
    _step_2 = proof.use(orcs, _step_1)  # ⊢ wi(ph, wb(ps, wi(wo(ph, ch), ps)))
    return proof.qed(_step_2)


@norasslem3.proof
def prove_norasslem3(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import imbi1d
    from metamath_setmm_provider.shards.s004 import biorf


    _step_1 = proof.use(biorf, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wb(ps, wo(ph, ps)))
    _step_2 = proof.use(
        imbi1d,
        _step_1,
        subst={
            "th": "ch",
        },
    )  # ⊢ wi(wn(ph), wb(wi(ps, ch), wi(wo(ph, ps), ch)))
    return proof.qed(_step_2)

__all__ = (
    'jaao',
    'jaoa',
    'animorl',
    'animorr',
    'animorlr',
    'animorrl',
    'ianor',
    'anor',
    'ioran',
    'pm4_52',
    'pm4_53',
    'pm4_54',
    'pm4_55',
    'pm4_56',
    'oran',
    'pm4_57',
    'pm3_1',
    'pm3_11',
    'pm3_12',
    'pm3_13',
    'pm3_14',
    'pm4_44',
    'pm4_45',
    'orabs',
    'oranabs',
    'pm5_61',
    'pm5_6',
    'orcanai',
    'pm4_79',
    'ordi',
    'ordir',
    'andi',
    'andir',
    'orddi',
    'anddi',
    'pm5_54',
    'pm5_62',
    'pm5_63',
    'niabn',
    'ninba',
    'pm4_43',
    'pm4_82',
    'pm4_83',
    'pclem6',
    'bigolden',
    'pm5_71',
    'pm5_75',
    'cases2',
    'cases2ALT',
    'mm_4exmid',
    'consensus',
    'pm4_42',
    'prlem2',
    'bianir',
    'norasslem2',
    'norasslem3',
)
