# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from metamath_setmm_provider.shards.s007 import (
    df_nor as df_nor,
)
from metamath_setmm_provider.shards.s007 import (
    noran as noran,
)
from metamath_setmm_provider.shards.s007 import (
    norass as norass,
)
from metamath_setmm_provider.shards.s007 import (
    norasslem1 as norasslem1,
)
from metamath_setmm_provider.shards.s007 import (
    norcom as norcom,
)
from metamath_setmm_provider.shards.s007 import (
    nornot as nornot,
)
from metamath_setmm_provider.shards.s007 import (
    noror as noror,
)
from metamath_setmm_provider.shards.s007 import (
    wnor as wnor,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.metamath_language import FormationBinding
from skfd.authoring.theory import TheoryProofAuthor

if str(wnor.syntax_assertion) != (
    'urn:uuid:f29cdcd1-8745-5647-9a78-e1404d9d4bfa'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(df_nor.id) != (
    'urn:uuid:134eb93a-afaf-5b98-8d15-105d4fac8dc8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norcom.id) != (
    'urn:uuid:27531927-41c5-5c6d-9a8e-ec10af92625d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(nornot.id) != (
    'urn:uuid:ad3f47f0-724c-5a83-bb12-88ab35c40ceb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(noran.id) != (
    'urn:uuid:0887f534-9778-5720-87a2-aa1b7787b354'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(noror.id) != (
    'urn:uuid:973af780-8d0b-50c8-a793-de333fcb10ba'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norasslem1.id) != (
    'urn:uuid:ae3bce36-759f-53f5-ae6c-889243250871'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(norass.id) != (
    'urn:uuid:16271ce8-125d-50ee-90f6-c20c5f531e5d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@norcom.proof
def prove_norcom(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, xchbinx
    from metamath_setmm_provider.shards.s004 import orcom


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wnor(ph, ps), wn(wo(ph, ps)))
    _step_2 = proof.use(orcom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wo(ps, ph))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnor(ph, ps), wn(wo(ps, ph)))
    _step_4 = proof.use(
        df_nor,
        subst={
            "ph": "ps",
            "ps": "ph",
        },
    )  # ⊢ wb(wnor(ps, ph), wn(wo(ps, ph)))
    _step_5 = proof.use(bitr4i, _step_3, _step_4)  # ⊢ wb(wnor(ph, ps), wnor(ps, ph))
    return proof.qed(_step_5)


@nornot.proof
def prove_nornot(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi, xchbinx
    from metamath_setmm_provider.shards.s004 import oridm


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "ph",
            "ps": "ph",
        },
    )  # ⊢ wb(wnor(ph, ph), wn(wo(ph, ph)))
    _step_2 = proof.use(oridm, subst={"ph": "ph"})  # ⊢ wb(wo(ph, ph), ph)
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnor(ph, ph), wn(ph))
    _step_4 = proof.use(bicomi, _step_3)  # ⊢ wb(wn(ph), wnor(ph, ph))
    return proof.qed(_step_4)


@noran.proof
def prove_noran(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, xchbinx
    from metamath_setmm_provider.shards.s004 import anor, orbi12i


    _step_1 = proof.use(
        anor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(ph, ps), wn(wo(wn(ph), wn(ps))))
    _step_2 = proof.use(nornot, subst={"ph": "ph"})  # ⊢ wb(wn(ph), wnor(ph, ph))
    _step_3 = proof.use(nornot, subst={"ph": "ps"})  # ⊢ wb(wn(ps), wnor(ps, ps))
    _step_4 = proof.use(
        orbi12i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(wn(ph), wn(ps)), wo(wnor(ph, ph), wnor(ps, ps)))
    _step_5 = proof.use(
        xchbinx,
        _step_1,
        _step_4,
    )  # ⊢ wb(wa(ph, ps), wn(wo(wnor(ph, ph), wnor(ps, ps))))
    _step_6 = proof.use(
        df_nor,
        subst={
            "ph": "wnor(ph, ph)",
            "ps": "wnor(ps, ps)",
        },
    )  # ⊢ wb(wnor(wnor(ph, ph), wnor(ps, ps)), wn(wo(wnor(ph, ph), wnor(ps, ps))))
    _step_7 = proof.use(
        bitr4i,
        _step_5,
        _step_6,
    )  # ⊢ wb(wa(ph, ps), wnor(wnor(ph, ph), wnor(ps, ps)))
    return proof.qed(_step_7)


@noror.proof
def prove_noror(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, con2bii


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wnor(ph, ps), wn(wo(ph, ps)))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wo(ph, ps), wn(wnor(ph, ps)))
    _step_3 = proof.use(
        nornot,
        subst={
            "ph": "wnor(ph, ps)",
        },
    )  # ⊢ wb(wn(wnor(ph, ps)), wnor(wnor(ph, ps), wnor(ph, ps)))
    _step_4 = proof.use(
        bitri,
        _step_2,
        _step_3,
    )  # ⊢ wb(wo(ph, ps), wnor(wnor(ph, ps), wnor(ph, ps)))
    return proof.qed(_step_4)


@norasslem1.proof
def prove_norasslem1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i
    from metamath_setmm_provider.shards.s004 import imor, orbi1i


    _step_1 = proof.use(
        imor,
        subst={
            "ph": "wo(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wi(wo(ph, ps), ch), wo(wn(wo(ph, ps)), ch))
    _step_2 = proof.use(
        df_nor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wnor(ph, ps), wn(wo(ph, ps)))
    _step_3 = proof.use(
        orbi1i,
        _step_2,
        subst={
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wnor(ph, ps), ch), wo(wn(wo(ph, ps)), ch))
    _step_4 = proof.use(bitr4i, _step_1, _step_3)  # ⊢ wb(wi(wo(ph, ps), ch), wo(wnor(ph, ps), ch))
    return proof.qed(_step_4)


@norass.proof
def prove_norass(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_61i
    from metamath_setmm_provider.shards.s001 import (
        bibi12d,
        bibi12i,
        bicom,
        bitrid,
        mm_3bitr4i,
        notbi,
    )
    from metamath_setmm_provider.shards.s004 import impimprbi, orbi1i, orcom
    from metamath_setmm_provider.shards.s007 import norasslem2, norasslem3


    _step_1 = proof.use(
        notbi,
        subst={
            "ph": "wo(wnor(ph, ps), ch)",
            "ps": "wo(ph, wnor(ps, ch))",
        },
    )  # ⊢ wb(wb(wo(wnor(ph, ps), ch), wo(ph, wnor(ps, ch))), wb(wn(wo(wnor(ph, ps), ch)), wn(wo(ph…
    _step_2 = proof.use(
        norasslem1,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wo(ps, ph), ch), wo(wnor(ps, ph), ch))
    _step_3 = proof.use(
        norasslem1,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "ph",
        },
    )  # ⊢ wb(wi(wo(ps, ch), ph), wo(wnor(ps, ch), ph))
    _step_4 = proof.use(
        bibi12i,
        _step_2,
        _step_3,
    )  # ⊢ wb(wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph)), wb(wo(wnor(ps, ph), ch), wo(wnor(ps, ch),…
    _step_5 = proof.use(bicom, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wb(ph, ch), wb(ch, ph))
    _step_6 = proof.use(
        norasslem2,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "ph",
        },
    )  # ⊢ wi(ps, wb(ch, wi(wo(ps, ph), ch)))
    _step_7 = proof.use(
        norasslem2,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wi(ps, wb(ph, wi(wo(ps, ch), ph)))
    _step_8 = proof.use(
        bibi12d,
        _step_6,
        _step_7,
    )  # ⊢ wi(ps, wb(wb(ch, ph), wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph))))
    _step_9 = proof.use(
        bitrid,
        _step_5,
        _step_8,
    )  # ⊢ wi(ps, wb(wb(ph, ch), wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph))))
    _step_10 = proof.use(
        impimprbi,
        subst={
            "ph": "ph",
            "ps": "ch",
        },
    )  # ⊢ wb(wb(ph, ch), wb(wi(ph, ch), wi(ch, ph)))
    _step_11 = proof.use(
        norasslem3,
        subst={
            "ph": "ps",
            "ps": "ph",
            "ch": "ch",
        },
    )  # ⊢ wi(wn(ps), wb(wi(ph, ch), wi(wo(ps, ph), ch)))
    _step_12 = proof.use(
        norasslem3,
        subst={
            "ph": "ps",
            "ps": "ch",
            "ch": "ph",
        },
    )  # ⊢ wi(wn(ps), wb(wi(ch, ph), wi(wo(ps, ch), ph)))
    _step_13 = proof.use(
        bibi12d,
        _step_11,
        _step_12,
    )  # ⊢ wi(wn(ps), wb(wb(wi(ph, ch), wi(ch, ph)), wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph))))
    _step_14 = proof.use(
        bitrid,
        _step_10,
        _step_13,
    )  # ⊢ wi(wn(ps), wb(wb(ph, ch), wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph))))
    _step_15 = proof.use(
        pm2_61i,
        _step_9,
        _step_14,
    )  # ⊢ wb(wb(ph, ch), wb(wi(wo(ps, ph), ch), wi(wo(ps, ch), ph)))
    _step_16 = proof.use(norcom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wnor(ph, ps), wnor(ps, ph))
    _step_17 = proof.use(
        orbi1i,
        _step_16,
        subst={
            "ch": "ch",
        },
    )  # ⊢ wb(wo(wnor(ph, ps), ch), wo(wnor(ps, ph), ch))
    _step_18 = proof.use(
        orcom,
        subst={
            "ph": "ph",
            "ps": "wnor(ps, ch)",
        },
    )  # ⊢ wb(wo(ph, wnor(ps, ch)), wo(wnor(ps, ch), ph))
    _step_19 = proof.use(
        bibi12i,
        _step_17,
        _step_18,
    )  # ⊢ wb(wb(wo(wnor(ph, ps), ch), wo(ph, wnor(ps, ch))), wb(wo(wnor(ps, ph), ch), wo(wnor(ps, …
    _step_20 = proof.use(
        mm_3bitr4i,
        _step_4,
        _step_15,
        _step_19,
    )  # ⊢ wb(wb(ph, ch), wb(wo(wnor(ph, ps), ch), wo(ph, wnor(ps, ch))))
    _step_21 = proof.use(
        df_nor,
        subst={
            "ph": "wnor(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wnor(wnor(ph, ps), ch), wn(wo(wnor(ph, ps), ch)))
    _step_22 = proof.use(
        df_nor,
        subst={
            "ph": "ph",
            "ps": "wnor(ps, ch)",
        },
    )  # ⊢ wb(wnor(ph, wnor(ps, ch)), wn(wo(ph, wnor(ps, ch))))
    _step_23 = proof.use(
        bibi12i,
        _step_21,
        _step_22,
    )  # ⊢ wb(wb(wnor(wnor(ph, ps), ch), wnor(ph, wnor(ps, ch))), wb(wn(wo(wnor(ph, ps), ch)), wn(w…
    _step_24 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_20,
        _step_23,
    )  # ⊢ wb(wb(ph, ch), wb(wnor(wnor(ph, ps), ch), wnor(ph, wnor(ps, ch))))
    return proof.qed(_step_24)

__all__ = (
    'df_nor',
    'norcom',
    'nornot',
    'noran',
    'noror',
    'norasslem1',
    'norass',
)

FORMATION_BINDINGS_BY_LABEL: Mapping[str, FormationBinding] = MappingProxyType({
    'wnor': wnor,
})
