# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from metamath_setmm_provider.shards.s007 import (
    falbifal as falbifal,
)
from metamath_setmm_provider.shards.s007 import (
    falbitru as falbitru,
)
from metamath_setmm_provider.shards.s007 import (
    falimfal as falimfal,
)
from metamath_setmm_provider.shards.s007 import (
    falimtru as falimtru,
)
from metamath_setmm_provider.shards.s007 import (
    notfal as notfal,
)
from metamath_setmm_provider.shards.s007 import (
    nottru as nottru,
)
from metamath_setmm_provider.shards.s007 import (
    trubifal as trubifal,
)
from metamath_setmm_provider.shards.s007 import (
    trubitru as trubitru,
)
from metamath_setmm_provider.shards.s007 import (
    truimfal as truimfal,
)
from metamath_setmm_provider.shards.s007 import (
    truimtru as truimtru,
)
from metamath_setmm_provider.shards.s008 import (
    falanfal as falanfal,
)
from metamath_setmm_provider.shards.s008 import (
    falantru as falantru,
)
from metamath_setmm_provider.shards.s008 import (
    falnanfal as falnanfal,
)
from metamath_setmm_provider.shards.s008 import (
    falnantru as falnantru,
)
from metamath_setmm_provider.shards.s008 import (
    falnorfal as falnorfal,
)
from metamath_setmm_provider.shards.s008 import (
    falnortru as falnortru,
)
from metamath_setmm_provider.shards.s008 import (
    falorfal as falorfal,
)
from metamath_setmm_provider.shards.s008 import (
    falortru as falortru,
)
from metamath_setmm_provider.shards.s008 import (
    falxorfal as falxorfal,
)
from metamath_setmm_provider.shards.s008 import (
    falxortru as falxortru,
)
from metamath_setmm_provider.shards.s008 import (
    truanfal as truanfal,
)
from metamath_setmm_provider.shards.s008 import (
    truantru as truantru,
)
from metamath_setmm_provider.shards.s008 import (
    trunanfal as trunanfal,
)
from metamath_setmm_provider.shards.s008 import (
    trunantru as trunantru,
)
from metamath_setmm_provider.shards.s008 import (
    trunorfal as trunorfal,
)
from metamath_setmm_provider.shards.s008 import (
    trunortru as trunortru,
)
from metamath_setmm_provider.shards.s008 import (
    truorfal as truorfal,
)
from metamath_setmm_provider.shards.s008 import (
    truortru as truortru,
)
from metamath_setmm_provider.shards.s008 import (
    truxorfal as truxorfal,
)
from metamath_setmm_provider.shards.s008 import (
    truxortru as truxortru,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.theory import TheoryProofAuthor

if str(truimtru.id) != (
    'urn:uuid:9aa099bf-eafa-5930-8f86-e719fac5250c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truimfal.id) != (
    'urn:uuid:9b5140ae-246f-560b-821e-14d293921462'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falimtru.id) != (
    'urn:uuid:94dae44d-b503-5c42-a71e-ca1eef20f236'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falimfal.id) != (
    'urn:uuid:7d7dec23-0c43-5347-aadb-c831ffd3e6e0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(nottru.id) != (
    'urn:uuid:7c61ddd3-3d50-5810-b928-d4c4b78ab50d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(notfal.id) != (
    'urn:uuid:9b29b319-8d6c-5059-904b-a5eddeca5090'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trubitru.id) != (
    'urn:uuid:3aad8628-c834-5ced-8802-880d28132191'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falbitru.id) != (
    'urn:uuid:f2696bc2-f255-5958-b1d5-364b454e911a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trubifal.id) != (
    'urn:uuid:d11e8631-2735-5e3d-b889-f3cee023404e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falbifal.id) != (
    'urn:uuid:1e765a8a-3959-550e-bdbf-a2437fa870a6'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truantru.id) != (
    'urn:uuid:f109368d-5519-562a-af02-83ba8508727d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truanfal.id) != (
    'urn:uuid:d21df5c6-06c2-53a4-a247-f55a55d55ce9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falantru.id) != (
    'urn:uuid:d8b93f24-2e68-52d6-bf80-a3edbdac5b85'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falanfal.id) != (
    'urn:uuid:ff5cb765-9161-5f97-8e4a-e87720b95909'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truortru.id) != (
    'urn:uuid:534ee767-e3cf-5c89-92bd-7546d13e0236'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truorfal.id) != (
    'urn:uuid:6c823a8a-a129-5ccd-952b-e9ba7b7e13d4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falortru.id) != (
    'urn:uuid:e4f551b8-8367-5bd3-bf90-f7faebda40b5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falorfal.id) != (
    'urn:uuid:f6908d58-2357-5202-897a-1612359b77f0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trunantru.id) != (
    'urn:uuid:ec31340f-5f74-5d26-a57b-f101007cf1fe'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trunanfal.id) != (
    'urn:uuid:59ab954f-05b7-5268-b476-72e5fa191649'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falnantru.id) != (
    'urn:uuid:29d28f05-bdbf-56ab-9b0a-02c6da9611ad'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falnanfal.id) != (
    'urn:uuid:b0cc1f74-7508-5335-b79c-22e5a7c1f8a4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truxortru.id) != (
    'urn:uuid:add30b1e-1580-5d6c-af97-35a1e651cdf0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truxorfal.id) != (
    'urn:uuid:793bcaa8-5058-5352-82c0-ba208555b89b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falxortru.id) != (
    'urn:uuid:49622d0a-0e08-5ee5-bcdb-aac42411648c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falxorfal.id) != (
    'urn:uuid:2d412b13-c8e9-5a07-95f8-1679a95adcd1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trunortru.id) != (
    'urn:uuid:ad834aa0-a47d-51e2-bd9e-7dd2ba13556d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trunorfal.id) != (
    'urn:uuid:05ed71c5-99d9-5823-98da-e7cc4d8c0008'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falnortru.id) != (
    'urn:uuid:c586e254-86e2-50cc-82da-ac345d660504'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falnorfal.id) != (
    'urn:uuid:bea3fe6e-30b0-5e20-95be-a2ccaca62a6c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@truimtru.proof
def prove_truimtru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s007 import bitru


    _step_1 = proof.use(id, subst={"ph": "wtru()"})  # ⊢ wi(wtru(), wtru())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wi(wtru(), wtru()), wtru())
    return proof.qed(_step_2)


@truimfal.proof
def prove_truimfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s007 import trut


    _step_1 = proof.use(trut, subst={"ph": "wfal()"})  # ⊢ wb(wfal(), wi(wtru(), wfal()))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wi(wtru(), wfal()), wfal())
    return proof.qed(_step_2)


@falimtru.proof
def prove_falimtru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s007 import bitru, trud

    _step_1 = proof.use(trud, subst={"ph": "wfal()"})  # ⊢ wi(wfal(), wtru())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wi(wfal(), wtru()), wtru())
    return proof.qed(_step_2)


@falimfal.proof
def prove_falimfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s007 import bitru


    _step_1 = proof.use(id, subst={"ph": "wfal()"})  # ⊢ wi(wfal(), wfal())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wi(wfal(), wfal()), wtru())
    return proof.qed(_step_2)


@nottru.proof
def prove_nottru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s007 import df_fal


    _step_1 = proof.use(df_fal)  # ⊢ wb(wfal(), wn(wtru()))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wn(wtru()), wfal())
    return proof.qed(_step_2)


@notfal.proof
def prove_notfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s007 import bitru, fal

    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wn(wfal()), wtru())
    return proof.qed(_step_2)


@trubitru.proof
def prove_trubitru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biid
    from metamath_setmm_provider.shards.s007 import bitru


    _step_1 = proof.use(biid, subst={"ph": "wtru()"})  # ⊢ wb(wtru(), wtru())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wb(wtru(), wtru()), wtru())
    return proof.qed(_step_2)


@falbitru.proof
def prove_falbitru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s007 import tbtru


    _step_1 = proof.use(tbtru, subst={"ph": "wfal()"})  # ⊢ wb(wfal(), wb(wfal(), wtru()))
    _step_2 = proof.use(bicomi, _step_1)  # ⊢ wb(wb(wfal(), wtru()), wfal())
    return proof.qed(_step_2)


@trubifal.proof
def prove_trubifal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicom, bitri


    _step_1 = proof.use(
        bicom,
        subst={
            "ph": "wtru()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wb(wtru(), wfal()), wb(wfal(), wtru()))
    _step_2 = proof.use(falbitru)  # ⊢ wb(wb(wfal(), wtru()), wfal())
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(wb(wtru(), wfal()), wfal())
    return proof.qed(_step_3)


@falbifal.proof
def prove_falbifal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biid
    from metamath_setmm_provider.shards.s007 import bitru


    _step_1 = proof.use(biid, subst={"ph": "wfal()"})  # ⊢ wb(wfal(), wfal())
    _step_2 = proof.use(bitru, _step_1)  # ⊢ wb(wb(wfal(), wfal()), wtru())
    return proof.qed(_step_2)


@truantru.proof
def prove_truantru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import anidm


    _step_1 = proof.use(anidm, subst={"ph": "wtru()"})  # ⊢ wb(wa(wtru(), wtru()), wtru())
    return proof.qed(_step_1)


@truanfal.proof
def prove_truanfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s007 import truan


    _step_1 = proof.use(truan, subst={"ph": "wfal()"})  # ⊢ wb(wa(wtru(), wfal()), wfal())
    return proof.qed(_step_1)


@falantru.proof
def prove_falantru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import intnanr
    from metamath_setmm_provider.shards.s007 import bifal, fal


    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(intnanr, _step_1, subst={"ps": "wtru()"})  # ⊢ wn(wa(wfal(), wtru()))
    _step_3 = proof.use(bifal, _step_2)  # ⊢ wb(wa(wfal(), wtru()), wfal())
    return proof.qed(_step_3)


@falanfal.proof
def prove_falanfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import anidm


    _step_1 = proof.use(anidm, subst={"ph": "wfal()"})  # ⊢ wb(wa(wfal(), wfal()), wfal())
    return proof.qed(_step_1)


@truortru.proof
def prove_truortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import oridm


    _step_1 = proof.use(oridm, subst={"ph": "wtru()"})  # ⊢ wb(wo(wtru(), wtru()), wtru())
    return proof.qed(_step_1)


@truorfal.proof
def prove_truorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import orci
    from metamath_setmm_provider.shards.s007 import bitru, tru


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(orci, _step_1, subst={"ps": "wfal()"})  # ⊢ wo(wtru(), wfal())
    _step_3 = proof.use(bitru, _step_2)  # ⊢ wb(wo(wtru(), wfal()), wtru())
    return proof.qed(_step_3)


@falortru.proof
def prove_falortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import olci
    from metamath_setmm_provider.shards.s007 import bitru, tru


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(olci, _step_1, subst={"ps": "wfal()"})  # ⊢ wo(wfal(), wtru())
    _step_3 = proof.use(bitru, _step_2)  # ⊢ wb(wo(wfal(), wtru()), wtru())
    return proof.qed(_step_3)


@falorfal.proof
def prove_falorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import oridm


    _step_1 = proof.use(oridm, subst={"ph": "wfal()"})  # ⊢ wb(wo(wfal(), wfal()), wfal())
    return proof.qed(_step_1)


@trunantru.proof
def prove_trunantru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr3i
    from metamath_setmm_provider.shards.s007 import nannot


    _step_1 = proof.use(nannot, subst={"ph": "wtru()"})  # ⊢ wb(wn(wtru()), wnan(wtru(), wtru()))
    _step_2 = proof.use(nottru)  # ⊢ wb(wn(wtru()), wfal())
    _step_3 = proof.use(bitr3i, _step_1, _step_2)  # ⊢ wb(wnan(wtru(), wtru()), wfal())
    return proof.qed(_step_3)


@trunanfal.proof
def prove_trunanfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx
    from metamath_setmm_provider.shards.s007 import df_nan


    _step_1 = proof.use(
        df_nan,
        subst={
            "ph": "wtru()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wnan(wtru(), wfal()), wn(wa(wtru(), wfal())))
    _step_2 = proof.use(truanfal)  # ⊢ wb(wa(wtru(), wfal()), wfal())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnan(wtru(), wfal()), wn(wfal()))
    _step_4 = proof.use(notfal)  # ⊢ wb(wn(wfal()), wtru())
    _step_5 = proof.use(bitri, _step_3, _step_4)  # ⊢ wb(wnan(wtru(), wfal()), wtru())
    return proof.qed(_step_5)


@falnantru.proof
def prove_falnantru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s007 import nancom


    _step_1 = proof.use(
        nancom,
        subst={
            "ph": "wfal()",
            "ps": "wtru()",
        },
    )  # ⊢ wb(wnan(wfal(), wtru()), wnan(wtru(), wfal()))
    _step_2 = proof.use(trunanfal)  # ⊢ wb(wnan(wtru(), wfal()), wtru())
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(wnan(wfal(), wtru()), wtru())
    return proof.qed(_step_3)


@falnanfal.proof
def prove_falnanfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr3i
    from metamath_setmm_provider.shards.s007 import nannot


    _step_1 = proof.use(nannot, subst={"ph": "wfal()"})  # ⊢ wb(wn(wfal()), wnan(wfal(), wfal()))
    _step_2 = proof.use(notfal)  # ⊢ wb(wn(wfal()), wtru())
    _step_3 = proof.use(bitr3i, _step_1, _step_2)  # ⊢ wb(wnan(wfal(), wfal()), wtru())
    return proof.qed(_step_3)


@truxortru.proof
def prove_truxortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx
    from metamath_setmm_provider.shards.s007 import df_xor


    _step_1 = proof.use(
        df_xor,
        subst={
            "ph": "wtru()",
            "ps": "wtru()",
        },
    )  # ⊢ wb(wxo(wtru(), wtru()), wn(wb(wtru(), wtru())))
    _step_2 = proof.use(trubitru)  # ⊢ wb(wb(wtru(), wtru()), wtru())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wxo(wtru(), wtru()), wn(wtru()))
    _step_4 = proof.use(nottru)  # ⊢ wb(wn(wtru()), wfal())
    _step_5 = proof.use(bitri, _step_3, _step_4)  # ⊢ wb(wxo(wtru(), wtru()), wfal())
    return proof.qed(_step_5)


@truxorfal.proof
def prove_truxorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx
    from metamath_setmm_provider.shards.s007 import df_xor


    _step_1 = proof.use(
        df_xor,
        subst={
            "ph": "wtru()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wxo(wtru(), wfal()), wn(wb(wtru(), wfal())))
    _step_2 = proof.use(trubifal)  # ⊢ wb(wb(wtru(), wfal()), wfal())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wxo(wtru(), wfal()), wn(wfal()))
    _step_4 = proof.use(notfal)  # ⊢ wb(wn(wfal()), wtru())
    _step_5 = proof.use(bitri, _step_3, _step_4)  # ⊢ wb(wxo(wtru(), wfal()), wtru())
    return proof.qed(_step_5)


@falxortru.proof
def prove_falxortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s007 import xorcom


    _step_1 = proof.use(
        xorcom,
        subst={
            "ph": "wfal()",
            "ps": "wtru()",
        },
    )  # ⊢ wb(wxo(wfal(), wtru()), wxo(wtru(), wfal()))
    _step_2 = proof.use(truxorfal)  # ⊢ wb(wxo(wtru(), wfal()), wtru())
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(wxo(wfal(), wtru()), wtru())
    return proof.qed(_step_3)


@falxorfal.proof
def prove_falxorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx
    from metamath_setmm_provider.shards.s007 import df_xor


    _step_1 = proof.use(
        df_xor,
        subst={
            "ph": "wfal()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wxo(wfal(), wfal()), wn(wb(wfal(), wfal())))
    _step_2 = proof.use(falbifal)  # ⊢ wb(wb(wfal(), wfal()), wtru())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wxo(wfal(), wfal()), wn(wtru()))
    _step_4 = proof.use(nottru)  # ⊢ wb(wn(wtru()), wfal())
    _step_5 = proof.use(bitri, _step_3, _step_4)  # ⊢ wb(wxo(wfal(), wfal()), wfal())
    return proof.qed(_step_5)


@trunortru.proof
def prove_trunortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, xchbinx
    from metamath_setmm_provider.shards.s007 import df_fal, df_nor


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "wtru()",
            "ps": "wtru()",
        },
    )  # ⊢ wb(wnor(wtru(), wtru()), wn(wo(wtru(), wtru())))
    _step_2 = proof.use(truortru)  # ⊢ wb(wo(wtru(), wtru()), wtru())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnor(wtru(), wtru()), wn(wtru()))
    _step_4 = proof.use(df_fal)  # ⊢ wb(wfal(), wn(wtru()))
    _step_5 = proof.use(bitr4i, _step_3, _step_4)  # ⊢ wb(wnor(wtru(), wtru()), wfal())
    return proof.qed(_step_5)


@trunorfal.proof
def prove_trunorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, xchbinx
    from metamath_setmm_provider.shards.s007 import df_fal, df_nor


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "wtru()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wnor(wtru(), wfal()), wn(wo(wtru(), wfal())))
    _step_2 = proof.use(truorfal)  # ⊢ wb(wo(wtru(), wfal()), wtru())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnor(wtru(), wfal()), wn(wtru()))
    _step_4 = proof.use(df_fal)  # ⊢ wb(wfal(), wn(wtru()))
    _step_5 = proof.use(bitr4i, _step_3, _step_4)  # ⊢ wb(wnor(wtru(), wfal()), wfal())
    return proof.qed(_step_5)


@falnortru.proof
def prove_falnortru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri
    from metamath_setmm_provider.shards.s007 import norcom


    _step_1 = proof.use(
        norcom,
        subst={
            "ph": "wfal()",
            "ps": "wtru()",
        },
    )  # ⊢ wb(wnor(wfal(), wtru()), wnor(wtru(), wfal()))
    _step_2 = proof.use(trunorfal)  # ⊢ wb(wnor(wtru(), wfal()), wfal())
    _step_3 = proof.use(bitri, _step_1, _step_2)  # ⊢ wb(wnor(wfal(), wtru()), wfal())
    return proof.qed(_step_3)


@falnorfal.proof
def prove_falnorfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx
    from metamath_setmm_provider.shards.s007 import df_nor


    _step_1 = proof.use(
        df_nor,
        subst={
            "ph": "wfal()",
            "ps": "wfal()",
        },
    )  # ⊢ wb(wnor(wfal(), wfal()), wn(wo(wfal(), wfal())))
    _step_2 = proof.use(falorfal)  # ⊢ wb(wo(wfal(), wfal()), wfal())
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wnor(wfal(), wfal()), wn(wfal()))
    _step_4 = proof.use(notfal)  # ⊢ wb(wn(wfal()), wtru())
    _step_5 = proof.use(bitri, _step_3, _step_4)  # ⊢ wb(wnor(wfal(), wfal()), wtru())
    return proof.qed(_step_5)

__all__ = (
    'truimtru',
    'truimfal',
    'falimtru',
    'falimfal',
    'nottru',
    'notfal',
    'trubitru',
    'falbitru',
    'trubifal',
    'falbifal',
    'truantru',
    'truanfal',
    'falantru',
    'falanfal',
    'truortru',
    'truorfal',
    'falortru',
    'falorfal',
    'trunantru',
    'trunanfal',
    'falnantru',
    'falnanfal',
    'truxortru',
    'truxorfal',
    'falxortru',
    'falxorfal',
    'trunortru',
    'trunorfal',
    'falnortru',
    'falnorfal',
)
