# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from metamath_setmm_provider.shards.s007 import (
    bifal as bifal,
)
from metamath_setmm_provider.shards.s007 import (
    bitru as bitru,
)
from metamath_setmm_provider.shards.s007 import (
    df_fal as df_fal,
)
from metamath_setmm_provider.shards.s007 import (
    df_tru as df_tru,
)
from metamath_setmm_provider.shards.s007 import (
    dfnot as dfnot,
)
from metamath_setmm_provider.shards.s007 import (
    dftru2 as dftru2,
)
from metamath_setmm_provider.shards.s007 import (
    efald as efald,
)
from metamath_setmm_provider.shards.s007 import (
    fal as fal,
)
from metamath_setmm_provider.shards.s007 import (
    falim as falim,
)
from metamath_setmm_provider.shards.s007 import (
    falimd as falimd,
)
from metamath_setmm_provider.shards.s007 import (
    inegd as inegd,
)
from metamath_setmm_provider.shards.s007 import (
    mptru as mptru,
)
from metamath_setmm_provider.shards.s007 import (
    nbfal as nbfal,
)
from metamath_setmm_provider.shards.s007 import (
    pm2_21fal as pm2_21fal,
)
from metamath_setmm_provider.shards.s007 import (
    tbtru as tbtru,
)
from metamath_setmm_provider.shards.s007 import (
    tru as tru,
)
from metamath_setmm_provider.shards.s007 import (
    truan as truan,
)
from metamath_setmm_provider.shards.s007 import (
    trud as trud,
)
from metamath_setmm_provider.shards.s007 import (
    trujust as trujust,
)
from metamath_setmm_provider.shards.s007 import (
    trut as trut,
)
from metamath_setmm_provider.shards.s007 import (
    wfal as wfal,
)
from metamath_setmm_provider.shards.s007 import (
    wtru as wtru,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.metamath_language import FormationBinding
from skfd.authoring.theory import TheoryProofAuthor

if str(wtru.syntax_assertion) != (
    'urn:uuid:e5400d60-1384-5b3d-b14c-010634971bba'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trujust.id) != (
    'urn:uuid:df504e4a-44f9-5271-8416-32f48561a549'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(df_tru.id) != (
    'urn:uuid:2ad17678-7233-5645-bdd5-5891608085d5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(tru.id) != (
    'urn:uuid:6b0c4155-70fa-55b8-b59e-ebd77c34952a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dftru2.id) != (
    'urn:uuid:d9267597-9f40-59d6-9178-3e1d5a50af18'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trut.id) != (
    'urn:uuid:4cff9540-4154-510d-ad01-b2671bf87b5b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(mptru.id) != (
    'urn:uuid:020d6e08-62d7-5d71-ae70-ffe1733641c9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(tbtru.id) != (
    'urn:uuid:83d81741-44ce-55e4-b5cf-5e02420e7c06'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(bitru.id) != (
    'urn:uuid:24ec1c34-c6cb-5b16-8d37-3019c0b71583'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(trud.id) != (
    'urn:uuid:fe86063a-a598-59b1-81fb-3085ca1fe37e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(truan.id) != (
    'urn:uuid:852b8ddb-b459-5d01-bfcb-f7585c69f855'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(wfal.syntax_assertion) != (
    'urn:uuid:bb691f12-9a08-54c1-86dc-8d6c0c0108f9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(df_fal.id) != (
    'urn:uuid:556a5aee-3c7a-5bcf-b1c3-3c96b5b27bf5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(fal.id) != (
    'urn:uuid:1abbd6d6-cf87-5b5e-bf16-60714a6b4251'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(nbfal.id) != (
    'urn:uuid:eac10f3e-dde1-53c6-bbad-88ffd3baf06c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(bifal.id) != (
    'urn:uuid:663c42cf-f560-56a3-ada9-53a0483d04f8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falim.id) != (
    'urn:uuid:8b52b95b-1326-5404-ac9a-d535f390b9af'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(falimd.id) != (
    'urn:uuid:98c47a34-67e6-55eb-90eb-a7629f15884f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dfnot.id) != (
    'urn:uuid:8d9eeec9-e87f-5697-a36a-250aed763c4e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(inegd.id) != (
    'urn:uuid:1b957fd1-9f0d-5eda-8c02-b951ccb39f91'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(efald.id) != (
    'urn:uuid:2a9b392d-4ac6-54cc-a7d5-b8ca12d8f227'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm2_21fal.id) != (
    'urn:uuid:9c0a9420-5fa7-598b-a8f8-205ec8f4ebc4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@trujust.proof
def prove_trujust(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import monothetic


    _step_1 = proof.use(
        monothetic,
        subst={
            "ph": "wal(wceq(cv(x), cv(x)), x)",
            "ps": "wal(wceq(cv(y), cv(y)), y)",
        },
    )  # ⊢ wb(wi(wal(wceq(cv(x), cv(x)), x), wal(wceq(cv(x), cv(x)), x)), wi(wal(wceq(cv(y), cv(y))…
    return proof.qed(_step_1)


@tru.proof(
    dummy_variables=(
        "x:setvar",
    ),
)
def prove_tru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s001 import mpbir


    _step_1 = proof.use(
        id,
        subst={
            "ph": "wal(wceq(cv(x), cv(x)), x)",
        },
    )  # ⊢ wi(wal(wceq(cv(x), cv(x)), x), wal(wceq(cv(x), cv(x)), x))
    _step_2 = proof.use(
        df_tru,
        subst={
            "x": "x",
        },
    )  # ⊢ wb(wtru(), wi(wal(wceq(cv(x), cv(x)), x), wal(wceq(cv(x), cv(x)), x)))
    _step_3 = proof.use(mpbir, _step_1, _step_2)  # ⊢ wtru()
    return proof.qed(_step_3)


@dftru2.proof
def prove_dftru2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import id
    from metamath_setmm_provider.shards.s001 import mm_2th


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(id, subst={"ph": "ph"})  # ⊢ wi(ph, ph)
    _step_3 = proof.use(mm_2th, _step_1, _step_2)  # ⊢ wb(wtru(), wi(ph, ph))
    return proof.qed(_step_3)


@trut.proof
def prove_trut(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import a1bi


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(a1bi, _step_1, subst={"ps": "ph"})  # ⊢ wb(ph, wi(wtru(), ph))
    return proof.qed(_step_2)


@mptru.proof
def prove_mptru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wtru(), ph)
    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(ax_mp, _step_1, _hypothesis_1)  # ⊢ ph
    return proof.qed(_step_2)


@tbtru.proof
def prove_tbtru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import tbt


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(tbt, _step_1, subst={"ps": "ph"})  # ⊢ wb(ph, wb(ph, wtru()))
    return proof.qed(_step_2)


@bitru.proof
def prove_bitru(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_2th


    _hypothesis_1, = proof.hypotheses  # ⊢ ph
    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(mm_2th, _hypothesis_1, _step_1)  # ⊢ wb(ph, wtru())
    return proof.qed(_step_2)


@trud.proof
def prove_trud(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import a1i


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(a1i, _step_1, subst={"ps": "ph"})  # ⊢ wi(ph, wtru())
    return proof.qed(_step_2)


@truan.proof
def prove_truan(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s002 import biantrur


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(biantrur, _step_1, subst={"ps": "ph"})  # ⊢ wb(ph, wa(wtru(), ph))
    _step_3 = proof.use(bicomi, _step_2)  # ⊢ wb(wa(wtru(), ph), ph)
    return proof.qed(_step_3)


@fal.proof
def prove_fal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import notnoti
    from metamath_setmm_provider.shards.s001 import mtbir


    _step_1 = proof.use(tru)  # ⊢ wtru()
    _step_2 = proof.use(notnoti, _step_1)  # ⊢ wn(wn(wtru()))
    _step_3 = proof.use(df_fal)  # ⊢ wb(wfal(), wn(wtru()))
    _step_4 = proof.use(mtbir, _step_2, _step_3)  # ⊢ wn(wfal())
    return proof.qed(_step_4)


@nbfal.proof
def prove_nbfal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import nbn


    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(nbn, _step_1, subst={"ps": "ph"})  # ⊢ wb(wn(ph), wb(ph, wfal()))
    return proof.qed(_step_2)


@bifal.proof
def prove_bifal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_2false


    _hypothesis_1, = proof.hypotheses  # ⊢ wn(ph)
    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(mm_2false, _hypothesis_1, _step_1)  # ⊢ wb(ph, wfal())
    return proof.qed(_step_2)


@falim.proof
def prove_falim(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_21i


    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(pm2_21i, _step_1, subst={"ps": "ph"})  # ⊢ wi(wfal(), ph)
    return proof.qed(_step_2)


@falimd.proof
def prove_falimd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import adantl


    _step_1 = proof.use(falim, subst={"ph": "ps"})  # ⊢ wi(wfal(), ps)
    _step_2 = proof.use(adantl, _step_1, subst={"ch": "ph"})  # ⊢ wi(wa(ph, wfal()), ps)
    return proof.qed(_step_2)


@dfnot.proof
def prove_dfnot(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import ax_mp
    from metamath_setmm_provider.shards.s001 import mtt


    _step_1 = proof.use(fal)  # ⊢ wn(wfal())
    _step_2 = proof.use(
        mtt,
        subst={
            "ph": "wfal()",
            "ps": "ph",
        },
    )  # ⊢ wi(wn(wfal()), wb(wn(ph), wi(ph, wfal())))
    _step_3 = proof.use(ax_mp, _step_1, _step_2)  # ⊢ wb(wn(ph), wi(ph, wfal()))
    return proof.qed(_step_3)


@inegd.proof
def prove_inegd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylibr
    from metamath_setmm_provider.shards.s002 import ex


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wa(ph, ps), wfal())
    _step_1 = proof.use(ex, _hypothesis_1)  # ⊢ wi(ph, wi(ps, wfal()))
    _step_2 = proof.use(dfnot, subst={"ph": "ps"})  # ⊢ wb(wn(ps), wi(ps, wfal()))
    _step_3 = proof.use(sylibr, _step_1, _step_2)  # ⊢ wi(ph, wn(ps))
    return proof.qed(_step_3)


@efald.proof
def prove_efald(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import notnotrd


    _hypothesis_1, = proof.hypotheses  # ⊢ wi(wa(ph, wn(ps)), wfal())
    _step_1 = proof.use(inegd, _hypothesis_1)  # ⊢ wi(ph, wn(wn(ps)))
    _step_2 = proof.use(notnotrd, _step_1)  # ⊢ wi(ph, ps)
    return proof.qed(_step_2)


@pm2_21fal.proof
def prove_pm2_21fal(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_21dd


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, ps); wi(ph, wn(ps))
    _step_1 = proof.use(
        pm2_21dd,
        _hypothesis_1,
        _hypothesis_2,
        subst={
            "ch": "wfal()",
        },
    )  # ⊢ wi(ph, wfal())
    return proof.qed(_step_1)

__all__ = (
    'trujust',
    'df_tru',
    'tru',
    'dftru2',
    'trut',
    'mptru',
    'tbtru',
    'bitru',
    'trud',
    'truan',
    'df_fal',
    'fal',
    'nbfal',
    'bifal',
    'falim',
    'falimd',
    'dfnot',
    'inegd',
    'efald',
    'pm2_21fal',
)

FORMATION_BINDINGS_BY_LABEL: Mapping[str, FormationBinding] = MappingProxyType({
    'wtru': wtru,
    'wfal': wfal,
})
