# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from metamath_setmm_provider.shards.s005 import (
    dedlem0a as dedlem0a,
)
from metamath_setmm_provider.shards.s005 import (
    dedlem0b as dedlem0b,
)
from metamath_setmm_provider.shards.s005 import (
    dedlema as dedlema,
)
from metamath_setmm_provider.shards.s005 import (
    dedlemb as dedlemb,
)
from metamath_setmm_provider.shards.s005 import (
    dedt as dedt,
)
from metamath_setmm_provider.shards.s005 import (
    elimh as elimh,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.theory import TheoryProofAuthor

if str(dedlem0a.id) != (
    'urn:uuid:962b8b10-247b-56f1-abdf-d9e70fd6f3b9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dedlem0b.id) != (
    'urn:uuid:01e7b878-2566-5958-a711-8452fea702a9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dedlema.id) != (
    'urn:uuid:89c5be20-6b51-5c69-b25b-a050a710a08b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dedlemb.id) != (
    'urn:uuid:9fb654d1-fd7f-5046-9056-96e5624ce14d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(elimh.id) != (
    'urn:uuid:ff90341c-aabb-5f33-9015-65ff387a636a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dedt.id) != (
    'urn:uuid:3babad48-ae1d-5e55-ad53-a423a1dc0cbb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@dedlem0a.proof
def prove_dedlem0a(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import jarri
    from metamath_setmm_provider.shards.s001 import biimt, bitrd
    from metamath_setmm_provider.shards.s002 import iba


    _step_1 = proof.use(iba, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wb(ps, wa(ps, ph)))
    _step_2 = proof.use(
        biimt,
        subst={
            "ph": "wi(ch, ph)",
            "ps": "wa(ps, ph)",
        },
    )  # ⊢ wi(wi(ch, ph), wb(wa(ps, ph), wi(wi(ch, ph), wa(ps, ph))))
    _step_3 = proof.use(jarri, _step_2)  # ⊢ wi(ph, wb(wa(ps, ph), wi(wi(ch, ph), wa(ps, ph))))
    _step_4 = proof.use(bitrd, _step_1, _step_3)  # ⊢ wi(ph, wb(ps, wi(wi(ch, ph), wa(ps, ph))))
    return proof.qed(_step_4)


@dedlem0b.proof
def prove_dedlem0b(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import com12, com23, con1d, imim2d, imim12i, pm2_21
    from metamath_setmm_provider.shards.s001 import impbid
    from metamath_setmm_provider.shards.s002 import simpr


    _step_1 = proof.use(
        pm2_21,
        subst={
            "ph": "ph",
            "ps": "wa(ch, ph)",
        },
    )  # ⊢ wi(wn(ph), wi(ph, wa(ch, ph)))
    _step_2 = proof.use(
        imim2d,
        _step_1,
        subst={
            "th": "ps",
        },
    )  # ⊢ wi(wn(ph), wi(wi(ps, ph), wi(ps, wa(ch, ph))))
    _step_3 = proof.use(com23, _step_2)  # ⊢ wi(wn(ph), wi(ps, wi(wi(ps, ph), wa(ch, ph))))
    _step_4 = proof.use(pm2_21, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wn(ps), wi(ps, ph))
    _step_5 = proof.use(simpr, subst={"ph": "ch", "ps": "ph"})  # ⊢ wi(wa(ch, ph), ph)
    _step_6 = proof.use(
        imim12i,
        _step_4,
        _step_5,
    )  # ⊢ wi(wi(wi(ps, ph), wa(ch, ph)), wi(wn(ps), ph))
    _step_7 = proof.use(con1d, _step_6)  # ⊢ wi(wi(wi(ps, ph), wa(ch, ph)), wi(wn(ph), ps))
    _step_8 = proof.use(com12, _step_7)  # ⊢ wi(wn(ph), wi(wi(wi(ps, ph), wa(ch, ph)), ps))
    _step_9 = proof.use(
        impbid,
        _step_3,
        _step_8,
    )  # ⊢ wi(wn(ph), wb(ps, wi(wi(ps, ph), wa(ch, ph))))
    return proof.qed(_step_9)


@dedlema.proof
def prove_dedlema(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import a1i, pm2_24
    from metamath_setmm_provider.shards.s001 import impbid
    from metamath_setmm_provider.shards.s002 import adantld, expcom, simpl
    from metamath_setmm_provider.shards.s004 import jaod, orc


    _step_1 = proof.use(
        orc,
        subst={
            "ph": "wa(ps, ph)",
            "ps": "wa(ch, wn(ph))",
        },
    )  # ⊢ wi(wa(ps, ph), wo(wa(ps, ph), wa(ch, wn(ph))))
    _step_2 = proof.use(expcom, _step_1)  # ⊢ wi(ph, wi(ps, wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_3 = proof.use(simpl, subst={"ph": "ps", "ps": "ph"})  # ⊢ wi(wa(ps, ph), ps)
    _step_4 = proof.use(a1i, _step_3, subst={"ps": "ph"})  # ⊢ wi(ph, wi(wa(ps, ph), ps))
    _step_5 = proof.use(pm2_24, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(wn(ph), ps))
    _step_6 = proof.use(adantld, _step_5, subst={"th": "ch"})  # ⊢ wi(ph, wi(wa(ch, wn(ph)), ps))
    _step_7 = proof.use(jaod, _step_4, _step_6)  # ⊢ wi(ph, wi(wo(wa(ps, ph), wa(ch, wn(ph))), ps))
    _step_8 = proof.use(
        impbid,
        _step_2,
        _step_7,
    )  # ⊢ wi(ph, wb(ps, wo(wa(ps, ph), wa(ch, wn(ph)))))
    return proof.qed(_step_8)


@dedlemb.proof
def prove_dedlemb(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import a1i, pm2_21
    from metamath_setmm_provider.shards.s001 import impbid
    from metamath_setmm_provider.shards.s002 import adantld, expcom, simpl
    from metamath_setmm_provider.shards.s004 import jaod, olc


    _step_1 = proof.use(
        olc,
        subst={
            "ph": "wa(ch, wn(ph))",
            "ps": "wa(ps, ph)",
        },
    )  # ⊢ wi(wa(ch, wn(ph)), wo(wa(ps, ph), wa(ch, wn(ph))))
    _step_2 = proof.use(expcom, _step_1)  # ⊢ wi(wn(ph), wi(ch, wo(wa(ps, ph), wa(ch, wn(ph)))))
    _step_3 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ch"})  # ⊢ wi(wn(ph), wi(ph, ch))
    _step_4 = proof.use(adantld, _step_3, subst={"th": "ps"})  # ⊢ wi(wn(ph), wi(wa(ps, ph), ch))
    _step_5 = proof.use(simpl, subst={"ph": "ch", "ps": "wn(ph)"})  # ⊢ wi(wa(ch, wn(ph)), ch)
    _step_6 = proof.use(
        a1i,
        _step_5,
        subst={
            "ps": "wn(ph)",
        },
    )  # ⊢ wi(wn(ph), wi(wa(ch, wn(ph)), ch))
    _step_7 = proof.use(
        jaod,
        _step_4,
        _step_6,
    )  # ⊢ wi(wn(ph), wi(wo(wa(ps, ph), wa(ch, wn(ph))), ch))
    _step_8 = proof.use(
        impbid,
        _step_2,
        _step_7,
    )  # ⊢ wi(wn(ph), wb(ch, wo(wa(ps, ph), wa(ch, wn(ph)))))
    return proof.qed(_step_8)


@elimh.proof
def prove_elimh(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_61i, syl
    from metamath_setmm_provider.shards.s001 import ibir, mpbiri
    from metamath_setmm_provider.shards.s005 import ifpfal, ifptru


    (
        _hypothesis_1,
        _hypothesis_2,
        _hypothesis_3,
    ) = proof.hypotheses  # ⊢ wi(wb(wif(ch, ph, ps), ph), wb(ta, ch)); wi(wb(wif(ch, ph, ps), ps), …
    _step_1 = proof.use(
        ifptru,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wi(ch, wb(wif(ch, ph, ps), ph))
    _step_2 = proof.use(syl, _step_1, _hypothesis_1)  # ⊢ wi(ch, wb(ta, ch))
    _step_3 = proof.use(ibir, _step_2)  # ⊢ wi(ch, ta)
    _step_4 = proof.use(
        ifpfal,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wi(wn(ch), wb(wif(ch, ph, ps), ps))
    _step_5 = proof.use(syl, _step_4, _hypothesis_2)  # ⊢ wi(wn(ch), wb(ta, th))
    _step_6 = proof.use(mpbiri, _hypothesis_3, _step_5)  # ⊢ wi(wn(ch), ta)
    _step_7 = proof.use(pm2_61i, _step_3, _step_6)  # ⊢ ta
    return proof.qed(_step_7)


@dedt.proof
def prove_dedt(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import syl
    from metamath_setmm_provider.shards.s001 import mpbii
    from metamath_setmm_provider.shards.s005 import ifptru


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(wb(wif(ch, ph, ps), ph), wb(ta, th)); ta
    _step_1 = proof.use(
        ifptru,
        subst={
            "ph": "ch",
            "ps": "ph",
            "ch": "ps",
        },
    )  # ⊢ wi(ch, wb(wif(ch, ph, ps), ph))
    _step_2 = proof.use(mpbii, _hypothesis_2, _hypothesis_1)  # ⊢ wi(wb(wif(ch, ph, ps), ph), th)
    _step_3 = proof.use(syl, _step_1, _step_2)  # ⊢ wi(ch, th)
    return proof.qed(_step_3)

__all__ = (
    'dedlem0a',
    'dedlem0b',
    'dedlema',
    'dedlemb',
    'elimh',
    'dedt',
)
