# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from metamath_setmm_provider.shards.s001 import (
    xor3 as xor3,
)
from metamath_setmm_provider.shards.s005 import (
    nbi2 as nbi2,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_15 as pm5_15,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_16 as pm5_16,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_17 as pm5_17,
)
from metamath_setmm_provider.shards.s005 import (
    pm5_24 as pm5_24,
)
from metamath_setmm_provider.shards.s005 import (
    xor as xor,
)
from metamath_setmm_provider.shards.s005 import (
    xordi as xordi,
)
from metamath_setmm_provider.shards.s007 import (
    anxordi as anxordi,
)
from metamath_setmm_provider.shards.s007 import (
    df_xor as df_xor,
)
from metamath_setmm_provider.shards.s007 import (
    excxor as excxor,
)
from metamath_setmm_provider.shards.s007 import (
    wxo as wxo,
)
from metamath_setmm_provider.shards.s007 import (
    xnor as xnor,
)
from metamath_setmm_provider.shards.s007 import (
    xor2 as xor2,
)
from metamath_setmm_provider.shards.s007 import (
    xorass as xorass,
)
from metamath_setmm_provider.shards.s007 import (
    xorbi12d as xorbi12d,
)
from metamath_setmm_provider.shards.s007 import (
    xorbi12i as xorbi12i,
)
from metamath_setmm_provider.shards.s007 import (
    xorcom as xorcom,
)
from metamath_setmm_provider.shards.s007 import (
    xorexmid as xorexmid,
)
from metamath_setmm_provider.shards.s007 import (
    xornan as xornan,
)
from metamath_setmm_provider.shards.s007 import (
    xornan2 as xornan2,
)
from metamath_setmm_provider.shards.s007 import (
    xorneg as xorneg,
)
from metamath_setmm_provider.shards.s007 import (
    xorneg1 as xorneg1,
)
from metamath_setmm_provider.shards.s007 import (
    xorneg2 as xorneg2,
)
from metamath_setmm_provider.shards.s007 import (
    xoror as xoror,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.metamath_language import FormationBinding
from skfd.authoring.theory import TheoryProofAuthor

if str(xor3.id) != (
    'urn:uuid:e3f36d72-5887-525f-9686-461ec9971cbb'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_17.id) != (
    'urn:uuid:c8e4e6ff-5435-558f-9139-9aa9bd81d6ee'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_15.id) != (
    'urn:uuid:d2a92fdc-17e7-57f5-91b8-7b9e03dfd130'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_16.id) != (
    'urn:uuid:9d60ab1f-4484-58c9-be28-54b7ac7a96f5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xor.id) != (
    'urn:uuid:ffa31c7b-db33-5077-8e3f-8058446355cd'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(nbi2.id) != (
    'urn:uuid:bb2d3b77-fa29-54e2-bd1a-42d3b823a166'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xordi.id) != (
    'urn:uuid:53af977d-b0ec-5b5d-ab11-8b394f05b251'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(pm5_24.id) != (
    'urn:uuid:9a7c6675-2fcc-5d44-acdf-2af576bc3972'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(wxo.syntax_assertion) != (
    'urn:uuid:983bb82a-555b-5661-a235-302515e3d9f5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(df_xor.id) != (
    'urn:uuid:793a40f3-222a-5990-86da-f08c5abb792a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xnor.id) != (
    'urn:uuid:1829a3a5-dea7-549b-be44-8e7a3072f441'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorcom.id) != (
    'urn:uuid:525a28bc-b63b-5f9a-af47-415350307ab1'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorass.id) != (
    'urn:uuid:2e2d31f7-3744-5171-85e5-d0343f9c5640'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(excxor.id) != (
    'urn:uuid:2f49e1be-3bbf-5ead-bd2c-57dc499b684a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xor2.id) != (
    'urn:uuid:0e1dc19a-34c1-5e23-85fd-104bc88b57f3'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xoror.id) != (
    'urn:uuid:62dccf47-4a49-5658-a683-5d66d95905e9'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xornan.id) != (
    'urn:uuid:f53dc024-e48c-5162-bff7-1615bc734c4e'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xornan2.id) != (
    'urn:uuid:8ea2d08b-198b-5239-b31b-f2a5c872cfe8'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorneg2.id) != (
    'urn:uuid:3f7b6b44-f0c2-5a48-bb7c-5bdf765871b0'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorneg1.id) != (
    'urn:uuid:8503924a-e998-51a5-8959-ffb38b32752c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorneg.id) != (
    'urn:uuid:d6ddd243-fe9b-5f19-a889-dabb13dd720a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorbi12i.id) != (
    'urn:uuid:bec88e32-b6d4-5906-a5f6-8817d34e0b9f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorbi12d.id) != (
    'urn:uuid:aa501848-82ef-5c21-8287-6eff566a0f32'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(anxordi.id) != (
    'urn:uuid:eaf67558-8516-51e9-baf2-9182d5e346f5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(xorexmid.id) != (
    'urn:uuid:d73fe73e-4bf8-54b2-99c2-a6606f61dab5'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@xor3.proof
def prove_xor3(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi, con2bii, pm5_18

    _step_1 = proof.use(
        pm5_18,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wb(ph, ps), wn(wb(ph, wn(ps))))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wb(ph, wn(ps)), wn(wb(ph, ps)))
    _step_3 = proof.use(bicomi, _step_2)  # ⊢ wb(wn(wb(ph, ps)), wb(ph, wn(ps)))
    return proof.qed(_step_3)


@pm5_17.proof
def prove_pm5_17(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicom, bitr2i, mm_3bitrri
    from metamath_setmm_provider.shards.s002 import dfbi2, imnan
    from metamath_setmm_provider.shards.s003 import anbi12i
    from metamath_setmm_provider.shards.s004 import df_or, orcom


    _step_1 = proof.use(
        bicom,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wb(ph, wn(ps)), wb(wn(ps), ph))
    _step_2 = proof.use(
        dfbi2,
        subst={
            "ph": "wn(ps)",
            "ps": "ph",
        },
    )  # ⊢ wb(wb(wn(ps), ph), wa(wi(wn(ps), ph), wi(ph, wn(ps))))
    _step_3 = proof.use(orcom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wo(ph, ps), wo(ps, ph))
    _step_4 = proof.use(df_or, subst={"ph": "ps", "ps": "ph"})  # ⊢ wb(wo(ps, ph), wi(wn(ps), ph))
    _step_5 = proof.use(bitr2i, _step_3, _step_4)  # ⊢ wb(wi(wn(ps), ph), wo(ph, ps))
    _step_6 = proof.use(
        imnan,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, wn(ps)), wn(wa(ph, ps)))
    _step_7 = proof.use(
        anbi12i,
        _step_5,
        _step_6,
    )  # ⊢ wb(wa(wi(wn(ps), ph), wi(ph, wn(ps))), wa(wo(ph, ps), wn(wa(ph, ps))))
    _step_8 = proof.use(
        mm_3bitrri,
        _step_1,
        _step_2,
        _step_7,
    )  # ⊢ wb(wa(wo(ph, ps), wn(wa(ph, ps))), wb(ph, wn(ps)))
    return proof.qed(_step_8)


@pm5_15.proof
def prove_pm5_15(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi
    from metamath_setmm_provider.shards.s004 import orri


    _step_1 = proof.use(
        xor3,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wb(ph, ps)), wb(ph, wn(ps)))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wn(wb(ph, ps)), wb(ph, wn(ps)))
    _step_3 = proof.use(orri, _step_2)  # ⊢ wo(wb(ph, ps), wb(ph, wn(ps)))
    return proof.qed(_step_3)


@pm5_16.proof
def prove_pm5_16(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import biimpi, mpbi, pm5_18
    from metamath_setmm_provider.shards.s002 import imnan


    _step_1 = proof.use(
        pm5_18,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wb(ph, ps), wn(wb(ph, wn(ps))))
    _step_2 = proof.use(biimpi, _step_1)  # ⊢ wi(wb(ph, ps), wn(wb(ph, wn(ps))))
    _step_3 = proof.use(
        imnan,
        subst={
            "ph": "wb(ph, ps)",
            "ps": "wb(ph, wn(ps))",
        },
    )  # ⊢ wb(wi(wb(ph, ps), wn(wb(ph, wn(ps)))), wn(wa(wb(ph, ps), wb(ph, wn(ps)))))
    _step_4 = proof.use(mpbi, _step_2, _step_3)  # ⊢ wn(wa(wb(ph, ps), wb(ph, wn(ps))))
    return proof.qed(_step_4)


@xor.proof
def prove_xor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import con1bii, mm_3bitr4ri
    from metamath_setmm_provider.shards.s002 import dfbi2, iman
    from metamath_setmm_provider.shards.s003 import anbi12i
    from metamath_setmm_provider.shards.s004 import ioran


    _step_1 = proof.use(
        iman,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wi(ph, ps), wn(wa(ph, wn(ps))))
    _step_2 = proof.use(
        iman,
        subst={
            "ph": "ps",
            "ps": "ph",
        },
    )  # ⊢ wb(wi(ps, ph), wn(wa(ps, wn(ph))))
    _step_3 = proof.use(
        anbi12i,
        _step_1,
        _step_2,
    )  # ⊢ wb(wa(wi(ph, ps), wi(ps, ph)), wa(wn(wa(ph, wn(ps))), wn(wa(ps, wn(ph)))))
    _step_4 = proof.use(
        dfbi2,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wb(ph, ps), wa(wi(ph, ps), wi(ps, ph)))
    _step_5 = proof.use(
        ioran,
        subst={
            "ph": "wa(ph, wn(ps))",
            "ps": "wa(ps, wn(ph))",
        },
    )  # ⊢ wb(wn(wo(wa(ph, wn(ps)), wa(ps, wn(ph)))), wa(wn(wa(ph, wn(ps))), wn(wa(ps, wn(ph)))))
    _step_6 = proof.use(
        mm_3bitr4ri,
        _step_3,
        _step_4,
        _step_5,
    )  # ⊢ wb(wn(wo(wa(ph, wn(ps)), wa(ps, wn(ph)))), wb(ph, ps))
    _step_7 = proof.use(
        con1bii,
        _step_6,
    )  # ⊢ wb(wn(wb(ph, ps)), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    return proof.qed(_step_7)


@nbi2.proof
def prove_nbi2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i


    _step_1 = proof.use(
        xor3,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wb(ph, ps)), wb(ph, wn(ps)))
    _step_2 = proof.use(
        pm5_17,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wa(wo(ph, ps), wn(wa(ph, ps))), wb(ph, wn(ps)))
    _step_3 = proof.use(
        bitr4i,
        _step_1,
        _step_2,
    )  # ⊢ wb(wn(wb(ph, ps)), wa(wo(ph, ps), wn(wa(ph, ps))))
    return proof.qed(_step_3)


@xordi.proof
def prove_xordi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import xchbinx
    from metamath_setmm_provider.shards.s002 import annim, pm5_32


    _step_1 = proof.use(
        annim,
        subst={
            "ph": "ph",
            "ps": "wb(ps, ch)",
        },
    )  # ⊢ wb(wa(ph, wn(wb(ps, ch))), wn(wi(ph, wb(ps, ch))))
    _step_2 = proof.use(
        pm5_32,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(ph, wb(ps, ch)), wb(wa(ph, ps), wa(ph, ch)))
    _step_3 = proof.use(
        xchbinx,
        _step_1,
        _step_2,
    )  # ⊢ wb(wa(ph, wn(wb(ps, ch))), wn(wb(wa(ph, ps), wa(ph, ch))))
    return proof.qed(_step_3)


@pm5_24.proof
def prove_pm5_24(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import xchnxbi
    from metamath_setmm_provider.shards.s005 import dfbi3


    _step_1 = proof.use(
        xor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wb(ph, ps)), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    _step_2 = proof.use(
        dfbi3,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wb(ph, ps), wo(wa(ph, ps), wa(wn(ph), wn(ps))))
    _step_3 = proof.use(
        xchnxbi,
        _step_1,
        _step_2,
    )  # ⊢ wb(wn(wo(wa(ph, ps), wa(wn(ph), wn(ps)))), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    return proof.qed(_step_3)


@xnor.proof
def prove_xnor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import con2bii


    _step_1 = proof.use(df_xor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wxo(ph, ps), wn(wb(ph, ps)))
    _step_2 = proof.use(con2bii, _step_1)  # ⊢ wb(wb(ph, ps), wn(wxo(ph, ps)))
    return proof.qed(_step_2)


@xorcom.proof
def prove_xorcom(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicom, bitr4i, xchbinx


    _step_1 = proof.use(df_xor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wxo(ph, ps), wn(wb(ph, ps)))
    _step_2 = proof.use(bicom, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wb(ph, ps), wb(ps, ph))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wxo(ph, ps), wn(wb(ps, ph)))
    _step_4 = proof.use(df_xor, subst={"ph": "ps", "ps": "ph"})  # ⊢ wb(wxo(ps, ph), wn(wb(ps, ph)))
    _step_5 = proof.use(bitr4i, _step_3, _step_4)  # ⊢ wb(wxo(ph, ps), wxo(ps, ph))
    return proof.qed(_step_5)


@xorass.proof
def prove_xorass(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import (
        biass,
        bibi1i,
        bibi2i,
        mm_3bitr2ri,
        mm_3bitr3i,
        mm_3bitr4i,
        nbbn,
    )


    _step_1 = proof.use(
        xor3,
        subst={
            "ph": "ph",
            "ps": "wxo(ps, ch)",
        },
    )  # ⊢ wb(wn(wb(ph, wxo(ps, ch))), wb(ph, wn(wxo(ps, ch))))
    _step_2 = proof.use(
        biass,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wb(wb(ph, ps), ch), wb(ph, wb(ps, ch)))
    _step_3 = proof.use(xnor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wb(ph, ps), wn(wxo(ph, ps)))
    _step_4 = proof.use(
        bibi1i,
        _step_3,
        subst={
            "ch": "ch",
        },
    )  # ⊢ wb(wb(wb(ph, ps), ch), wb(wn(wxo(ph, ps)), ch))
    _step_5 = proof.use(xnor, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wb(ps, ch), wn(wxo(ps, ch)))
    _step_6 = proof.use(
        bibi2i,
        _step_5,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wb(ph, wb(ps, ch)), wb(ph, wn(wxo(ps, ch))))
    _step_7 = proof.use(
        mm_3bitr3i,
        _step_2,
        _step_4,
        _step_6,
    )  # ⊢ wb(wb(wn(wxo(ph, ps)), ch), wb(ph, wn(wxo(ps, ch))))
    _step_8 = proof.use(
        nbbn,
        subst={
            "ph": "wxo(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wb(wn(wxo(ph, ps)), ch), wn(wb(wxo(ph, ps), ch)))
    _step_9 = proof.use(
        mm_3bitr2ri,
        _step_1,
        _step_7,
        _step_8,
    )  # ⊢ wb(wn(wb(wxo(ph, ps), ch)), wn(wb(ph, wxo(ps, ch))))
    _step_10 = proof.use(
        df_xor,
        subst={
            "ph": "wxo(ph, ps)",
            "ps": "ch",
        },
    )  # ⊢ wb(wxo(wxo(ph, ps), ch), wn(wb(wxo(ph, ps), ch)))
    _step_11 = proof.use(
        df_xor,
        subst={
            "ph": "ph",
            "ps": "wxo(ps, ch)",
        },
    )  # ⊢ wb(wxo(ph, wxo(ps, ch)), wn(wb(ph, wxo(ps, ch))))
    _step_12 = proof.use(
        mm_3bitr4i,
        _step_9,
        _step_10,
        _step_11,
    )  # ⊢ wb(wxo(wxo(ph, ps), ch), wxo(ph, wxo(ps, ch)))
    return proof.qed(_step_12)


@excxor.proof
def prove_excxor(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitri
    from metamath_setmm_provider.shards.s002 import ancom
    from metamath_setmm_provider.shards.s004 import orbi2i


    _step_1 = proof.use(df_xor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wxo(ph, ps), wn(wb(ph, ps)))
    _step_2 = proof.use(
        xor,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wb(ph, ps)), wo(wa(ph, wn(ps)), wa(ps, wn(ph))))
    _step_3 = proof.use(
        ancom,
        subst={
            "ph": "ps",
            "ps": "wn(ph)",
        },
    )  # ⊢ wb(wa(ps, wn(ph)), wa(wn(ph), ps))
    _step_4 = proof.use(
        orbi2i,
        _step_3,
        subst={
            "ch": "wa(ph, wn(ps))",
        },
    )  # ⊢ wb(wo(wa(ph, wn(ps)), wa(ps, wn(ph))), wo(wa(ph, wn(ps)), wa(wn(ph), ps)))
    _step_5 = proof.use(
        mm_3bitri,
        _step_1,
        _step_2,
        _step_4,
    )  # ⊢ wb(wxo(ph, ps), wo(wa(ph, wn(ps)), wa(wn(ph), ps)))
    return proof.qed(_step_5)


@xor2.proof
def prove_xor2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri


    _step_1 = proof.use(df_xor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wxo(ph, ps), wn(wb(ph, ps)))
    _step_2 = proof.use(
        nbi2,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wn(wb(ph, ps)), wa(wo(ph, ps), wn(wa(ph, ps))))
    _step_3 = proof.use(
        bitri,
        _step_1,
        _step_2,
    )  # ⊢ wb(wxo(ph, ps), wa(wo(ph, ps), wn(wa(ph, ps))))
    return proof.qed(_step_3)


@xoror.proof
def prove_xoror(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simplbi


    _step_1 = proof.use(
        xor2,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wxo(ph, ps), wa(wo(ph, ps), wn(wa(ph, ps))))
    _step_2 = proof.use(simplbi, _step_1)  # ⊢ wi(wxo(ph, ps), wo(ph, ps))
    return proof.qed(_step_2)


@xornan.proof
def prove_xornan(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simprbi


    _step_1 = proof.use(
        xor2,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wxo(ph, ps), wa(wo(ph, ps), wn(wa(ph, ps))))
    _step_2 = proof.use(simprbi, _step_1)  # ⊢ wi(wxo(ph, ps), wn(wa(ph, ps)))
    return proof.qed(_step_2)


@xornan2.proof
def prove_xornan2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylibr
    from metamath_setmm_provider.shards.s007 import df_nan


    _step_1 = proof.use(xornan, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wxo(ph, ps), wn(wa(ph, ps)))
    _step_2 = proof.use(
        df_nan,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wnan(ph, ps), wn(wa(ph, ps)))
    _step_3 = proof.use(sylibr, _step_1, _step_2)  # ⊢ wi(wxo(ph, ps), wnan(ph, ps))
    return proof.qed(_step_3)


@xorneg2.proof
def prove_xorneg2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr2i, pm5_18


    _step_1 = proof.use(
        df_xor,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wxo(ph, wn(ps)), wn(wb(ph, wn(ps))))
    _step_2 = proof.use(
        pm5_18,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wb(ph, ps), wn(wb(ph, wn(ps))))
    _step_3 = proof.use(xnor, subst={"ph": "ph", "ps": "ps"})  # ⊢ wb(wb(ph, ps), wn(wxo(ph, ps)))
    _step_4 = proof.use(
        mm_3bitr2i,
        _step_1,
        _step_2,
        _step_3,
    )  # ⊢ wb(wxo(ph, wn(ps)), wn(wxo(ph, ps)))
    return proof.qed(_step_4)


@xorneg1.proof
def prove_xorneg1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, xchbinx


    _step_1 = proof.use(
        xorcom,
        subst={
            "ph": "wn(ph)",
            "ps": "ps",
        },
    )  # ⊢ wb(wxo(wn(ph), ps), wxo(ps, wn(ph)))
    _step_2 = proof.use(
        xorneg2,
        subst={
            "ph": "ps",
            "ps": "ph",
        },
    )  # ⊢ wb(wxo(ps, wn(ph)), wn(wxo(ps, ph)))
    _step_3 = proof.use(xorcom, subst={"ph": "ps", "ps": "ph"})  # ⊢ wb(wxo(ps, ph), wxo(ph, ps))
    _step_4 = proof.use(xchbinx, _step_2, _step_3)  # ⊢ wb(wxo(ps, wn(ph)), wn(wxo(ph, ps)))
    _step_5 = proof.use(bitri, _step_1, _step_4)  # ⊢ wb(wxo(wn(ph), ps), wn(wxo(ph, ps)))
    return proof.qed(_step_5)


@xorneg.proof
def prove_xorneg(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitr4i, con2bii


    _step_1 = proof.use(
        xorneg1,
        subst={
            "ph": "ph",
            "ps": "wn(ps)",
        },
    )  # ⊢ wb(wxo(wn(ph), wn(ps)), wn(wxo(ph, wn(ps))))
    _step_2 = proof.use(
        xorneg2,
        subst={
            "ph": "ph",
            "ps": "ps",
        },
    )  # ⊢ wb(wxo(ph, wn(ps)), wn(wxo(ph, ps)))
    _step_3 = proof.use(con2bii, _step_2)  # ⊢ wb(wxo(ph, ps), wn(wxo(ph, wn(ps))))
    _step_4 = proof.use(bitr4i, _step_1, _step_3)  # ⊢ wb(wxo(wn(ph), wn(ps)), wxo(ph, ps))
    return proof.qed(_step_4)


@xorbi12i.proof
def prove_xorbi12i(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bibi12i, bitr4i, xchbinx


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wb(ph, ps); wb(ch, th)
    _step_1 = proof.use(df_xor, subst={"ph": "ph", "ps": "ch"})  # ⊢ wb(wxo(ph, ch), wn(wb(ph, ch)))
    _step_2 = proof.use(bibi12i, _hypothesis_1, _hypothesis_2)  # ⊢ wb(wb(ph, ch), wb(ps, th))
    _step_3 = proof.use(xchbinx, _step_1, _step_2)  # ⊢ wb(wxo(ph, ch), wn(wb(ps, th)))
    _step_4 = proof.use(df_xor, subst={"ph": "ps", "ps": "th"})  # ⊢ wb(wxo(ps, th), wn(wb(ps, th)))
    _step_5 = proof.use(bitr4i, _step_3, _step_4)  # ⊢ wb(wxo(ph, ch), wxo(ps, th))
    return proof.qed(_step_5)


@xorbi12d.proof
def prove_xorbi12d(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bibi12d, mm_3bitr4g, notbid


    _hypothesis_1, _hypothesis_2 = proof.hypotheses  # ⊢ wi(ph, wb(ps, ch)); wi(ph, wb(th, ta))
    _step_1 = proof.use(
        bibi12d,
        _hypothesis_1,
        _hypothesis_2,
    )  # ⊢ wi(ph, wb(wb(ps, th), wb(ch, ta)))
    _step_2 = proof.use(notbid, _step_1)  # ⊢ wi(ph, wb(wn(wb(ps, th)), wn(wb(ch, ta))))
    _step_3 = proof.use(df_xor, subst={"ph": "ps", "ps": "th"})  # ⊢ wb(wxo(ps, th), wn(wb(ps, th)))
    _step_4 = proof.use(df_xor, subst={"ph": "ch", "ps": "ta"})  # ⊢ wb(wxo(ch, ta), wn(wb(ch, ta)))
    _step_5 = proof.use(
        mm_3bitr4g,
        _step_2,
        _step_3,
        _step_4,
    )  # ⊢ wi(ph, wb(wxo(ps, th), wxo(ch, ta)))
    return proof.qed(_step_5)


@anxordi.proof
def prove_anxordi(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mm_3bitr4i
    from metamath_setmm_provider.shards.s003 import anbi2i


    _step_1 = proof.use(
        xordi,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wa(ph, wn(wb(ps, ch))), wn(wb(wa(ph, ps), wa(ph, ch))))
    _step_2 = proof.use(df_xor, subst={"ph": "ps", "ps": "ch"})  # ⊢ wb(wxo(ps, ch), wn(wb(ps, ch)))
    _step_3 = proof.use(
        anbi2i,
        _step_2,
        subst={
            "ch": "ph",
        },
    )  # ⊢ wb(wa(ph, wxo(ps, ch)), wa(ph, wn(wb(ps, ch))))
    _step_4 = proof.use(
        df_xor,
        subst={
            "ph": "wa(ph, ps)",
            "ps": "wa(ph, ch)",
        },
    )  # ⊢ wb(wxo(wa(ph, ps), wa(ph, ch)), wn(wb(wa(ph, ps), wa(ph, ch))))
    _step_5 = proof.use(
        mm_3bitr4i,
        _step_1,
        _step_3,
        _step_4,
    )  # ⊢ wb(wa(ph, wxo(ps, ch)), wxo(wa(ph, ps), wa(ph, ch)))
    return proof.qed(_step_5)


@xorexmid.proof
def prove_xorexmid(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbir, pm5_19


    _step_1 = proof.use(pm5_19, subst={"ph": "ph"})  # ⊢ wn(wb(ph, wn(ph)))
    _step_2 = proof.use(
        df_xor,
        subst={
            "ph": "ph",
            "ps": "wn(ph)",
        },
    )  # ⊢ wb(wxo(ph, wn(ph)), wn(wb(ph, wn(ph))))
    _step_3 = proof.use(mpbir, _step_1, _step_2)  # ⊢ wxo(ph, wn(ph))
    return proof.qed(_step_3)

__all__ = (
    'xor3',
    'pm5_17',
    'pm5_15',
    'pm5_16',
    'xor',
    'nbi2',
    'xordi',
    'pm5_24',
    'df_xor',
    'xnor',
    'xorcom',
    'xorass',
    'excxor',
    'xor2',
    'xoror',
    'xornan',
    'xornan2',
    'xorneg2',
    'xorneg1',
    'xorneg',
    'xorbi12i',
    'xorbi12d',
    'anxordi',
    'xorexmid',
)

FORMATION_BINDINGS_BY_LABEL: Mapping[str, FormationBinding] = MappingProxyType({
    'wxo': wxo,
})
