"""Backward-compatible shim — explicit re-exports from knowledge modules.

Static imports so mypy can verify. When new modules are created,
merge_scratch.py appends new import lines here.
"""

from logic.propositional.hilbert.implication import (
    prove_2a1,
    prove_2a1d,
    prove_a1d,
    prove_a1i,
    prove_a1i13,
    prove_a2d,
    prove_a2i,
    prove_com12,
    prove_id,
    prove_idd,
    prove_imim1,
    prove_imim2,
    prove_mpcom,
    prove_mpd,
    prove_mpdd,
    prove_mpid,
    prove_notnot,
    prove_notnotr,
    prove_pm2_18,
    prove_pm2_18d,
    prove_pm2_27,
    prove_pm2_43,
    prove_simplim,
    prove_syl,
    prove_syl11,
    prove_syl2im,
    prove_syl2imc,
    prove_syl5,
    prove_syl56,
    prove_syl5com,
    prove_syl6,
    prove_syl6com,
    prove_sylcom,
    prove_syli,
)

from logic.propositional.hilbert.negation import (
    prove_con1,
    prove_con1d,
    prove_con1i,
    prove_con2,
    prove_con2d,
    prove_con2i,
    prove_con3,
    prove_con3d,
    prove_con3i,
    prove_con4,
    prove_con4d,
    prove_con4i,
    prove_conax1,
    prove_modus_tollens,
    prove_mt2,
    prove_mt3,
    prove_mt4d,
    prove_nsyl,
    prove_nsyl2,
    prove_nsyl3,
    prove_pm2_21,
    prove_pm2_21d,
    prove_pm2_24,
    prove_pm2_521,
    prove_pm2_521g,
    prove_pm2_61,
    prove_pm2_65,
)

from logic.propositional.hilbert.disjunction import (
    prove_ja,
    prove_jarli,
    prove_peirce,
    prove_pm1_4,
    prove_pm2_36,
    prove_pm2_38,
)

__all__ = [
    "prove_2a1",
    "prove_2a1d",
    "prove_a1d",
    "prove_a1i",
    "prove_a1i13",
    "prove_a2d",
    "prove_a2i",
    "prove_com12",
    "prove_con1",
    "prove_con1d",
    "prove_con1i",
    "prove_con2",
    "prove_con2d",
    "prove_con2i",
    "prove_con3",
    "prove_con3d",
    "prove_con3i",
    "prove_con4",
    "prove_con4d",
    "prove_con4i",
    "prove_conax1",
    "prove_id",
    "prove_idd",
    "prove_imim1",
    "prove_imim2",
    "prove_ja",
    "prove_jarli",
    "prove_modus_tollens",
    "prove_mpcom",
    "prove_mpd",
    "prove_mpdd",
    "prove_mpid",
    "prove_mt2",
    "prove_mt3",
    "prove_mt4d",
    "prove_notnot",
    "prove_notnotr",
    "prove_nsyl",
    "prove_nsyl2",
    "prove_nsyl3",
    "prove_peirce",
    "prove_pm1_4",
    "prove_pm2_18",
    "prove_pm2_18d",
    "prove_pm2_21",
    "prove_pm2_21d",
    "prove_pm2_24",
    "prove_pm2_27",
    "prove_pm2_36",
    "prove_pm2_38",
    "prove_pm2_43",
    "prove_pm2_521",
    "prove_pm2_521g",
    "prove_pm2_61",
    "prove_pm2_65",
    "prove_simplim",
    "prove_syl",
    "prove_syl11",
    "prove_syl2im",
    "prove_syl2imc",
    "prove_syl5",
    "prove_syl56",
    "prove_syl5com",
    "prove_syl6",
    "prove_syl6com",
    "prove_sylcom",
    "prove_syli",
    "Proof",
]


from skfd.proof import Proof  # noqa: F401