# ruff: noqa: W605
from __future__ import annotations

from collections.abc import Callable, Mapping

from . import System
from .conjunction import MIGRATION_THEOREMS as CONJUNCTION_MIGRATIONS
from .constants import MIGRATION_THEOREMS as CONSTANT_MIGRATIONS
from .disjunction import MIGRATION_THEOREMS as DISJUNCTION_MIGRATIONS
from .equivalence import MIGRATION_THEOREMS as EQUIVALENCE_MIGRATIONS
from .implication import MIGRATION_THEOREMS as IMPLICATION_MIGRATIONS
from .lemmas import (
    Proof,
    prove_1fpid3,
    prove_2a1,
    prove_2a1d,
    prove_2a1dd,
    prove_2a1i,
    prove_2false,
    prove_2falsed,
    prove_2th,
    prove_2thd,
    prove_3ad2antr1,
    prove_3ad2antr2,
    prove_3adant3,
    prove_3adant3r3,
    prove_3adantr3,
    prove_3an1rs,
    prove_3an4anass,
    prove_3an6,
    prove_3anan12,
    prove_3anan32,
    prove_3anan32OLD,
    prove_3anass,
    prove_3anassrs,
    prove_3anbi1d,
    prove_3anbi1i,
    prove_3anbi2d,
    prove_3anbi2i,
    prove_3anbi3d,
    prove_3anbi3i,
    prove_3anbi12d,
    prove_3anbi13d,
    prove_3anbi23d,
    prove_3anbi123d,
    prove_3anbi123i,
    prove_3ancoma,
    prove_3ancomb,
    prove_3anidm,
    prove_3anidm12,
    prove_3anidm13,
    prove_3anim123d,
    prove_3anor,
    prove_3anrev,
    prove_3anrot,
    prove_3biant1d,
    prove_3bior1fand,
    prove_3bior1fd,
    prove_3bior2fd,
    prove_3bitr2d,
    prove_3bitr2i,
    prove_3bitr2rd,
    prove_3bitr2ri,
    prove_3bitr3d,
    prove_3bitr3g,
    prove_3bitr3i,
    prove_3bitr3rd,
    prove_3bitr3ri,
    prove_3bitr4d,
    prove_3bitr4g,
    prove_3bitr4i,
    prove_3bitr4rd,
    prove_3bitr4ri,
    prove_3bitrd,
    prove_3bitri,
    prove_3bitrrd,
    prove_3bitrri,
    prove_3com12,
    prove_3com13,
    prove_3com23,
    prove_3coml,
    prove_3comr,
    prove_3ecase,
    prove_3exp,
    prove_3exp1,
    prove_3exp2,
    prove_3expa,
    prove_3expb,
    prove_3expd,
    prove_3expia,
    prove_3expib,
    prove_3ianor,
    prove_3imp,
    prove_3imp1,
    prove_3imp2,
    prove_3imp21,
    prove_3imp31,
    prove_3imp231,
    prove_3impa,
    prove_3impb,
    prove_3impd,
    prove_3impexp,
    prove_3impia,
    prove_3impib,
    prove_3imtr3d,
    prove_3imtr3g,
    prove_3imtr3i,
    prove_3imtr4d,
    prove_3imtr4g,
    prove_3imtr4i,
    prove_3ioran,
    prove_3jao,
    prove_3jaob,
    prove_3jaod,
    prove_3jaodan,
    prove_3jaoi,
    prove_3jaoian,
    prove_3jaoiOLD,
    prove_3jca,
    prove_3jcad,
    prove_3mix1,
    prove_3mix1d,
    prove_3mix1i,
    prove_3mix2,
    prove_3mix2d,
    prove_3mix2i,
    prove_3mix3,
    prove_3mix3d,
    prove_3mix3i,
    prove_3or6,
    prove_3oran,
    prove_3orass,
    prove_3orbi123d,
    prove_3orbi123i,
    prove_3orcoma,
    prove_3orcomb,
    prove_3orel1,
    prove_3orel2,
    prove_3orel2OLD,
    prove_3orel3,
    prove_3orel13,
    prove_3ori,
    prove_3orim123d,
    prove_3orrot,
    prove_3pm3_2i,
    prove_3pm3_2ni,
    prove_3simpa,
    prove_3syl,
    prove_3syld,
    prove_4anpull2,
    prove_4anpull2OLD,
    prove_4cases,
    prove_4casesdan,
    prove_4syl,
    prove_a1bi,
    prove_a1d,
    prove_a1dd,
    prove_a1ddd,
    prove_a1i,
    prove_a1i13,
    prove_a2d,
    prove_a2i,
    prove_abai,
    prove_ad2antll,
    prove_ad2antrl,
    prove_ad4ant123,
    prove_ad5ant125OLD,
    prove_ad5ant2345,
    prove_adantl,
    prove_adantld,
    prove_adantr,
    prove_adantrd,
    prove_adantrl,
    prove_adantrr,
    prove_an2anr,
    prove_an3,
    prove_an3andi,
    prove_an4,
    prove_an4s,
    prove_an6,
    prove_an12,
    prove_an12s,
    prove_an13,
    prove_an13s,
    prove_an21,
    prove_an31,
    prove_an31s,
    prove_an32,
    prove_an32s,
    prove_an33rean,
    prove_an42,
    prove_an42ds,
    prove_an42s,
    prove_an43,
    prove_anabs1,
    prove_anabs5,
    prove_anabs7,
    prove_anabsi5,
    prove_anabsi6,
    prove_anabsi7,
    prove_anabsi8,
    prove_anandi,
    prove_anandi3,
    prove_anandi3r,
    prove_anandir,
    prove_anass,
    prove_anass1rs,
    prove_anassrs,
    prove_anasss,
    prove_anbi1,
    prove_anbi1cd,
    prove_anbi1ci,
    prove_anbi1d,
    prove_anbi1i,
    prove_anbi2,
    prove_anbi2ci,
    prove_anbi2d,
    prove_anbi2i,
    prove_anbi12ci,
    prove_anbi12d,
    prove_anbi12i,
    prove_anbiim,
    prove_anbiimOLD,
    prove_anc2l,
    prove_anc2li,
    prove_anc2r,
    prove_anc2ri,
    prove_ancl,
    prove_anclb,
    prove_ancld,
    prove_ancli,
    prove_ancom,
    prove_ancom2s,
    prove_ancomd,
    prove_ancoms,
    prove_ancomsd,
    prove_ancomst,
    prove_ancr,
    prove_ancrb,
    prove_ancrd,
    prove_ancri,
    prove_anidm,
    prove_anidmdbi,
    prove_anidms,
    prove_anim1d,
    prove_anim2d,
    prove_anim12d,
    prove_anim12d1,
    prove_anim12dan,
    prove_animorl,
    prove_animorlr,
    prove_animorr,
    prove_animorrl,
    prove_animpimp2impd,
    prove_anmp,
    prove_annim,
    prove_annotanannot,
    prove_anor,
    prove_anxordi,
    prove_ax1,
    prove_ax1w,
    prove_ax3,
    prove_axia1,
    prove_axia2,
    prove_axia3,
    prove_axin1,
    prove_axin2,
    prove_axio,
    prove_baib,
    prove_baibd,
    prove_baibr,
    prove_bi2_04,
    prove_bi2bian9,
    prove_bi23imp13,
    prove_biadaniALT,
    prove_biadanid,
    prove_bian1d,
    prove_bianabs,
    prove_bianass,
    prove_bianassc,
    prove_bianbi,
    prove_biancomd,
    prove_biancomi,
    prove_bianfd,
    prove_bianfi,
    prove_bianim,
    prove_bianir,
    prove_biantr,
    prove_biantru,
    prove_biantrud,
    prove_biantrur,
    prove_biantrurd,
    prove_bibi1,
    prove_bibi1d,
    prove_bibi1i,
    prove_bibi2d,
    prove_bibi2i,
    prove_bibi12d,
    prove_bibi12i,
    prove_bibiad,
    prove_bibif,
    prove_bicom,
    prove_bicom1,
    prove_bicomd,
    prove_bicomi,
    prove_bifal,
    prove_bigolden,
    prove_biid,
    prove_biidd,
    prove_biimp,
    prove_biimp3a,
    prove_biimp3ar,
    prove_biimpa,
    prove_biimpac,
    prove_biimpar,
    prove_biimparc,
    prove_biimpcd,
    prove_biimpd,
    prove_biimpi,
    prove_biimpr,
    prove_biimprcd,
    prove_biimprd,
    prove_biimpri,
    prove_biimt,
    prove_biimtrdi,
    prove_biimtrid,
    prove_biimtrrdi,
    prove_biimtrrid,
    prove_bija,
    prove_bijust,
    prove_bijust0,
    prove_bilani,
    prove_bilanri,
    prove_bimsc1,
    prove_biorf,
    prove_biorfi,
    prove_biorfri,
    prove_biorfriOLD,
    prove_biort,
    prove_biortn,
    prove_birani,
    prove_biranri,
    prove_bitr,
    prove_bitr2d,
    prove_bitr2di,
    prove_bitr2i,
    prove_bitr2id,
    prove_bitr3,
    prove_bitr3d,
    prove_bitr3di,
    prove_bitr3i,
    prove_bitr3id,
    prove_bitr4d,
    prove_bitr4di,
    prove_bitr4i,
    prove_bitr4id,
    prove_bitrd,
    prove_bitrdi,
    prove_bitri,
    prove_bitrid,
    prove_bitru,
    prove_cad0,
    prove_cad11,
    prove_cadbi123d,
    prove_cadbi123i,
    prove_cadcoma,
    prove_cadtru,
    prove_cases2,
    prove_cases2ALT,
    prove_ccase,
    prove_ccase2,
    prove_ccased,
    prove_com3l,
    prove_com3r,
    prove_com4l,
    prove_com4r,
    prove_com4t,
    prove_com5l,
    prove_com5r,
    prove_com12,
    prove_com13,
    prove_com14,
    prove_com15,
    prove_com23,
    prove_com24,
    prove_com25,
    prove_com34,
    prove_com35,
    prove_com45,
    prove_com52l,
    prove_com52r,
    prove_con1,
    prove_con1b,
    prove_con1bid,
    prove_con1bii,
    prove_con1d,
    prove_con1i,
    prove_con2,
    prove_con2b,
    prove_con2bi,
    prove_con2bid,
    prove_con2bii,
    prove_con2d,
    prove_con2i,
    prove_con3,
    prove_con3ALT,
    prove_con3d,
    prove_con3dimp,
    prove_con3i,
    prove_con3rr3,
    prove_con4,
    prove_con4bid,
    prove_con4bii,
    prove_con4d,
    prove_con4i,
    prove_con34b,
    prove_conax1,
    prove_conax1k,
    prove_condan,
    prove_consensus,
    prove_curryax,
    prove_dedlem0a,
    prove_dedlem0b,
    prove_dedlema,
    prove_dedlemb,
    prove_dedt,
    prove_dfbi,
    prove_dfbi1,
    prove_dfbi1ALT,
    prove_dfbi2,
    prove_dfbi3,
    prove_dfifp2,
    prove_dfifp3,
    prove_dfifp4,
    prove_dfifp5,
    prove_dfifp6,
    prove_dfifp7,
    prove_dfnan2,
    prove_dfnot,
    prove_dfor2,
    prove_dftru2,
    prove_dn1,
    prove_ecase,
    prove_ecase2d,
    prove_ecase3,
    prove_ecase3d,
    prove_ecase23d,
    prove_ecased,
    prove_efald,
    prove_embantd,
    prove_ex,
    prove_ex3,
    prove_exbiri,
    prove_exmid,
    prove_exmidd,
    prove_exp4a,
    prove_exp4b,
    prove_exp4c,
    prove_exp4d,
    prove_exp5c,
    prove_exp5j,
    prove_exp5l,
    prove_exp5o,
    prove_exp31,
    prove_exp32,
    prove_exp41,
    prove_exp42,
    prove_exp43,
    prove_exp44,
    prove_exp45,
    prove_exp53,
    prove_exp516,
    prove_exp520,
    prove_expcom,
    prove_expcomd,
    prove_expd,
    prove_expdcom,
    prove_expdimp,
    prove_expi,
    prove_expimpd,
    prove_expl,
    prove_expr,
    prove_expt,
    prove_exptOLD,
    prove_fal,
    prove_falanfal,
    prove_falantru,
    prove_falbifal,
    prove_falbitru,
    prove_falim,
    prove_falimd,
    prove_falimfal,
    prove_falimtru,
    prove_falnantru,
    prove_falnorfal,
    prove_falnortru,
    prove_falorfal,
    prove_falortru,
    prove_falxorfal,
    prove_falxortru,
    prove_ianor,
    prove_iba,
    prove_ibar,
    prove_ibd,
    prove_ibi,
    prove_ibib,
    prove_ibibr,
    prove_ibir,
    prove_id,
    prove_idALT,
    prove_idd,
    prove_ifpbi23d,
    prove_ifpbi123d,
    prove_ifpdfbi,
    prove_ifpdfbiOLD,
    prove_ifpfal,
    prove_ifpid,
    prove_ifpimpda,
    prove_ifpn,
    prove_ifptru,
    prove_iman,
    prove_imbi1,
    prove_imbi1d,
    prove_imbi1i,
    prove_imbi2,
    prove_imbi2d,
    prove_imbi2i,
    prove_imbi12,
    prove_imbi12d,
    prove_imbi12i,
    prove_imbibi,
    prove_imbibiOLD,
    prove_imbitrdi,
    prove_imbitrid,
    prove_imbitrrdi,
    prove_imbitrrid,
    prove_imdi,
    prove_imdistan,
    prove_imdistand,
    prove_imdistanda,
    prove_imdistani,
    prove_imdistanri,
    prove_imim1,
    prove_imim1d,
    prove_imim1i,
    prove_imim2,
    prove_imim2d,
    prove_imim2i,
    prove_imim3i,
    prove_imim12,
    prove_imim12d,
    prove_imim12i,
    prove_imim21b,
    prove_imimorb,
    prove_imnan,
    prove_imnani,
    prove_imnot,
    prove_imor,
    prove_imori,
    prove_imorri,
    prove_imp,
    prove_imp4a,
    prove_imp4b,
    prove_imp4c,
    prove_imp4d,
    prove_imp5a,
    prove_imp5d,
    prove_imp5g,
    prove_imp31,
    prove_imp32,
    prove_imp41,
    prove_imp42,
    prove_imp43,
    prove_imp44,
    prove_imp45,
    prove_imp55,
    prove_imp511,
    prove_impac,
    prove_impancom,
    prove_impbi,
    prove_impbid,
    prove_impbid1,
    prove_impbid2,
    prove_impbid21d,
    prove_impbida,
    prove_impbidd,
    prove_impbii,
    prove_impcom,
    prove_impcomd,
    prove_impcon4bid,
    prove_impd,
    prove_impel,
    prove_impexp,
    prove_impi,
    prove_impimprbi,
    prove_impl,
    prove_impr,
    prove_impsingle,
    prove_impsingle_ax1,
    prove_impsingle_imim1,
    prove_impsingle_peirce,
    prove_impsingle_step4,
    prove_impsingle_step8,
    prove_impsingle_step15,
    prove_impsingle_step18,
    prove_impsingle_step19,
    prove_impsingle_step20,
    prove_impsingle_step21,
    prove_impsingle_step22,
    prove_impsingle_step25,
    prove_impt,
    prove_inegd,
    prove_intnan,
    prove_intnand,
    prove_intnanr,
    prove_intnanrd,
    prove_ioran,
    prove_ja,
    prove_jaao,
    prove_jad,
    prove_jao,
    prove_jao1i,
    prove_jaoa,
    prove_jaob,
    prove_jaod,
    prove_jaodan,
    prove_jaoi,
    prove_jaoi2,
    prove_jaoi3,
    prove_jaoian,
    prove_jarl,
    prove_jarli,
    prove_jarr,
    prove_jarri,
    prove_jc,
    prove_jca,
    prove_jca2,
    prove_jca31,
    prove_jca32,
    prove_jcab,
    prove_jcad,
    prove_jcai,
    prove_jccil,
    prove_jccir,
    prove_jcn,
    prove_jcnd,
    prove_jctil,
    prove_jctild,
    prove_jctir,
    prove_jctird,
    prove_jctl,
    prove_jctr,
    prove_just1_df,
    prove_looinv,
    prove_loolin,
    prove_loowoz,
    prove_luk_1,
    prove_luk_2,
    prove_luk_3,
    prove_luklem1,
    prove_luklem2,
    prove_luklem3,
    prove_luklem4,
    prove_luklem5,
    prove_luklem6,
    prove_luklem7,
    prove_lukshef_ax1,
    prove_lukshefth1,
    prove_lukshefth2,
    prove_merco1,
    prove_merco1lem1,
    prove_merco1lem2,
    prove_merco1lem3,
    prove_merco1lem4,
    prove_merco1lem5,
    prove_merco1lem6,
    prove_merco1lem7,
    prove_merco1lem8,
    prove_merco1lem9,
    prove_merco1lem10,
    prove_merco1lem11,
    prove_merco1lem12,
    prove_merco1lem13,
    prove_merco1lem14,
    prove_merco1lem15,
    prove_merco1lem16,
    prove_merco1lem17,
    prove_merco2,
    prove_mercolem1,
    prove_mercolem2,
    prove_mercolem3,
    prove_mercolem4,
    prove_mercolem5,
    prove_mercolem6,
    prove_mercolem7,
    prove_mercolem8,
    prove_meredith,
    prove_merlem1,
    prove_merlem2,
    prove_merlem3,
    prove_merlem4,
    prove_merlem5,
    prove_merlem6,
    prove_merlem7,
    prove_merlem8,
    prove_merlem9,
    prove_merlem10,
    prove_merlem11,
    prove_merlem12,
    prove_merlem13,
    prove_minimp,
    prove_minimp_ax1,
    prove_minimp_ax2,
    prove_minimp_ax2c,
    prove_minimp_pm2_43,
    prove_minimp_syllsimp,
    prove_monothetic,
    prove_mp1i,
    prove_mp2,
    prove_mp2an,
    prove_mp2and,
    prove_mp2ani,
    prove_mp2b,
    prove_mp2d,
    prove_mp3an,
    prove_mp3an1,
    prove_mp3an1i,
    prove_mp3an2i,
    prove_mp3an3,
    prove_mp3an12,
    prove_mp3an12i,
    prove_mp3an13,
    prove_mp3an23,
    prove_mp3and,
    prove_mp3anl1,
    prove_mp3anl3,
    prove_mp3anr1,
    prove_mp3anr3,
    prove_mp4an,
    prove_mpan,
    prove_mpan2,
    prove_mpan2d,
    prove_mpan2i,
    prove_mpancom,
    prove_mpand,
    prove_mpani,
    prove_mpanr2,
    prove_mpbi,
    prove_mpbi2and,
    prove_mpbid,
    prove_mpbidi,
    prove_mpbii,
    prove_mpbir,
    prove_mpbir2an,
    prove_mpbir2and,
    prove_mpbir3an,
    prove_mpbir3and,
    prove_mpbiran,
    prove_mpbiran2,
    prove_mpbird,
    prove_mpbiri,
    prove_mpcom,
    prove_mpd,
    prove_mpd3an3,
    prove_mpd3an23,
    prove_mpdan,
    prove_mpdd,
    prove_mpdi,
    prove_mpi,
    prove_mpid,
    prove_mpidan,
    prove_mpii,
    prove_mpisyl,
    prove_mpjao3dan,
    prove_mpjaod,
    prove_mpjaodan,
    prove_mpnanrd,
    prove_mpsyl,
    prove_mpsyl4anc,
    prove_mpsylsyld,
    prove_mptnan,
    prove_mptru,
    prove_mt2,
    prove_mt2bi,
    prove_mt2d,
    prove_mt2i,
    prove_mt3,
    prove_mt3d,
    prove_mt3i,
    prove_mt4,
    prove_mt4d,
    prove_mt4i,
    prove_mtand,
    prove_mtbi,
    prove_mtbid,
    prove_mtbii,
    prove_mtbir,
    prove_mtbird,
    prove_mtbiri,
    prove_mto,
    prove_mtod,
    prove_mtoi,
    prove_mtord,
    prove_mtpor,
    prove_mtt,
    prove_nan,
    prove_nanan,
    prove_nanass,
    prove_nanbi1,
    prove_nanbi1d,
    prove_nanbi1i,
    prove_nanbi2,
    prove_nanbi2d,
    prove_nanbi2i,
    prove_nanbi12,
    prove_nanbi12d,
    prove_nanbi12i,
    prove_nancom,
    prove_nanim,
    prove_nannan,
    prove_nanor,
    prove_nbfal,
    prove_nbior,
    prove_nbn,
    prove_nbn2,
    prove_nbn3,
    prove_niabn,
    prove_nic_ax,
    prove_nic_axALT,
    prove_nic_bi1,
    prove_nic_bi2,
    prove_nic_bijust,
    prove_nic_ich,
    prove_nic_id,
    prove_nic_idbl,
    prove_nic_idel,
    prove_nic_idlem1,
    prove_nic_idlem2,
    prove_nic_iimp1,
    prove_nic_iimp2,
    prove_nic_imp,
    prove_nic_isw1,
    prove_nic_isw2,
    prove_nic_mp,
    prove_nic_mp_alt,
    prove_nic_swap,
    prove_ninba,
    prove_noran,
    prove_norass,
    prove_norasslem1,
    prove_norasslem2,
    prove_norasslem3,
    prove_norbi,
    prove_norcom,
    prove_nornot,
    prove_noror,
    prove_notbi,
    prove_notbid,
    prove_notbii,
    prove_notfal,
    prove_notnot,
    prove_notnotb,
    prove_notnotd,
    prove_notnoti,
    prove_notnotr,
    prove_notnotrd,
    prove_notnotri,
    prove_notnotriALT,
    prove_nottru,
    prove_nsyl,
    prove_nsyl2,
    prove_nsyl3,
    prove_nsyl4,
    prove_nsyl5,
    prove_nsyld,
    prove_nsyli,
    prove_oibabs,
    prove_olc,
    prove_olcd,
    prove_olci,
    prove_olcnd,
    prove_olcs,
    prove_oplem1,
    prove_or4,
    prove_or12,
    prove_or32,
    prove_or42,
    prove_orabs,
    prove_oran,
    prove_oranabs,
    prove_orass,
    prove_orbi1,
    prove_orbi1d,
    prove_orbi1i,
    prove_orbi2d,
    prove_orbi2i,
    prove_orbi12d,
    prove_orbi12i,
    prove_orbidi,
    prove_orc,
    prove_orcanai,
    prove_orcd,
    prove_orci,
    prove_orcnd,
    prove_orcom,
    prove_orcomd,
    prove_orcoms,
    prove_orcs,
    prove_ord,
    prove_orddi,
    prove_ordi,
    prove_ordir,
    prove_orel1,
    prove_orel2,
    prove_ori,
    prove_oridm,
    prove_orim1d,
    prove_orim1i,
    prove_orim2,
    prove_orim2d,
    prove_orim2i,
    prove_orim12d,
    prove_orim12da,
    prove_orim12dALT,
    prove_orim12i,
    prove_orimdi,
    prove_orordi,
    prove_orordir,
    prove_orrd,
    prove_orri,
    prove_peirce,
    prove_peirceroll,
    prove_pm1_2,
    prove_pm1_4,
    prove_pm1_5,
    prove_pm2_01,
    prove_pm2_01d,
    prove_pm2_01da,
    prove_pm2_01i,
    prove_pm2_04,
    prove_pm2_07,
    prove_pm2_1,
    prove_pm2_3,
    prove_pm2_4,
    prove_pm2_5,
    prove_pm2_5g,
    prove_pm2_6,
    prove_pm2_8,
    prove_pm2_13,
    prove_pm2_18,
    prove_pm2_18d,
    prove_pm2_18da,
    prove_pm2_18i,
    prove_pm2_21,
    prove_pm2_21d,
    prove_pm2_21dd,
    prove_pm2_21ddALT,
    prove_pm2_21fal,
    prove_pm2_21i,
    prove_pm2_24,
    prove_pm2_24d,
    prove_pm2_24i,
    prove_pm2_24ii,
    prove_pm2_25,
    prove_pm2_26,
    prove_pm2_27,
    prove_pm2_31,
    prove_pm2_32,
    prove_pm2_36,
    prove_pm2_37,
    prove_pm2_38,
    prove_pm2_41,
    prove_pm2_42,
    prove_pm2_43,
    prove_pm2_43a,
    prove_pm2_43b,
    prove_pm2_43d,
    prove_pm2_43i,
    prove_pm2_45,
    prove_pm2_46,
    prove_pm2_47,
    prove_pm2_48,
    prove_pm2_49,
    prove_pm2_51,
    prove_pm2_52,
    prove_pm2_53,
    prove_pm2_54,
    prove_pm2_61,
    prove_pm2_61d,
    prove_pm2_61d1,
    prove_pm2_61d2,
    prove_pm2_61i,
    prove_pm2_61ian,
    prove_pm2_61ii,
    prove_pm2_61iii,
    prove_pm2_61nii,
    prove_pm2_62,
    prove_pm2_63,
    prove_pm2_64,
    prove_pm2_65,
    prove_pm2_65d,
    prove_pm2_65da,
    prove_pm2_65i,
    prove_pm2_65iold,
    prove_pm2_65ni,
    prove_pm2_67,
    prove_pm2_67_2,
    prove_pm2_68,
    prove_pm2_73,
    prove_pm2_74,
    prove_pm2_75,
    prove_pm2_76,
    prove_pm2_81,
    prove_pm2_82,
    prove_pm2_83,
    prove_pm2_85,
    prove_pm2_86,
    prove_pm2_86d,
    prove_pm2_86i,
    prove_pm2_521,
    prove_pm2_521g,
    prove_pm2_521g2,
    prove_pm2_621,
    prove_pm3_1,
    prove_pm3_2,
    prove_pm3_2an3,
    prove_pm3_2i,
    prove_pm3_2im,
    prove_pm3_2ni,
    prove_pm3_3,
    prove_pm3_4,
    prove_pm3_11,
    prove_pm3_12,
    prove_pm3_13,
    prove_pm3_14,
    prove_pm3_21,
    prove_pm3_22,
    prove_pm3_24,
    prove_pm3_31,
    prove_pm3_33,
    prove_pm3_34,
    prove_pm3_35,
    prove_pm3_37,
    prove_pm3_41,
    prove_pm3_42,
    prove_pm3_43,
    prove_pm3_43i,
    prove_pm3_44,
    prove_pm3_45,
    prove_pm3_48,
    prove_pm4_8,
    prove_pm4_14,
    prove_pm4_15,
    prove_pm4_24,
    prove_pm4_25,
    prove_pm4_38,
    prove_pm4_42,
    prove_pm4_43,
    prove_pm4_44,
    prove_pm4_45,
    prove_pm4_45im,
    prove_pm4_52,
    prove_pm4_53,
    prove_pm4_54,
    prove_pm4_55,
    prove_pm4_56,
    prove_pm4_57,
    prove_pm4_61,
    prove_pm4_62,
    prove_pm4_63,
    prove_pm4_64,
    prove_pm4_65,
    prove_pm4_66,
    prove_pm4_67,
    prove_pm4_71,
    prove_pm4_71d,
    prove_pm4_71da,
    prove_pm4_71i,
    prove_pm4_71r,
    prove_pm4_71rd,
    prove_pm4_71ri,
    prove_pm4_72,
    prove_pm4_76,
    prove_pm4_77,
    prove_pm4_78,
    prove_pm4_79,
    prove_pm4_81,
    prove_pm4_82,
    prove_pm4_83,
    prove_pm4_87,
    prove_pm5_1,
    prove_pm5_1im,
    prove_pm5_3,
    prove_pm5_4,
    prove_pm5_5,
    prove_pm5_6,
    prove_pm5_7,
    prove_pm5_11,
    prove_pm5_11g,
    prove_pm5_12,
    prove_pm5_13,
    prove_pm5_14,
    prove_pm5_17,
    prove_pm5_21,
    prove_pm5_21im,
    prove_pm5_21nd,
    prove_pm5_21ndd,
    prove_pm5_21ni,
    prove_pm5_21nii,
    prove_pm5_31,
    prove_pm5_32,
    prove_pm5_32d,
    prove_pm5_32da,
    prove_pm5_32i,
    prove_pm5_32rd,
    prove_pm5_32ri,
    prove_pm5_33,
    prove_pm5_35,
    prove_pm5_36,
    prove_pm5_41,
    prove_pm5_42,
    prove_pm5_44,
    prove_pm5_53,
    prove_pm5_54,
    prove_pm5_55,
    prove_pm5_61,
    prove_pm5_62,
    prove_pm5_63,
    prove_pm5_71,
    prove_pm5_74,
    prove_pm5_74d,
    prove_pm5_74da,
    prove_pm5_74i,
    prove_pm5_74rd,
    prove_pm5_74ri,
    prove_pm5_75,
    prove_pm5_501,
    prove_prlem1,
    prove_prlem2,
    prove_rb_ax1,
    prove_rb_ax2,
    prove_rb_ax3,
    prove_rb_ax4,
    prove_rb_bijust,
    prove_rb_imdf,
    prove_rbaib,
    prove_rbaibd,
    prove_rbaibr,
    prove_rblem1,
    prove_rblem2,
    prove_rblem3,
    prove_rblem4,
    prove_rblem5,
    prove_rblem6,
    prove_rblem7,
    prove_rbsyl,
    prove_re1axmp,
    prove_re1luk1,
    prove_re1luk2,
    prove_re1luk3,
    prove_re1tbw1,
    prove_re1tbw2,
    prove_re1tbw3,
    prove_re1tbw4,
    prove_re2luk1,
    prove_re2luk2,
    prove_re2luk3,
    prove_renicax,
    prove_retbwax2,
    prove_retbwax3,
    prove_retbwax4,
    prove_simpl,
    prove_simpl2im,
    prove_simplbda,
    prove_simplbi,
    prove_simplbi2,
    prove_simplbi2com,
    prove_simplbiim,
    prove_simpld,
    prove_simpli,
    prove_simplim,
    prove_simplld,
    prove_simplrd,
    prove_simpr,
    prove_simpr1,
    prove_simpr1l,
    prove_simpr1r,
    prove_simpr2,
    prove_simpr2l,
    prove_simpr2r,
    prove_simpr11,
    prove_simpr12,
    prove_simpr21,
    prove_simpr22,
    prove_simprbda,
    prove_simprbi,
    prove_simprd,
    prove_simpri,
    prove_simprim,
    prove_simprl,
    prove_simprld,
    prove_simprll,
    prove_simprlr,
    prove_simprr,
    prove_simprrd,
    prove_simprrl,
    prove_simprrr,
    prove_stoic1a,
    prove_stoic1b,
    prove_stoic2a,
    prove_stoic2b,
    prove_syl,
    prove_syl2an2,
    prove_syl2anc,
    prove_syl2anc2,
    prove_syl2and,
    prove_syl2ani,
    prove_syl2im,
    prove_syl2imc,
    prove_syl3an9b,
    prove_syl3anb,
    prove_syl3anbr,
    prove_syl3anbrc,
    prove_syl3anc,
    prove_syl3c,
    prove_syl5,
    prove_syl5com,
    prove_syl5d,
    prove_syl5ibcom,
    prove_syl5ibrcom,
    prove_syl6,
    prove_syl6an,
    prove_syl6c,
    prove_syl6ci,
    prove_syl6com,
    prove_syl6d,
    prove_syl6mpi,
    prove_syl7,
    prove_syl7bi,
    prove_syl8,
    prove_syl8ib,
    prove_syl9,
    prove_syl9r,
    prove_syl10,
    prove_syl11,
    prove_syl12anc,
    prove_syl13anc,
    prove_syl21anbrc,
    prove_syl21anc,
    prove_syl22anc,
    prove_syl23anc,
    prove_syl31anc,
    prove_syl32anc,
    prove_syl33anc,
    prove_syl56,
    prove_syl112anc,
    prove_syl113anc,
    prove_syl121anc,
    prove_syl122anc,
    prove_syl123anc,
    prove_syl131anc,
    prove_syl132anc,
    prove_syl133anc,
    prove_syl211anc,
    prove_syl212anc,
    prove_syl213anc,
    prove_syl221anc,
    prove_syl222anc,
    prove_syl223anc,
    prove_syl231anc,
    prove_syl232anc,
    prove_syl233anc,
    prove_syl311anc,
    prove_syl312anc,
    prove_syl313anc,
    prove_syl321anc,
    prove_syl322anc,
    prove_syl323anc,
    prove_syl331anc,
    prove_syl332anc,
    prove_syl333anc,
    prove_syl1111anc,
    prove_sylan2,
    prove_sylan2b,
    prove_sylan2br,
    prove_sylan2d,
    prove_sylan2i,
    prove_sylan9,
    prove_sylan9bb,
    prove_sylan9bbr,
    prove_sylan9r,
    prove_sylanblc,
    prove_sylanblrc,
    prove_sylanbrc,
    prove_sylancl,
    prove_sylancom,
    prove_sylancr,
    prove_syland,
    prove_sylani,
    prove_sylbb,
    prove_sylbb1,
    prove_sylbb2,
    prove_sylbbr,
    prove_sylbi,
    prove_sylbid,
    prove_sylbida,
    prove_sylbir,
    prove_sylbird,
    prove_sylc,
    prove_sylcom,
    prove_syld,
    prove_syldan,
    prove_syldbl2,
    prove_syldc,
    prove_syldd,
    prove_syli,
    prove_sylib,
    prove_sylibd,
    prove_sylibr,
    prove_sylibrd,
    prove_sylnbi,
    prove_sylnbir,
    prove_sylnib,
    prove_sylnibr,
    prove_sylsyld,
    prove_tarski_bernays_ax2,
    prove_tbt,
    prove_tbtru,
    prove_tbw_ax1,
    prove_tbw_ax2,
    prove_tbw_ax3,
    prove_tbw_ax4,
    prove_tbw_bijust,
    prove_tbw_negdf,
    prove_tbwlem1,
    prove_tbwlem2,
    prove_tbwlem3,
    prove_tbwlem4,
    prove_tbwlem5,
    prove_tbwsyl,
    prove_tru,
    prove_truan,
    prove_truanfal,
    prove_truantru,
    prove_trubifal,
    prove_trubitru,
    prove_trud,
    prove_truimfal,
    prove_truimtru,
    prove_trunanfal,
    prove_trunorfal,
    prove_trunortru,
    prove_truorfal,
    prove_truortru,
    prove_trut,
    prove_truxorfal,
    prove_truxortru,
    prove_xchbinx,
    prove_xchbinxr,
    prove_xchnxbi,
    prove_xchnxbir,
    prove_xnor,
    prove_xorbi12d,
    prove_xorbi12i,
    prove_xorcom,
    prove_xordi,
)
from .negation import MIGRATION_THEOREMS as NEGATION_MIGRATIONS

LemmaCtor = Callable[[System], Proof]


_LEGACY_HILBERT_LEMMAS: Mapping[str, LemmaCtor] = {
    "1fpid3": prove_1fpid3,
    "ifpimpda": prove_ifpimpda,
    "ifptru": prove_ifptru,
    "ifpid": prove_ifpid,
    "ifpbi123d": prove_ifpbi123d,
    "ifpbi23d": prove_ifpbi23d,
    "3imp1": prove_3imp1,
    "3com12": prove_3com12,
    "3com13": prove_3com13,
    "3com23": prove_3com23,
    "3ad2antr1": prove_3ad2antr1,
    "3ad2antr2": prove_3ad2antr2,
    "3adant3": prove_3adant3,
    "3adant3r3": prove_3adant3r3,
    "3adantr3": prove_3adantr3,
    "3coml": prove_3coml,
    "3comr": prove_3comr,
    "3ecase": prove_3ecase,
    "3imp": prove_3imp,
    "3imp231": prove_3imp231,
    "3impd": prove_3impd,
    "3impexp": prove_3impexp,
    "3imp2": prove_3imp2,
    "3jao": prove_3jao,
    "3jaob": prove_3jaob,
    "3jaod": prove_3jaod,
    "3jaodan": prove_3jaodan,
    "3jaoiOLD": prove_3jaoiOLD,
    "3jaoian": prove_3jaoian,
    "3jaoi": prove_3jaoi,
    "3jca": prove_3jca,
    "3jcad": prove_3jcad,
    "3imp21": prove_3imp21,
    "3impb": prove_3impb,
    "3impib": prove_3impib,
    "3impia": prove_3impia,
    "3imp31": prove_3imp31,
    "impexp": prove_impexp,
    "imp": prove_imp,
    "impac": prove_impac,
    "imdistan": prove_imdistan,
    "imdistand": prove_imdistand,
    "imdistani": prove_imdistani,
    "imdistanda": prove_imdistanda,
    "intnan": prove_intnan,
    "impl": prove_impl,
    "intnanr": prove_intnanr,
    "intnanrd": prove_intnanrd,
    "imdistanri": prove_imdistanri,
    "imnan": prove_imnan,
    "imnani": prove_imnani,
    "iman": prove_iman,
    "annim": prove_annim,
    "intnand": prove_intnand,
    "ioran": prove_ioran,
    "3oran": prove_3oran,
    "3ioran": prove_3ioran,
    "3ianor": prove_3ianor,
    "3anor": prove_3anor,
    "impancom": prove_impancom,
    "imp31": prove_imp31,
    "imp41": prove_imp41,
    "imp42": prove_imp42,
    "imp43": prove_imp43,
    "imp44": prove_imp44,
    "imp45": prove_imp45,
    "imp32": prove_imp32,
    "impr": prove_impr,
    "4anpull2": prove_4anpull2,
    "4anpull2OLD": prove_4anpull2OLD,
    "abai": prove_abai,
    "an12": prove_an12,
    "an12s": prove_an12s,
    "an13": prove_an13,
    "an13s": prove_an13s,
    "an21": prove_an21,
    "an2anr": prove_an2anr,
    "an32": prove_an32,
    "an4": prove_an4,
    "an32s": prove_an32s,
    "an4s": prove_an4s,
    "an42": prove_an42,
    "an42ds": prove_an42ds,
    "an42s": prove_an42s,
    "an3": prove_an3,
    "an43": prove_an43,
    "an33rean": prove_an33rean,
    "an6": prove_an6,
    "anandi3": prove_anandi3,
    "anandi3r": prove_anandi3r,
    "an3andi": prove_an3andi,
    "anandi": prove_anandi,
    "anandir": prove_anandir,
    "3an6": prove_3an6,
    "an31": prove_an31,
    "an31s": prove_an31s,
    "ancom2s": prove_ancom2s,
    "anabsi6": prove_anabsi6,
    "anabsi7": prove_anabsi7,
    "anabsi8": prove_anabsi8,
    "annotanannot": prove_annotanannot,
    "anabs1": prove_anabs1,
    "anabs5": prove_anabs5,
    "anabs7": prove_anabs7,
    "syldbl2": prove_syldbl2,
    "anabsi5": prove_anabsi5,
    "anassrs": prove_anassrs,
    "anass1rs": prove_anass1rs,
    "3anassrs": prove_3anassrs,
    "3anbi123i": prove_3anbi123i,
    "3anbi12d": prove_3anbi12d,
    "3anbi13d": prove_3anbi13d,
    "3anbi1d": prove_3anbi1d,
    "3anbi2d": prove_3anbi2d,
    "3anbi3d": prove_3anbi3d,
    "3anbi123d": prove_3anbi123d,
    "3anbi23d": prove_3anbi23d,
    "3anbi1i": prove_3anbi1i,
    "3anbi2i": prove_3anbi2i,
    "3anbi3i": prove_3anbi3i,
    "3an1rs": prove_3an1rs,
    "3anidm12": prove_3anidm12,
    "3anidm13": prove_3anidm13,
    "3anidm": prove_3anidm,
    "ancrd": prove_ancrd,
    "ancld": prove_ancld,
    "anc2l": prove_anc2l,
    "anc2li": prove_anc2li,
    "anc2r": prove_anc2r,
    "anc2ri": prove_anc2ri,
    "ancl": prove_ancl,
    "ancr": prove_ancr,
    "ancrb": prove_ancrb,
    "anclb": prove_anclb,
    "ancli": prove_ancli,
    "ancri": prove_ancri,
    "anasss": prove_anasss,
    "anass": prove_anass,
    "anbi1": prove_anbi1,
    "anbi1i": prove_anbi1i,
    "anbi12d": prove_anbi12d,
    "anbi12i": prove_anbi12i,
    "anbi12ci": prove_anbi12ci,
    "anbi2i": prove_anbi2i,
    "anbi1d": prove_anbi1d,
    "anbi1cd": prove_anbi1cd,
    "anbi1ci": prove_anbi1ci,
    "anbi2": prove_anbi2,
    "imp4a": prove_imp4a,
    "anbiim": prove_anbiim,
    "anbiimOLD": prove_anbiimOLD,
    "imp4b": prove_imp4b,
    "imp4c": prove_imp4c,
    "imp4d": prove_imp4d,
    "imp5d": prove_imp5d,
    "imp5a": prove_imp5a,
    "imp5g": prove_imp5g,
    "imp511": prove_imp511,
    "imp55": prove_imp55,
    "impel": prove_impel,
    "impcom": prove_impcom,
    "expr": prove_expr,
    "expl": prove_expl,
    "ancom": prove_ancom,
    "ancoms": prove_ancoms,
    "ancomd": prove_ancomd,
    "ancomsd": prove_ancomsd,
    "ancomst": prove_ancomst,
    "impcomd": prove_impcomd,
    "impd": prove_impd,
    "id": prove_id,
    "idALT": prove_idALT,
    "notnot": prove_notnot,
    "notbi": prove_notbi,
    "notbii": prove_notbii,
    "notbid": prove_notbid,
    "notnotb": prove_notnotb,
    "notnotd": prove_notnotd,
    "notnoti": prove_notnoti,
    "notnotr": prove_notnotr,
    "notnotrd": prove_notnotrd,
    "a1bi": prove_a1bi,
    "baib": prove_baib,
    "baibr": prove_baibr,
    "rbaibr": prove_rbaibr,
    "rbaib": prove_rbaib,
    "baibd": prove_baibd,
    "rbaibd": prove_rbaibd,
    "a1i": prove_a1i,
    "a1i13": prove_a1i13,
    "ax1": prove_ax1,
    "ax1w": prove_ax1w,
    "axin1": prove_axin1,
    "axin2": prove_axin2,
    "a2i": prove_a2i,
    "ad4ant123": prove_ad4ant123,
    "ad5ant125OLD": prove_ad5ant125OLD,
    "ad5ant2345": prove_ad5ant2345,
    "ad2antll": prove_ad2antll,
    "ad2antrl": prove_ad2antrl,
    "adantl": prove_adantl,
    "adantr": prove_adantr,
    "adantrd": prove_adantrd,
    "adantrl": prove_adantrl,
    "adantrr": prove_adantrr,
    "adantld": prove_adantld,
    "anidms": prove_anidms,
    "anidm": prove_anidm,
    "anidmdbi": prove_anidmdbi,
    "animpimp2impd": prove_animpimp2impd,
    "mp2": prove_mp2,
    "mp2b": prove_mp2b,
    "mp2d": prove_mp2d,
    "mp2an": prove_mp2an,
    "mp2ani": prove_mp2ani,
    "mp2and": prove_mp2and,
    "mp3an": prove_mp3an,
    "mp3an12": prove_mp3an12,
    "mp3an12i": prove_mp3an12i,
    "mp4an": prove_mp4an,
    "mp1i": prove_mp1i,
    "mpancom": prove_mpancom,
    "mpan2": prove_mpan2,
    "mpanr2": prove_mpanr2,
    "mpan2d": prove_mpan2d,
    "mpan2i": prove_mpan2i,
    "mpand": prove_mpand,
    "mpani": prove_mpani,
    "mpan": prove_mpan,
    "mpcom": prove_mpcom,
    "mpbi": prove_mpbi,
    "mpbir": prove_mpbir,
    "mpbir2an": prove_mpbir2an,
    "mpbir3an": prove_mpbir3an,
    "mpbiran": prove_mpbiran,
    "mpbiran2": prove_mpbiran2,
    "niabn": prove_niabn,
    "ninba": prove_ninba,
    "mpbid": prove_mpbid,
    "mpbird": prove_mpbird,
    "mpbii": prove_mpbii,
    "mpbi2and": prove_mpbi2and,
    "mpbiri": prove_mpbiri,
    "mpbir2and": prove_mpbir2and,
    "mpbir3and": prove_mpbir3and,
    "mpbidi": prove_mpbidi,
    "mpd": prove_mpd,
    "mpdan": prove_mpdan,
    "mpidan": prove_mpidan,
    "mpd3an3": prove_mpd3an3,
    "mp3an1": prove_mp3an1,
    "mp3an1i": prove_mp3an1i,
    "mp3an3": prove_mp3an3,
    "mp3anr3": prove_mp3anr3,
    "mp3anr1": prove_mp3anr1,
    "mp3anl3": prove_mp3anl3,
    "mpd3an23": prove_mpd3an23,
    "mp3anl1": prove_mp3anl1,
    "mp3an13": prove_mp3an13,
    "mp3an2i": prove_mp3an2i,
    "mp3and": prove_mp3and,
    "mp3an23": prove_mp3an23,
    "mpi": prove_mpi,
    "mpii": prove_mpii,
    "mpid": prove_mpid,
    "mpisyl": prove_mpisyl,
    "mpsyl": prove_mpsyl,
    "mpsylsyld": prove_mpsylsyld,
    "simpl": prove_simpl,
    "simpli": prove_simpli,
    "simplld": prove_simplld,
    "simpld": prove_simpld,
    "simplbda": prove_simplbda,
    "simpr": prove_simpr,
    "simprbda": prove_simprbda,
    "simprbi": prove_simprbi,
    "simplbiim": prove_simplbiim,
    "simpl2im": prove_simpl2im,
    "simprd": prove_simprd,
    "simplrd": prove_simplrd,
    "simprl": prove_simprl,
    "simpr11": prove_simpr11,
    "simpr1": prove_simpr1,
    "simpr1r": prove_simpr1r,
    "simpr1l": prove_simpr1l,
    "simpr2": prove_simpr2,
    "simpr12": prove_simpr12,
    "simpr2l": prove_simpr2l,
    "simpr2r": prove_simpr2r,
    "simpr21": prove_simpr21,
    "simpr22": prove_simpr22,
    "simprr": prove_simprr,
    "simprrd": prove_simprrd,
    "simprld": prove_simprld,
    "simpri": prove_simpri,
    "simprlr": prove_simprlr,
    "simprll": prove_simprll,
    "simprrl": prove_simprrl,
    "simprrr": prove_simprrr,
    "syl": prove_syl,
    "sylbi": prove_sylbi,
    "sylbir": prove_sylbir,
    "sylbb": prove_sylbb,
    "sylbbr": prove_sylbbr,
    "sylbb1": prove_sylbb1,
    "sylbb2": prove_sylbb2,
    "sylbid": prove_sylbid,
    "sylbird": prove_sylbird,
    "sylbida": prove_sylbida,
    "3imtr3g": prove_3imtr3g,
    "3imtr3i": prove_3imtr3i,
    "3imtr3d": prove_3imtr3d,
    "3imtr4i": prove_3imtr4i,
    "3imtr4g": prove_3imtr4g,
    "3imtr4d": prove_3imtr4d,
    "3mix1": prove_3mix1,
    "3mix1d": prove_3mix1d,
    "3mix1i": prove_3mix1i,
    "3mix2": prove_3mix2,
    "3mix2d": prove_3mix2d,
    "3mix3": prove_3mix3,
    "3mix3d": prove_3mix3d,
    "3mix3i": prove_3mix3i,
    "3mix2i": prove_3mix2i,
    "3syl": prove_3syl,
    "sylib": prove_sylib,
    "sylibd": prove_sylibd,
    "sylibr": prove_sylibr,
    "sylibrd": prove_sylibrd,
    "3syld": prove_3syld,
    "3simpa": prove_3simpa,
    "3impa": prove_3impa,
    "3expa": prove_3expa,
    "3expb": prove_3expb,
    "3expia": prove_3expia,
    "4cases": prove_4cases,
    "4casesdan": prove_4casesdan,
    "4syl": prove_4syl,
    "sylc": prove_sylc,
    "syl3anc": prove_syl3anc,
    "syl31anc": prove_syl31anc,
    "syl312anc": prove_syl312anc,
    "syl313anc": prove_syl313anc,
    "syl311anc": prove_syl311anc,
    "syl33anc": prove_syl33anc,
    "syl331anc": prove_syl331anc,
    "syl332anc": prove_syl332anc,
    "syl333anc": prove_syl333anc,
    "syl32anc": prove_syl32anc,
    "syl321anc": prove_syl321anc,
    "syl322anc": prove_syl322anc,
    "syl323anc": prove_syl323anc,
    "syl3an9b": prove_syl3an9b,
    "syl3anb": prove_syl3anb,
    "syl3anbr": prove_syl3anbr,
    "syl3anbrc": prove_syl3anbrc,
    "syl3c": prove_syl3c,
    "sylancr": prove_sylancr,
    "sylancl": prove_sylancl,
    "sylanblc": prove_sylanblc,
    "syl2anc": prove_syl2anc,
    "syl2anc2": prove_syl2anc2,
    "syl2an2": prove_syl2an2,
    "syl12anc": prove_syl12anc,
    "syl121anc": prove_syl121anc,
    "syl123anc": prove_syl123anc,
    "syl122anc": prove_syl122anc,
    "syl23anc": prove_syl23anc,
    "syl231anc": prove_syl231anc,
    "syl232anc": prove_syl232anc,
    "syl233anc": prove_syl233anc,
    "syl113anc": prove_syl113anc,
    "syl112anc": prove_syl112anc,
    "syl133anc": prove_syl133anc,
    "syl131anc": prove_syl131anc,
    "syl132anc": prove_syl132anc,
    "syl13anc": prove_syl13anc,
    "syl21anc": prove_syl21anc,
    "syl211anc": prove_syl211anc,
    "syl212anc": prove_syl212anc,
    "syl213anc": prove_syl213anc,
    "syl221anc": prove_syl221anc,
    "syl222anc": prove_syl222anc,
    "syl223anc": prove_syl223anc,
    "syl1111anc": prove_syl1111anc,
    "mpsyl4anc": prove_mpsyl4anc,
    "monothetic": prove_monothetic,
    "syl21anbrc": prove_syl21anbrc,
    "syl22anc": prove_syl22anc,
    "sylanblrc": prove_sylanblrc,
    "sylanbrc": prove_sylanbrc,
    "sylcom": prove_sylcom,
    "bi23imp13": prove_bi23imp13,
    "bi2bian9": prove_bi2bian9,
    "bianass": prove_bianass,
    "bianassc": prove_bianassc,
    "bianbi": prove_bianbi,
    "bianir": prove_bianir,
    "biancomd": prove_biancomd,
    "bian1d": prove_bian1d,
    "biancomi": prove_biancomi,
    "anbi2ci": prove_anbi2ci,
    "anbi2d": prove_anbi2d,
    "bianfd": prove_bianfd,
    "bilani": prove_bilani,
    "bianfi": prove_bianfi,
    "bianim": prove_bianim,
    "birani": prove_birani,
    "biranri": prove_biranri,
    "bilanri": prove_bilanri,
    "biantr": prove_biantr,
    "bi2.04": prove_bi2_04,
    "biadaniALT": prove_biadaniALT,
    "biadanid": prove_biadanid,
    "bianabs": prove_bianabs,
    "bibiad": prove_bibiad,
    "bibif": prove_bibif,
    "biantru": prove_biantru,
    "biantrur": prove_biantrur,
    "biantrud": prove_biantrud,
    "biantrurd": prove_biantrurd,
    "bicom": prove_bicom,
    "bicomi": prove_bicomi,
    "bicomd": prove_bicomd,
    "bicom1": prove_bicom1,
    "bibi2d": prove_bibi2d,
    "bibi2i": prove_bibi2i,
    "bibi1d": prove_bibi1d,
    "bibi1": prove_bibi1,
    "bibi1i": prove_bibi1i,
    "bibi12d": prove_bibi12d,
    "bibi12i": prove_bibi12i,
    "bigolden": prove_bigolden,
    "biid": prove_biid,
    "biidd": prove_biidd,
    "bitr": prove_bitr,
    "bitr2i": prove_bitr2i,
    "bitr3i": prove_bitr3i,
    "bitr3id": prove_bitr3id,
    "bitri": prove_bitri,
    "bitrd": prove_bitrd,
    "bitrdi": prove_bitrdi,
    "bitrid": prove_bitrid,
    "bitr2d": prove_bitr2d,
    "bitr2di": prove_bitr2di,
    "bitr2id": prove_bitr2id,
    "bitr4di": prove_bitr4di,
    "bitr3di": prove_bitr3di,
    "bitr4id": prove_bitr4id,
    "bitr3": prove_bitr3,
    "bitr3d": prove_bitr3d,
    "bitr4d": prove_bitr4d,
    "bitr4i": prove_bitr4i,
    "3bitr2i": prove_3bitr2i,
    "3bitr2ri": prove_3bitr2ri,
    "3bitr2d": prove_3bitr2d,
    "3bitr2rd": prove_3bitr2rd,
    "3bitrd": prove_3bitrd,
    "3an4anass": prove_3an4anass,
    "3anim123d": prove_3anim123d,
    "3anan12": prove_3anan12,
    "3anan32": prove_3anan32,
    "3anan32OLD": prove_3anan32OLD,
    "3ancomb": prove_3ancomb,
    "3anrot": prove_3anrot,
    "3anrev": prove_3anrev,
    "3anass": prove_3anass,
    "3ancoma": prove_3ancoma,
    "3biant1d": prove_3biant1d,
    "3bitrrd": prove_3bitrrd,
    "3bitr3d": prove_3bitr3d,
    "3bitr3g": prove_3bitr3g,
    "3bitr3i": prove_3bitr3i,
    "3bitri": prove_3bitri,
    "3bitrri": prove_3bitrri,
    "3bitr3rd": prove_3bitr3rd,
    "3bitr3ri": prove_3bitr3ri,
    "3bitr4rd": prove_3bitr4rd,
    "3bitr4d": prove_3bitr4d,
    "3bitr4ri": prove_3bitr4ri,
    "3bitr4i": prove_3bitr4i,
    "3bitr4g": prove_3bitr4g,
    "3bior1fd": prove_3bior1fd,
    "3bior1fand": prove_3bior1fand,
    "3bior2fd": prove_3bior2fd,
    "biimp": prove_biimp,
    "biimpr": prove_biimpr,
    "biimpi": prove_biimpi,
    "biimpri": prove_biimpri,
    "biimpcd": prove_biimpcd,
    "biimprcd": prove_biimprcd,
    "biimp3ar": prove_biimp3ar,
    "biimp3a": prove_biimp3a,
    "biimpa": prove_biimpa,
    "biimpar": prove_biimpar,
    "biimpac": prove_biimpac,
    "biimparc": prove_biimparc,
    "biimpd": prove_biimpd,
    "biimprd": prove_biimprd,
    "biimt": prove_biimt,
    "biimtrdi": prove_biimtrdi,
    "biimtrrdi": prove_biimtrrdi,
    "biimtrid": prove_biimtrid,
    "bija": prove_bija,
    "biort": prove_biort,
    "biorf": prove_biorf,
    "biortn": prove_biortn,
    "biorfi": prove_biorfi,
    "bijust0": prove_bijust0,
    "biorfri": prove_biorfri,
    "biorfriOLD": prove_biorfriOLD,
    "bijust": prove_bijust,
    "cad0": prove_cad0,
    "cad11": prove_cad11,
    "cadbi123d": prove_cadbi123d,
    "cadbi123i": prove_cadbi123i,
    "cadcoma": prove_cadcoma,
    "cadtru": prove_cadtru,
    "com12": prove_com12,
    "syl5": prove_syl5,
    "syl6": prove_syl6,
    "syl6an": prove_syl6an,
    "syl6mpi": prove_syl6mpi,
    "syl7": prove_syl7,
    "syl7bi": prove_syl7bi,
    "syl8ib": prove_syl8ib,
    "syl8": prove_syl8,
    "a1d": prove_a1d,
    "a1dd": prove_a1dd,
    "a1ddd": prove_a1ddd,
    "2a1dd": prove_2a1dd,
    "a2d": prove_a2d,
    "syl5com": prove_syl5com,
    "syl5d": prove_syl5d,
    "imbitrid": prove_imbitrid,
    "imbitrrid": prove_imbitrrid,
    "bimsc1": prove_bimsc1,
    "biimtrrid": prove_biimtrrid,
    "imbitrdi": prove_imbitrdi,
    "imbitrrdi": prove_imbitrrdi,
    "syl5ibcom": prove_syl5ibcom,
    "syl5ibrcom": prove_syl5ibrcom,
    "con1": prove_con1,
    "con1b": prove_con1b,
    "con1bii": prove_con1bii,
    "con1bid": prove_con1bid,
    "con1d": prove_con1d,
    "con2": prove_con2,
    "con2d": prove_con2d,
    "con3ALT": prove_con3ALT,
    "con3": prove_con3,
    "con3d": prove_con3d,
    "con3dimp": prove_con3dimp,
    "con3rr3": prove_con3rr3,
    "con4": prove_con4,
    "con4d": prove_con4d,
    "conax1": prove_conax1,
    "conax1k": prove_conax1k,
    "condan": prove_condan,
    "dedt": prove_dedt,
    "cases2": prove_cases2,
    "cases2ALT": prove_cases2ALT,
    "ccase": prove_ccase,
    "ccased": prove_ccased,
    "ccase2": prove_ccase2,
    "consensus": prove_consensus,
    "curryax": prove_curryax,
    "dedlem0a": prove_dedlem0a,
    "dedlem0b": prove_dedlem0b,
    "dedlemb": prove_dedlemb,
    "dedlema": prove_dedlema,
    "dfnan2": prove_dfnan2,
    "dfbi1": prove_dfbi1,
    "dfbi3": prove_dfbi3,
    "dfbi2": prove_dfbi2,
    "dfor2": prove_dfor2,
    "dfbi": prove_dfbi,
    "dfbi1ALT": prove_dfbi1ALT,
    "dfifp2": prove_dfifp2,
    "dfifp3": prove_dfifp3,
    "dfifp4": prove_dfifp4,
    "dfifp6": prove_dfifp6,
    "dfifp7": prove_dfifp7,
    "dfifp5": prove_dfifp5,
    "pm2.21": prove_pm2_21,
    "pm2.21d": prove_pm2_21d,
    "pm2.24": prove_pm2_24,
    "pm2.18": prove_pm2_18,
    "pm2.18d": prove_pm2_18d,
    "pm2.18da": prove_pm2_18da,
    "pm2.521": prove_pm2_521,
    "pm2.521g": prove_pm2_521g,
    "mt4i": prove_mt4i,
    "mtand": prove_mtand,
    "mtbi": prove_mtbi,
    "mtbii": prove_mtbii,
    "mtbid": prove_mtbid,
    "mtbir": prove_mtbir,
    "mtbiri": prove_mtbiri,
    "mtbird": prove_mtbird,
    "mt4d": prove_mt4d,
    "3orass": prove_3orass,
    "3orcoma": prove_3orcoma,
    "3orcomb": prove_3orcomb,
    "3ori": prove_3ori,
    "3orrot": prove_3orrot,
    "3or6": prove_3or6,
    "3orbi123i": prove_3orbi123i,
    "3orim123d": prove_3orim123d,
    "3orbi123d": prove_3orbi123d,
    "3pm3.2ni": prove_3pm3_2ni,
    "3pm3.2i": prove_3pm3_2i,
    "3orel1": prove_3orel1,
    "3orel2OLD": prove_3orel2OLD,
    "3orel2": prove_3orel2,
    "3orel3": prove_3orel3,
    "3orel13": prove_3orel13,
    "imim1": prove_imim1,
    "imim2": prove_imim2,
    "impsingle": prove_impsingle,
    "impsingle-step4": prove_impsingle_step4,
    "impsingle-step8": prove_impsingle_step8,
    "impsingle-step15": prove_impsingle_step15,
    "impsingle-step18": prove_impsingle_step18,
    "impsingle-step19": prove_impsingle_step19,
    "impsingle-step20": prove_impsingle_step20,
    "impsingle-step21": prove_impsingle_step21,
    "impsingle-step22": prove_impsingle_step22,
    "impsingle-step25": prove_impsingle_step25,
    "impsingle-imim1": prove_impsingle_imim1,
    "impsingle-peirce": prove_impsingle_peirce,
    "impsingle-ax1": prove_impsingle_ax1,
    "ja": prove_ja,
    "jao": prove_jao,
    "jaob": prove_jaob,
    "axio": prove_axio,
    "jaao": prove_jaao,
    "jaoa": prove_jaoa,
    "peirce": prove_peirce,
    "peirceroll": prove_peirceroll,
    "simplim": prove_simplim,
    "simprim": prove_simprim,
    "simplbi": prove_simplbi,
    "just1-df": prove_just1_df,
    "con1i": prove_con1i,
    "simplbi2": prove_simplbi2,
    "con2i": prove_con2i,
    "con3i": prove_con3i,
    "con2b": prove_con2b,
    "con2bi": prove_con2bi,
    "con2bid": prove_con2bid,
    "simplbi2com": prove_simplbi2com,
    "con2bii": prove_con2bii,
    "con34b": prove_con34b,
    "imdi": prove_imdi,
    "con4i": prove_con4i,
    "jarli": prove_jarli,
    "pm1.2": prove_pm1_2,
    "pm1.4": prove_pm1_4,
    "pm1.5": prove_pm1_5,
    "pm2.36": prove_pm2_36,
    "pm2.38": prove_pm2_38,
    "pm2.4": prove_pm2_4,
    "anim2d": prove_anim2d,
    "anim12d": prove_anim12d,
    "anim12d1": prove_anim12d1,
    "anim1d": prove_anim1d,
    "anim12dan": prove_anim12dan,
    "animorl": prove_animorl,
    "animorr": prove_animorr,
    "animorrl": prove_animorrl,
    "animorlr": prove_animorlr,
    "anmp": prove_anmp,
    "imim3i": prove_imim3i,
    "imor": prove_imor,
    "imori": prove_imori,
    "imimorb": prove_imimorb,
    "imorri": prove_imorri,
    "impi": prove_impi,
    "impt": prove_impt,
    "inegd": prove_inegd,
    "jad": prove_jad,
    "mpnanrd": prove_mpnanrd,
    "mptnan": prove_mptnan,
    "mt2": prove_mt2,
    "mt2d": prove_mt2d,
    "mt3i": prove_mt3i,
    "mt3d": prove_mt3d,
    "mt2i": prove_mt2i,
    "mt2bi": prove_mt2bi,
    "mtt": prove_mtt,
    "nan": prove_nan,
    "nanbi1i": prove_nanbi1i,
    "nanbi1": prove_nanbi1,
    "nanbi1d": prove_nanbi1d,
    "nanass": prove_nanass,
    "nancom": prove_nancom,
    "nanim": prove_nanim,
    "nanbi2": prove_nanbi2,
    "nanbi2i": prove_nanbi2i,
    "nanbi2d": prove_nanbi2d,
    "nanbi12": prove_nanbi12,
    "nanbi12i": prove_nanbi12i,
    "nanbi12d": prove_nanbi12d,
    "nanor": prove_nanor,
    "nanan": prove_nanan,
    "nannan": prove_nannan,
    "nic-mp": prove_nic_mp,
    "nic-mpALT": prove_nic_mp_alt,
    "nic-ax": prove_nic_ax,
    "nic-axALT": prove_nic_axALT,
    "nic-imp": prove_nic_imp,
    "nic-id": prove_nic_id,
    "nic-idlem1": prove_nic_idlem1,
    "nic-idlem2": prove_nic_idlem2,
    "nic-bi1": prove_nic_bi1,
    "nic-bi2": prove_nic_bi2,
    "nic-swap": prove_nic_swap,
    "nic-bijust": prove_nic_bijust,
    "nic-isw2": prove_nic_isw2,
    "nic-isw1": prove_nic_isw1,
    "nic-ich": prove_nic_ich,
    "nic-idbl": prove_nic_idbl,
    "nic-idel": prove_nic_idel,
    "nic-iimp1": prove_nic_iimp1,
    "nic-iimp2": prove_nic_iimp2,
    "luk-1": prove_luk_1,
    "luk-2": prove_luk_2,
    "luk-3": prove_luk_3,
    "luklem1": prove_luklem1,
    "luklem2": prove_luklem2,
    "luklem3": prove_luklem3,
    "luklem4": prove_luklem4,
    "luklem6": prove_luklem6,
    "luklem7": prove_luklem7,
    "luklem5": prove_luklem5,
    "lukshef-ax1": prove_lukshef_ax1,
    "lukshefth1": prove_lukshefth1,
    "lukshefth2": prove_lukshefth2,
    "renicax": prove_renicax,
    "nbfal": prove_nbfal,
    "nbn": prove_nbn,
    "nbn3": prove_nbn3,
    "nbn2": prove_nbn2,
    "imnot": prove_imnot,
    "mt3": prove_mt3,
    "merco1": prove_merco1,
    "retbwax4": prove_retbwax4,
    "merco1lem1": prove_merco1lem1,
    "merco1lem2": prove_merco1lem2,
    "merco1lem3": prove_merco1lem3,
    "merco1lem4": prove_merco1lem4,
    "merco1lem5": prove_merco1lem5,
    "merco1lem6": prove_merco1lem6,
    "merco1lem8": prove_merco1lem8,
    "merco1lem7": prove_merco1lem7,
    "merco1lem9": prove_merco1lem9,
    "merco1lem10": prove_merco1lem10,
    "merco1lem11": prove_merco1lem11,
    "merco1lem12": prove_merco1lem12,
    "merco1lem13": prove_merco1lem13,
    "merco1lem14": prove_merco1lem14,
    "merco1lem15": prove_merco1lem15,
    "merco1lem16": prove_merco1lem16,
    "merco1lem17": prove_merco1lem17,
    "merco2": prove_merco2,
    "mercolem1": prove_mercolem1,
    "mercolem2": prove_mercolem2,
    "mercolem3": prove_mercolem3,
    "mercolem4": prove_mercolem4,
    "mercolem5": prove_mercolem5,
    "mercolem6": prove_mercolem6,
    "mercolem7": prove_mercolem7,
    "mercolem8": prove_mercolem8,
    "meredith": prove_meredith,
    "merlem1": prove_merlem1,
    "merlem2": prove_merlem2,
    "merlem3": prove_merlem3,
    "merlem4": prove_merlem4,
    "merlem6": prove_merlem6,
    "merlem7": prove_merlem7,
    "merlem8": prove_merlem8,
    "merlem9": prove_merlem9,
    "merlem10": prove_merlem10,
    "merlem11": prove_merlem11,
    "merlem12": prove_merlem12,
    "merlem13": prove_merlem13,
    "merlem5": prove_merlem5,
    "mto": prove_mto,
    "mtod": prove_mtod,
    "mtoi": prove_mtoi,
    "mtord": prove_mtord,
    "mtpor": prove_mtpor,
    "stoic1a": prove_stoic1a,
    "stoic1b": prove_stoic1b,
    "stoic2a": prove_stoic2a,
    "stoic2b": prove_stoic2b,
    "notnotri": prove_notnotri,
    "notnotriALT": prove_notnotriALT,
    "fal": prove_fal,
    "falantru": prove_falantru,
    "falnantru": prove_falnantru,
    "falbifal": prove_falbifal,
    "falbitru": prove_falbitru,
    "bifal": prove_bifal,
    "bitru": prove_bitru,
    "tbtru": prove_tbtru,
    "falim": prove_falim,
    "falimd": prove_falimd,
    "falnorfal": prove_falnorfal,
    "falimfal": prove_falimfal,
    "falnortru": prove_falnortru,
    "falorfal": prove_falorfal,
    "falortru": prove_falortru,
    "falxorfal": prove_falxorfal,
    "falxortru": prove_falxortru,
    "truxortru": prove_truxortru,
    "truxorfal": prove_truxorfal,
    "tbw-ax4": prove_tbw_ax4,
    "tbw-bijust": prove_tbw_bijust,
    "tbw-negdf": prove_tbw_negdf,
    "dfnot": prove_dfnot,
    "dftru2": prove_dftru2,
    "dn1": prove_dn1,
    "tru": prove_tru,
    "truan": prove_truan,
    "truantru": prove_truantru,
    "truanfal": prove_truanfal,
    "falanfal": prove_falanfal,
    "trubitru": prove_trubitru,
    "trubifal": prove_trubifal,
    "trut": prove_trut,
    "truimfal": prove_truimfal,
    "truimtru": prove_truimtru,
    "trunortru": prove_trunortru,
    "trunanfal": prove_trunanfal,
    "trunorfal": prove_trunorfal,
    "truorfal": prove_truorfal,
    "truortru": prove_truortru,
    "notfal": prove_notfal,
    "nottru": prove_nottru,
    "trud": prove_trud,
    "falimtru": prove_falimtru,
    "mptru": prove_mptru,
    "pm2.65i": prove_pm2_65i,
    "pm2.65iOLD": prove_pm2_65iold,
    "2a1": prove_2a1,
    "2a1d": prove_2a1d,
    "2a1i": prove_2a1i,
    "2th": prove_2th,
    "2thd": prove_2thd,
    "2false": prove_2false,
    "2falsed": prove_2falsed,
    "ianor": prove_ianor,
    "anor": prove_anor,
    "ibd": prove_ibd,
    "ibi": prove_ibi,
    "iba": prove_iba,
    "ibar": prove_ibar,
    "ibib": prove_ibib,
    "ibibr": prove_ibibr,
    "ifpdfbi": prove_ifpdfbi,
    "ifpdfbiOLD": prove_ifpdfbiOLD,
    "ifpfal": prove_ifpfal,
    "ifpn": prove_ifpn,
    "ibir": prove_ibir,
    "idd": prove_idd,
    "jao1i": prove_jao1i,
    "jaoian": prove_jaoian,
    "jaoi": prove_jaoi,
    "jaod": prove_jaod,
    "jaoi2": prove_jaoi2,
    "jaoi3": prove_jaoi3,
    "jaodan": prove_jaodan,
    "mpdd": prove_mpdd,
    "mpjaod": prove_mpjaod,
    "mpjaodan": prove_mpjaodan,
    "mpjao3dan": prove_mpjao3dan,
    "nsyld": prove_nsyld,
    "nsyli": prove_nsyli,
    "nsyl": prove_nsyl,
    "nsyl2": prove_nsyl2,
    "nsyl3": prove_nsyl3,
    "sylnbi": prove_sylnbi,
    "sylnbir": prove_sylnbir,
    "sylnib": prove_sylnib,
    "sylnibr": prove_sylnibr,
    "pm2.32": prove_pm2_32,
    "pm2.3": prove_pm2_3,
    "pm2.31": prove_pm2_31,
    "pm2.27": prove_pm2_27,
    "pm2.43": prove_pm2_43,
    "pm2.45": prove_pm2_45,
    "pm2.46": prove_pm2_46,
    "pm2.47": prove_pm2_47,
    "pm2.48": prove_pm2_48,
    "pm2.49": prove_pm2_49,
    "pm2.6": prove_pm2_6,
    "pm2.8": prove_pm2_8,
    "pm2.61": prove_pm2_61,
    "pm2.65": prove_pm2_65,
    "syl2im": prove_syl2im,
    "imim2i": prove_imim2i,
    "impbi": prove_impbi,
    "impbii": prove_impbii,
    "impbida": prove_impbida,
    "impbid": prove_impbid,
    "impbid1": prove_impbid1,
    "impbid2": prove_impbid2,
    "impcon4bid": prove_impcon4bid,
    "xchnxbi": prove_xchnxbi,
    "xchnxbir": prove_xchnxbir,
    "xchbinx": prove_xchbinx,
    "xordi": prove_xordi,
    "anxordi": prove_anxordi,
    "xchbinxr": prove_xchbinxr,
    "xorcom": prove_xorcom,
    "xorbi12d": prove_xorbi12d,
    "xorbi12i": prove_xorbi12i,
    "xnor": prove_xnor,
    "impimprbi": prove_impimprbi,
    "con4bid": prove_con4bid,
    "con4bii": prove_con4bii,
    "impbidd": prove_impbidd,
    "pm5.1im": prove_pm5_1im,
    "pm5.1": prove_pm5_1,
    "pm5.3": prove_pm5_3,
    "pm5.35": prove_pm5_35,
    "pm5.32": prove_pm5_32,
    "pm5.31": prove_pm5_31,
    "pm5.32i": prove_pm5_32i,
    "pm5.32ri": prove_pm5_32ri,
    "pm5.33": prove_pm5_33,
    "pm5.32d": prove_pm5_32d,
    "pm5.32rd": prove_pm5_32rd,
    "pm5.32da": prove_pm5_32da,
    "pm5.36": prove_pm5_36,
    "pm5.42": prove_pm5_42,
    "pm5.44": prove_pm5_44,
    "pm5.12": prove_pm5_12,
    "pm5.6": prove_pm5_6,
    "pm5.7": prove_pm5_7,
    "pm5.61": prove_pm5_61,
    "pm5.62": prove_pm5_62,
    "pm5.63": prove_pm5_63,
    "pm5.11": prove_pm5_11,
    "pm5.71": prove_pm5_71,
    "pm5.11g": prove_pm5_11g,
    "pm5.13": prove_pm5_13,
    "pm5.14": prove_pm5_14,
    "pm5.17": prove_pm5_17,
    "pm5.53": prove_pm5_53,
    "pm5.54": prove_pm5_54,
    "pm5.55": prove_pm5_55,
    "pm5.21": prove_pm5_21,
    "pm5.21ni": prove_pm5_21ni,
    "pm5.21nii": prove_pm5_21nii,
    "pm5.21ndd": prove_pm5_21ndd,
    "pm5.21nd": prove_pm5_21nd,
    "pm5.21im": prove_pm5_21im,
    "pm5.501": prove_pm5_501,
    "pm5.4": prove_pm5_4,
    "pm5.41": prove_pm5_41,
    "pm5.5": prove_pm5_5,
    "pm5.74": prove_pm5_74,
    "pm5.74da": prove_pm5_74da,
    "pm5.74d": prove_pm5_74d,
    "pm5.74rd": prove_pm5_74rd,
    "pm5.74i": prove_pm5_74i,
    "pm5.74ri": prove_pm5_74ri,
    "pm5.75": prove_pm5_75,
    "imbi2d": prove_imbi2d,
    "imbi1": prove_imbi1,
    "imbi1i": prove_imbi1i,
    "imbi12d": prove_imbi12d,
    "imbi12i": prove_imbi12i,
    "imbi12": prove_imbi12,
    "imim21b": prove_imim21b,
    "imbi1d": prove_imbi1d,
    "imbi2i": prove_imbi2i,
    "imbibi": prove_imbibi,
    "imbibiOLD": prove_imbibiOLD,
    "imbi2": prove_imbi2,
    "impbid21d": prove_impbid21d,
    "imim12i": prove_imim12i,
    "imim1i": prove_imim1i,
    "imim1d": prove_imim1d,
    "imim2d": prove_imim2d,
    "imim12": prove_imim12,
    "imim12d": prove_imim12d,
    "embantd": prove_embantd,
    "ecase": prove_ecase,
    "ecase3": prove_ecase3,
    "ecased": prove_ecased,
    "ecase3d": prove_ecase3d,
    "ecase2d": prove_ecase2d,
    "ecase23d": prove_ecase23d,
    "efald": prove_efald,
    "exbiri": prove_exbiri,
    "exp31": prove_exp31,
    "exp32": prove_exp32,
    "exp41": prove_exp41,
    "exp42": prove_exp42,
    "3exp": prove_3exp,
    "exp43": prove_exp43,
    "exp44": prove_exp44,
    "exp45": prove_exp45,
    "3expib": prove_3expib,
    "3expd": prove_3expd,
    "3exp1": prove_3exp1,
    "3exp2": prove_3exp2,
    "expcom": prove_expcom,
    "ex": prove_ex,
    "ex3": prove_ex3,
    "expd": prove_expd,
    "expcomd": prove_expcomd,
    "expdimp": prove_expdimp,
    "expimpd": prove_expimpd,
    "exp4a": prove_exp4a,
    "exp4b": prove_exp4b,
    "exp4c": prove_exp4c,
    "exp4d": prove_exp4d,
    "exp5c": prove_exp5c,
    "expdcom": prove_expdcom,
    "exp5j": prove_exp5j,
    "exp5l": prove_exp5l,
    "exp516": prove_exp516,
    "exp520": prove_exp520,
    "exp5o": prove_exp5o,
    "exp53": prove_exp53,
    "exmid": prove_exmid,
    "exmidd": prove_exmidd,
    "expi": prove_expi,
    "syland": prove_syland,
    "syldan": prove_syldan,
    "sylan2": prove_sylan2,
    "sylan2d": prove_sylan2d,
    "sylan2i": prove_sylan2i,
    "sylan2br": prove_sylan2br,
    "sylan2b": prove_sylan2b,
    "sylan9": prove_sylan9,
    "sylan9r": prove_sylan9r,
    "sylan9bb": prove_sylan9bb,
    "sylan9bbr": prove_sylan9bbr,
    "sylani": prove_sylani,
    "syl2ani": prove_syl2ani,
    "syl2and": prove_syl2and,
    "sylancom": prove_sylancom,
    "syld": prove_syld,
    "syldc": prove_syldc,
    "syldd": prove_syldd,
    "sylsyld": prove_sylsyld,
    "tarski-bernays-ax2": prove_tarski_bernays_ax2,
    "tbt": prove_tbt,
    "tbw-ax2": prove_tbw_ax2,
    "pm2.01": prove_pm2_01,
    "tbw-ax1": prove_tbw_ax1,
    "tbwsyl": prove_tbwsyl,
    "olcs": prove_olcs,
    "tbw-ax3": prove_tbw_ax3,
    "tbwlem1": prove_tbwlem1,
    "tbwlem2": prove_tbwlem2,
    "tbwlem3": prove_tbwlem3,
    "tbwlem4": prove_tbwlem4,
    "tbwlem5": prove_tbwlem5,
    "rb-ax1": prove_rb_ax1,
    "rblem1": prove_rblem1,
    "rblem2": prove_rblem2,
    "rblem3": prove_rblem3,
    "rblem4": prove_rblem4,
    "rblem5": prove_rblem5,
    "rblem6": prove_rblem6,
    "rblem7": prove_rblem7,
    "rbsyl": prove_rbsyl,
    "re1axmp": prove_re1axmp,
    "rb-ax2": prove_rb_ax2,
    "rb-ax3": prove_rb_ax3,
    "re1luk1": prove_re1luk1,
    "re1luk2": prove_re1luk2,
    "re1luk3": prove_re1luk3,
    "re1tbw1": prove_re1tbw1,
    "re1tbw2": prove_re1tbw2,
    "re1tbw3": prove_re1tbw3,
    "re1tbw4": prove_re1tbw4,
    "re2luk1": prove_re2luk1,
    "re2luk2": prove_re2luk2,
    "re2luk3": prove_re2luk3,
    "retbwax2": prove_retbwax2,
    "retbwax3": prove_retbwax3,
    "rb-ax4": prove_rb_ax4,
    "pm2.01da": prove_pm2_01da,
    "rb-bijust": prove_rb_bijust,
    "rb-imdf": prove_rb_imdf,
    "pm2.01d": prove_pm2_01d,
    "pm2.01i": prove_pm2_01i,
    "pm2.18i": prove_pm2_18i,
    "pm2.21dd": prove_pm2_21dd,
    "pm2.21i": prove_pm2_21i,
    "pm2.24d": prove_pm2_24d,
    "pm2.24i": prove_pm2_24i,
    "pm2.24ii": prove_pm2_24ii,
    "pm2.43a": prove_pm2_43a,
    "pm2.43b": prove_pm2_43b,
    "pm2.43d": prove_pm2_43d,
    "pm2.43i": prove_pm2_43i,
    "pm2.521g2": prove_pm2_521g2,
    "pm2.53": prove_pm2_53,
    "pm2.54": prove_pm2_54,
    "pm2.61d": prove_pm2_61d,
    "pm2.61d1": prove_pm2_61d1,
    "pm2.61ian": prove_pm2_61ian,
    "pm2.61i": prove_pm2_61i,
    "nsyl5": prove_nsyl5,
    "nsyl4": prove_nsyl4,
    "norbi": prove_norbi,
    "norcom": prove_norcom,
    "norass": prove_norass,
    "noror": prove_noror,
    "nornot": prove_nornot,
    "noran": prove_noran,
    "norasslem1": prove_norasslem1,
    "norasslem2": prove_norasslem2,
    "norasslem3": prove_norasslem3,
    "oibabs": prove_oibabs,
    "nbior": prove_nbior,
    "jarl": prove_jarl,
    "jarr": prove_jarr,
    "minimp": prove_minimp,
    "minimp-syllsimp": prove_minimp_syllsimp,
    "minimp-ax1": prove_minimp_ax1,
    "minimp-ax2": prove_minimp_ax2,
    "minimp-ax2c": prove_minimp_ax2c,
    "minimp-pm2.43": prove_minimp_pm2_43,
    "loolin": prove_loolin,
    "loowoz": prove_loowoz,
    "looinv": prove_looinv,
    "mpdi": prove_mpdi,
    "mt4": prove_mt4,
    "pm2.04": prove_pm2_04,
    "pm2.07": prove_pm2_07,
    "pm2.37": prove_pm2_37,
    "pm2.42": prove_pm2_42,
    "pm2.41": prove_pm2_41,
    "syl11": prove_syl11,
    "syl2imc": prove_syl2imc,
    "syl56": prove_syl56,
    "syl6c": prove_syl6c,
    "syl6ci": prove_syl6ci,
    "syl6d": prove_syl6d,
    "syl6com": prove_syl6com,
    "syli": prove_syli,
    "com13": prove_com13,
    "com23": prove_com23,
    "com3r": prove_com3r,
    "com3l": prove_com3l,
    "com34": prove_com34,
    "com45": prove_com45,
    "com35": prove_com35,
    "com4l": prove_com4l,
    "com4t": prove_com4t,
    "com4r": prove_com4r,
    "com5l": prove_com5l,
    "com52l": prove_com52l,
    "com14": prove_com14,
    "com15": prove_com15,
    "com52r": prove_com52r,
    "com5r": prove_com5r,
    "com24": prove_com24,
    "com25": prove_com25,
    "jarri": prove_jarri,
    "jc": prove_jc,
    "jca": prove_jca,
    "jcai": prove_jcai,
    "jcab": prove_jcab,
    "jccir": prove_jccir,
    "jccil": prove_jccil,
    "jctil": prove_jctil,
    "jctl": prove_jctl,
    "jctir": prove_jctir,
    "jctr": prove_jctr,
    "jcad": prove_jcad,
    "jctild": prove_jctild,
    "jca2": prove_jca2,
    "jca32": prove_jca32,
    "jca31": prove_jca31,
    "jctird": prove_jctird,
    "jcn": prove_jcn,
    "jcnd": prove_jcnd,
    "pm2.1": prove_pm2_1,
    "pm2.13": prove_pm2_13,
    "pm2.21ddALT": prove_pm2_21ddALT,
    "pm2.21fal": prove_pm2_21fal,
    "pm2.25": prove_pm2_25,
    "pm2.26": prove_pm2_26,
    "pm2.5": prove_pm2_5,
    "pm2.5g": prove_pm2_5g,
    "pm2.51": prove_pm2_51,
    "pm2.52": prove_pm2_52,
    "pm2.61d2": prove_pm2_61d2,
    "pm2.61ii": prove_pm2_61ii,
    "pm2.61iii": prove_pm2_61iii,
    "pm2.61nii": prove_pm2_61nii,
    "pm2.62": prove_pm2_62,
    "pm2.621": prove_pm2_621,
    "pm2.63": prove_pm2_63,
    "pm2.64": prove_pm2_64,
    "pm2.65d": prove_pm2_65d,
    "pm2.65da": prove_pm2_65da,
    "pm2.65ni": prove_pm2_65ni,
    "pm2.67": prove_pm2_67,
    "pm2.67-2": prove_pm2_67_2,
    "pm2.68": prove_pm2_68,
    "pm2.73": prove_pm2_73,
    "pm2.74": prove_pm2_74,
    "pm2.75": prove_pm2_75,
    "pm2.76": prove_pm2_76,
    "pm2.81": prove_pm2_81,
    "pm2.82": prove_pm2_82,
    "pm2.83": prove_pm2_83,
    "pm2.85": prove_pm2_85,
    "pm2.86": prove_pm2_86,
    "pm2.86d": prove_pm2_86d,
    "pm2.86i": prove_pm2_86i,
    "pm3.11": prove_pm3_11,
    "pm3.12": prove_pm3_12,
    "pm3.13": prove_pm3_13,
    "pm3.14": prove_pm3_14,
    "olc": prove_olc,
    "olcnd": prove_olcnd,
    "orcnd": prove_orcnd,
    "or12": prove_or12,
    "orass": prove_orass,
    "orc": prove_orc,
    "orcs": prove_orcs,
    "oridm": prove_oridm,
    "orim12i": prove_orim12i,
    "orimdi": prove_orimdi,
    "orordi": prove_orordi,
    "orordir": prove_orordir,
    "orim1i": prove_orim1i,
    "orim1d": prove_orim1d,
    "orim12dALT": prove_orim12dALT,
    "orim12d": prove_orim12d,
    "orim12da": prove_orim12da,
    "orim2i": prove_orim2i,
    "orim2d": prove_orim2d,
    "orbi2i": prove_orbi2i,
    "orim2": prove_orim2,
    "orbi2d": prove_orbi2d,
    "orbi1d": prove_orbi1d,
    "orbi1": prove_orbi1,
    "orbi12i": prove_orbi12i,
    "orbi12d": prove_orbi12d,
    "orbidi": prove_orbidi,
    "orbi1i": prove_orbi1i,
    "olci": prove_olci,
    "orel1": prove_orel1,
    "ordi": prove_ordi,
    "ordir": prove_ordir,
    "orddi": prove_orddi,
    "ord": prove_ord,
    "orcanai": prove_orcanai,
    "orrd": prove_orrd,
    "or32": prove_or32,
    "or42": prove_or42,
    "or4": prove_or4,
    "ori": prove_ori,
    "oranabs": prove_oranabs,
    "oran": prove_oran,
    "orabs": prove_orabs,
    "pm4.45": prove_pm4_45,
    "orci": prove_orci,
    "orcd": prove_orcd,
    "olcd": prove_olcd,
    "orcom": prove_orcom,
    "orcomd": prove_orcomd,
    "orcoms": prove_orcoms,
    "orri": prove_orri,
    "orel2": prove_orel2,
    "pm3.2im": prove_pm3_2im,
    "pm3.1": prove_pm3_1,
    "pm3.2ni": prove_pm3_2ni,
    "pm3.2an3": prove_pm3_2an3,
    "pm3.2": prove_pm3_2,
    "pm3.21": prove_pm3_21,
    "pm3.22": prove_pm3_22,
    "pm3.24": prove_pm3_24,
    "pm3.2i": prove_pm3_2i,
    "pm3.43i": prove_pm3_43i,
    "pm3.43": prove_pm3_43,
    "pm3.45": prove_pm3_45,
    "pm3.44": prove_pm3_44,
    "pm3.48": prove_pm3_48,
    "pm3.3": prove_pm3_3,
    "pm3.33": prove_pm3_33,
    "pm3.34": prove_pm3_34,
    "pm3.4": prove_pm3_4,
    "pm3.35": prove_pm3_35,
    "pm3.41": prove_pm3_41,
    "pm3.42": prove_pm3_42,
    "pm3.37": prove_pm3_37,
    "pm3.31": prove_pm3_31,
    "pm4.14": prove_pm4_14,
    "pm4.15": prove_pm4_15,
    "pm4.25": prove_pm4_25,
    "pm4.42": prove_pm4_42,
    "pm4.43": prove_pm4_43,
    "pm4.44": prove_pm4_44,
    "pm4.62": prove_pm4_62,
    "pm4.63": prove_pm4_63,
    "pm4.67": prove_pm4_67,
    "pm4.71": prove_pm4_71,
    "pm4.24": prove_pm4_24,
    "pm4.38": prove_pm4_38,
    "pm4.71i": prove_pm4_71i,
    "pm4.45im": prove_pm4_45im,
    "pm4.71ri": prove_pm4_71ri,
    "pm4.71rd": prove_pm4_71rd,
    "pm4.71d": prove_pm4_71d,
    "pm4.71da": prove_pm4_71da,
    "pm4.71r": prove_pm4_71r,
    "pm4.76": prove_pm4_76,
    "pm4.82": prove_pm4_82,
    "pm4.77": prove_pm4_77,
    "pm4.72": prove_pm4_72,
    "pm4.78": prove_pm4_78,
    "pm4.79": prove_pm4_79,
    "pm4.83": prove_pm4_83,
    "pm4.87": prove_pm4_87,
    "pm4.52": prove_pm4_52,
    "pm4.53": prove_pm4_53,
    "pm4.54": prove_pm4_54,
    "pm4.55": prove_pm4_55,
    "pm4.56": prove_pm4_56,
    "pm4.57": prove_pm4_57,
    "pm4.61": prove_pm4_61,
    "pm4.65": prove_pm4_65,
    "pm4.64": prove_pm4_64,
    "pm4.66": prove_pm4_66,
    "pm4.8": prove_pm4_8,
    "pm4.81": prove_pm4_81,
    "prlem1": prove_prlem1,
    "prlem2": prove_prlem2,
    "expt": prove_expt,
    "exptOLD": prove_exptOLD,
    "syl9": prove_syl9,
    "syl9r": prove_syl9r,
    "oplem1": prove_oplem1,
    "syl10": prove_syl10,
    "ax3": prove_ax3,
    "axia1": prove_axia1,
    "axia2": prove_axia2,
    "axia3": prove_axia3,
}


def _merge_migration_registries() -> Mapping[str, LemmaCtor]:
    merged = dict(_LEGACY_HILBERT_LEMMAS)
    registries = (
        IMPLICATION_MIGRATIONS,
        NEGATION_MIGRATIONS,
        EQUIVALENCE_MIGRATIONS,
        CONJUNCTION_MIGRATIONS,
        DISJUNCTION_MIGRATIONS,
        CONSTANT_MIGRATIONS,
    )
    for registry in registries:
        duplicates = merged.keys() & registry.keys()
        if duplicates:
            raise RuntimeError(f"duplicate Hilbert theorem registrations: {sorted(duplicates)}")
        merged.update(registry)
    return merged


SETMM_TO_HILBERT_LEMMAS = _merge_migration_registries()


__all__ = ["LemmaCtor", "SETMM_TO_HILBERT_LEMMAS"]
