from __future__ import annotations

from collections.abc import Callable, Mapping

from . import System
from .lemmas import (
    Proof,
    prove_a1d,
    prove_a1i,
    prove_a2d,
    prove_a2i,
    prove_com12,
    prove_con1,
    prove_con1d,
    prove_con1i,
    prove_con2,
    prove_con2d,
    prove_con2i,
    prove_con3,
    prove_con3d,
    prove_con3i,
    prove_con4,
    prove_con4d,
    prove_con4i,
    prove_conax1,
    prove_id,
    prove_imim1,
    prove_imim2,
    prove_ja,
    prove_jarli,
    prove_mpd,
    prove_mt4d,
    prove_notnot,
    prove_notnotr,
    prove_pm1_4,
    prove_pm2_18,
    prove_pm2_18d,
    prove_pm2_21,
    prove_pm2_21d,
    prove_pm2_24,
    prove_pm2_36,
    prove_pm2_38,
    prove_pm2_521,
    prove_pm2_521g,
    prove_simplim,
    prove_syl,
    prove_syl5,
    prove_syl5com,
    prove_syl6,
    prove_sylcom,
    prove_2a1d,
    prove_idd,
    prove_jaoi,
    prove_mpdd,
    prove_nsyl3,
    prove_pm2_27,
    prove_pm2_43,
    prove_pm2_45,
    prove_pm2_46,
    prove_pm2_6,
    prove_pm2_61,
    prove_pm2_65,
    prove_syl2im,
    prove_imim3i,
    prove_jad,
    prove_mt2d,
    prove_mto,
    prove_notnotri,
    prove_pm2_65i,
)


LemmaCtor = Callable[[System], Proof]


SETMM_TO_HILBERT_LEMMAS: Mapping[str, LemmaCtor] = {
    "id": prove_id,
    "notnot": prove_notnot,
    "notnotr": prove_notnotr,
    "a1i": prove_a1i,
    "a2i": prove_a2i,
    "mpd": prove_mpd,
    "syl": prove_syl,
    "sylcom": prove_sylcom,
    "com12": prove_com12,
    "syl5": prove_syl5,
    "syl6": prove_syl6,
    "a1d": prove_a1d,
    "a2d": prove_a2d,
    "syl5com": prove_syl5com,
    "con1": prove_con1,
    "con1d": prove_con1d,
    "con2": prove_con2,
    "con2d": prove_con2d,
    "con3": prove_con3,
    "con3d": prove_con3d,
    "con4": prove_con4,
    "con4d": prove_con4d,
    "conax1": prove_conax1,
    "pm2.21": prove_pm2_21,
    "pm2.21d": prove_pm2_21d,
    "pm2.24": prove_pm2_24,
    "pm2.18": prove_pm2_18,
    "pm2.18d": prove_pm2_18d,
    "pm2.521": prove_pm2_521,
    "pm2.521g": prove_pm2_521g,
    "mt4d": prove_mt4d,
    "imim1": prove_imim1,
    "imim2": prove_imim2,
    "ja": prove_ja,
    "simplim": prove_simplim,
    "con1i": prove_con1i,
    "con2i": prove_con2i,
    "con3i": prove_con3i,
    "con4i": prove_con4i,
    "jarli": prove_jarli,
    "pm1.4": prove_pm1_4,
    "pm2.36": prove_pm2_36,
    "pm2.38": prove_pm2_38,
    "imim3i": prove_imim3i,
    "jad": prove_jad,
    "mt2d": prove_mt2d,
    "mto": prove_mto,
    "notnotri": prove_notnotri,
    "pm2.65i": prove_pm2_65i,
    "2a1d": prove_2a1d,
    "idd": prove_idd,
    "jaoi": prove_jaoi,
    "mpdd": prove_mpdd,
    "nsyl3": prove_nsyl3,
    "pm2.27": prove_pm2_27,
    "pm2.43": prove_pm2_43,
    "pm2.45": prove_pm2_45,
    "pm2.46": prove_pm2_46,
    "pm2.6": prove_pm2_6,
    "pm2.61": prove_pm2_61,
    "pm2.65": prove_pm2_65,
    "syl2im": prove_syl2im,
}


__all__ = ["LemmaCtor", "SETMM_TO_HILBERT_LEMMAS"]
