# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from metamath_setmm_provider.shards.s013 import (
    axbnd as axbnd,
)
from metamath_setmm_provider.shards.s013 import (
    axi4 as axi4,
)
from metamath_setmm_provider.shards.s013 import (
    axi5r as axi5r,
)
from metamath_setmm_provider.shards.s013 import (
    axi9 as axi9,
)
from metamath_setmm_provider.shards.s013 import (
    axi10 as axi10,
)
from metamath_setmm_provider.shards.s013 import (
    axi12 as axi12,
)
from metamath_setmm_provider.shards.s013 import (
    axia1 as axia1,
)
from metamath_setmm_provider.shards.s013 import (
    axia2 as axia2,
)
from metamath_setmm_provider.shards.s013 import (
    axia3 as axia3,
)
from metamath_setmm_provider.shards.s013 import (
    axial as axial,
)
from metamath_setmm_provider.shards.s013 import (
    axie1 as axie1,
)
from metamath_setmm_provider.shards.s013 import (
    axie2 as axie2,
)
from metamath_setmm_provider.shards.s013 import (
    axin1 as axin1,
)
from metamath_setmm_provider.shards.s013 import (
    axin2 as axin2,
)
from metamath_setmm_provider.shards.s013 import (
    axio as axio,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.theory import TheoryProofAuthor

if str(axia1.id) != (
    'urn:uuid:b9704c5d-597c-555e-80ce-d731612b1474'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axia2.id) != (
    'urn:uuid:bb5655f3-07f6-5e4b-a454-44e851fce878'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axia3.id) != (
    'urn:uuid:9e2d581a-02cd-54cc-8c97-23efd32a8096'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axin1.id) != (
    'urn:uuid:c9cc7378-521c-5c18-96d5-0b83d6222738'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axin2.id) != (
    'urn:uuid:0b4af11d-d603-5051-963c-25cf1ca4db98'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axio.id) != (
    'urn:uuid:c28d4961-1cd6-5f96-978f-a7589f185d72'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axi4.id) != (
    'urn:uuid:50d790ad-f70b-54d4-bbc2-4430e18dd989'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axi5r.id) != (
    'urn:uuid:13c490a0-164a-5ac8-a511-df3b7a5d414a'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axial.id) != (
    'urn:uuid:3b2bf90b-440d-5142-ae76-cde83c8b102c'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axie1.id) != (
    'urn:uuid:439cb7b7-6da5-5bbd-a3ac-0410774f4709'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axie2.id) != (
    'urn:uuid:265563a3-2c3a-583a-9589-018c1de81e40'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axi9.id) != (
    'urn:uuid:462dd89e-6295-5ae5-b26c-80f00d009fac'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axi10.id) != (
    'urn:uuid:144b09aa-2008-51b4-9b97-8a27a4d773d2'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axi12.id) != (
    'urn:uuid:00ede682-6af9-5769-a8e9-6fd78301b280'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axbnd.id) != (
    'urn:uuid:0da1812e-0859-5cd5-8647-3e3a084e814b'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@axia1.proof
def prove_axia1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpl


    _step_1 = proof.use(simpl, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ph)
    return proof.qed(_step_1)


@axia2.proof
def prove_axia2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import simpr


    _step_1 = proof.use(simpr, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wa(ph, ps), ps)
    return proof.qed(_step_1)


@axia3.proof
def prove_axia3(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s002 import pm3_2


    _step_1 = proof.use(pm3_2, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(ph, wi(ps, wa(ph, ps)))
    return proof.qed(_step_1)


@axin1.proof
def prove_axin1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_01


    _step_1 = proof.use(pm2_01, subst={"ph": "ph"})  # ⊢ wi(wi(ph, wn(ph)), wn(ph))
    return proof.qed(_step_1)


@axin2.proof
def prove_axin2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_21


    _step_1 = proof.use(pm2_21, subst={"ph": "ph", "ps": "ps"})  # ⊢ wi(wn(ph), wi(ph, ps))
    return proof.qed(_step_1)


@axio.proof
def prove_axio(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s004 import jaob


    _step_1 = proof.use(
        jaob,
        subst={
            "ph": "ph",
            "ps": "ps",
            "ch": "ch",
        },
    )  # ⊢ wb(wi(wo(ph, ch), ps), wa(wi(ph, ps), wi(ch, ps)))
    return proof.qed(_step_1)


@axi4.proof
def prove_axi4(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s011 import sp


    _step_1 = proof.use(sp, subst={"ph": "ph", "x": "x"})  # ⊢ wi(wal(ph, x), ph)
    return proof.qed(_step_1)


@axi5r.proof
def prove_axi5r(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import imim2i
    from metamath_setmm_provider.shards.s009 import alrimih
    from metamath_setmm_provider.shards.s011 import hba1, hbim, sp


    _step_1 = proof.use(hba1, subst={"ph": "ph", "x": "x"})  # ⊢ wi(wal(ph, x), wal(wal(ph, x), x))
    _step_2 = proof.use(hba1, subst={"ph": "ps", "x": "x"})  # ⊢ wi(wal(ps, x), wal(wal(ps, x), x))
    _step_3 = proof.use(
        hbim,
        _step_1,
        _step_2,
    )  # ⊢ wi(wi(wal(ph, x), wal(ps, x)), wal(wi(wal(ph, x), wal(ps, x)), x))
    _step_4 = proof.use(sp, subst={"ph": "ps", "x": "x"})  # ⊢ wi(wal(ps, x), ps)
    _step_5 = proof.use(
        imim2i,
        _step_4,
        subst={
            "ch": "wal(ph, x)",
        },
    )  # ⊢ wi(wi(wal(ph, x), wal(ps, x)), wi(wal(ph, x), ps))
    _step_6 = proof.use(
        alrimih,
        _step_3,
        _step_5,
    )  # ⊢ wi(wi(wal(ph, x), wal(ps, x)), wal(wi(wal(ph, x), ps), x))
    return proof.qed(_step_6)


@axial.proof
def prove_axial(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s011 import hba1


    _step_1 = proof.use(hba1, subst={"ph": "ph", "x": "x"})  # ⊢ wi(wal(ph, x), wal(wal(ph, x), x))
    return proof.qed(_step_1)


@axie1.proof
def prove_axie1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s010 import hbe1


    _step_1 = proof.use(hbe1, subst={"ph": "ph", "x": "x"})  # ⊢ wi(wex(ph, x), wal(wex(ph, x), x))
    return proof.qed(_step_1)


@axie2.proof
def prove_axie2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import sylbir
    from metamath_setmm_provider.shards.s011 import mm_19_23t, nf5


    _step_1 = proof.use(
        nf5,
        subst={
            "ph": "ps",
            "x": "x",
        },
    )  # ⊢ wb(wnf(ps, x), wal(wi(ps, wal(ps, x)), x))
    _step_2 = proof.use(
        mm_19_23t,
        subst={
            "ph": "ph",
            "ps": "ps",
            "x": "x",
        },
    )  # ⊢ wi(wnf(ps, x), wb(wal(wi(ph, ps), x), wi(wex(ph, x), ps)))
    _step_3 = proof.use(
        sylbir,
        _step_1,
        _step_2,
    )  # ⊢ wi(wal(wi(ps, wal(ps, x)), x), wb(wal(wi(ph, ps), x), wi(wex(ph, x), ps)))
    return proof.qed(_step_3)


@axi9.proof
def prove_axi9(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s012 import ax6e


    _step_1 = proof.use(ax6e, subst={"x": "x", "y": "y"})  # ⊢ wex(wceq(cv(x), cv(y)), x)
    return proof.qed(_step_1)


@axi10.proof
def prove_axi10(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s012 import axc11n


    _step_1 = proof.use(
        axc11n,
        subst={
            "x": "x",
            "y": "y",
        },
    )  # ⊢ wi(wal(wceq(cv(x), cv(y)), x), wal(wceq(cv(y), cv(x)), y))
    return proof.qed(_step_1)


@axi12.proof
def prove_axi12(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import mpbi, mpbir
    from metamath_setmm_provider.shards.s004 import orass, orrd, orri
    from metamath_setmm_provider.shards.s009 import mpgbi, nfor
    from metamath_setmm_provider.shards.s010 import nfa1
    from metamath_setmm_provider.shards.s011 import mm_19_32
    from metamath_setmm_provider.shards.s012 import axc9


    _step_1 = proof.use(
        nfa1,
        subst={
            "ph": "wceq(cv(z), cv(x))",
            "x": "z",
        },
    )  # ⊢ wnf(wal(wceq(cv(z), cv(x)), z), z)
    _step_2 = proof.use(
        nfa1,
        subst={
            "ph": "wceq(cv(z), cv(y))",
            "x": "z",
        },
    )  # ⊢ wnf(wal(wceq(cv(z), cv(y)), z), z)
    _step_3 = proof.use(
        nfor,
        _step_1,
        _step_2,
    )  # ⊢ wnf(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), z)
    _step_4 = proof.use(
        mm_19_32,
        _step_3,
        subst={
            "ps": "wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z))",
        },
    )  # ⊢ wb(wal(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wi(wceq(cv(x), cv(…
    _step_5 = proof.use(
        axc9,
        subst={
            "x": "x",
            "y": "y",
            "z": "z",
        },
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(x)), z)), wi(wn(wal(wceq(cv(z), cv(y)), z)), wi(wceq(cv(x), cv(…
    _step_6 = proof.use(
        orrd,
        _step_5,
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(x)), z)), wo(wal(wceq(cv(z), cv(y)), z), wi(wceq(cv(x), cv(y)),…
    _step_7 = proof.use(
        orri,
        _step_6,
    )  # ⊢ wo(wal(wceq(cv(z), cv(x)), z), wo(wal(wceq(cv(z), cv(y)), z), wi(wceq(cv(x), cv(y)), wal…
    _step_8 = proof.use(
        orass,
        subst={
            "ph": "wal(wceq(cv(z), cv(x)), z)",
            "ps": "wal(wceq(cv(z), cv(y)), z)",
            "ch": "wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z))",
        },
    )  # ⊢ wb(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wi(wceq(cv(x), cv(y)),…
    _step_9 = proof.use(
        mpbir,
        _step_7,
        _step_8,
    )  # ⊢ wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wi(wceq(cv(x), cv(y)), wa…
    _step_10 = proof.use(
        mpgbi,
        _step_4,
        _step_9,
    )  # ⊢ wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x), cv(y))…
    _step_11 = proof.use(
        orass,
        subst={
            "ph": "wal(wceq(cv(z), cv(x)), z)",
            "ps": "wal(wceq(cv(z), cv(y)), z)",
            "ch": "wal(wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z)), z)",
        },
    )  # ⊢ wb(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x), cv(…
    _step_12 = proof.use(
        mpbi,
        _step_10,
        _step_11,
    )  # ⊢ wo(wal(wceq(cv(z), cv(x)), z), wo(wal(wceq(cv(z), cv(y)), z), wal(wi(wceq(cv(x), cv(y)),…
    return proof.qed(_step_12)


@axbnd.proof
def prove_axbnd(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bitri, mpbir
    from metamath_setmm_provider.shards.s004 import orass
    from metamath_setmm_provider.shards.s009 import mpgbi, nfor
    from metamath_setmm_provider.shards.s011 import mm_19_32
    from metamath_setmm_provider.shards.s012 import nfae


    _step_1 = proof.use(
        nfae,
        subst={
            "x": "z",
            "y": "x",
            "z": "x",
        },
    )  # ⊢ wnf(wal(wceq(cv(z), cv(x)), z), x)
    _step_2 = proof.use(
        nfae,
        subst={
            "x": "z",
            "y": "y",
            "z": "x",
        },
    )  # ⊢ wnf(wal(wceq(cv(z), cv(y)), z), x)
    _step_3 = proof.use(
        nfor,
        _step_1,
        _step_2,
    )  # ⊢ wnf(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), x)
    _step_4 = proof.use(
        mm_19_32,
        _step_3,
        subst={
            "ps": "wal(wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z)), z)",
        },
    )  # ⊢ wb(wal(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x),…
    _step_5 = proof.use(
        orass,
        subst={
            "ph": "wal(wceq(cv(z), cv(x)), z)",
            "ps": "wal(wceq(cv(z), cv(y)), z)",
            "ch": "wal(wal(wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z)), z), x)",
        },
    )  # ⊢ wb(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wal(wi(wceq(cv(x),…
    _step_6 = proof.use(
        bitri,
        _step_4,
        _step_5,
    )  # ⊢ wb(wal(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x),…
    _step_7 = proof.use(
        axi12,
        subst={
            "x": "x",
            "y": "y",
            "z": "z",
        },
    )  # ⊢ wo(wal(wceq(cv(z), cv(x)), z), wo(wal(wceq(cv(z), cv(y)), z), wal(wi(wceq(cv(x), cv(y)),…
    _step_8 = proof.use(
        orass,
        subst={
            "ph": "wal(wceq(cv(z), cv(x)), z)",
            "ps": "wal(wceq(cv(z), cv(y)), z)",
            "ch": "wal(wi(wceq(cv(x), cv(y)), wal(wceq(cv(x), cv(y)), z)), z)",
        },
    )  # ⊢ wb(wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x), cv(…
    _step_9 = proof.use(
        mpbir,
        _step_7,
        _step_8,
    )  # ⊢ wo(wo(wal(wceq(cv(z), cv(x)), z), wal(wceq(cv(z), cv(y)), z)), wal(wi(wceq(cv(x), cv(y))…
    _step_10 = proof.use(
        mpgbi,
        _step_6,
        _step_9,
    )  # ⊢ wo(wal(wceq(cv(z), cv(x)), z), wo(wal(wceq(cv(z), cv(y)), z), wal(wal(wi(wceq(cv(x), cv(…
    return proof.qed(_step_10)

__all__ = (
    'axia1',
    'axia2',
    'axia3',
    'axin1',
    'axin2',
    'axio',
    'axi4',
    'axi5r',
    'axial',
    'axie1',
    'axie2',
    'axi9',
    'axi10',
    'axi12',
    'axbnd',
)
