# GENERATED by mm-transpiler.
from __future__ import annotations

from collections.abc import Callable, Mapping

from skfd.proof import Proof

from logic.prop._system import (
    SETMM_TO_HILBERT_AXIOMS,
    SETMM_TO_HILBERT_RULES,
    System,
    _extend_names,
    make,
)
from logic.prop.axiom_systems import THEOREMS as MODULE_8_THEOREMS
from logic.prop.circuits import THEOREMS as MODULE_7_THEOREMS
from logic.prop.conjunction import THEOREMS as MODULE_2_THEOREMS
from logic.prop.conjunction_inference import THEOREMS as MODULE_3_THEOREMS
from logic.prop.connectives import THEOREMS as MODULE_4_THEOREMS
from logic.prop.core import THEOREMS as MODULE_0_THEOREMS
from logic.prop.equivalence import THEOREMS as MODULE_1_THEOREMS
from logic.prop.ternary import THEOREMS as MODULE_5_THEOREMS
from logic.prop.ternary_inference import THEOREMS as MODULE_6_THEOREMS

LemmaCtor = Callable[..., Proof]


def _all_theorems() -> Mapping[str, LemmaCtor]:
    merged: dict[str, LemmaCtor] = {}
    for registry in (
        MODULE_0_THEOREMS, MODULE_1_THEOREMS, MODULE_2_THEOREMS,
        MODULE_3_THEOREMS, MODULE_4_THEOREMS, MODULE_5_THEOREMS,
        MODULE_6_THEOREMS, MODULE_7_THEOREMS, MODULE_8_THEOREMS,
    ):
        for label, ctor in registry.items():
            previous = merged.get(label)
            if previous is not None and previous is not ctor:
                raise ValueError(f"duplicate theorem label {label!r}")
            merged[label] = ctor
    return merged


THEOREMS = _all_theorems()

__all__ = [
    "SETMM_TO_HILBERT_AXIOMS",
    "SETMM_TO_HILBERT_RULES",
    "System",
    "THEOREMS",
    "_extend_names",
    "make",
]
