# GENERATED by mm-transpiler from replayed set.mm proofs.
from __future__ import annotations

from collections.abc import Callable, Mapping

from skfd.proof import Proof, ProofBuilder

from logic.prop._system import System

LemmaCtor = Callable[[System], Proof]


def prove_ad5ant2345(sys: System) -> Proof:
    """Deduction adding conjuncts to antecedent.  (Contributed by Alan Sare,
    17-Oct-2017.)
    """
    lb = ProofBuilder(sys, "ad5ant2345")
    h1 = lb.hyp("ad5ant2345.1", "( ( ( ( φ ∧ ψ ) ∧ χ ) ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → ( ψ → ( χ → ( θ → τ ) ) ) )", h1, ref="exp41", note="exp41")
    s2 = lb.ref("s2", "( ( η ∧ φ ) → ( ψ → ( χ → ( θ → τ ) ) ) )", s1, ref="adantl", note="adantl")
    res = lb.ref("res", "( ( ( ( ( η ∧ φ ) ∧ ψ ) ∧ χ ) ∧ θ ) → τ )", s2, ref="imp41", note="imp41")
    return lb.build(res)

def prove_syl3anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl3anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3anc.4", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ∧ θ ) )", h1, h2, h3, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → τ )", s1, h4, ref="syl", note="syl")
    return lb.build(res)

def prove_syl13anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl13anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl13anc.5", "( ( ψ ∧ ( χ ∧ θ ∧ τ ) ) → η )")
    s1 = lb.ref("s1", "( φ → ( χ ∧ θ ∧ τ ) )", h2, h3, h4, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → η )", h1, s1, h5, ref="syl2anc", note="syl2anc")
    return lb.build(res)

def prove_syl31anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl31anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl31anc.5", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ) → η )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ∧ θ ) )", h1, h2, h3, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → η )", s1, h4, h5, ref="syl2anc", note="syl2anc")
    return lb.build(res)

def prove_syl112anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl112anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl112anc.5", "( ( ψ ∧ χ ∧ ( θ ∧ τ ) ) → η )")
    s1 = lb.ref("s1", "( φ → ( θ ∧ τ ) )", h3, h4, ref="jca", note="jca")
    res = lb.ref("res", "( φ → η )", h1, h2, s1, h5, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl121anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl121anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl121anc.5", "( ( ψ ∧ ( χ ∧ θ ) ∧ τ ) → η )")
    s1 = lb.ref("s1", "( φ → ( χ ∧ θ ) )", h2, h3, ref="jca", note="jca")
    res = lb.ref("res", "( φ → η )", h1, s1, h4, h5, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl211anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl211anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl211anc.5", "( ( ( ψ ∧ χ ) ∧ θ ∧ τ ) → η )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ) )", h1, h2, ref="jca", note="jca")
    res = lb.ref("res", "( φ → η )", s1, h3, h4, h5, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl23anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl23anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl23anc.6", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ) )", h1, h2, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ζ )", s1, h3, h4, h5, h6, ref="syl13anc", note="syl13anc")
    return lb.build(res)

def prove_syl32anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl32anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl32anc.6", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ) ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ) )", h4, h5, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ζ )", h1, h2, h3, s1, h6, ref="syl31anc", note="syl31anc")
    return lb.build(res)

def prove_syl122anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl122anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl122anc.6", "( ( ψ ∧ ( χ ∧ θ ) ∧ ( τ ∧ η ) ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ) )", h4, h5, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ζ )", h1, h2, h3, s1, h6, ref="syl121anc", note="syl121anc")
    return lb.build(res)

def prove_syl212anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl212anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl212anc.6", "( ( ( ψ ∧ χ ) ∧ θ ∧ ( τ ∧ η ) ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ) )", h4, h5, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ζ )", h1, h2, h3, s1, h6, ref="syl211anc", note="syl211anc")
    return lb.build(res)

def prove_syl221anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl221anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl221anc.6", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ) ∧ η ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( θ ∧ τ ) )", h3, h4, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ζ )", h1, h2, s1, h5, h6, ref="syl211anc", note="syl211anc")
    return lb.build(res)

def prove_syl113anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl113anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl113anc.6", "( ( ψ ∧ χ ∧ ( θ ∧ τ ∧ η ) ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( θ ∧ τ ∧ η ) )", h3, h4, h5, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ζ )", h1, h2, s1, h6, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl131anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl131anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl131anc.6", "( ( ψ ∧ ( χ ∧ θ ∧ τ ) ∧ η ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( χ ∧ θ ∧ τ ) )", h2, h3, h4, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ζ )", h1, s1, h5, h6, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl311anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl311anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl311anc.6", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ∧ η ) → ζ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ∧ θ ) )", h1, h2, h3, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ζ )", s1, h4, h5, h6, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl33anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl33anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl33anc.7", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ∧ θ ) )", h1, h2, h3, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → σ )", s1, h4, h5, h6, h7, ref="syl13anc", note="syl13anc")
    return lb.build(res)

def prove_syl222anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl222anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl222anc.7", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ) ∧ ( η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( η ∧ ζ ) )", h5, h6, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", h1, h2, h3, h4, s1, h7, ref="syl221anc", note="syl221anc")
    return lb.build(res)

def prove_syl123anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl123anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl123anc.7", "( ( ψ ∧ ( χ ∧ θ ) ∧ ( τ ∧ η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( χ ∧ θ ) )", h2, h3, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", h1, s1, h4, h5, h6, h7, ref="syl113anc", note="syl113anc")
    return lb.build(res)

def prove_syl132anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Jul-2012.)
    """
    lb = ProofBuilder(sys, "syl132anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl132anc.7", "( ( ψ ∧ ( χ ∧ θ ∧ τ ) ∧ ( η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( η ∧ ζ ) )", h5, h6, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", h1, h2, h3, h4, s1, h7, ref="syl131anc", note="syl131anc")
    return lb.build(res)

def prove_syl213anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl213anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl213anc.7", "( ( ( ψ ∧ χ ) ∧ θ ∧ ( τ ∧ η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ) )", h1, h2, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", s1, h3, h4, h5, h6, h7, ref="syl113anc", note="syl113anc")
    return lb.build(res)

def prove_syl231anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl231anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl231anc.7", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ∧ ζ ) → σ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ) )", h1, h2, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", s1, h3, h4, h5, h6, h7, ref="syl131anc", note="syl131anc")
    return lb.build(res)

def prove_syl312anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Jul-2012.)
    """
    lb = ProofBuilder(sys, "syl312anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl312anc.7", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ∧ ( η ∧ ζ ) ) → σ )")
    s1 = lb.ref("s1", "( φ → ( η ∧ ζ ) )", h5, h6, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", h1, h2, h3, h4, s1, h7, ref="syl311anc", note="syl311anc")
    return lb.build(res)

def prove_syl321anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Jul-2012.)
    """
    lb = ProofBuilder(sys, "syl321anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl321anc.7", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ) ∧ ζ ) → σ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ) )", h4, h5, ref="jca", note="jca")
    res = lb.ref("res", "( φ → σ )", h1, h2, h3, s1, h6, h7, ref="syl311anc", note="syl311anc")
    return lb.build(res)

def prove_syl133anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl133anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl133anc.8", "( ( ψ ∧ ( χ ∧ θ ∧ τ ) ∧ ( η ∧ ζ ∧ σ ) ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( η ∧ ζ ∧ σ ) )", h5, h6, h7, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, h3, h4, s1, h8, ref="syl131anc", note="syl131anc")
    return lb.build(res)

def prove_syl313anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl313anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl313anc.8", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ∧ ( η ∧ ζ ∧ σ ) ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( η ∧ ζ ∧ σ ) )", h5, h6, h7, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, h3, h4, s1, h8, ref="syl311anc", note="syl311anc")
    return lb.build(res)

def prove_syl331anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl331anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl331anc.8", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ∧ ζ ) ∧ σ ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ∧ ζ ) )", h4, h5, h6, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, h3, s1, h7, h8, ref="syl311anc", note="syl311anc")
    return lb.build(res)

def prove_syl223anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl223anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl223anc.8", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ) ∧ ( η ∧ ζ ∧ σ ) ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( θ ∧ τ ) )", h3, h4, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, s1, h5, h6, h7, h8, ref="syl213anc", note="syl213anc")
    return lb.build(res)

def prove_syl232anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl232anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl232anc.8", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ∧ ( ζ ∧ σ ) ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( ζ ∧ σ ) )", h6, h7, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, h3, h4, h5, s1, h8, ref="syl231anc", note="syl231anc")
    return lb.build(res)

def prove_syl322anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl322anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl322anc.8", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ) ∧ ( ζ ∧ σ ) ) → ρ )")
    s1 = lb.ref("s1", "( φ → ( ζ ∧ σ ) )", h6, h7, ref="jca", note="jca")
    res = lb.ref("res", "( φ → ρ )", h1, h2, h3, h4, h5, s1, h8, ref="syl321anc", note="syl321anc")
    return lb.build(res)

def prove_syl233anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl233anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl233anc.8", "( φ → ρ )")
    h9 = lb.hyp("syl233anc.9", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ∧ ( ζ ∧ σ ∧ ρ ) ) → μ )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ) )", h1, h2, ref="jca", note="jca")
    res = lb.ref("res", "( φ → μ )", s1, h3, h4, h5, h6, h7, h8, h9, ref="syl133anc", note="syl133anc")
    return lb.build(res)

def prove_syl323anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl323anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl233anc.8", "( φ → ρ )")
    h9 = lb.hyp("syl323anc.9", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ) ∧ ( ζ ∧ σ ∧ ρ ) ) → μ )")
    s1 = lb.ref("s1", "( φ → ( τ ∧ η ) )", h4, h5, ref="jca", note="jca")
    res = lb.ref("res", "( φ → μ )", h1, h2, h3, s1, h6, h7, h8, h9, ref="syl313anc", note="syl313anc")
    return lb.build(res)

def prove_syl332anc(sys: System) -> Proof:
    """Syllogism combined with contraction.  (Contributed by NM,
    11-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl332anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl233anc.8", "( φ → ρ )")
    h9 = lb.hyp("syl332anc.9", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ∧ ζ ) ∧ ( σ ∧ ρ ) ) → μ )")
    s1 = lb.ref("s1", "( φ → ( σ ∧ ρ ) )", h7, h8, ref="jca", note="jca")
    res = lb.ref("res", "( φ → μ )", h1, h2, h3, h4, h5, h6, s1, h9, ref="syl331anc", note="syl331anc")
    return lb.build(res)

def prove_syl333anc(sys: System) -> Proof:
    """A syllogism inference combined with contraction.  (Contributed by NM,
    10-Mar-2012.)
    """
    lb = ProofBuilder(sys, "syl333anc")
    h1 = lb.hyp("syl3anc.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anc.2", "( φ → χ )")
    h3 = lb.hyp("syl3anc.3", "( φ → θ )")
    h4 = lb.hyp("syl3Xanc.4", "( φ → τ )")
    h5 = lb.hyp("syl23anc.5", "( φ → η )")
    h6 = lb.hyp("syl33anc.6", "( φ → ζ )")
    h7 = lb.hyp("syl133anc.7", "( φ → σ )")
    h8 = lb.hyp("syl233anc.8", "( φ → ρ )")
    h9 = lb.hyp("syl333anc.9", "( φ → μ )")
    h10 = lb.hyp("syl333anc.10", "( ( ( ψ ∧ χ ∧ θ ) ∧ ( τ ∧ η ∧ ζ ) ∧ ( σ ∧ ρ ∧ μ ) ) → λ )")
    s1 = lb.ref("s1", "( φ → ( σ ∧ ρ ∧ μ ) )", h7, h8, h9, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → λ )", h1, h2, h3, h4, h5, h6, s1, h10, ref="syl331anc", note="syl331anc")
    return lb.build(res)

def prove_syl3an1b(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an1b")
    h1 = lb.hyp("syl3an1b.1", "( φ ↔ ψ )")
    h2 = lb.hyp("syl3an1b.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → ψ )", h1, ref="biimpi", note="biimpi")
    res = lb.ref("res", "( ( φ ∧ χ ∧ θ ) → τ )", s1, h2, ref="syl3an1", note="syl3an1")
    return lb.build(res)

def prove_syl3an2b(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an2b")
    h1 = lb.hyp("syl3an2b.1", "( φ ↔ χ )")
    h2 = lb.hyp("syl3an2b.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → χ )", h1, ref="biimpi", note="biimpi")
    res = lb.ref("res", "( ( ψ ∧ φ ∧ θ ) → τ )", s1, h2, ref="syl3an2", note="syl3an2")
    return lb.build(res)

def prove_syl3an3b(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an3b")
    h1 = lb.hyp("syl3an3b.1", "( φ ↔ θ )")
    h2 = lb.hyp("syl3an3b.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → θ )", h1, ref="biimpi", note="biimpi")
    res = lb.ref("res", "( ( ψ ∧ χ ∧ φ ) → τ )", s1, h2, ref="syl3an3", note="syl3an3")
    return lb.build(res)

def prove_syl3an1br(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an1br")
    h1 = lb.hyp("syl3an1br.1", "( ψ ↔ φ )")
    h2 = lb.hyp("syl3an1br.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → ψ )", h1, ref="biimpri", note="biimpri")
    res = lb.ref("res", "( ( φ ∧ χ ∧ θ ) → τ )", s1, h2, ref="syl3an1", note="syl3an1")
    return lb.build(res)

def prove_syl3an2br(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an2br")
    h1 = lb.hyp("syl3an2br.1", "( χ ↔ φ )")
    h2 = lb.hyp("syl3an2br.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → χ )", h1, ref="biimpri", note="biimpri")
    res = lb.ref("res", "( ( ψ ∧ φ ∧ θ ) → τ )", s1, h2, ref="syl3an2", note="syl3an2")
    return lb.build(res)

def prove_syl3an3br(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 22-Aug-1995.)"""
    lb = ProofBuilder(sys, "syl3an3br")
    h1 = lb.hyp("syl3an3br.1", "( θ ↔ φ )")
    h2 = lb.hyp("syl3an3br.2", "( ( ψ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( φ → θ )", h1, ref="biimpri", note="biimpri")
    res = lb.ref("res", "( ( ψ ∧ χ ∧ φ ) → τ )", s1, h2, ref="syl3an3", note="syl3an3")
    return lb.build(res)

def prove_syld3an3(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 20-May-2007.)"""
    lb = ProofBuilder(sys, "syld3an3")
    h1 = lb.hyp("syld3an3.1", "( ( φ ∧ ψ ∧ χ ) → θ )")
    h2 = lb.hyp("syld3an3.2", "( ( φ ∧ ψ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ∧ χ ) → φ )", ref="simp1", note="simp1")
    s2 = lb.ref("s2", "( ( φ ∧ ψ ∧ χ ) → ψ )", ref="simp2", note="simp2")
    res = lb.ref("res", "( ( φ ∧ ψ ∧ χ ) → τ )", s1, s2, h1, h2, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syld3an1(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 7-Jul-2008.)  (Proof
    shortened by Wolf Lammen, 26-Jun-2022.)
    """
    lb = ProofBuilder(sys, "syld3an1")
    h1 = lb.hyp("syld3an1.1", "( ( χ ∧ ψ ∧ θ ) → φ )")
    h2 = lb.hyp("syld3an1.2", "( ( φ ∧ ψ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( χ ∧ ψ ∧ θ ) → ψ )", ref="simp2", note="simp2")
    s2 = lb.ref("s2", "( ( χ ∧ ψ ∧ θ ) → θ )", ref="simp3", note="simp3")
    res = lb.ref("res", "( ( χ ∧ ψ ∧ θ ) → τ )", h1, s1, s2, h2, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syld3an2(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 20-May-2007.)"""
    lb = ProofBuilder(sys, "syld3an2")
    h1 = lb.hyp("syld3an2.1", "( ( φ ∧ χ ∧ θ ) → ψ )")
    h2 = lb.hyp("syld3an2.2", "( ( φ ∧ ψ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ χ ∧ θ ) → φ )", ref="simp1", note="simp1")
    s2 = lb.ref("s2", "( ( φ ∧ χ ∧ θ ) → θ )", ref="simp3", note="simp3")
    res = lb.ref("res", "( ( φ ∧ χ ∧ θ ) → τ )", s1, h1, s2, h2, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_syl3anl1(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 24-Feb-2005.)"""
    lb = ProofBuilder(sys, "syl3anl1")
    h1 = lb.hyp("syl3anl1.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anl1.2", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( φ ∧ χ ∧ θ ) → ( ψ ∧ χ ∧ θ ) )", h1, ref="3anim1i", note="3anim1i")
    res = lb.ref("res", "( ( ( φ ∧ χ ∧ θ ) ∧ τ ) → η )", s1, h2, ref="sylan", note="sylan")
    return lb.build(res)

def prove_syl3anl2(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 24-Feb-2005.)  (Proof
    shortened by Wolf Lammen, 27-Jun-2022.)
    """
    lb = ProofBuilder(sys, "syl3anl2")
    h1 = lb.hyp("syl3anl2.1", "( φ → χ )")
    h2 = lb.hyp("syl3anl2.2", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( ψ ∧ φ ∧ θ ) → ( ψ ∧ χ ∧ θ ) )", h1, ref="3anim2i", note="3anim2i")
    res = lb.ref("res", "( ( ( ψ ∧ φ ∧ θ ) ∧ τ ) → η )", s1, h2, ref="sylan", note="sylan")
    return lb.build(res)

def prove_syl3anl3(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 24-Feb-2005.)"""
    lb = ProofBuilder(sys, "syl3anl3")
    h1 = lb.hyp("syl3anl3.1", "( φ → θ )")
    h2 = lb.hyp("syl3anl3.2", "( ( ( ψ ∧ χ ∧ θ ) ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( ψ ∧ χ ∧ φ ) → ( ψ ∧ χ ∧ θ ) )", h1, ref="3anim3i", note="3anim3i")
    res = lb.ref("res", "( ( ( ψ ∧ χ ∧ φ ) ∧ τ ) → η )", s1, h2, ref="sylan", note="sylan")
    return lb.build(res)

def prove_syl3anl(sys: System) -> Proof:
    """A triple syllogism inference.  (Contributed by NM, 24-Dec-2006.)"""
    lb = ProofBuilder(sys, "syl3anl")
    h1 = lb.hyp("syl3anl.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anl.2", "( χ → θ )")
    h3 = lb.hyp("syl3anl.3", "( τ → η )")
    h4 = lb.hyp("syl3anl.4", "( ( ( ψ ∧ θ ∧ η ) ∧ ζ ) → σ )")
    s1 = lb.ref("s1", "( ( φ ∧ χ ∧ τ ) → ( ψ ∧ θ ∧ η ) )", h1, h2, h3, ref="3anim123i", note="3anim123i")
    res = lb.ref("res", "( ( ( φ ∧ χ ∧ τ ) ∧ ζ ) → σ )", s1, h4, ref="sylan", note="sylan")
    return lb.build(res)

def prove_syl3anr1(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 31-Jul-2007.)"""
    lb = ProofBuilder(sys, "syl3anr1")
    h1 = lb.hyp("syl3anr1.1", "( φ → ψ )")
    h2 = lb.hyp("syl3anr1.2", "( ( χ ∧ ( ψ ∧ θ ∧ τ ) ) → η )")
    s1 = lb.ref("s1", "( ( φ ∧ θ ∧ τ ) → ( ψ ∧ θ ∧ τ ) )", h1, ref="3anim1i", note="3anim1i")
    res = lb.ref("res", "( ( χ ∧ ( φ ∧ θ ∧ τ ) ) → η )", s1, h2, ref="sylan2", note="sylan2")
    return lb.build(res)

def prove_syl3anr2(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 1-Aug-2007.)  (Proof
    shortened by Wolf Lammen, 27-Jun-2022.)
    """
    lb = ProofBuilder(sys, "syl3anr2")
    h1 = lb.hyp("syl3anr2.1", "( φ → θ )")
    h2 = lb.hyp("syl3anr2.2", "( ( χ ∧ ( ψ ∧ θ ∧ τ ) ) → η )")
    s1 = lb.ref("s1", "( ( ψ ∧ φ ∧ τ ) → ( ψ ∧ θ ∧ τ ) )", h1, ref="3anim2i", note="3anim2i")
    res = lb.ref("res", "( ( χ ∧ ( ψ ∧ φ ∧ τ ) ) → η )", s1, h2, ref="sylan2", note="sylan2")
    return lb.build(res)

def prove_syl3anr3(sys: System) -> Proof:
    """A syllogism inference.  (Contributed by NM, 23-Aug-2007.)"""
    lb = ProofBuilder(sys, "syl3anr3")
    h1 = lb.hyp("syl3anr3.1", "( φ → τ )")
    h2 = lb.hyp("syl3anr3.2", "( ( χ ∧ ( ψ ∧ θ ∧ τ ) ) → η )")
    s1 = lb.ref("s1", "( ( ψ ∧ θ ∧ φ ) → ( ψ ∧ θ ∧ τ ) )", h1, ref="3anim3i", note="3anim3i")
    res = lb.ref("res", "( ( χ ∧ ( ψ ∧ θ ∧ φ ) ) → η )", s1, h2, ref="sylan2", note="sylan2")
    return lb.build(res)

def prove_3anidm12(sys: System) -> Proof:
    """Inference from idempotent law for conjunction.  (Contributed by NM,
    7-Mar-2008.)
    """
    lb = ProofBuilder(sys, "3anidm12")
    h1 = lb.hyp("3anidm12.1", "( ( φ ∧ φ ∧ ψ ) → χ )")
    s1 = lb.ref("s1", "( φ → ( ( φ ∧ ψ ) → χ ) )", h1, ref="3expib", note="3expib")
    res = lb.ref("res", "( ( φ ∧ ψ ) → χ )", s1, ref="anabsi5", note="anabsi5")
    return lb.build(res)

def prove_3anidm13(sys: System) -> Proof:
    """Inference from idempotent law for conjunction.  (Contributed by NM,
    7-Mar-2008.)
    """
    lb = ProofBuilder(sys, "3anidm13")
    h1 = lb.hyp("3anidm13.1", "( ( φ ∧ ψ ∧ φ ) → χ )")
    s1 = lb.ref("s1", "( ( φ ∧ φ ∧ ψ ) → χ )", h1, ref="3com23", note="3com23")
    res = lb.ref("res", "( ( φ ∧ ψ ) → χ )", s1, ref="3anidm12", note="3anidm12")
    return lb.build(res)

def prove_3anidm23(sys: System) -> Proof:
    """Inference from idempotent law for conjunction.  (Contributed by NM,
    1-Feb-2007.)
    """
    lb = ProofBuilder(sys, "3anidm23")
    h1 = lb.hyp("3anidm23.1", "( ( φ ∧ ψ ∧ ψ ) → χ )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ) ∧ ψ ) → χ )", h1, ref="3expa", note="3expa")
    res = lb.ref("res", "( ( φ ∧ ψ ) → χ )", s1, ref="anabss3", note="anabss3")
    return lb.build(res)

def prove_syl2an3an(sys: System) -> Proof:
    """~ syl3an with antecedents in standard conjunction form.  (Contributed by
    Alan Sare, 31-Aug-2016.)
    """
    lb = ProofBuilder(sys, "syl2an3an")
    h1 = lb.hyp("syl2an3an.1", "( φ → ψ )")
    h2 = lb.hyp("syl2an3an.2", "( φ → χ )")
    h3 = lb.hyp("syl2an3an.3", "( θ → τ )")
    h4 = lb.hyp("syl2an3an.4", "( ( ψ ∧ χ ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( φ ∧ φ ∧ θ ) → η )", h1, h2, h3, h4, ref="syl3an", note="syl3an")
    res = lb.ref("res", "( ( φ ∧ θ ) → η )", s1, ref="3anidm12", note="3anidm12")
    return lb.build(res)

def prove_syl2an23an(sys: System) -> Proof:
    """Deduction related to ~ syl3an with antecedents in standard conjunction
    form.  (Contributed by Alan Sare, 31-Aug-2016.)  (Proof shortened by
    Wolf Lammen, 28-Jun-2022.)
    """
    lb = ProofBuilder(sys, "syl2an23an")
    h1 = lb.hyp("syl2an23an.1", "( φ → ψ )")
    h2 = lb.hyp("syl2an23an.2", "( φ → χ )")
    h3 = lb.hyp("syl2an23an.3", "( ( θ ∧ φ ) → τ )")
    h4 = lb.hyp("syl2an23an.4", "( ( ψ ∧ χ ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( φ ∧ ( θ ∧ φ ) ) → η )", h1, h2, h3, h4, ref="syl2an3an", note="syl2an3an")
    res = lb.ref("res", "( ( θ ∧ φ ) → η )", s1, ref="anabss7", note="anabss7")
    return lb.build(res)

def prove_3ori(sys: System) -> Proof:
    """Infer implication from triple disjunction.  (Contributed by NM,
    26-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3ori")
    h1 = lb.hyp("3ori.1", "( φ ∨ ψ ∨ χ )")
    s1 = lb.ref("s1", "( ¬ ( φ ∨ ψ ) ↔ ( ¬ φ ∧ ¬ ψ ) )", ref="ioran", note="ioran")
    s2 = lb.ref("s2", "( ( φ ∨ ψ ∨ χ ) ↔ ( ( φ ∨ ψ ) ∨ χ ) )", ref="df-3or", note="df-3or")
    s3 = lb.ref("s3", "( ( φ ∨ ψ ) ∨ χ )", h1, s2, ref="mpbi", note="mpbi")
    s4 = lb.ref("s4", "( ¬ ( φ ∨ ψ ) → χ )", s3, ref="ori", note="ori")
    res = lb.ref("res", "( ( ¬ φ ∧ ¬ ψ ) → χ )", s1, s4, ref="sylbir", note="sylbir")
    return lb.build(res)

def prove_3jao(sys: System) -> Proof:
    """Disjunction of three antecedents.  (Contributed by NM, 8-Apr-1994.)"""
    lb = ProofBuilder(sys, "3jao")
    s1 = lb.ref("s1", "( ( φ → ψ ) → ( ( χ → ψ ) → ( ( φ ∨ χ ) → ψ ) ) )", ref="jao", note="jao")
    s2 = lb.ref("s2", "( ( φ ∨ χ ∨ θ ) ↔ ( ( φ ∨ χ ) ∨ θ ) )", ref="df-3or", note="df-3or")
    s3 = lb.ref("s3", "( ( ( φ ∨ χ ) → ψ ) → ( ( θ → ψ ) → ( ( ( φ ∨ χ ) ∨ θ ) → ψ ) ) )", ref="jao", note="jao")
    s4 = lb.ref("s4", "( ( ( φ ∨ χ ) → ψ ) → ( ( θ → ψ ) → ( ( φ ∨ χ ∨ θ ) → ψ ) ) )", s2, s3, ref="syl7bi", note="syl7bi")
    s5 = lb.ref("s5", "( ( φ → ψ ) → ( ( χ → ψ ) → ( ( θ → ψ ) → ( ( φ ∨ χ ∨ θ ) → ψ ) ) ) )", s1, s4, ref="syl6", note="syl6")
    res = lb.ref("res", "( ( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) ) → ( ( φ ∨ χ ∨ θ ) → ψ ) )", s5, ref="3imp", note="3imp")
    return lb.build(res)

def prove_3jaob(sys: System) -> Proof:
    """Disjunction of three antecedents.  (Contributed by NM, 13-Sep-2011.)
    (Proof shortened by Hongxiu Chen, 29-Jun-2025.)
    """
    lb = ProofBuilder(sys, "3jaob")
    s1 = lb.ref("s1", "( ( ( ( φ ∨ χ ) ∨ θ ) → ψ ) ↔ ( ( ( φ → ψ ) ∧ ( χ → ψ ) ) ∧ ( θ → ψ ) ) )", ref="pm5.53", note="pm5.53")
    s2 = lb.ref("s2", "( ( φ ∨ χ ∨ θ ) ↔ ( ( φ ∨ χ ) ∨ θ ) )", ref="df-3or", note="df-3or")
    s3 = lb.ref("s3", "( ( ( φ ∨ χ ∨ θ ) → ψ ) ↔ ( ( ( φ ∨ χ ) ∨ θ ) → ψ ) )", s2, ref="imbi1i", note="imbi1i")
    s4 = lb.ref("s4", "( ( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) ) ↔ ( ( ( φ → ψ ) ∧ ( χ → ψ ) ) ∧ ( θ → ψ ) ) )", ref="df-3an", note="df-3an")
    res = lb.ref("res", "( ( ( φ ∨ χ ∨ θ ) → ψ ) ↔ ( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) ) )", s1, s3, s4, ref="3bitr4i", note="3bitr4i")
    return lb.build(res)

def prove_3jaoi(sys: System) -> Proof:
    """Disjunction of three antecedents (inference).  (Contributed by NM,
    12-Sep-1995.)  (Proof shortened by Garrett Katz, 16-Jun-2026.)
    """
    lb = ProofBuilder(sys, "3jaoi")
    h1 = lb.hyp("3jaoi.1", "( φ → ψ )")
    h2 = lb.hyp("3jaoi.2", "( χ → ψ )")
    h3 = lb.hyp("3jaoi.3", "( θ → ψ )")
    s1 = lb.ref("s1", "( ( ( φ ∨ χ ∨ θ ) → ψ ) ↔ ( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) ) )", ref="3jaob", note="3jaob")
    res = lb.ref("res", "( ( φ ∨ χ ∨ θ ) → ψ )", h1, h2, h3, s1, ref="mpbir3an", note="mpbir3an")
    return lb.build(res)

def prove_3jaoiOLD(sys: System) -> Proof:
    """Obsolete version of ~ 3jaoi as of 16-Jun-2026.  Disjunction of three
    antecedents (inference).  (Contributed by NM, 12-Sep-1995.)
    (Proof modification is discouraged.)  (New usage is discouraged.)
    """
    lb = ProofBuilder(sys, "3jaoiOLD")
    h1 = lb.hyp("3jaoi.1", "( φ → ψ )")
    h2 = lb.hyp("3jaoi.2", "( χ → ψ )")
    h3 = lb.hyp("3jaoi.3", "( θ → ψ )")
    s1 = lb.ref("s1", "( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) )", h1, h2, h3, ref="3pm3.2i", note="3pm3.2i")
    s2 = lb.ref("s2", "( ( ( φ → ψ ) ∧ ( χ → ψ ) ∧ ( θ → ψ ) ) → ( ( φ ∨ χ ∨ θ ) → ψ ) )", ref="3jao", note="3jao")
    res = lb.mp("res", s1, s2, "ax-mp")
    return lb.build(res)

def prove_3jaod(sys: System) -> Proof:
    """Disjunction of three antecedents (deduction).  (Contributed by NM,
    14-Oct-2005.)
    """
    lb = ProofBuilder(sys, "3jaod")
    h1 = lb.hyp("3jaod.1", "( φ → ( ψ → χ ) )")
    h2 = lb.hyp("3jaod.2", "( φ → ( θ → χ ) )")
    h3 = lb.hyp("3jaod.3", "( φ → ( τ → χ ) )")
    s1 = lb.ref("s1", "( ( ( ψ → χ ) ∧ ( θ → χ ) ∧ ( τ → χ ) ) → ( ( ψ ∨ θ ∨ τ ) → χ ) )", ref="3jao", note="3jao")
    res = lb.ref("res", "( φ → ( ( ψ ∨ θ ∨ τ ) → χ ) )", h1, h2, h3, s1, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_3jaoian(sys: System) -> Proof:
    """Disjunction of three antecedents (inference).  (Contributed by NM,
    14-Oct-2005.)
    """
    lb = ProofBuilder(sys, "3jaoian")
    h1 = lb.hyp("3jaoian.1", "( ( φ ∧ ψ ) → χ )")
    h2 = lb.hyp("3jaoian.2", "( ( θ ∧ ψ ) → χ )")
    h3 = lb.hyp("3jaoian.3", "( ( τ ∧ ψ ) → χ )")
    s1 = lb.ref("s1", "( φ → ( ψ → χ ) )", h1, ref="ex", note="ex")
    s2 = lb.ref("s2", "( θ → ( ψ → χ ) )", h2, ref="ex", note="ex")
    s3 = lb.ref("s3", "( τ → ( ψ → χ ) )", h3, ref="ex", note="ex")
    s4 = lb.ref("s4", "( ( φ ∨ θ ∨ τ ) → ( ψ → χ ) )", s1, s2, s3, ref="3jaoi", note="3jaoi")
    res = lb.ref("res", "( ( ( φ ∨ θ ∨ τ ) ∧ ψ ) → χ )", s4, ref="imp", note="imp")
    return lb.build(res)

def prove_3jaodan(sys: System) -> Proof:
    """Disjunction of three antecedents (deduction).  (Contributed by NM,
    14-Oct-2005.)
    """
    lb = ProofBuilder(sys, "3jaodan")
    h1 = lb.hyp("3jaodan.1", "( ( φ ∧ ψ ) → χ )")
    h2 = lb.hyp("3jaodan.2", "( ( φ ∧ θ ) → χ )")
    h3 = lb.hyp("3jaodan.3", "( ( φ ∧ τ ) → χ )")
    s1 = lb.ref("s1", "( φ → ( ψ → χ ) )", h1, ref="ex", note="ex")
    s2 = lb.ref("s2", "( φ → ( θ → χ ) )", h2, ref="ex", note="ex")
    s3 = lb.ref("s3", "( φ → ( τ → χ ) )", h3, ref="ex", note="ex")
    s4 = lb.ref("s4", "( φ → ( ( ψ ∨ θ ∨ τ ) → χ ) )", s1, s2, s3, ref="3jaod", note="3jaod")
    res = lb.ref("res", "( ( φ ∧ ( ψ ∨ θ ∨ τ ) ) → χ )", s4, ref="imp", note="imp")
    return lb.build(res)

def prove_mpjao3dan(sys: System) -> Proof:
    """Eliminate a three-way disjunction in a deduction.  (Contributed by
    Thierry Arnoux, 13-Apr-2018.)  (Proof shortened by Wolf Lammen,
    20-Apr-2024.)
    """
    lb = ProofBuilder(sys, "mpjao3dan")
    h1 = lb.hyp("mpjao3dan.1", "( ( φ ∧ ψ ) → χ )")
    h2 = lb.hyp("mpjao3dan.2", "( ( φ ∧ θ ) → χ )")
    h3 = lb.hyp("mpjao3dan.3", "( ( φ ∧ τ ) → χ )")
    h4 = lb.hyp("mpjao3dan.4", "( φ → ( ψ ∨ θ ∨ τ ) )")
    s1 = lb.ref("s1", "( ( φ ∧ ( ψ ∨ θ ∨ τ ) ) → χ )", h1, h2, h3, ref="3jaodan", note="3jaodan")
    res = lb.ref("res", "( φ → χ )", h4, s1, ref="mpdan", note="mpdan")
    return lb.build(res)

def prove_3jaao(sys: System) -> Proof:
    """Inference conjoining and disjoining the antecedents of three
    implications.  (Contributed by Jeff Hankins, 15-Aug-2009.)  (Proof
    shortened by Andrew Salmon, 13-May-2011.)  (Proof shortened by Garrett
    Katz, 16-Jun-2026.)
    """
    lb = ProofBuilder(sys, "3jaao")
    h1 = lb.hyp("3jaao.1", "( φ → ( ψ → χ ) )")
    h2 = lb.hyp("3jaao.2", "( θ → ( τ → χ ) )")
    h3 = lb.hyp("3jaao.3", "( η → ( ζ → χ ) )")
    s1 = lb.ref("s1", "( ( ( ψ → χ ) ∧ ( τ → χ ) ∧ ( ζ → χ ) ) → ( ( ψ ∨ τ ∨ ζ ) → χ ) )", ref="3jao", note="3jao")
    res = lb.ref("res", "( ( φ ∧ θ ∧ η ) → ( ( ψ ∨ τ ∨ ζ ) → χ ) )", h1, h2, h3, s1, ref="syl3an", note="syl3an")
    return lb.build(res)

def prove_3jaaoOLD(sys: System) -> Proof:
    """Obsolete version of ~ 3jaao as of 16-Jun-2026.  Inference conjoining and
    disjoining the antecedents of three implications.  (Contributed by Jeff
    Hankins, 15-Aug-2009.)  (Proof shortened by Andrew Salmon, 13-May-2011.)
    (Proof modification is discouraged.)  (New usage is discouraged.)
    """
    lb = ProofBuilder(sys, "3jaaoOLD")
    h1 = lb.hyp("3jaao.1", "( φ → ( ψ → χ ) )")
    h2 = lb.hyp("3jaao.2", "( θ → ( τ → χ ) )")
    h3 = lb.hyp("3jaao.3", "( η → ( ζ → χ ) )")
    s1 = lb.ref("s1", "( ( φ ∧ θ ∧ η ) → ( ψ → χ ) )", h1, ref="3ad2ant1", note="3ad2ant1")
    s2 = lb.ref("s2", "( ( φ ∧ θ ∧ η ) → ( τ → χ ) )", h2, ref="3ad2ant2", note="3ad2ant2")
    s3 = lb.ref("s3", "( ( φ ∧ θ ∧ η ) → ( ζ → χ ) )", h3, ref="3ad2ant3", note="3ad2ant3")
    res = lb.ref("res", "( ( φ ∧ θ ∧ η ) → ( ( ψ ∨ τ ∨ ζ ) → χ ) )", s1, s2, s3, ref="3jaod", note="3jaod")
    return lb.build(res)

def prove_syl3an9b(sys: System) -> Proof:
    """Nested syllogism inference conjoining 3 dissimilar antecedents.
    (Contributed by NM, 1-May-1995.)
    """
    lb = ProofBuilder(sys, "syl3an9b")
    h1 = lb.hyp("syl3an9b.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("syl3an9b.2", "( θ → ( χ ↔ τ ) )")
    h3 = lb.hyp("syl3an9b.3", "( η → ( τ ↔ ζ ) )")
    s1 = lb.ref("s1", "( ( φ ∧ θ ) → ( ψ ↔ τ ) )", h1, h2, ref="sylan9bb", note="sylan9bb")
    s2 = lb.ref("s2", "( ( ( φ ∧ θ ) ∧ η ) → ( ψ ↔ ζ ) )", s1, h3, ref="sylan9bb", note="sylan9bb")
    res = lb.ref("res", "( ( φ ∧ θ ∧ η ) → ( ψ ↔ ζ ) )", s2, ref="3impa", note="3impa")
    return lb.build(res)

def prove_3orbi123d(sys: System) -> Proof:
    """Deduction joining 3 equivalences to form equivalence of disjunctions.
    (Contributed by NM, 20-Apr-1994.)
    """
    lb = ProofBuilder(sys, "3orbi123d")
    h1 = lb.hyp("bi3d.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("bi3d.2", "( φ → ( θ ↔ τ ) )")
    h3 = lb.hyp("bi3d.3", "( φ → ( η ↔ ζ ) )")
    s1 = lb.ref("s1", "( φ → ( ( ψ ∨ θ ) ↔ ( χ ∨ τ ) ) )", h1, h2, ref="orbi12d", note="orbi12d")
    s2 = lb.ref("s2", "( φ → ( ( ( ψ ∨ θ ) ∨ η ) ↔ ( ( χ ∨ τ ) ∨ ζ ) ) )", s1, h3, ref="orbi12d", note="orbi12d")
    s3 = lb.ref("s3", "( ( ψ ∨ θ ∨ η ) ↔ ( ( ψ ∨ θ ) ∨ η ) )", ref="df-3or", note="df-3or")
    s4 = lb.ref("s4", "( ( χ ∨ τ ∨ ζ ) ↔ ( ( χ ∨ τ ) ∨ ζ ) )", ref="df-3or", note="df-3or")
    res = lb.ref("res", "( φ → ( ( ψ ∨ θ ∨ η ) ↔ ( χ ∨ τ ∨ ζ ) ) )", s2, s3, s4, ref="3bitr4g", note="3bitr4g")
    return lb.build(res)

def prove_3anbi123d(sys: System) -> Proof:
    """Deduction joining 3 equivalences to form equivalence of conjunctions.
    (Contributed by NM, 22-Apr-1994.)
    """
    lb = ProofBuilder(sys, "3anbi123d")
    h1 = lb.hyp("bi3d.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("bi3d.2", "( φ → ( θ ↔ τ ) )")
    h3 = lb.hyp("bi3d.3", "( φ → ( η ↔ ζ ) )")
    s1 = lb.ref("s1", "( φ → ( ( ψ ∧ θ ) ↔ ( χ ∧ τ ) ) )", h1, h2, ref="anbi12d", note="anbi12d")
    s2 = lb.ref("s2", "( φ → ( ( ( ψ ∧ θ ) ∧ η ) ↔ ( ( χ ∧ τ ) ∧ ζ ) ) )", s1, h3, ref="anbi12d", note="anbi12d")
    s3 = lb.ref("s3", "( ( ψ ∧ θ ∧ η ) ↔ ( ( ψ ∧ θ ) ∧ η ) )", ref="df-3an", note="df-3an")
    s4 = lb.ref("s4", "( ( χ ∧ τ ∧ ζ ) ↔ ( ( χ ∧ τ ) ∧ ζ ) )", ref="df-3an", note="df-3an")
    res = lb.ref("res", "( φ → ( ( ψ ∧ θ ∧ η ) ↔ ( χ ∧ τ ∧ ζ ) ) )", s2, s3, s4, ref="3bitr4g", note="3bitr4g")
    return lb.build(res)

def prove_3anbi12d(sys: System) -> Proof:
    """Deduction conjoining and adding a conjunct to equivalences.
    (Contributed by NM, 8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi12d")
    h1 = lb.hyp("3anbi12d.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("3anbi12d.2", "( φ → ( θ ↔ τ ) )")
    s1 = lb.ref("s1", "( φ → ( η ↔ η ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( ψ ∧ θ ∧ η ) ↔ ( χ ∧ τ ∧ η ) ) )", h1, h2, s1, ref="3anbi123d", note="3anbi123d")
    return lb.build(res)

def prove_3anbi13d(sys: System) -> Proof:
    """Deduction conjoining and adding a conjunct to equivalences.
    (Contributed by NM, 8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi13d")
    h1 = lb.hyp("3anbi12d.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("3anbi12d.2", "( φ → ( θ ↔ τ ) )")
    s1 = lb.ref("s1", "( φ → ( η ↔ η ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( ψ ∧ η ∧ θ ) ↔ ( χ ∧ η ∧ τ ) ) )", h1, s1, h2, ref="3anbi123d", note="3anbi123d")
    return lb.build(res)

def prove_3anbi23d(sys: System) -> Proof:
    """Deduction conjoining and adding a conjunct to equivalences.
    (Contributed by NM, 8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi23d")
    h1 = lb.hyp("3anbi12d.1", "( φ → ( ψ ↔ χ ) )")
    h2 = lb.hyp("3anbi12d.2", "( φ → ( θ ↔ τ ) )")
    s1 = lb.ref("s1", "( φ → ( η ↔ η ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( η ∧ ψ ∧ θ ) ↔ ( η ∧ χ ∧ τ ) ) )", s1, h1, h2, ref="3anbi123d", note="3anbi123d")
    return lb.build(res)

def prove_3anbi1d(sys: System) -> Proof:
    """Deduction adding conjuncts to an equivalence.  (Contributed by NM,
    8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi1d")
    h1 = lb.hyp("3anbi1d.1", "( φ → ( ψ ↔ χ ) )")
    s1 = lb.ref("s1", "( φ → ( θ ↔ θ ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( ψ ∧ θ ∧ τ ) ↔ ( χ ∧ θ ∧ τ ) ) )", h1, s1, ref="3anbi12d", note="3anbi12d")
    return lb.build(res)

def prove_3anbi2d(sys: System) -> Proof:
    """Deduction adding conjuncts to an equivalence.  (Contributed by NM,
    8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi2d")
    h1 = lb.hyp("3anbi1d.1", "( φ → ( ψ ↔ χ ) )")
    s1 = lb.ref("s1", "( φ → ( θ ↔ θ ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( θ ∧ ψ ∧ τ ) ↔ ( θ ∧ χ ∧ τ ) ) )", s1, h1, ref="3anbi12d", note="3anbi12d")
    return lb.build(res)

def prove_3anbi3d(sys: System) -> Proof:
    """Deduction adding conjuncts to an equivalence.  (Contributed by NM,
    8-Sep-2006.)
    """
    lb = ProofBuilder(sys, "3anbi3d")
    h1 = lb.hyp("3anbi1d.1", "( φ → ( ψ ↔ χ ) )")
    s1 = lb.ref("s1", "( φ → ( θ ↔ θ ) )", ref="biidd", note="biidd")
    res = lb.ref("res", "( φ → ( ( θ ∧ τ ∧ ψ ) ↔ ( θ ∧ τ ∧ χ ) ) )", s1, h1, ref="3anbi13d", note="3anbi13d")
    return lb.build(res)

def prove_3anim123d(sys: System) -> Proof:
    """Deduction joining 3 implications to form implication of conjunctions.
    (Contributed by NM, 24-Feb-2005.)
    """
    lb = ProofBuilder(sys, "3anim123d")
    h1 = lb.hyp("3anim123d.1", "( φ → ( ψ → χ ) )")
    h2 = lb.hyp("3anim123d.2", "( φ → ( θ → τ ) )")
    h3 = lb.hyp("3anim123d.3", "( φ → ( η → ζ ) )")
    s1 = lb.ref("s1", "( φ → ( ( ψ ∧ θ ) → ( χ ∧ τ ) ) )", h1, h2, ref="anim12d", note="anim12d")
    s2 = lb.ref("s2", "( φ → ( ( ( ψ ∧ θ ) ∧ η ) → ( ( χ ∧ τ ) ∧ ζ ) ) )", s1, h3, ref="anim12d", note="anim12d")
    s3 = lb.ref("s3", "( ( ψ ∧ θ ∧ η ) ↔ ( ( ψ ∧ θ ) ∧ η ) )", ref="df-3an", note="df-3an")
    s4 = lb.ref("s4", "( ( χ ∧ τ ∧ ζ ) ↔ ( ( χ ∧ τ ) ∧ ζ ) )", ref="df-3an", note="df-3an")
    res = lb.ref("res", "( φ → ( ( ψ ∧ θ ∧ η ) → ( χ ∧ τ ∧ ζ ) ) )", s2, s3, s4, ref="3imtr4g", note="3imtr4g")
    return lb.build(res)

def prove_3orim123d(sys: System) -> Proof:
    """Deduction joining 3 implications to form implication of disjunctions.
    (Contributed by NM, 4-Apr-1997.)
    """
    lb = ProofBuilder(sys, "3orim123d")
    h1 = lb.hyp("3anim123d.1", "( φ → ( ψ → χ ) )")
    h2 = lb.hyp("3anim123d.2", "( φ → ( θ → τ ) )")
    h3 = lb.hyp("3anim123d.3", "( φ → ( η → ζ ) )")
    s1 = lb.ref("s1", "( φ → ( ( ψ ∨ θ ) → ( χ ∨ τ ) ) )", h1, h2, ref="orim12d", note="orim12d")
    s2 = lb.ref("s2", "( φ → ( ( ( ψ ∨ θ ) ∨ η ) → ( ( χ ∨ τ ) ∨ ζ ) ) )", s1, h3, ref="orim12d", note="orim12d")
    s3 = lb.ref("s3", "( ( ψ ∨ θ ∨ η ) ↔ ( ( ψ ∨ θ ) ∨ η ) )", ref="df-3or", note="df-3or")
    s4 = lb.ref("s4", "( ( χ ∨ τ ∨ ζ ) ↔ ( ( χ ∨ τ ) ∨ ζ ) )", ref="df-3or", note="df-3or")
    res = lb.ref("res", "( φ → ( ( ψ ∨ θ ∨ η ) → ( χ ∨ τ ∨ ζ ) ) )", s2, s3, s4, ref="3imtr4g", note="3imtr4g")
    return lb.build(res)

def prove_an6(sys: System) -> Proof:
    """Rearrangement of 6 conjuncts.  (Contributed by NM, 13-Mar-1995.)"""
    lb = ProofBuilder(sys, "an6")
    s1 = lb.ref("s1", "( ( ( ( φ ∧ ψ ) ∧ χ ) ∧ ( ( θ ∧ τ ) ∧ η ) ) ↔ ( ( ( φ ∧ ψ ) ∧ ( θ ∧ τ ) ) ∧ ( χ ∧ η ) ) )", ref="an4", note="an4")
    s2 = lb.ref("s2", "( ( ( φ ∧ ψ ) ∧ ( θ ∧ τ ) ) ↔ ( ( φ ∧ θ ) ∧ ( ψ ∧ τ ) ) )", ref="an4", note="an4")
    s3 = lb.ref("s3", "( ( ( ( φ ∧ ψ ) ∧ χ ) ∧ ( ( θ ∧ τ ) ∧ η ) ) ↔ ( ( ( φ ∧ θ ) ∧ ( ψ ∧ τ ) ) ∧ ( χ ∧ η ) ) )", s1, s2, ref="bianbi", note="bianbi")
    s4 = lb.ref("s4", "( ( φ ∧ ψ ∧ χ ) ↔ ( ( φ ∧ ψ ) ∧ χ ) )", ref="df-3an", note="df-3an")
    s5 = lb.ref("s5", "( ( θ ∧ τ ∧ η ) ↔ ( ( θ ∧ τ ) ∧ η ) )", ref="df-3an", note="df-3an")
    s6 = lb.ref("s6", "( ( ( φ ∧ ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ) ↔ ( ( ( φ ∧ ψ ) ∧ χ ) ∧ ( ( θ ∧ τ ) ∧ η ) ) )", s4, s5, ref="anbi12i", note="anbi12i")
    s7 = lb.ref("s7", "( ( ( φ ∧ θ ) ∧ ( ψ ∧ τ ) ∧ ( χ ∧ η ) ) ↔ ( ( ( φ ∧ θ ) ∧ ( ψ ∧ τ ) ) ∧ ( χ ∧ η ) ) )", ref="df-3an", note="df-3an")
    res = lb.ref("res", "( ( ( φ ∧ ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ) ↔ ( ( φ ∧ θ ) ∧ ( ψ ∧ τ ) ∧ ( χ ∧ η ) ) )", s3, s6, s7, ref="3bitr4i", note="3bitr4i")
    return lb.build(res)

def prove_3an6(sys: System) -> Proof:
    """Analogue of ~ an4 for triple conjunction.  (Contributed by Scott Fenton,
    16-Mar-2011.)  (Proof shortened by Andrew Salmon, 25-May-2011.)
    """
    lb = ProofBuilder(sys, "3an6")
    s1 = lb.ref("s1", "( ( ( φ ∧ χ ∧ τ ) ∧ ( ψ ∧ θ ∧ η ) ) ↔ ( ( φ ∧ ψ ) ∧ ( χ ∧ θ ) ∧ ( τ ∧ η ) ) )", ref="an6", note="an6")
    res = lb.ref("res", "( ( ( φ ∧ ψ ) ∧ ( χ ∧ θ ) ∧ ( τ ∧ η ) ) ↔ ( ( φ ∧ χ ∧ τ ) ∧ ( ψ ∧ θ ∧ η ) ) )", s1, ref="bicomi", note="bicomi")
    return lb.build(res)

def prove_3or6(sys: System) -> Proof:
    """Analogue of ~ or4 for triple conjunction.  (Contributed by Scott Fenton,
    16-Mar-2011.)
    """
    lb = ProofBuilder(sys, "3or6")
    s1 = lb.ref("s1", "( ( ( ( φ ∨ χ ) ∨ τ ) ∨ ( ( ψ ∨ θ ) ∨ η ) ) ↔ ( ( ( φ ∨ χ ) ∨ ( ψ ∨ θ ) ) ∨ ( τ ∨ η ) ) )", ref="or4", note="or4")
    s2 = lb.ref("s2", "( ( ( φ ∨ χ ) ∨ ( ψ ∨ θ ) ) ↔ ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ) )", ref="or4", note="or4")
    s3 = lb.ref("s3", "( ( ( ( φ ∨ χ ) ∨ ( ψ ∨ θ ) ) ∨ ( τ ∨ η ) ) ↔ ( ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ) ∨ ( τ ∨ η ) ) )", s2, ref="orbi1i", note="orbi1i")
    s4 = lb.ref("s4", "( ( ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ) ∨ ( τ ∨ η ) ) ↔ ( ( ( φ ∨ χ ) ∨ τ ) ∨ ( ( ψ ∨ θ ) ∨ η ) ) )", s1, s3, ref="bitr2i", note="bitr2i")
    s5 = lb.ref("s5", "( ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ∨ ( τ ∨ η ) ) ↔ ( ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ) ∨ ( τ ∨ η ) ) )", ref="df-3or", note="df-3or")
    s6 = lb.ref("s6", "( ( φ ∨ χ ∨ τ ) ↔ ( ( φ ∨ χ ) ∨ τ ) )", ref="df-3or", note="df-3or")
    s7 = lb.ref("s7", "( ( ψ ∨ θ ∨ η ) ↔ ( ( ψ ∨ θ ) ∨ η ) )", ref="df-3or", note="df-3or")
    s8 = lb.ref("s8", "( ( ( φ ∨ χ ∨ τ ) ∨ ( ψ ∨ θ ∨ η ) ) ↔ ( ( ( φ ∨ χ ) ∨ τ ) ∨ ( ( ψ ∨ θ ) ∨ η ) ) )", s6, s7, ref="orbi12i", note="orbi12i")
    res = lb.ref("res", "( ( ( φ ∨ ψ ) ∨ ( χ ∨ θ ) ∨ ( τ ∨ η ) ) ↔ ( ( φ ∨ χ ∨ τ ) ∨ ( ψ ∨ θ ∨ η ) ) )", s4, s5, s8, ref="3bitr4i", note="3bitr4i")
    return lb.build(res)

def prove_mp3an1(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    21-Nov-1994.)
    """
    lb = ProofBuilder(sys, "mp3an1")
    h1 = lb.hyp("mp3an1.1", "φ")
    h2 = lb.hyp("mp3an1.2", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( φ ∧ ( ψ ∧ χ ) ) → θ )", h2, ref="3expb", note="3expb")
    res = lb.ref("res", "( ( ψ ∧ χ ) → θ )", h1, s1, ref="mpan", note="mpan")
    return lb.build(res)

def prove_mp3an2(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    21-Nov-1994.)
    """
    lb = ProofBuilder(sys, "mp3an2")
    h1 = lb.hyp("mp3an2.1", "ψ")
    h2 = lb.hyp("mp3an2.2", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ) ∧ χ ) → θ )", h2, ref="3expa", note="3expa")
    res = lb.ref("res", "( ( φ ∧ χ ) → θ )", h1, s1, ref="mpanl2", note="mpanl2")
    return lb.build(res)

def prove_mp3an3(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    21-Nov-1994.)
    """
    lb = ProofBuilder(sys, "mp3an3")
    h1 = lb.hyp("mp3an3.1", "χ")
    h2 = lb.hyp("mp3an3.2", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ) → ( χ → θ ) )", h2, ref="3expia", note="3expia")
    res = lb.ref("res", "( ( φ ∧ ψ ) → θ )", h1, s1, ref="mpi", note="mpi")
    return lb.build(res)

def prove_mp3an12(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    13-Jul-2005.)
    """
    lb = ProofBuilder(sys, "mp3an12")
    h1 = lb.hyp("mp3an12.1", "φ")
    h2 = lb.hyp("mp3an12.2", "ψ")
    h3 = lb.hyp("mp3an12.3", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( ψ ∧ χ ) → θ )", h1, h3, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "( χ → θ )", h2, s1, ref="mpan", note="mpan")
    return lb.build(res)

def prove_mp3an13(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    14-Jul-2005.)
    """
    lb = ProofBuilder(sys, "mp3an13")
    h1 = lb.hyp("mp3an13.1", "φ")
    h2 = lb.hyp("mp3an13.2", "χ")
    h3 = lb.hyp("mp3an13.3", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ) → θ )", h2, h3, ref="mp3an3", note="mp3an3")
    res = lb.ref("res", "( ψ → θ )", h1, s1, ref="mpan", note="mpan")
    return lb.build(res)

def prove_mp3an23(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    14-Jul-2005.)
    """
    lb = ProofBuilder(sys, "mp3an23")
    h1 = lb.hyp("mp3an23.1", "ψ")
    h2 = lb.hyp("mp3an23.2", "χ")
    h3 = lb.hyp("mp3an23.3", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ) → θ )", h2, h3, ref="mp3an3", note="mp3an3")
    res = lb.ref("res", "( φ → θ )", h1, s1, ref="mpan2", note="mpan2")
    return lb.build(res)

def prove_mp3an1i(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM, 5-Jul-2005.)"""
    lb = ProofBuilder(sys, "mp3an1i")
    h1 = lb.hyp("mp3an1i.1", "ψ")
    h2 = lb.hyp("mp3an1i.2", "( φ → ( ( ψ ∧ χ ∧ θ ) → τ ) )")
    s1 = lb.ref("s1", "( ( ψ ∧ χ ∧ θ ) → ( φ → τ ) )", h2, ref="com12", note="com12")
    s2 = lb.ref("s2", "( ( χ ∧ θ ) → ( φ → τ ) )", h1, s1, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "( φ → ( ( χ ∧ θ ) → τ ) )", s2, ref="com12", note="com12")
    return lb.build(res)

def prove_mp3anl1(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    24-Feb-2005.)
    """
    lb = ProofBuilder(sys, "mp3anl1")
    h1 = lb.hyp("mp3anl1.1", "φ")
    h2 = lb.hyp("mp3anl1.2", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ∧ χ ) → ( θ → τ ) )", h2, ref="ex", note="ex")
    s2 = lb.ref("s2", "( ( ψ ∧ χ ) → ( θ → τ ) )", h1, s1, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "( ( ( ψ ∧ χ ) ∧ θ ) → τ )", s2, ref="imp", note="imp")
    return lb.build(res)

def prove_mp3anl2(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    24-Feb-2005.)
    """
    lb = ProofBuilder(sys, "mp3anl2")
    h1 = lb.hyp("mp3anl2.1", "ψ")
    h2 = lb.hyp("mp3anl2.2", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ∧ χ ) → ( θ → τ ) )", h2, ref="ex", note="ex")
    s2 = lb.ref("s2", "( ( φ ∧ χ ) → ( θ → τ ) )", h1, s1, ref="mp3an2", note="mp3an2")
    res = lb.ref("res", "( ( ( φ ∧ χ ) ∧ θ ) → τ )", s2, ref="imp", note="imp")
    return lb.build(res)

def prove_mp3anl3(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    24-Feb-2005.)
    """
    lb = ProofBuilder(sys, "mp3anl3")
    h1 = lb.hyp("mp3anl3.1", "χ")
    h2 = lb.hyp("mp3anl3.2", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ∧ χ ) → ( θ → τ ) )", h2, ref="ex", note="ex")
    s2 = lb.ref("s2", "( ( φ ∧ ψ ) → ( θ → τ ) )", h1, s1, ref="mp3an3", note="mp3an3")
    res = lb.ref("res", "( ( ( φ ∧ ψ ) ∧ θ ) → τ )", s2, ref="imp", note="imp")
    return lb.build(res)

def prove_mp3anr1(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM, 4-Nov-2006.)"""
    lb = ProofBuilder(sys, "mp3anr1")
    h1 = lb.hyp("mp3anr1.1", "ψ")
    h2 = lb.hyp("mp3anr1.2", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → τ )")
    s1 = lb.ref("s1", "( ( ( ψ ∧ χ ∧ θ ) ∧ φ ) → τ )", h2, ref="ancoms", note="ancoms")
    s2 = lb.ref("s2", "( ( ( χ ∧ θ ) ∧ φ ) → τ )", h1, s1, ref="mp3anl1", note="mp3anl1")
    res = lb.ref("res", "( ( φ ∧ ( χ ∧ θ ) ) → τ )", s2, ref="ancoms", note="ancoms")
    return lb.build(res)

def prove_mp3anr2(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    24-Nov-2006.)
    """
    lb = ProofBuilder(sys, "mp3anr2")
    h1 = lb.hyp("mp3anr2.1", "χ")
    h2 = lb.hyp("mp3anr2.2", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → τ )")
    s1 = lb.ref("s1", "( ( ( ψ ∧ χ ∧ θ ) ∧ φ ) → τ )", h2, ref="ancoms", note="ancoms")
    s2 = lb.ref("s2", "( ( ( ψ ∧ θ ) ∧ φ ) → τ )", h1, s1, ref="mp3anl2", note="mp3anl2")
    res = lb.ref("res", "( ( φ ∧ ( ψ ∧ θ ) ) → τ )", s2, ref="ancoms", note="ancoms")
    return lb.build(res)

def prove_mp3anr3(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    19-Oct-2007.)
    """
    lb = ProofBuilder(sys, "mp3anr3")
    h1 = lb.hyp("mp3anr3.1", "θ")
    h2 = lb.hyp("mp3anr3.2", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → τ )")
    s1 = lb.ref("s1", "( ( ( ψ ∧ χ ∧ θ ) ∧ φ ) → τ )", h2, ref="ancoms", note="ancoms")
    s2 = lb.ref("s2", "( ( ( ψ ∧ χ ) ∧ φ ) → τ )", h1, s1, ref="mp3anl3", note="mp3anl3")
    res = lb.ref("res", "( ( φ ∧ ( ψ ∧ χ ) ) → τ )", s2, ref="ancoms", note="ancoms")
    return lb.build(res)

def prove_mp3an(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM,
    14-May-1999.)
    """
    lb = ProofBuilder(sys, "mp3an")
    h1 = lb.hyp("mp3an.1", "φ")
    h2 = lb.hyp("mp3an.2", "ψ")
    h3 = lb.hyp("mp3an.3", "χ")
    h4 = lb.hyp("mp3an.4", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( ψ ∧ χ ) → θ )", h1, h4, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "θ", h2, h3, s1, ref="mp2an", note="mp2an")
    return lb.build(res)

def prove_mpd3an3(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM, 8-Nov-2007.)"""
    lb = ProofBuilder(sys, "mpd3an3")
    h1 = lb.hyp("mpd3an3.2", "( ( φ ∧ ψ ) → χ )")
    h2 = lb.hyp("mpd3an3.3", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ) ∧ χ ) → θ )", h2, ref="3expa", note="3expa")
    res = lb.ref("res", "( ( φ ∧ ψ ) → θ )", h1, s1, ref="mpdan", note="mpdan")
    return lb.build(res)

def prove_mpd3an23(sys: System) -> Proof:
    """An inference based on modus ponens.  (Contributed by NM, 4-Dec-2006.)"""
    lb = ProofBuilder(sys, "mpd3an23")
    h1 = lb.hyp("mpd3an23.1", "( φ → ψ )")
    h2 = lb.hyp("mpd3an23.2", "( φ → χ )")
    h3 = lb.hyp("mpd3an23.3", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( φ → φ )", ref="id", note="id")
    res = lb.ref("res", "( φ → θ )", s1, h1, h2, h3, ref="syl3anc", note="syl3anc")
    return lb.build(res)

def prove_mp3and(sys: System) -> Proof:
    """A deduction based on modus ponens.  (Contributed by Mario Carneiro,
    24-Dec-2016.)
    """
    lb = ProofBuilder(sys, "mp3and")
    h1 = lb.hyp("mp3and.1", "( φ → ψ )")
    h2 = lb.hyp("mp3and.2", "( φ → χ )")
    h3 = lb.hyp("mp3and.3", "( φ → θ )")
    h4 = lb.hyp("mp3and.4", "( φ → ( ( ψ ∧ χ ∧ θ ) → τ ) )")
    s1 = lb.ref("s1", "( φ → ( ψ ∧ χ ∧ θ ) )", h1, h2, h3, ref="3jca", note="3jca")
    res = lb.ref("res", "( φ → τ )", s1, h4, ref="mpd", note="mpd")
    return lb.build(res)

def prove_mp3an12i(sys: System) -> Proof:
    """~ mp3an with antecedents in standard conjunction form and with one
    hypothesis an implication.  (Contributed by Alan Sare, 28-Aug-2016.)
    """
    lb = ProofBuilder(sys, "mp3an12i")
    h1 = lb.hyp("mp3an12i.1", "φ")
    h2 = lb.hyp("mp3an12i.2", "ψ")
    h3 = lb.hyp("mp3an12i.3", "( χ → θ )")
    h4 = lb.hyp("mp3an12i.4", "( ( φ ∧ ψ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( θ → τ )", h1, h2, h4, ref="mp3an12", note="mp3an12")
    res = lb.ref("res", "( χ → τ )", h3, s1, ref="syl", note="syl")
    return lb.build(res)

def prove_mp3an2i(sys: System) -> Proof:
    """~ mp3an with antecedents in standard conjunction form and with two
    hypotheses which are implications.  (Contributed by Alan Sare,
    28-Aug-2016.)
    """
    lb = ProofBuilder(sys, "mp3an2i")
    h1 = lb.hyp("mp3an2i.1", "φ")
    h2 = lb.hyp("mp3an2i.2", "( ψ → χ )")
    h3 = lb.hyp("mp3an2i.3", "( ψ → θ )")
    h4 = lb.hyp("mp3an2i.4", "( ( φ ∧ χ ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( χ ∧ θ ) → τ )", h1, h4, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "( ψ → τ )", h2, h3, s1, ref="syl2anc", note="syl2anc")
    return lb.build(res)

def prove_mp3an3an(sys: System) -> Proof:
    """~ mp3an with antecedents in standard conjunction form and with two
    hypotheses which are implications.  (Contributed by Alan Sare,
    28-Aug-2016.)
    """
    lb = ProofBuilder(sys, "mp3an3an")
    h1 = lb.hyp("mp3an3an.1", "φ")
    h2 = lb.hyp("mp3an3an.2", "( ψ → χ )")
    h3 = lb.hyp("mp3an3an.3", "( θ → τ )")
    h4 = lb.hyp("mp3an3an.4", "( ( φ ∧ χ ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( χ ∧ τ ) → η )", h1, h4, ref="mp3an1", note="mp3an1")
    res = lb.ref("res", "( ( ψ ∧ θ ) → η )", h2, h3, s1, ref="syl2an", note="syl2an")
    return lb.build(res)

def prove_mp3an2ani(sys: System) -> Proof:
    """An elimination deduction.  (Contributed by Alan Sare, 17-Oct-2017.)"""
    lb = ProofBuilder(sys, "mp3an2ani")
    h1 = lb.hyp("mp3an2ani.1", "φ")
    h2 = lb.hyp("mp3an2ani.2", "( ψ → χ )")
    h3 = lb.hyp("mp3an2ani.3", "( ( ψ ∧ θ ) → τ )")
    h4 = lb.hyp("mp3an2ani.4", "( ( φ ∧ χ ∧ τ ) → η )")
    s1 = lb.ref("s1", "( ( ψ ∧ ( ψ ∧ θ ) ) → η )", h1, h2, h3, h4, ref="mp3an3an", note="mp3an3an")
    res = lb.ref("res", "( ( ψ ∧ θ ) → η )", s1, ref="anabss5", note="anabss5")
    return lb.build(res)

def prove_biimp3a(sys: System) -> Proof:
    """Infer implication from a logical equivalence.  Similar to ~ biimpa .
    (Contributed by NM, 4-Sep-2005.)
    """
    lb = ProofBuilder(sys, "biimp3a")
    h1 = lb.hyp("biimp3a.1", "( ( φ ∧ ψ ) → ( χ ↔ θ ) )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ) ∧ χ ) → θ )", h1, ref="biimpa", note="biimpa")
    res = lb.ref("res", "( ( φ ∧ ψ ∧ χ ) → θ )", s1, ref="3impa", note="3impa")
    return lb.build(res)

def prove_biimp3ar(sys: System) -> Proof:
    """Infer implication from a logical equivalence.  Similar to ~ biimpar .
    (Contributed by NM, 2-Jan-2009.)
    """
    lb = ProofBuilder(sys, "biimp3ar")
    h1 = lb.hyp("biimp3a.1", "( ( φ ∧ ψ ) → ( χ ↔ θ ) )")
    s1 = lb.ref("s1", "( φ → ( ψ → ( θ → χ ) ) )", h1, ref="exbiri", note="exbiri")
    res = lb.ref("res", "( ( φ ∧ ψ ∧ θ ) → χ )", s1, ref="3imp", note="3imp")
    return lb.build(res)

def prove_3anandis(sys: System) -> Proof:
    """Inference that undistributes a triple conjunction in the antecedent.
    (Contributed by NM, 18-Apr-2007.)
    """
    lb = ProofBuilder(sys, "3anandis")
    h1 = lb.hyp("3anandis.1", "( ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ∧ ( φ ∧ θ ) ) → τ )")
    s1 = lb.ref("s1", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → φ )", ref="simpl", note="simpl")
    s2 = lb.ref("s2", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → ψ )", ref="simpr1", note="simpr1")
    s3 = lb.ref("s3", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → φ )", ref="simpl", note="simpl")
    s4 = lb.ref("s4", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → χ )", ref="simpr2", note="simpr2")
    s5 = lb.ref("s5", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → φ )", ref="simpl", note="simpl")
    s6 = lb.ref("s6", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → θ )", ref="simpr3", note="simpr3")
    res = lb.ref("res", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) → τ )", s1, s2, s3, s4, s5, s6, h1, ref="syl222anc", note="syl222anc")
    return lb.build(res)

def prove_3anandirs(sys: System) -> Proof:
    """Inference that undistributes a triple conjunction in the antecedent.
    (Contributed by NM, 25-Jul-2006.)
    """
    lb = ProofBuilder(sys, "3anandirs")
    h1 = lb.hyp("3anandirs.1", "( ( ( φ ∧ θ ) ∧ ( ψ ∧ θ ) ∧ ( χ ∧ θ ) ) → τ )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → φ )", ref="simpl1", note="simpl1")
    s2 = lb.ref("s2", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → θ )", ref="simpr", note="simpr")
    s3 = lb.ref("s3", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → ψ )", ref="simpl2", note="simpl2")
    s4 = lb.ref("s4", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → θ )", ref="simpr", note="simpr")
    s5 = lb.ref("s5", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → χ )", ref="simpl3", note="simpl3")
    s6 = lb.ref("s6", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → θ )", ref="simpr", note="simpr")
    res = lb.ref("res", "( ( ( φ ∧ ψ ∧ χ ) ∧ θ ) → τ )", s1, s2, s3, s4, s5, s6, h1, ref="syl222anc", note="syl222anc")
    return lb.build(res)

def prove_ecase23d(sys: System) -> Proof:
    """Deduction for elimination by cases.  (Contributed by NM,
    22-Apr-1994.)
    """
    lb = ProofBuilder(sys, "ecase23d")
    h1 = lb.hyp("ecase23d.1", "( φ → ¬ χ )")
    h2 = lb.hyp("ecase23d.2", "( φ → ¬ θ )")
    h3 = lb.hyp("ecase23d.3", "( φ → ( ψ ∨ χ ∨ θ ) )")
    s1 = lb.ref("s1", "( ( ψ ∨ χ ∨ θ ) ↔ ( ψ ∨ ( χ ∨ θ ) ) )", ref="3orass", note="3orass")
    s2 = lb.ref("s2", "( φ → ( ψ ∨ ( χ ∨ θ ) ) )", h3, s1, ref="sylib", note="sylib")
    s3 = lb.ref("s3", "( ¬ ( χ ∨ θ ) ↔ ( ¬ χ ∧ ¬ θ ) )", ref="ioran", note="ioran")
    s4 = lb.ref("s4", "( φ → ¬ ( χ ∨ θ ) )", h1, h2, s3, ref="sylanbrc", note="sylanbrc")
    res = lb.ref("res", "( φ → ψ )", s2, s4, ref="olcnd", note="olcnd")
    return lb.build(res)

def prove_3ecase(sys: System) -> Proof:
    """Inference for elimination by cases.  (Contributed by NM,
    13-Jul-2005.)
    """
    lb = ProofBuilder(sys, "3ecase")
    h1 = lb.hyp("3ecase.1", "( ¬ φ → θ )")
    h2 = lb.hyp("3ecase.2", "( ¬ ψ → θ )")
    h3 = lb.hyp("3ecase.3", "( ¬ χ → θ )")
    h4 = lb.hyp("3ecase.4", "( ( φ ∧ ψ ∧ χ ) → θ )")
    s1 = lb.ref("s1", "( φ → ( ψ → ( χ → θ ) ) )", h4, ref="3exp", note="3exp")
    s2 = lb.ref("s2", "( ¬ φ → ( ψ → ( χ → θ ) ) )", h1, ref="2a1d", note="2a1d")
    s3 = lb.ref("s3", "( ψ → ( χ → θ ) )", s1, s2, ref="pm2.61i", note="pm2.61i")
    res = lb.ref("res", "θ", s3, h2, h3, ref="pm2.61nii", note="pm2.61nii")
    return lb.build(res)

def prove_3bior1fd(sys: System) -> Proof:
    """A disjunction is equivalent to a threefold disjunction with single
    falsehood, analogous to ~ biorf .  (Contributed by Alexander van der
    Vekens, 8-Sep-2017.)
    """
    lb = ProofBuilder(sys, "3bior1fd")
    h1 = lb.hyp("3biorfd.1", "( φ → ¬ θ )")
    s1 = lb.ref("s1", "( ¬ θ → ( ( χ ∨ ψ ) ↔ ( θ ∨ ( χ ∨ ψ ) ) ) )", ref="biorf", note="biorf")
    s2 = lb.ref("s2", "( φ → ( ( χ ∨ ψ ) ↔ ( θ ∨ ( χ ∨ ψ ) ) ) )", h1, s1, ref="syl", note="syl")
    s3 = lb.ref("s3", "( ( θ ∨ χ ∨ ψ ) ↔ ( θ ∨ ( χ ∨ ψ ) ) )", ref="3orass", note="3orass")
    res = lb.ref("res", "( φ → ( ( χ ∨ ψ ) ↔ ( θ ∨ χ ∨ ψ ) ) )", s2, s3, ref="bitr4di", note="bitr4di")
    return lb.build(res)

def prove_3bior1fand(sys: System) -> Proof:
    """A disjunction is equivalent to a threefold disjunction with single
    falsehood of a conjunction.  (Contributed by Alexander van der Vekens,
    8-Sep-2017.)
    """
    lb = ProofBuilder(sys, "3bior1fand")
    h1 = lb.hyp("3biorfd.1", "( φ → ¬ θ )")
    s1 = lb.ref("s1", "( φ → ¬ ( θ ∧ τ ) )", h1, ref="intnanrd", note="intnanrd")
    res = lb.ref("res", "( φ → ( ( χ ∨ ψ ) ↔ ( ( θ ∧ τ ) ∨ χ ∨ ψ ) ) )", s1, ref="3bior1fd", note="3bior1fd")
    return lb.build(res)

def prove_3bior2fd(sys: System) -> Proof:
    """A wff is equivalent to its threefold disjunction with double falsehood,
    analogous to ~ biorf .  (Contributed by Alexander van der Vekens,
    8-Sep-2017.)
    """
    lb = ProofBuilder(sys, "3bior2fd")
    h1 = lb.hyp("3biorfd.1", "( φ → ¬ θ )")
    h2 = lb.hyp("3biorfd.2", "( φ → ¬ χ )")
    s1 = lb.ref("s1", "( ¬ χ → ( ψ ↔ ( χ ∨ ψ ) ) )", ref="biorf", note="biorf")
    s2 = lb.ref("s2", "( φ → ( ψ ↔ ( χ ∨ ψ ) ) )", h2, s1, ref="syl", note="syl")
    s3 = lb.ref("s3", "( φ → ( ( χ ∨ ψ ) ↔ ( θ ∨ χ ∨ ψ ) ) )", h1, ref="3bior1fd", note="3bior1fd")
    res = lb.ref("res", "( φ → ( ψ ↔ ( θ ∨ χ ∨ ψ ) ) )", s2, s3, ref="bitrd", note="bitrd")
    return lb.build(res)

def prove_3biant1d(sys: System) -> Proof:
    """A conjunction is equivalent to a threefold conjunction with single
    truth, analogous to ~ biantrud .  (Contributed by Alexander van der
    Vekens, 26-Sep-2017.)
    """
    lb = ProofBuilder(sys, "3biant1d")
    h1 = lb.hyp("3biantd.1", "( φ → θ )")
    s1 = lb.ref("s1", "( φ → ( ( χ ∧ ψ ) ↔ ( θ ∧ ( χ ∧ ψ ) ) ) )", h1, ref="biantrurd", note="biantrurd")
    s2 = lb.ref("s2", "( ( θ ∧ χ ∧ ψ ) ↔ ( θ ∧ ( χ ∧ ψ ) ) )", ref="3anass", note="3anass")
    res = lb.ref("res", "( φ → ( ( χ ∧ ψ ) ↔ ( θ ∧ χ ∧ ψ ) ) )", s1, s2, ref="bitr4di", note="bitr4di")
    return lb.build(res)

def prove_intn3an1d(sys: System) -> Proof:
    """Introduction of a triple conjunct inside a contradiction.  (Contributed
    by FL, 27-Dec-2007.)  (Proof shortened by Andrew Salmon,
    26-Jun-2011.)
    """
    lb = ProofBuilder(sys, "intn3an1d")
    h1 = lb.hyp("intn3and.1", "( φ → ¬ ψ )")
    s1 = lb.ref("s1", "( ( ψ ∧ χ ∧ θ ) → ψ )", ref="simp1", note="simp1")
    res = lb.ref("res", "( φ → ¬ ( ψ ∧ χ ∧ θ ) )", h1, s1, ref="nsyl", note="nsyl")
    return lb.build(res)

def prove_intn3an2d(sys: System) -> Proof:
    """Introduction of a triple conjunct inside a contradiction.  (Contributed
    by FL, 27-Dec-2007.)  (Proof shortened by Andrew Salmon,
    26-Jun-2011.)
    """
    lb = ProofBuilder(sys, "intn3an2d")
    h1 = lb.hyp("intn3and.1", "( φ → ¬ ψ )")
    s1 = lb.ref("s1", "( ( χ ∧ ψ ∧ θ ) → ψ )", ref="simp2", note="simp2")
    res = lb.ref("res", "( φ → ¬ ( χ ∧ ψ ∧ θ ) )", h1, s1, ref="nsyl", note="nsyl")
    return lb.build(res)

def prove_intn3an3d(sys: System) -> Proof:
    """Introduction of a triple conjunct inside a contradiction.  (Contributed
    by FL, 27-Dec-2007.)  (Proof shortened by Andrew Salmon,
    26-Jun-2011.)
    """
    lb = ProofBuilder(sys, "intn3an3d")
    h1 = lb.hyp("intn3and.1", "( φ → ¬ ψ )")
    s1 = lb.ref("s1", "( ( χ ∧ θ ∧ ψ ) → ψ )", ref="simp3", note="simp3")
    res = lb.ref("res", "( φ → ¬ ( χ ∧ θ ∧ ψ ) )", h1, s1, ref="nsyl", note="nsyl")
    return lb.build(res)

def prove_an3andi(sys: System) -> Proof:
    """Distribution of conjunction over threefold conjunction.  (Contributed by
    Thierry Arnoux, 8-Apr-2019.)
    """
    lb = ProofBuilder(sys, "an3andi")
    s1 = lb.ref("s1", "( ( φ ∧ ( ( ψ ∧ χ ) ∧ θ ) ) ↔ ( ( φ ∧ ( ψ ∧ χ ) ) ∧ ( φ ∧ θ ) ) )", ref="anandi", note="anandi")
    s2 = lb.ref("s2", "( ( φ ∧ ( ψ ∧ χ ) ) ↔ ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ) )", ref="anandi", note="anandi")
    s3 = lb.ref("s3", "( ( φ ∧ ( ( ψ ∧ χ ) ∧ θ ) ) ↔ ( ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ) ∧ ( φ ∧ θ ) ) )", s1, s2, ref="bianbi", note="bianbi")
    s4 = lb.ref("s4", "( ( ψ ∧ χ ∧ θ ) ↔ ( ( ψ ∧ χ ) ∧ θ ) )", ref="df-3an", note="df-3an")
    s5 = lb.ref("s5", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) ↔ ( φ ∧ ( ( ψ ∧ χ ) ∧ θ ) ) )", s4, ref="anbi2i", note="anbi2i")
    s6 = lb.ref("s6", "( ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ∧ ( φ ∧ θ ) ) ↔ ( ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ) ∧ ( φ ∧ θ ) ) )", ref="df-3an", note="df-3an")
    res = lb.ref("res", "( ( φ ∧ ( ψ ∧ χ ∧ θ ) ) ↔ ( ( φ ∧ ψ ) ∧ ( φ ∧ χ ) ∧ ( φ ∧ θ ) ) )", s3, s5, s6, ref="3bitr4i", note="3bitr4i")
    return lb.build(res)

def prove_an33rean(sys: System) -> Proof:
    """Rearrange a 9-fold conjunction.  (Contributed by Thierry Arnoux,
    14-Apr-2019.)  (Proof shortened by Wolf Lammen, 21-Apr-2024.)
    """
    lb = ProofBuilder(sys, "an33rean")
    s1 = lb.ref("s1", "( ( φ ∧ ψ ∧ χ ) ↔ ( φ ∧ ( ψ ∧ χ ) ) )", ref="3anass", note="3anass")
    s2 = lb.ref("s2", "( ( θ ∧ τ ∧ η ) ↔ ( τ ∧ ( θ ∧ η ) ) )", ref="3anan12", note="3anan12")
    s3 = lb.ref("s3", "( ( ζ ∧ σ ∧ ρ ) ↔ ( ρ ∧ σ ∧ ζ ) )", ref="3anrev", note="3anrev")
    s4 = lb.ref("s4", "( ( ρ ∧ σ ∧ ζ ) ↔ ( ρ ∧ ( σ ∧ ζ ) ) )", ref="3anass", note="3anass")
    s5 = lb.ref("s5", "( ( ζ ∧ σ ∧ ρ ) ↔ ( ρ ∧ ( σ ∧ ζ ) ) )", s3, s4, ref="bitri", note="bitri")
    s6 = lb.ref("s6", "( ( ( φ ∧ ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ∧ ( ζ ∧ σ ∧ ρ ) ) ↔ ( ( φ ∧ ( ψ ∧ χ ) ) ∧ ( τ ∧ ( θ ∧ η ) ) ∧ ( ρ ∧ ( σ ∧ ζ ) ) ) )", s1, s2, s5, ref="3anbi123i", note="3anbi123i")
    s7 = lb.ref("s7", "( ( ( φ ∧ ( ψ ∧ χ ) ) ∧ ( τ ∧ ( θ ∧ η ) ) ∧ ( ρ ∧ ( σ ∧ ζ ) ) ) ↔ ( ( φ ∧ τ ∧ ρ ) ∧ ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ∧ ( σ ∧ ζ ) ) ) )", ref="3an6", note="3an6")
    s8 = lb.ref("s8", "( ( ( θ ∧ η ) ∧ σ ) ↔ ( θ ∧ ( η ∧ σ ) ) )", ref="anass", note="anass")
    s9 = lb.ref("s9", "( ( ( ψ ∧ χ ) ∧ ( ( θ ∧ η ) ∧ σ ) ) ↔ ( ( ψ ∧ χ ) ∧ ( θ ∧ ( η ∧ σ ) ) ) )", s8, ref="anbi2i", note="anbi2i")
    s10 = lb.ref("s10", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ ( η ∧ σ ) ) ) ↔ ( ( ψ ∧ θ ) ∧ ( ( η ∧ σ ) ∧ χ ) ) )", ref="an42", note="an42")
    s11 = lb.ref("s11", "( ( ( ψ ∧ χ ) ∧ ( ( θ ∧ η ) ∧ σ ) ) ↔ ( ( ψ ∧ θ ) ∧ ( ( η ∧ σ ) ∧ χ ) ) )", s9, s10, ref="bitri", note="bitri")
    s12 = lb.ref("s12", "( ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ σ ) ↔ ( ( ψ ∧ χ ) ∧ ( ( θ ∧ η ) ∧ σ ) ) )", ref="anass", note="anass")
    s13 = lb.ref("s13", "( ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ χ ) ↔ ( ( ψ ∧ θ ) ∧ ( ( η ∧ σ ) ∧ χ ) ) )", ref="anass", note="anass")
    s14 = lb.ref("s14", "( ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ σ ) ↔ ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ χ ) )", s11, s12, s13, ref="3bitr4i", note="3bitr4i")
    s15 = lb.ref("s15", "( ( ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ σ ) ∧ ζ ) ↔ ( ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ χ ) ∧ ζ ) )", s14, ref="anbi1i", note="anbi1i")
    s16 = lb.ref("s16", "( ( ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ σ ) ∧ ζ ) ↔ ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ ( σ ∧ ζ ) ) )", ref="anass", note="anass")
    s17 = lb.ref("s17", "( ( ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ χ ) ∧ ζ ) ↔ ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ ( χ ∧ ζ ) ) )", ref="anass", note="anass")
    s18 = lb.ref("s18", "( ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ ( σ ∧ ζ ) ) ↔ ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ ( χ ∧ ζ ) ) )", s15, s16, s17, ref="3bitr3i", note="3bitr3i")
    s19 = lb.ref("s19", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ∧ ( σ ∧ ζ ) ) ↔ ( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ) ∧ ( σ ∧ ζ ) ) )", ref="df-3an", note="df-3an")
    s20 = lb.ref("s20", "( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ∧ ( χ ∧ ζ ) ) ↔ ( ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ) ∧ ( χ ∧ ζ ) ) )", ref="df-3an", note="df-3an")
    s21 = lb.ref("s21", "( ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ∧ ( σ ∧ ζ ) ) ↔ ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ∧ ( χ ∧ ζ ) ) )", s18, s19, s20, ref="3bitr4i", note="3bitr4i")
    s22 = lb.ref("s22", "( ( ( φ ∧ τ ∧ ρ ) ∧ ( ( ψ ∧ χ ) ∧ ( θ ∧ η ) ∧ ( σ ∧ ζ ) ) ) ↔ ( ( φ ∧ τ ∧ ρ ) ∧ ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ∧ ( χ ∧ ζ ) ) ) )", s21, ref="anbi2i", note="anbi2i")
    res = lb.ref("res", "( ( ( φ ∧ ψ ∧ χ ) ∧ ( θ ∧ τ ∧ η ) ∧ ( ζ ∧ σ ∧ ρ ) ) ↔ ( ( φ ∧ τ ∧ ρ ) ∧ ( ( ψ ∧ θ ) ∧ ( η ∧ σ ) ∧ ( χ ∧ ζ ) ) ) )", s6, s7, s22, ref="3bitri", note="3bitri")
    return lb.build(res)

def prove_3orel2(sys: System) -> Proof:
    """Partial elimination of a triple disjunction by denial of a disjunct.
    (Contributed by Scott Fenton, 26-Mar-2011.)  (Proof shortened by Andrew
    Salmon, 25-May-2011.)  (Proof shortened by Eric Schmidt, 8-Oct-2025.)
    """
    lb = ProofBuilder(sys, "3orel2")
    s1 = lb.ref("s1", "( ( φ ∨ ψ ∨ χ ) ↔ ( ψ ∨ φ ∨ χ ) )", ref="3orcoma", note="3orcoma")
    s2 = lb.ref("s2", "( ¬ ψ → ( ( ψ ∨ φ ∨ χ ) → ( φ ∨ χ ) ) )", ref="3orel1", note="3orel1")
    res = lb.ref("res", "( ¬ ψ → ( ( φ ∨ ψ ∨ χ ) → ( φ ∨ χ ) ) )", s1, s2, ref="biimtrid", note="biimtrid")
    return lb.build(res)

def prove_3orel2OLD(sys: System) -> Proof:
    """Obsolete version of ~ 3orel2 as of 8-Oct-2025.  (Contributed by Scott
    Fenton, 26-Mar-2011.)  (Proof shortened by Andrew Salmon, 25-May-2011.)
    (Proof modification is discouraged.)  (New usage is discouraged.)
    """
    lb = ProofBuilder(sys, "3orel2OLD")
    s1 = lb.ref("s1", "( ( φ ∨ ψ ∨ χ ) ↔ ( ψ ∨ χ ∨ φ ) )", ref="3orrot", note="3orrot")
    s2 = lb.ref("s2", "( ¬ ψ → ( ( ψ ∨ χ ∨ φ ) → ( χ ∨ φ ) ) )", ref="3orel1", note="3orel1")
    s3 = lb.ref("s3", "( ( χ ∨ φ ) ↔ ( φ ∨ χ ) )", ref="orcom", note="orcom")
    s4 = lb.ref("s4", "( ¬ ψ → ( ( ψ ∨ χ ∨ φ ) → ( φ ∨ χ ) ) )", s2, s3, ref="imbitrdi", note="imbitrdi")
    res = lb.ref("res", "( ¬ ψ → ( ( φ ∨ ψ ∨ χ ) → ( φ ∨ χ ) ) )", s1, s4, ref="biimtrid", note="biimtrid")
    return lb.build(res)

def prove_3orel3(sys: System) -> Proof:
    """Partial elimination of a triple disjunction by denial of a disjunct.
    (Contributed by Scott Fenton, 26-Mar-2011.)
    """
    lb = ProofBuilder(sys, "3orel3")
    s1 = lb.ref("s1", "( ( φ ∨ ψ ∨ χ ) ↔ ( ( φ ∨ ψ ) ∨ χ ) )", ref="df-3or", note="df-3or")
    s2 = lb.ref("s2", "( ¬ χ → ( ( ( φ ∨ ψ ) ∨ χ ) → ( φ ∨ ψ ) ) )", ref="orel2", note="orel2")
    res = lb.ref("res", "( ¬ χ → ( ( φ ∨ ψ ∨ χ ) → ( φ ∨ ψ ) ) )", s1, s2, ref="biimtrid", note="biimtrid")
    return lb.build(res)

def prove_3orel13(sys: System) -> Proof:
    """Elimination of two disjuncts in a triple disjunction.  (Contributed by
    Scott Fenton, 9-Jun-2011.)
    """
    lb = ProofBuilder(sys, "3orel13")
    s1 = lb.ref("s1", "( ¬ χ → ( ( φ ∨ ψ ∨ χ ) → ( φ ∨ ψ ) ) )", ref="3orel3", note="3orel3")
    s2 = lb.ref("s2", "( ¬ φ → ( ( φ ∨ ψ ) → ψ ) )", ref="orel1", note="orel1")
    res = lb.ref("res", "( ( ¬ φ ∧ ¬ χ ) → ( ( φ ∨ ψ ∨ χ ) → ψ ) )", s1, s2, ref="sylan9r", note="sylan9r")
    return lb.build(res)

def prove_3pm3_2ni(sys: System) -> Proof:
    """Triple negated disjunction introduction.  (Contributed by Scott Fenton,
    20-Apr-2011.)
    """
    lb = ProofBuilder(sys, "3pm3.2ni")
    h1 = lb.hyp("3pm3.2ni.1", "¬ φ")
    h2 = lb.hyp("3pm3.2ni.2", "¬ ψ")
    h3 = lb.hyp("3pm3.2ni.3", "¬ χ")
    s1 = lb.ref("s1", "¬ ( φ ∨ ψ )", h1, h2, ref="pm3.2ni", note="pm3.2ni")
    s2 = lb.ref("s2", "¬ ( ( φ ∨ ψ ) ∨ χ )", s1, h3, ref="pm3.2ni", note="pm3.2ni")
    s3 = lb.ref("s3", "( ( φ ∨ ψ ∨ χ ) ↔ ( ( φ ∨ ψ ) ∨ χ ) )", ref="df-3or", note="df-3or")
    res = lb.ref("res", "¬ ( φ ∨ ψ ∨ χ )", s2, s3, ref="mtbir", note="mtbir")
    return lb.build(res)

def prove_an42ds(sys: System) -> Proof:
    """Inference exchanging the last antecedent with the second one.  See also
    ~ an32s .  (Contributed by Thierry Arnoux, 3-Jun-2025.)
    """
    lb = ProofBuilder(sys, "an42ds")
    h1 = lb.hyp("an42ds.1", "( ( ( ( φ ∧ ψ ) ∧ χ ) ∧ θ ) → τ )")
    s1 = lb.ref("s1", "( ( ( φ ∧ ψ ) ∧ θ ) ↔ ( ( φ ∧ θ ) ∧ ψ ) )", ref="an32", note="an32")
    s2 = lb.ref("s2", "( ( ( ( φ ∧ ψ ) ∧ θ ) ∧ χ ) ↔ ( ( ( φ ∧ θ ) ∧ ψ ) ∧ χ ) )", s1, ref="anbi1i", note="anbi1i")
    s3 = lb.ref("s3", "( ( ( ( φ ∧ ψ ) ∧ θ ) ∧ χ ) ↔ ( ( ( φ ∧ ψ ) ∧ χ ) ∧ θ ) )", ref="an32", note="an32")
    s4 = lb.ref("s4", "( ( ( ( φ ∧ θ ) ∧ ψ ) ∧ χ ) ↔ ( ( ( φ ∧ θ ) ∧ χ ) ∧ ψ ) )", ref="an32", note="an32")
    s5 = lb.ref("s5", "( ( ( ( φ ∧ ψ ) ∧ χ ) ∧ θ ) ↔ ( ( ( φ ∧ θ ) ∧ χ ) ∧ ψ ) )", s2, s3, s4, ref="3bitr3i", note="3bitr3i")
    res = lb.ref("res", "( ( ( ( φ ∧ θ ) ∧ χ ) ∧ ψ ) → τ )", s5, h1, ref="sylbir", note="sylbir")
    return lb.build(res)


_THEOREMS: Mapping[str, LemmaCtor] = {
    'ad5ant2345': prove_ad5ant2345,
    'syl3anc': prove_syl3anc,
    'syl13anc': prove_syl13anc,
    'syl31anc': prove_syl31anc,
    'syl112anc': prove_syl112anc,
    'syl121anc': prove_syl121anc,
    'syl211anc': prove_syl211anc,
    'syl23anc': prove_syl23anc,
    'syl32anc': prove_syl32anc,
    'syl122anc': prove_syl122anc,
    'syl212anc': prove_syl212anc,
    'syl221anc': prove_syl221anc,
    'syl113anc': prove_syl113anc,
    'syl131anc': prove_syl131anc,
    'syl311anc': prove_syl311anc,
    'syl33anc': prove_syl33anc,
    'syl222anc': prove_syl222anc,
    'syl123anc': prove_syl123anc,
    'syl132anc': prove_syl132anc,
    'syl213anc': prove_syl213anc,
    'syl231anc': prove_syl231anc,
    'syl312anc': prove_syl312anc,
    'syl321anc': prove_syl321anc,
    'syl133anc': prove_syl133anc,
    'syl313anc': prove_syl313anc,
    'syl331anc': prove_syl331anc,
    'syl223anc': prove_syl223anc,
    'syl232anc': prove_syl232anc,
    'syl322anc': prove_syl322anc,
    'syl233anc': prove_syl233anc,
    'syl323anc': prove_syl323anc,
    'syl332anc': prove_syl332anc,
    'syl333anc': prove_syl333anc,
    'syl3an1b': prove_syl3an1b,
    'syl3an2b': prove_syl3an2b,
    'syl3an3b': prove_syl3an3b,
    'syl3an1br': prove_syl3an1br,
    'syl3an2br': prove_syl3an2br,
    'syl3an3br': prove_syl3an3br,
    'syld3an3': prove_syld3an3,
    'syld3an1': prove_syld3an1,
    'syld3an2': prove_syld3an2,
    'syl3anl1': prove_syl3anl1,
    'syl3anl2': prove_syl3anl2,
    'syl3anl3': prove_syl3anl3,
    'syl3anl': prove_syl3anl,
    'syl3anr1': prove_syl3anr1,
    'syl3anr2': prove_syl3anr2,
    'syl3anr3': prove_syl3anr3,
    '3anidm12': prove_3anidm12,
    '3anidm13': prove_3anidm13,
    '3anidm23': prove_3anidm23,
    'syl2an3an': prove_syl2an3an,
    'syl2an23an': prove_syl2an23an,
    '3ori': prove_3ori,
    '3jao': prove_3jao,
    '3jaob': prove_3jaob,
    '3jaoi': prove_3jaoi,
    '3jaoiOLD': prove_3jaoiOLD,
    '3jaod': prove_3jaod,
    '3jaoian': prove_3jaoian,
    '3jaodan': prove_3jaodan,
    'mpjao3dan': prove_mpjao3dan,
    '3jaao': prove_3jaao,
    '3jaaoOLD': prove_3jaaoOLD,
    'syl3an9b': prove_syl3an9b,
    '3orbi123d': prove_3orbi123d,
    '3anbi123d': prove_3anbi123d,
    '3anbi12d': prove_3anbi12d,
    '3anbi13d': prove_3anbi13d,
    '3anbi23d': prove_3anbi23d,
    '3anbi1d': prove_3anbi1d,
    '3anbi2d': prove_3anbi2d,
    '3anbi3d': prove_3anbi3d,
    '3anim123d': prove_3anim123d,
    '3orim123d': prove_3orim123d,
    'an6': prove_an6,
    '3an6': prove_3an6,
    '3or6': prove_3or6,
    'mp3an1': prove_mp3an1,
    'mp3an2': prove_mp3an2,
    'mp3an3': prove_mp3an3,
    'mp3an12': prove_mp3an12,
    'mp3an13': prove_mp3an13,
    'mp3an23': prove_mp3an23,
    'mp3an1i': prove_mp3an1i,
    'mp3anl1': prove_mp3anl1,
    'mp3anl2': prove_mp3anl2,
    'mp3anl3': prove_mp3anl3,
    'mp3anr1': prove_mp3anr1,
    'mp3anr2': prove_mp3anr2,
    'mp3anr3': prove_mp3anr3,
    'mp3an': prove_mp3an,
    'mpd3an3': prove_mpd3an3,
    'mpd3an23': prove_mpd3an23,
    'mp3and': prove_mp3and,
    'mp3an12i': prove_mp3an12i,
    'mp3an2i': prove_mp3an2i,
    'mp3an3an': prove_mp3an3an,
    'mp3an2ani': prove_mp3an2ani,
    'biimp3a': prove_biimp3a,
    'biimp3ar': prove_biimp3ar,
    '3anandis': prove_3anandis,
    '3anandirs': prove_3anandirs,
    'ecase23d': prove_ecase23d,
    '3ecase': prove_3ecase,
    '3bior1fd': prove_3bior1fd,
    '3bior1fand': prove_3bior1fand,
    '3bior2fd': prove_3bior2fd,
    '3biant1d': prove_3biant1d,
    'intn3an1d': prove_intn3an1d,
    'intn3an2d': prove_intn3an2d,
    'intn3an3d': prove_intn3an3d,
    'an3andi': prove_an3andi,
    'an33rean': prove_an33rean,
    '3orel2': prove_3orel2,
    '3orel2OLD': prove_3orel2OLD,
    '3orel3': prove_3orel3,
    '3orel13': prove_3orel13,
    '3pm3.2ni': prove_3pm3_2ni,
    'an42ds': prove_an42ds,
}

__all__ = [name for name in globals() if name.startswith("prove_")]
