# GENERATED by mm-transpiler.
from __future__ import annotations

from collections.abc import Callable, Mapping

from skfd.proof import Proof

from logic.prop.alternative_axiomatizations import _THEOREMS as MODULE_6_THEOREMS
from logic.prop.circuits import _THEOREMS as MODULE_5_THEOREMS
from logic.prop.conjunction import _THEOREMS as MODULE_2_THEOREMS
from logic.prop.connectives import _THEOREMS as MODULE_3_THEOREMS
from logic.prop.core import _THEOREMS as MODULE_0_THEOREMS
from logic.prop.equivalence import _THEOREMS as MODULE_1_THEOREMS
from logic.prop.ternary import _THEOREMS as MODULE_4_THEOREMS

LemmaCtor = Callable[..., Proof]


def _all_theorems() -> Mapping[str, LemmaCtor]:
    merged: dict[str, LemmaCtor] = {}
    for registry in (
        MODULE_0_THEOREMS,
        MODULE_1_THEOREMS,
        MODULE_2_THEOREMS,
        MODULE_3_THEOREMS,
        MODULE_4_THEOREMS,
        MODULE_5_THEOREMS,
        MODULE_6_THEOREMS,
    ):
        for label, ctor in registry.items():
            previous = merged.get(label)
            if previous is not None and previous is not ctor:
                raise ValueError(f"duplicate theorem label {label!r}")
            merged[label] = ctor
    return merged


THEOREMS = _all_theorems()

__all__ = ["THEOREMS"]
