# GENERATED by mm-transpiler; do not edit.
# Function-local imports are intentional: proof bodies elaborate lazily.
from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from metamath_setmm_provider.shards.s010 import (
    cleljust as cleljust,
)
from metamath_setmm_provider.shards.s010 import (
    ru0 as ru0,
)
from metamath_setmm_provider.shards.s010 import (
    wcel as wcel,
)
from metamath_setmm_provider.shards.s012 import (
    axc14 as axc14,
)
from metamath_setmm_provider.shards.s012 import (
    cleljustALT as cleljustALT,
)
from metamath_setmm_provider.shards.s012 import (
    cleljustALT2 as cleljustALT2,
)
from metamath_setmm_provider.shards.s012 import (
    dveel1 as dveel1,
)
from metamath_setmm_provider.shards.s012 import (
    dveel2 as dveel2,
)
from skfd.authoring.assertion import CompleteProof
from skfd.authoring.metamath_language import FormationBinding
from skfd.authoring.theory import TheoryProofAuthor

if str(wcel.syntax_assertion) != (
    'urn:uuid:59f0090c-0149-5281-8dfe-64acace7f97d'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(cleljust.id) != (
    'urn:uuid:8dcb1c14-0db2-5c94-bdf9-34648dc05c0f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(ru0.id) != (
    'urn:uuid:9373f9e0-2ef3-5c00-80a4-8d3d53d5145f'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(cleljustALT.id) != (
    'urn:uuid:26964f10-5de6-565e-b848-97f78587e035'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(cleljustALT2.id) != (
    'urn:uuid:f95acf57-142e-5188-bc0a-87704f810884'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dveel1.id) != (
    'urn:uuid:ba53d345-4d3b-553d-a94c-ca985dadfdc4'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(dveel2.id) != (
    'urn:uuid:1237299f-14be-5362-90fa-e55e260b0019'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

if str(axc14.id) != (
    'urn:uuid:3349363b-7789-5ed1-a669-58cd9cb9ce26'
):
    raise RuntimeError(
        'public semantic object ID differs from authority'
    )

# -- proof bodies --
@cleljust.proof
def prove_cleljust(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s010 import elequ1, equsexvw


    _step_1 = proof.use(
        elequ1,
        subst={
            "x": "z",
            "y": "x",
            "z": "y",
        },
    )  # ⊢ wi(wceq(cv(z), cv(x)), wb(wcel(cv(z), cv(y)), wcel(cv(x), cv(y))))
    _step_2 = proof.use(
        equsexvw,
        _step_1,
    )  # ⊢ wb(wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z), wcel(cv(x), cv(y)))
    _step_3 = proof.use(
        bicomi,
        _step_2,
    )  # ⊢ wb(wcel(cv(x), cv(y)), wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z))
    return proof.qed(_step_3)


@ru0.proof
def prove_ru0(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import mto
    from metamath_setmm_provider.shards.s001 import bibi12d, notbid, pm5_19
    from metamath_setmm_provider.shards.s002 import anidms
    from metamath_setmm_provider.shards.s010 import elequ1, elequ12, spvv


    _step_1 = proof.use(
        pm5_19,
        subst={
            "ph": "wcel(cv(y), cv(y))",
        },
    )  # ⊢ wn(wb(wcel(cv(y), cv(y)), wn(wcel(cv(y), cv(y)))))
    _step_2 = proof.use(
        elequ1,
        subst={
            "x": "x",
            "y": "y",
            "z": "y",
        },
    )  # ⊢ wi(wceq(cv(x), cv(y)), wb(wcel(cv(x), cv(y)), wcel(cv(y), cv(y))))
    _step_3 = proof.use(
        elequ12,
        subst={
            "x": "x",
            "y": "y",
            "z": "x",
            "t": "y",
        },
    )  # ⊢ wi(wa(wceq(cv(x), cv(y)), wceq(cv(x), cv(y))), wb(wcel(cv(x), cv(x)), wcel(cv(y), cv(y))…
    _step_4 = proof.use(
        anidms,
        _step_3,
    )  # ⊢ wi(wceq(cv(x), cv(y)), wb(wcel(cv(x), cv(x)), wcel(cv(y), cv(y))))
    _step_5 = proof.use(
        notbid,
        _step_4,
    )  # ⊢ wi(wceq(cv(x), cv(y)), wb(wn(wcel(cv(x), cv(x))), wn(wcel(cv(y), cv(y)))))
    _step_6 = proof.use(
        bibi12d,
        _step_2,
        _step_5,
    )  # ⊢ wi(wceq(cv(x), cv(y)), wb(wb(wcel(cv(x), cv(y)), wn(wcel(cv(x), cv(x)))), wb(wcel(cv(y),…
    _step_7 = proof.use(
        spvv,
        _step_6,
    )  # ⊢ wi(wal(wb(wcel(cv(x), cv(y)), wn(wcel(cv(x), cv(x)))), x), wb(wcel(cv(y), cv(y)), wn(wce…
    _step_8 = proof.use(
        mto,
        _step_1,
        _step_7,
    )  # ⊢ wn(wal(wb(wcel(cv(x), cv(y)), wn(wcel(cv(x), cv(x)))), x))
    return proof.qed(_step_8)


@cleljustALT.proof
def prove_cleljustALT(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s009 import ax_5
    from metamath_setmm_provider.shards.s010 import elequ1
    from metamath_setmm_provider.shards.s011 import equsexhv


    _step_1 = proof.use(
        ax_5,
        subst={
            "ph": "wcel(cv(x), cv(y))",
            "x": "z",
        },
    )  # ⊢ wi(wcel(cv(x), cv(y)), wal(wcel(cv(x), cv(y)), z))
    _step_2 = proof.use(
        elequ1,
        subst={
            "x": "z",
            "y": "x",
            "z": "y",
        },
    )  # ⊢ wi(wceq(cv(z), cv(x)), wb(wcel(cv(z), cv(y)), wcel(cv(x), cv(y))))
    _step_3 = proof.use(
        equsexhv,
        _step_1,
        _step_2,
    )  # ⊢ wb(wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z), wcel(cv(x), cv(y)))
    _step_4 = proof.use(
        bicomi,
        _step_3,
    )  # ⊢ wb(wcel(cv(x), cv(y)), wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z))
    return proof.qed(_step_4)


@cleljustALT2.proof
def prove_cleljustALT2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s001 import bicomi
    from metamath_setmm_provider.shards.s009 import nfv
    from metamath_setmm_provider.shards.s010 import elequ1
    from metamath_setmm_provider.shards.s011 import equsexv


    _step_1 = proof.use(
        nfv,
        subst={
            "ph": "wcel(cv(x), cv(y))",
            "x": "z",
        },
    )  # ⊢ wnf(wcel(cv(x), cv(y)), z)
    _step_2 = proof.use(
        elequ1,
        subst={
            "x": "z",
            "y": "x",
            "z": "y",
        },
    )  # ⊢ wi(wceq(cv(z), cv(x)), wb(wcel(cv(z), cv(y)), wcel(cv(x), cv(y))))
    _step_3 = proof.use(
        equsexv,
        _step_1,
        _step_2,
    )  # ⊢ wb(wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z), wcel(cv(x), cv(y)))
    _step_4 = proof.use(
        bicomi,
        _step_3,
    )  # ⊢ wb(wcel(cv(x), cv(y)), wex(wa(wceq(cv(z), cv(x)), wcel(cv(z), cv(y))), z))
    return proof.qed(_step_4)


@dveel1.proof(
    dummy_variables=(
        "w:setvar",
    ),
    distinct=(
        ("w", "x"),
        ("w", "y"),
        ("w", "z"),
    ),
)
def prove_dveel1(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s010 import elequ1
    from metamath_setmm_provider.shards.s012 import dvelimv


    _step_1 = proof.use(
        elequ1,
        subst={
            "x": "w",
            "y": "y",
            "z": "z",
        },
    )  # ⊢ wi(wceq(cv(w), cv(y)), wb(wcel(cv(w), cv(z)), wcel(cv(y), cv(z))))
    _step_2 = proof.use(
        dvelimv,
        _step_1,
        subst={
            "x": "x",
        },
    )  # ⊢ wi(wn(wal(wceq(cv(x), cv(y)), x)), wi(wcel(cv(y), cv(z)), wal(wcel(cv(y), cv(z)), x)))
    return proof.qed(_step_2)


@dveel2.proof(
    dummy_variables=(
        "w:setvar",
    ),
    distinct=(
        ("w", "x"),
        ("w", "y"),
        ("w", "z"),
    ),
)
def prove_dveel2(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s010 import elequ2
    from metamath_setmm_provider.shards.s012 import dvelimv


    _step_1 = proof.use(
        elequ2,
        subst={
            "x": "w",
            "y": "y",
            "z": "z",
        },
    )  # ⊢ wi(wceq(cv(w), cv(y)), wb(wcel(cv(z), cv(w)), wcel(cv(z), cv(y))))
    _step_2 = proof.use(
        dvelimv,
        _step_1,
        subst={
            "x": "x",
        },
    )  # ⊢ wi(wn(wal(wceq(cv(x), cv(y)), x)), wi(wcel(cv(z), cv(y)), wal(wcel(cv(z), cv(y)), x)))
    return proof.qed(_step_2)


@axc14.proof(
    dummy_variables=(
        "w:setvar",
    ),
    distinct=(
        ("w", "x"),
        ("w", "y"),
        ("w", "z"),
    ),
)
def prove_axc14(proof: TheoryProofAuthor) -> CompleteProof:
    from metamath_setmm_provider.shards.s000 import pm2_86d
    from metamath_setmm_provider.shards.s001 import imbi2d, imbitrdi
    from metamath_setmm_provider.shards.s009 import nfn
    from metamath_setmm_provider.shards.s010 import elequ1, hbn1, nfa1
    from metamath_setmm_provider.shards.s011 import hbim1, mm_19_21
    from metamath_setmm_provider.shards.s012 import dvelim


    _step_1 = proof.use(
        hbn1,
        subst={
            "ph": "wceq(cv(z), cv(y))",
            "x": "z",
        },
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(y)), z)), wal(wn(wal(wceq(cv(z), cv(y)), z)), z))
    _step_2 = proof.use(
        dveel2,
        subst={
            "x": "z",
            "y": "y",
            "z": "w",
        },
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(y)), z)), wi(wcel(cv(w), cv(y)), wal(wcel(cv(w), cv(y)), z)))
    _step_3 = proof.use(
        hbim1,
        _step_1,
        _step_2,
    )  # ⊢ wi(wi(wn(wal(wceq(cv(z), cv(y)), z)), wcel(cv(w), cv(y))), wal(wi(wn(wal(wceq(cv(z), cv(…
    _step_4 = proof.use(
        elequ1,
        subst={
            "x": "w",
            "y": "x",
            "z": "y",
        },
    )  # ⊢ wi(wceq(cv(w), cv(x)), wb(wcel(cv(w), cv(y)), wcel(cv(x), cv(y))))
    _step_5 = proof.use(
        imbi2d,
        _step_4,
        subst={
            "th": "wn(wal(wceq(cv(z), cv(y)), z))",
        },
    )  # ⊢ wi(wceq(cv(w), cv(x)), wb(wi(wn(wal(wceq(cv(z), cv(y)), z)), wcel(cv(w), cv(y))), wi(wn(…
    _step_6 = proof.use(
        dvelim,
        _step_3,
        _step_5,
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(x)), z)), wi(wi(wn(wal(wceq(cv(z), cv(y)), z)), wcel(cv(x), cv(…
    _step_7 = proof.use(
        nfa1,
        subst={
            "ph": "wceq(cv(z), cv(y))",
            "x": "z",
        },
    )  # ⊢ wnf(wal(wceq(cv(z), cv(y)), z), z)
    _step_8 = proof.use(nfn, _step_7)  # ⊢ wnf(wn(wal(wceq(cv(z), cv(y)), z)), z)
    _step_9 = proof.use(
        mm_19_21,
        _step_8,
        subst={
            "ps": "wcel(cv(x), cv(y))",
        },
    )  # ⊢ wb(wal(wi(wn(wal(wceq(cv(z), cv(y)), z)), wcel(cv(x), cv(y))), z), wi(wn(wal(wceq(cv(z),…
    _step_10 = proof.use(
        imbitrdi,
        _step_6,
        _step_9,
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(x)), z)), wi(wi(wn(wal(wceq(cv(z), cv(y)), z)), wcel(cv(x), cv(…
    _step_11 = proof.use(
        pm2_86d,
        _step_10,
    )  # ⊢ wi(wn(wal(wceq(cv(z), cv(x)), z)), wi(wn(wal(wceq(cv(z), cv(y)), z)), wi(wcel(cv(x), cv(…
    return proof.qed(_step_11)

__all__ = (
    'cleljust',
    'ru0',
    'cleljustALT',
    'cleljustALT2',
    'dveel1',
    'dveel2',
    'axc14',
)

FORMATION_BINDINGS_BY_LABEL: Mapping[str, FormationBinding] = MappingProxyType({
    'wcel': wcel,
})
