from __future__ import annotations

import argparse
import ast
import inspect
import sys
from collections.abc import Callable, Mapping
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "LEMMA_CATALOGUE.md"


def _source_link(constructor: Callable[..., object]) -> str:
    source = inspect.getsourcefile(constructor)
    if source is None:
        return "—"
    path = Path(source).resolve().relative_to(ROOT)
    line = inspect.getsourcelines(constructor)[1]
    return f"[`{path.as_posix()}`]({path.as_posix()}#L{line})"


def _proof_constructors() -> dict[str, Path]:
    constructors: dict[str, Path] = {}
    for path in sorted((SRC / "logic").glob("**/*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
                "prove_"
            ):
                if node.name in constructors:
                    raise RuntimeError(f"duplicate proof constructor {node.name}: {path}")
                constructors[node.name] = path
    return constructors


def render_catalogue() -> str:
    sys.path.insert(0, str(SRC))

    from logic.predicate.hilbert import SETMM_TO_PREDICATE_AXIOMS
    from logic.predicate.hilbert.theorems import SETMM_TO_PREDICATE_THEOREMS
    from logic.propositional.hilbert import SETMM_TO_HILBERT_AXIOMS, SETMM_TO_HILBERT_RULES
    from logic.propositional.hilbert.theorems import SETMM_TO_HILBERT_LEMMAS

    registries: tuple[tuple[str, Mapping[str, Callable[..., object]]], ...] = (
        ("Propositional theorem", SETMM_TO_HILBERT_LEMMAS),
        ("Predicate theorem", SETMM_TO_PREDICATE_THEOREMS),
    )
    registry_functions = {
        constructor.__name__ for _, registry in registries for constructor in registry.values()
    }
    source_constructors = _proof_constructors()
    uncovered = set(source_constructors) - registry_functions
    missing = registry_functions - set(source_constructors)

    if missing:
        raise RuntimeError(
            f"registered constructors missing from source audit: {sorted(missing)}"
        )
    if uncovered:
        raise RuntimeError(
            f"source proof constructors outside emission closure: {sorted(uncovered)}"
        )

    rows: list[tuple[str, str, str, str, str]] = []
    axiom_source = (
        "[`src/logic/propositional/hilbert/axioms.py`](src/logic/propositional/hilbert/axioms.py)"
    )
    system_source = "[`src/logic/propositional/hilbert/__init__.py`](src/logic/propositional/hilbert/__init__.py)"
    build_source = "[`src/logic/build.py`](src/logic/build.py)"
    for label in sorted(SETMM_TO_HILBERT_AXIOMS):
        rows.append((label, label, "Axiom", axiom_source, "emitted"))
    predicate_axiom_source = (
        "[`src/logic/predicate/hilbert/axioms.py`](src/logic/predicate/hilbert/axioms.py)"
    )
    for label in sorted(SETMM_TO_PREDICATE_AXIOMS):
        rows.append((label, label, "Predicate axiom", predicate_axiom_source, "emitted"))
    for label, local in sorted(SETMM_TO_HILBERT_RULES.items()):
        rows.append((label, local, "Rule", system_source, "emitted"))
    for label in ("wo", "wtru", "wfal"):
        rows.append((label, label, "Syntax", build_source, "emitted"))
    for label in ("idi", "a1ii"):
        rows.append((label, label, "Helper theorem", build_source, "emitted"))
    for category, registry in registries:
        for label, constructor in sorted(registry.items()):
            rows.append(
                (
                    label,
                    constructor.__name__,
                    category,
                    _source_link(constructor),
                    "emitted",
                )
            )

    md = [
        "# Lemma Catalogue",
        "",
        "Generated by `uv run --no-sync python tools/generate_lemma_catalogue.py`; do not edit by hand.",
        "",
        "The theorem rows come from both live Hilbert registries. Source links are resolved from the registered constructors, so predicate proofs point to `predicate/hilbert/lemmas.py`. All registry proofs are emitted and verifier-backed.",
        "",
        f"- Registry proofs: {sum(len(registry) for _, registry in registries)}",
        "- Support-only proofs: 0",
        f"- Source proof constructors: {len(source_constructors)}",
        f"- Uncovered source constructors: {len(uncovered)}",
        "- Latest verified coverage: 1896 declared / 3931 emitted / 0 declared-but-unemitted",
        "- Verifiers: `mmverify`, `metamath`, and `knife` pass",
        "",
        "| set.mm label | Local name/function | Category | Source module | Build status |",
        "|--------------|---------------------|----------|---------------|--------------|",
    ]
    md.extend(
        f"| {label} | {local} | {category} | {source} | {status} |"
        for label, local, category, source, status in rows
    )
    return "\n".join(md) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the emitted lemma catalogue")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when LEMMA_CATALOGUE.md is stale",
    )
    args = parser.parse_args()

    rendered = render_catalogue()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            raise SystemExit(
                "LEMMA_CATALOGUE.md is stale; run "
                "`uv run --no-sync python tools/generate_lemma_catalogue.py`"
            )
        return
    OUT.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
