from __future__ import annotations

from collections.abc import Callable, Mapping

from skfd.proof import Proof, SystemCore

from logic.predicate.hilbert.lemmas import (
    MIGRATION_THEOREMS as PREDICATE_MIGRATIONS,
)
from logic.predicate.hilbert.lemmas import (
    prove_2albidv,
    prove_2albii,
    prove_2albiim,
    prove_2ax5,
    prove_2eu2ex,
    prove_2exbidv,
    prove_2exbii,
    prove_2eximdv,
    prove_2eximi,
    prove_2exnexn,
    prove_2nalexn,
    prove_2sbbii,
    prove_2stdpc4,
    prove_3albii,
    prove_3exbidv,
    prove_3exbii,
    prove_4exbidv,
    prove_19_2,
    prove_19_2d,
    prove_19_3v,
    prove_19_8aw,
    prove_19_8v,
    prove_19_8w,
    prove_19_9v,
    prove_19_12vvv,
    prove_19_21v,
    prove_19_23v,
    prove_19_23vv,
    prove_19_24,
    prove_19_25,
    prove_19_26,
    prove_19_26_2,
    prove_19_26_3an,
    prove_19_27v,
    prove_19_28v,
    prove_19_29,
    prove_19_29r,
    prove_19_29r2,
    prove_19_29x,
    prove_19_30,
    prove_19_31v,
    prove_19_32v,
    prove_19_33,
    prove_19_33b,
    prove_19_34,
    prove_19_35,
    prove_19_35i,
    prove_19_35ri,
    prove_19_36imv,
    prove_19_36iv,
    prove_19_36v,
    prove_19_37imv,
    prove_19_37iv,
    prove_19_38,
    prove_19_38a,
    prove_19_38b,
    prove_19_39,
    prove_19_40,
    prove_19_40_2,
    prove_19_40b,
    prove_19_43,
    prove_19_43OLD,
    prove_19_44v,
    prove_19_45v,
    prove_aev,
    prove_aev2,
    prove_aeveq,
    prove_aevlem,
    prove_aevlem0,
    prove_alanimi,
    prove_albi,
    prove_albidh,
    prove_albidv,
    prove_albii,
    prove_albiim,
    prove_alcomimw,
    prove_alcomw,
    prove_alequexv,
    prove_alex,
    prove_alexbii,
    prove_aleximi,
    prove_alexn,
    prove_alfal,
    prove_alimex,
    prove_alinexa,
    prove_alnex,
    prove_alrot3,
    prove_alrot4,
    prove_alsyl,
    prove_altru,
    prove_ax5e,
    prove_ax5ea,
    prove_ax6dgen,
    prove_ax6ev,
    prove_ax6evr,
    prove_ax7,
    prove_ax8,
    prove_ax9,
    prove_ax10w,
    prove_ax11dgen,
    prove_ax11w,
    prove_ax12dgen,
    prove_ax12ev2,
    prove_ax12v2,
    prove_ax13dgen1,
    prove_ax13dgen2,
    prove_ax13dgen3,
    prove_ax13dgen4,
    prove_axie1,
    prove_bamalip,
    prove_barbara,
    prove_barbari,
    prove_barbarilem,
    prove_baroco,
    prove_bocardo,
    prove_calemes,
    prove_camestres,
    prove_camestros,
    prove_cbvaev,
    prove_cbval2vw,
    prove_cbvaldvaw,
    prove_cbvalivw,
    prove_cbvaliw,
    prove_cbvalvw,
    prove_cbvalw,
    prove_cbveuvw,
    prove_cbvex2vw,
    prove_cbvex4vw,
    prove_cbvexdvaw,
    prove_cbvexvw,
    prove_cbvmovw,
    prove_celarent,
    prove_celaront,
    prove_cesare,
    prove_cesaro,
    prove_chvarvv,
    prove_cleljust,
    prove_darii,
    prove_datisi,
    prove_dfeu,
    prove_dfmo,
    prove_dfsbimp,
    prove_dimatis,
    prove_disamis,
    prove_elequ1,
    prove_elequ2,
    prove_elequ2g,
    prove_elequ12,
    prove_emptyal,
    prove_emptyex,
    prove_emptynf,
    prove_equcom,
    prove_equcomd,
    prove_equcomi,
    prove_equcomiv,
    prove_equequ1,
    prove_equequ2,
    prove_equs4v,
    prove_equsalvw,
    prove_equsexvw,
    prove_equsv,
    prove_equtr,
    prove_equtrr,
    prove_equvinv,
    prove_equvinva,
    prove_eu3v,
    prove_euae,
    prove_euequ,
    prove_euex,
    prove_eujust,
    prove_eumo,
    prove_eumoi,
    prove_exa1,
    prove_exan,
    prove_exanali,
    prove_exancom,
    prove_exbi,
    prove_exbidh,
    prove_exbidv,
    prove_exbii,
    prove_exgen,
    prove_exim,
    prove_eximal,
    prove_eximdh,
    prove_eximdv,
    prove_eximi,
    prove_eximii,
    prove_exintr,
    prove_exintrbi,
    prove_exlimddv,
    prove_exlimdv,
    prove_exlimdvv,
    prove_exlimiiv,
    prove_exlimiv,
    prove_exlimivv,
    prove_exmo,
    prove_exmoeu,
    prove_exmoeub,
    prove_exnal,
    prove_exnalimn,
    prove_exsimpl,
    prove_exsimpr,
    prove_extru,
    prove_felapton,
    prove_ferio,
    prove_ferison,
    prove_fesapo,
    prove_festino,
    prove_fresison,
    prove_hba1w,
    prove_hbaev,
    prove_hbalw,
    prove_hbe1,
    prove_hbe1w,
    prove_hbn1,
    prove_hbn1fw,
    prove_hbn1w,
    prove_hbnaev,
    prove_hbxfrbi,
    prove_imnang,
    prove_moabs,
    prove_modal5,
    prove_moeu,
    prove_moeuex,
    prove_moim,
    prove_moimdv,
    prove_mojust,
    prove_mpg,
    prove_mpgbir,
    prove_naev,
    prove_naev2,
    prove_nex,
    prove_nexdh,
    prove_nexdv,
    prove_nexmo,
    prove_nf2,
    prove_nf3,
    prove_nf3an,
    prove_nf3and,
    prove_nf3or,
    prove_nf4,
    prove_nf5_1,
    prove_nf5dh,
    prove_nf5dv,
    prove_nf5i,
    prove_nfa2,
    prove_nfan,
    prove_nfand,
    prove_nfbi,
    prove_nfbidv,
    prove_nfbii,
    prove_nfbiit,
    prove_nfd,
    prove_nfe1,
    prove_nfequid,
    prove_nffal,
    prove_nfi,
    prove_nfia1,
    prove_nfim,
    prove_nfimd,
    prove_nfimt,
    prove_nfn,
    prove_nfna1,
    prove_nfnaew,
    prove_nfnan,
    prove_nfnd,
    prove_nfnf1,
    prove_nfnth,
    prove_nfntht,
    prove_nfntht2,
    prove_nfor,
    prove_nfri,
    prove_nfth,
    prove_nftht,
    prove_nftru,
    prove_nfv,
    prove_nfvd,
    prove_nfxfr,
    prove_nfxfrd,
    prove_nsb,
    prove_pm11_53v,
    prove_sb2imi,
    prove_sb3an,
    prove_sban,
    prove_sbbidv,
    prove_sbbii,
    prove_sbcom4,
    prove_sbi1,
    prove_sbi1lem,
    prove_sbimdv,
    prove_sbn1,
    prove_sbrimvw,
    prove_sbt,
    prove_sbtALT,
    prove_sbtlem,
    prove_sbtru,
    prove_sbv,
    prove_spaev,
    prove_speimfw,
    prove_speimfwALT,
    prove_speiv,
    prove_speivw,
    prove_spfalw,
    prove_spfw,
    prove_spimevw,
    prove_spimew,
    prove_spimfw,
    prove_spimvw,
    prove_spimw,
    prove_spnfw,
    prove_spsbbi,
    prove_spsbe,
    prove_spsbim,
    prove_spsv,
    prove_sptruw,
    prove_spvv,
    prove_spw,
    prove_stdpc4,
    prove_stdpc4lem,
    prove_stdpc6,
)
from logic.propositional.hilbert.conjunction import (
    prove_equtr2,
)
from logic.propositional.hilbert.constants import (
    prove_empty,
)
from logic.propositional.hilbert.equivalence import (
    prove_2exanali,
    prove_ax13b,
    prove_equvelv,
)
from logic.propositional.hilbert.implication import (
    prove_equcoms,
    prove_equeucl,
    prove_equeuclr,
)
from logic.propositional.hilbert.negation import (
    prove_ax13lem1,
    prove_ax13lem2,
    prove_ax13v,
)

PredicateTheoremCtor = Callable[[SystemCore], Proof]

_LEGACY_PREDICATE_THEOREMS: Mapping[str, PredicateTheoremCtor] = {
    "imnang": prove_imnang,
    "ax5e": prove_ax5e,
    "ax5ea": prove_ax5ea,
    "ax6ev": prove_ax6ev,
    "ax6dgen": prove_ax6dgen,
    "ax6evr": prove_ax6evr,
    "ax7": prove_ax7,
    "ax8": prove_ax8,
    "ax9": prove_ax9,
    "ax10w": prove_ax10w,
    "ax11w": prove_ax11w,
    "ax11dgen": prove_ax11dgen,
    "ax12v2": prove_ax12v2,
    "equequ1": prove_equequ1,
    "equequ2": prove_equequ2,
    "elequ1": prove_elequ1,
    "elequ12": prove_elequ12,
    "elequ2g": prove_elequ2g,
    "elequ2": prove_elequ2,
    "ax12dgen": prove_ax12dgen,
    "ax12ev2": prove_ax12ev2,
    "ax13dgen1": prove_ax13dgen1,
    "ax13dgen2": prove_ax13dgen2,
    "ax13dgen3": prove_ax13dgen3,
    "ax13dgen4": prove_ax13dgen4,
    "axie1": prove_axie1,
    "ax13b": prove_ax13b,
    "ax13v": prove_ax13v,
    "ax13lem1": prove_ax13lem1,
    "ax13lem2": prove_ax13lem2,
    "equtr": prove_equtr,
    "equtr2": prove_equtr2,
    "equtrr": prove_equtrr,
    "albidh": prove_albidh,
    "albidv": prove_albidv,
    "alcomimw": prove_alcomimw,
    "alcomw": prove_alcomw,
    "2albidv": prove_2albidv,
    "2albii": prove_2albii,
    "2albiim": prove_2albiim,
    "2ax5": prove_2ax5,
    "2stdpc4": prove_2stdpc4,
    "3albii": prove_3albii,
    "alfal": prove_alfal,
    "alnex": prove_alnex,
    "alequexv": prove_alequexv,
    "alex": prove_alex,
    "aleximi": prove_aleximi,
    "alimex": prove_alimex,
    "alexn": prove_alexn,
    "alinexa": prove_alinexa,
    "alexbii": prove_alexbii,
    "aevlem0": prove_aevlem0,
    "aevlem": prove_aevlem,
    "aev": prove_aev,
    "aev2": prove_aev2,
    "aeveq": prove_aeveq,
    "alanimi": prove_alanimi,
    "alsyl": prove_alsyl,
    "altru": prove_altru,
    "bamalip": prove_bamalip,
    "barbara": prove_barbara,
    "calemes": prove_calemes,
    "camestres": prove_camestres,
    "camestros": prove_camestros,
    "celarent": prove_celarent,
    "celaront": prove_celaront,
    "cesare": prove_cesare,
    "cesaro": prove_cesaro,
    "chvarvv": prove_chvarvv,
    "cleljust": prove_cleljust,
    "darii": prove_darii,
    "baroco": prove_baroco,
    "bocardo": prove_bocardo,
    "disamis": prove_disamis,
    "dimatis": prove_dimatis,
    "datisi": prove_datisi,
    "festino": prove_festino,
    "fresison": prove_fresison,
    "ferio": prove_ferio,
    "felapton": prove_felapton,
    "ferison": prove_ferison,
    "fesapo": prove_fesapo,
    "barbarilem": prove_barbarilem,
    "barbari": prove_barbari,
    "albi": prove_albi,
    "albii": prove_albii,
    "alrot3": prove_alrot3,
    "alrot4": prove_alrot4,
    "hba1w": prove_hba1w,
    "hbaev": prove_hbaev,
    "hbalw": prove_hbalw,
    "hbe1": prove_hbe1,
    "hbe1w": prove_hbe1w,
    "hbn1": prove_hbn1,
    "hbn1fw": prove_hbn1fw,
    "hbn1w": prove_hbn1w,
    "modal5": prove_modal5,
    "hbxfrbi": prove_hbxfrbi,
    "mpg": prove_mpg,
    "mpgbir": prove_mpgbir,
    "naev": prove_naev,
    "naev2": prove_naev2,
    "hbnaev": prove_hbnaev,
    "nex": prove_nex,
    "nexmo": prove_nexmo,
    "moabs": prove_moabs,
    "moeu": prove_moeu,
    "moim": prove_moim,
    "moimdv": prove_moimdv,
    "exmo": prove_exmo,
    "nexdh": prove_nexdh,
    "nexdv": prove_nexdv,
    "nfi": prove_nfi,
    "nfia1": prove_nfia1,
    "nfv": prove_nfv,
    "nfvd": prove_nfvd,
    "nfri": prove_nfri,
    "nf3": prove_nf3,
    "nf3or": prove_nf3or,
    "nf4": prove_nf4,
    "nf2": prove_nf2,
    "nfimd": prove_nfimd,
    "nfimt": prove_nfimt,
    "nfim": prove_nfim,
    "nfd": prove_nfd,
    "nfbiit": prove_nfbiit,
    "nfbii": prove_nfbii,
    "nfbidv": prove_nfbidv,
    "nfbi": prove_nfbi,
    "nfxfrd": prove_nfxfrd,
    "nfxfr": prove_nfxfr,
    "nf5-1": prove_nf5_1,
    "nfa2": prove_nfa2,
    "nfan": prove_nfan,
    "nfand": prove_nfand,
    "nfnan": prove_nfnan,
    "nf3and": prove_nf3and,
    "nf3an": prove_nf3an,
    "nfna1": prove_nfna1,
    "nfnaew": prove_nfnaew,
    "nfor": prove_nfor,
    "nf5i": prove_nf5i,
    "nf5dh": prove_nf5dh,
    "nf5dv": prove_nf5dv,
    "nfe1": prove_nfe1,
    "nfn": prove_nfn,
    "nfnf1": prove_nfnf1,
    "nfnd": prove_nfnd,
    "nfntht": prove_nfntht,
    "nfntht2": prove_nfntht2,
    "nfnth": prove_nfnth,
    "nffal": prove_nffal,
    "nftht": prove_nftht,
    "nfth": prove_nfth,
    "nftru": prove_nftru,
    "nfequid": prove_nfequid,
    "sbtlem": prove_sbtlem,
    "sbt": prove_sbt,
    "sbtALT": prove_sbtALT,
    "sbtru": prove_sbtru,
    "speiv": prove_speiv,
    "speivw": prove_speivw,
    "spimfw": prove_spimfw,
    "spimw": prove_spimw,
    "speimfw": prove_speimfw,
    "speimfwALT": prove_speimfwALT,
    "spimew": prove_spimew,
    "spimevw": prove_spimevw,
    "spimvw": prove_spimvw,
    "spvv": prove_spvv,
    "stdpc4": prove_stdpc4,
    "stdpc4lem": prove_stdpc4lem,
    "stdpc6": prove_stdpc6,
    "sbbidv": prove_sbbidv,
    "spsbe": prove_spsbe,
    "spsbim": prove_spsbim,
    "spsbbi": prove_spsbbi,
    "sbimdv": prove_sbimdv,
    "sbv": prove_sbv,
    "spaev": prove_spaev,
    "spfw": prove_spfw,
    "spw": prove_spw,
    "spsv": prove_spsv,
    "nsb": prove_nsb,
    "sptruw": prove_sptruw,
    "spnfw": prove_spnfw,
    "spfalw": prove_spfalw,
    "cbvaev": prove_cbvaev,
    "cbvaliw": prove_cbvaliw,
    "cbvalivw": prove_cbvalivw,
    "cbvalvw": prove_cbvalvw,
    "cbval2vw": prove_cbval2vw,
    "cbvaldvaw": prove_cbvaldvaw,
    "cbveuvw": prove_cbveuvw,
    "cbvexvw": prove_cbvexvw,
    "cbvex2vw": prove_cbvex2vw,
    "cbvex4vw": prove_cbvex4vw,
    "cbvmovw": prove_cbvmovw,
    "mojust": prove_mojust,
    "dfmo": prove_dfmo,
    "dfeu": prove_dfeu,
    "cbvalw": prove_cbvalw,
    "cbvexdvaw": prove_cbvexdvaw,
    "dfsbimp": prove_dfsbimp,
    "sbi1lem": prove_sbi1lem,
    "sbi1": prove_sbi1,
    "sb2imi": prove_sb2imi,
    "sbn1": prove_sbn1,
    "sban": prove_sban,
    "sb3an": prove_sb3an,
    "sbbii": prove_sbbii,
    "2sbbii": prove_2sbbii,
    "sbcom4": prove_sbcom4,
    "sbrimvw": prove_sbrimvw,
    "pm11.53v": prove_pm11_53v,
    "empty": prove_empty,
    "19.2": prove_19_2,
    "19.3v": prove_19_3v,
    "19.2d": prove_19_2d,
    "19.8w": prove_19_8w,
    "19.8v": prove_19_8v,
    "19.8aw": prove_19_8aw,
    "19.9v": prove_19_9v,
    "19.12vvv": prove_19_12vvv,
    "19.21v": prove_19_21v,
    "19.32v": prove_19_32v,
    "19.31v": prove_19_31v,
    "19.23v": prove_19_23v,
    "19.23vv": prove_19_23vv,
    "19.24": prove_19_24,
    "19.25": prove_19_25,
    "19.26": prove_19_26,
    "19.26-2": prove_19_26_2,
    "19.26-3an": prove_19_26_3an,
    "19.28v": prove_19_28v,
    "19.27v": prove_19_27v,
    "albiim": prove_albiim,
    "19.29r": prove_19_29r,
    "19.29r2": prove_19_29r2,
    "19.29": prove_19_29,
    "19.29x": prove_19_29x,
    "19.30": prove_19_30,
    "19.33": prove_19_33,
    "19.33b": prove_19_33b,
    "19.34": prove_19_34,
    "19.35": prove_19_35,
    "19.35i": prove_19_35i,
    "19.35ri": prove_19_35ri,
    "19.36iv": prove_19_36iv,
    "19.36v": prove_19_36v,
    "19.36imv": prove_19_36imv,
    "19.37imv": prove_19_37imv,
    "19.37iv": prove_19_37iv,
    "19.40": prove_19_40,
    "19.40-2": prove_19_40_2,
    "19.40b": prove_19_40b,
    "19.43": prove_19_43,
    "19.43OLD": prove_19_43OLD,
    "19.44v": prove_19_44v,
    "19.45v": prove_19_45v,
    "19.38": prove_19_38,
    "19.38a": prove_19_38a,
    "19.38b": prove_19_38b,
    "19.39": prove_19_39,
    "equcom": prove_equcom,
    "equcomd": prove_equcomd,
    "equcomi": prove_equcomi,
    "equcoms": prove_equcoms,
    "equeucl": prove_equeucl,
    "equeuclr": prove_equeuclr,
    "equcomiv": prove_equcomiv,
    "equvinva": prove_equvinva,
    "equvinv": prove_equvinv,
    "equvelv": prove_equvelv,
    "equsalvw": prove_equsalvw,
    "equsexvw": prove_equsexvw,
    "equsv": prove_equsv,
    "equs4v": prove_equs4v,
    "eu3v": prove_eu3v,
    "euae": prove_euae,
    "euequ": prove_euequ,
    "euex": prove_euex,
    "eujust": prove_eujust,
    "2eu2ex": prove_2eu2ex,
    "eumo": prove_eumo,
    "exbi": prove_exbi,
    "exbii": prove_exbii,
    "exbidh": prove_exbidh,
    "exbidv": prove_exbidv,
    "exan": prove_exan,
    "exancom": prove_exancom,
    "eumoi": prove_eumoi,
    "moeuex": prove_moeuex,
    "exmoeub": prove_exmoeub,
    "exanali": prove_exanali,
    "exmoeu": prove_exmoeu,
    "exnal": prove_exnal,
    "exnalimn": prove_exnalimn,
    "eximal": prove_eximal,
    "exim": prove_exim,
    "eximdh": prove_eximdh,
    "eximdv": prove_eximdv,
    "exa1": prove_exa1,
    "exgen": prove_exgen,
    "extru": prove_extru,
    "emptyex": prove_emptyex,
    "emptyal": prove_emptyal,
    "emptynf": prove_emptynf,
    "eximi": prove_eximi,
    "eximii": prove_eximii,
    "2eximi": prove_2eximi,
    "2exnexn": prove_2exnexn,
    "2exbii": prove_2exbii,
    "2exanali": prove_2exanali,
    "3exbii": prove_3exbii,
    "2eximdv": prove_2eximdv,
    "2exbidv": prove_2exbidv,
    "2nalexn": prove_2nalexn,
    "3exbidv": prove_3exbidv,
    "4exbidv": prove_4exbidv,
    "exlimiv": prove_exlimiv,
    "exlimddv": prove_exlimddv,
    "exlimdv": prove_exlimdv,
    "exlimdvv": prove_exlimdvv,
    "exlimiiv": prove_exlimiiv,
    "exlimivv": prove_exlimivv,
    "exintr": prove_exintr,
    "exintrbi": prove_exintrbi,
    "exsimpl": prove_exsimpl,
    "exsimpr": prove_exsimpr,
}


def _merge_migration_registries() -> Mapping[str, PredicateTheoremCtor]:
    merged = dict(_LEGACY_PREDICATE_THEOREMS)
    duplicates = merged.keys() & PREDICATE_MIGRATIONS.keys()
    if duplicates:
        raise RuntimeError(
            f"duplicate predicate theorem registrations: {sorted(duplicates)}"
        )
    merged.update(PREDICATE_MIGRATIONS)
    return merged


SETMM_TO_PREDICATE_THEOREMS = _merge_migration_registries()


__all__ = ["PredicateTheoremCtor", "SETMM_TO_PREDICATE_THEOREMS"]
